### ISSUE TITLE
export_to_filemaker does not seem to start the fm image import if no images have been added but file picking rules have changed

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1000]
That is just a hunch so far. On arch1900 after changing the file-picking rules only the resulting fm database had still not imported any image files. Fork and all was fine. When debugging the fm database and starting the import images script myself, everything was properly imported. That suggests that the script never got started.

**Comment by urapadmin** [comment]
while I have done tests that showed that file picking did change the results in file maker.  This should be tested.
### @test >0.11
does changing the file picking rules ONLY change the outcome in filemaker? 
- declare some file picking rules that would lead to dummy images in filemaker
- fork, export and make sure you see those dummy files
- reset the workstation, change ONLY the file picking rule and fork and prepare again. 
- [ ] are the dummy images now real images?

**Comment by urapadmin** [comment]
Ja, we had our first failure, which is reported in #1000.

**Comment by luizaogs** [comment]
Works.
