### ISSUE TITLE
showing details on a field manager error leads to localhost

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1004]
happened when I used an ipad for the first time. Must be some development environment issue.

**Comment by urapadmin** [comment]
the thing with the "developMode" did not really work. the wepback constant DEVELOPMENT does. But it needs more tsignores than I already have. I more or less tsignore ts.

**Comment by urapadmin** [comment]
### @test 0.11 
- [ ] if a task in the field manager had an error or warning and the button "show log" appears, you should be able to click on it and see the log.

**Comment by lbestock** [comment]
Tested accidentally while using it. Works.
