### ISSUE TITLE
prepare for field in sync manager starts at 50%

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1005]
This is just cosmetics. The percentage starts at 50% for a bit and is then reset.
Also there is still the issue in step 2 with preparing images or so. That also starts at a much higher percentage until it actually drops to something around 50.

**Comment by urapadmin** [comment]
the starting at 50% is solved.

**Comment by lbestock** [comment]
This still starts at 50% for me in PVD 0.11 on the local server.

**Comment by urapadmin** [comment]
this should really be done now > 0.11.6

**Comment by lbestock** [comment]
Haven't seen it for awhile and will close it.
