### ISSUE TITLE
cost has wrong format?

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#101]
cost display is different than remembered input if very large number or very long fraction

**Comment by lbestock** [comment]
Well I still don't know what's up with this, but it does still happen:
![image](https://user-images.githubusercontent.com/49291909/88433863-e9ef0680-cdcc-11ea-8255-99f38b13fbbf.png)

On the other hand, I am not convinced this is meaningful. I mean, unless someone finds something worth billions of dollars the weirdness never arises.

**Comment by lbestock** [comment]
Very nice Easter Eggs.

**Comment by urapadmin** [comment]
that's a numeric overflow. Both inputs can't make much sense, so I accept this as normal behaviour.
