### ISSUE TITLE
filemaker: The has_been_opened check does not work anymore

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1011]
I downloaded from the development server and immediately uploaded again and import filemaker happily imported the database although it had not been opened. The log shows: has_been_opened to be true.

**Comment by urapadmin** [comment]
I am not entirely sure what is going on. There is a new warning in the log now that checks if the check can be done at all:
Look out in the logs for: 
"The template file for this project does not have the config key 'has_been_opened'. The "
                                "check cannot be done."

**Comment by urapadmin** [comment]
### @test recording 10.5.2 / kiosk 0.11.8
that should work again, now. 
- [ ] prepare a workstation, download it and upload it immediately (don't open it!). When you import you should get an error that the file does not seem to have been opened.
- [ ] open the downloaded file, log in and log out immediately. Now upload and import and the import should run.

**Comment by luizaogs** [comment]
Hm, no -- the import (and even synchronization) ran without opening the database in USTP test 0.11.8.

**Comment by urapadmin** [comment]
I am sorry, I made a version mess. USTP was a few hours back. 
Please wait for recording 10.6 and try again.

**Comment by luizaogs** [comment]
Works.
