### ISSUE TITLE
File Picking: NOT IN for contexts

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1017]
The "context" rule can now use "NOT IN" or "!IN" as described in the wiki: 
[https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking](https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#rule_types)

**Comment by urapadmin** [comment]
### @test kiosk 0.11
- [ ] something like "context", "NOT IN", "CC" should apply to all files that are context-bound but are not bound to the context "CC". Keep in mind that "CC-001-1" is also part of "CC" so here the rule should NOT apply.

**Comment by urapadmin** [comment]
@test kiosk 0.11 for developer
-[ ] develop a test for this

**Comment by luizaogs** [comment]
Magic! And yes, I made sure that context and collected material images belonging to that context were there and not dummified.
