### ISSUE TITLE
File Picking: has operator

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1020]
the context rule could have a "has" operator that addresses identifiers that **include** instead of equal the search value.

**Comment by urapadmin** [comment]
### @test 0.11
- [ ] the has operator is available for the context rule. see documentation in ["https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#has"]("https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#has")
- [ ] it also exists as a !has operator, see ["https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#has_or_has_not"]("https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#has_or_has_not")

**Comment by luizaogs** [comment]
So -- and take this with a grain of salt if you wish, because who knows if I did this correctly -- !has does not seem to be working? The has operator did, though. But maybe someone should check my file picking rules before assuming this is actually not working :)

**Comment by luizaogs** [comment]
Oh! Oh! Hang on. It might have worked.

**Comment by luizaogs** [comment]
It did work, I'm just dumb. File picking is COOL. And the fact that I could figure it out means that you wrote a very good wiki article on it, by the way. File Picking for Dummies, if you will.
