### ISSUE TITLE
develop a colour scheme for arch1900

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1024]

**Comment by urapadmin** [comment]
a first version is ready. It is clear that it needs better views in the design tool (field manager and file repos) and that the plugins have to follow the color scheme way more strictly. 
But it is good to make different color schemes to see where the mistakes are.

**Comment by urapadmin** [comment]
### @test arch1900 kiosk 0.11.2
Make sure that the new color scheme in kiosk is quite readable.

**Comment by lbestock** [comment]
It looks really good to me. Even the polka dots, which don't really read as polka dots unless you really scrutinize the page. 

Tangentially I have noticed the redesign of the pagination in the file repository while looking at this, and I like that a lot, too.
