### ISSUE TITLE
synchronization dialog: disabled checkbox illegible in standard color scheme

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1026]
One ticket so we don't produce a big fat mess. PVD is the default color scheme. When I run into things that can't be read I will put them here. Like this:

![image](https://user-images.githubusercontent.com/49291909/115129724-a1105b00-9fb6-11eb-9040-05a2c0d8a4ea.png)

**Comment by urapadmin** [comment]
it is a disabled option, currently, so it is supposed to look greyed out. I have changed my greying-out strategy a bit and think it is better now.

**Comment by luizaogs** [comment]
I'm a bit blind these days but think it does look better now.
