### ISSUE TITLE
field manager iPad portrait mode not properly responsive

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1028]
When the iPad mini is used for the field manager the information in the lower part of the workstations is not exhibited.

**Comment by lbestock** [comment]
Oh funny, half of it even ends up on the bottom, which I didn't see until I swiped the screen up.
![image](https://user-images.githubusercontent.com/49291909/115157358-cf457780-a056-11eb-82d5-b3048bb0fc5d.png)

**Comment by urapadmin** [comment]
happens only on iOS devices. Firefox and Chrome work fine. That is always bad. Low Priority.

**Comment by urapadmin** [comment]
see #1156
