### ISSUE TITLE
new recording group with no file picking rules set nonetheless has images

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1029]
Created a new workstation with a new recording group (registration) in URAP 0.11 on the local server. I expected it to have no images in it - I downloaded it just for fun, not really to a purpose, and so I didn't even look at file picking before downloading. Whoops, lots of pictures are in there. In fact all images that are not pdfs are in there. PDFs are dummies. The only file picking rule set is that contextuals should be low resolution for default recording group. (Also the ability to see what recording group a workstation is in is pretty urgent. Since I can't edit a workstation in most states I can't even check on what recording group I'm in.)

**Comment by urapadmin** [comment]
and I have a hunch why that is the case: There is no empty template at hand anymore because it has been populated by the default recording group. That needs a change in export_to_filemaker!

**Comment by urapadmin** [comment]
### @test 0.11.1
- [ ] with a new recording group this should work now.

The only thing that is currently still in doubt is whether changing the file picking rules for a already existing recording group leads to different results during fork. But that is handled already by #955 (beware of the cryptic title).

**Comment by urapadmin** [comment]
### @test 0.11
It wasn't next on the list but there you have it:
- [ ] workstations appear grouped by recording group now in the field manager

**Comment by lbestock** [comment]
A 28MB URAP database. Funny to see that one zipping around.
