### ISSUE TITLE
forking hops to 50% too fast

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1032]
because an error prevented it from running at all (at least the image part just does not do anything).

**Comment by urapadmin** [comment]
### kiosk v0.11.1
- [x] an error like that would surface now and stop fork (I have tested that - lkh)
- [ ] should work now.

**Comment by lbestock** [comment]
Medium extensive file-picking tests with URAP on Hillside suggest this is not a problem.
