### ISSUE TITLE
tell URAP to recognize PDFs

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1036]
PDFs are dummies in URAP and wish to be made visible.

**Comment by urapadmin** [comment]
Urap where? On Hillside or online?

**Comment by urapadmin** [comment]
ah, wait. You mean they are dummies when exported to the filemaker database? dummies as in file picking dummies?

**Comment by urapadmin** [comment]
### @test 0.11.2
in that case it should be solved after the rollout of 0.11.2

**Comment by lbestock** [comment]
Yes, dummies in filemaker after export from Hillside. But no filepicking was involved - they were dummies even when the rules should have been low. We had the same thing with PVD and you just had to tell it that pdfs were a thing, I thought.

**Comment by urapadmin** [comment]
ja, all projects should get pdfs once they are on 0.11.2

**Comment by lbestock** [comment]
Tried this with a multi-page pdf of a publication relevant to feature F050 in URAP. Kiosk is 0.11.12 and recording 10.7.1 and I expected the pdf, which can be found in the file repository by searching F050, to pop up in the recording now. Why doesn't it? It is not even a dummy, so not the same problem as the original ticket? Does it matter that it is multiple pages?

**Comment by lbestock** [comment]
This still seems to be a problem. I added two PDFs (single page ones in case that was the problem) to URAP 10.7.1, with kiosk 0.11.12. One I added through import and then assigned to context PG-001. The other I added through FM, also to PG-001. Uploaded, synchronized, downloaded again. Both are present in the File Repository as they should be, but neither is present in the recording system when I download it again, not even the one I put in through the recording system. There are four blank image containers in dayplans for PG-001 but none of them correspond to this activity. So not even a blank or broken image container - nothing at all to show that these PDFs are there and attached to this context.

**Comment by lbestock** [comment]
They are there! I thought they were not at first, but there they are. I added one to PG-001 through import, and one through the recording system itself, and then a synchronization cycle run, and both PDFs where they belong, as is the old F050 one. So, good, this lurking ticket can be closed.
