### ISSUE TITLE
all tabs are disabled and inaccessible until a locus has all errors in the flag group "lc_1_" taken care of

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1040]
### @test: recording 10.4.3

- [x] before there isn't a date defined, a description and a locus type the tabs are greyed out and clicking on them gives you an explanatory message
- [x] the closing date is only visible after a "date defined" has been stated

💎  This works only with the new config setting admin/locus_form set to "locus_edit_with_qce"

**Comment by luizaogs** [comment]
Currently the tabs remain greyed out until a description is also there; just filling out date defined doesn't give me access to them. Is that purposeful? Sending it back so you can check.

**Comment by urapadmin** [comment]
there is so much more to tell you about this, and since you jumped on it, you motivate me to write a piece on it in the wiki tomorrow. For the time being: 
- [ ] Yes, there are a couple of rules that block you from getting into the tabs
- [ ] when you change something to tackle an error it is often necessary to click somewhere else (clicking somewhere in the header always work, but most often even clicking somewhere on the background is sufficient) to make filemaker actually save the record and process my rules again. So if you add a description, next you need to click in the header or on the background.

This is all totally dynamic and configurable in the configuration under the new button "quality control". But that needs some explanation in a user's manual. I'll get there and then I will create new testing tickets.

**Comment by luizaogs** [comment]
Alrighty, I look forward to reading more in the wiki about it! But for this specific ticket -- you do not want the other tabs to appear immediately once date defined is there, if date defined is the only field filled in -- right? The other tabs should only appear once all errors in the initial locus form are filled in (date defined, description, and context type)? I think I got confused because I thought this ticket was testing that they would appear specifically after date defined was filled in, but it seems like that depends on the other errors being resolved as well.

**Comment by urapadmin** [comment]
yes, the title is too specific. I changed it. Every error in the group of basic rules makes the tabs be greyed out. 
Currently those are description, type and opening date. You see that in admin/quality control in the tab "flags". All flags with an id starting with "lc_1_" and the severity "error" are triggering the behaviour.

**Comment by luizaogs** [comment]
Got it, so all is well.

**Comment by urapadmin** [comment]
If only documentation weren't so much work:
[https://www.meritaten.net/urapdev/doku.php?id=manuals:user_manual:quality_control_for_admins](https://www.meritaten.net/urapdev/doku.php?id=manuals:user_manual:quality_control_for_admins)

**Comment by luizaogs** [comment]
But it is so appreciated, too. I had looked at the quality control configuration last night (because I am nosy) and this makes it make so much more sense, unsurprisingly. I like learning. And I also like the idea of an Omar flag :)
