### ISSUE TITLE
quality control: show qc-indicators in the locus list of simple excavating

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1045]

**Comment by urapadmin** [comment]
### recording 10.5
- [ ] the locus list in simple excavating shows a qc-signal (and it is a button) for every locus in the list - if there is something to signal
- [ ] one can click on it to get the messages for a locus
- [ ] a little button on top of the list column runs the rules again, just in case the system gets out of sync for some reason that I did not forsee
- [ ] the whole thing can be slow. Please report if it is unbearable
- [ ] the configuration key visibility/qc_show_in_lists determines whether this costly feature is turned on or off
- [ ] the configuration key general/qc_use_at_all turns it off as well - but it turns qc off not only here but everywhere

**Comment by luizaogs** [comment]
Not slow at all, actually, quite quick. I didn't have any problems.

**Comment by urapadmin** [comment]
you should have seen it on Uronarti's locus "FA" or "CC". It really depended on how many warnings and hints excavators were able to create in a single locus :o)

**Comment by luizaogs** [comment]
Ha yes, I guess PVD is a baby database.
