### ISSUE TITLE
quality control: configuration in the recording system

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1046]
### @test recording 10.5
quality control can be configured by these keys in administration / config:

- [x] general/qc_use_at_all: switch qc off everywhere. It should not appear anywhere anymore and performance issues - if there were any - should be solved
- [x] general/qc_insist_on_error: if turned on the locus form does not let you leave if there are a rule with severity error. Instead it shows you the current qc issues. But in the popup you find a red okay button that let's you leave the locus form finally.
- [x] visibility/qc_show_in_lists: decides whether or not your want to process qc rules in larger quantities. If this is turned off you will not see the button to process the qc rules for all loci in simple excavating. Turned off the locus list in simple excavating form should have the usual performance it had before qc.

**Comment by luizaogs** [comment]
'Tis all working perfectly.
