### ISSUE TITLE
PVD is now Uronarti

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1054]
I don't think a big deal at all but I'm definitely still in PVD (while in Brazil, funny) but Filemaker now tells me I'm in Uronarti ... in the banner of all recording forms. I figured this might be related to a template mix up so thought I would point it out! In 10.5.

**Comment by urapadmin** [comment]
Did I mix up templates? Looks like it :o) I'll attend to it. Also, I kinda wish you weren't in Brazil.

**Comment by urapadmin** [comment]
nope, that is a real new bug in the filemaker recording.

**Comment by luizaogs** [comment]
My feelings about being in Brazil are complex, but I think I would like to be in Uronarti.

**Comment by urapadmin** [comment]
### @test 10.5.1
that was a bug. Should be back to normal now.

**Comment by luizaogs** [comment]
I am indeed back in PVD.
