### ISSUE TITLE
change wording in file upload

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1069]
A request to change the wording to be more precise in file importing in the file repository. The language differentiating upload and import is too vague: "bunch" and "ton". We know the cutoff is 10. As I like bunch and ton, I recommend adding "(1-10)" after bunch, and "(more than 10)" after ton.

**Comment by urapadmin** [comment]
If you really mean this, okay ... But I do keep the descriptions?

**Comment by urapadmin** [comment]
by the way: The limitation is not 10 it is due to the limitation set in the kiosk config.

**Comment by lbestock** [comment]
It has really been confusing me since the very beginning; I never even remember which one is the big one and which small from the wording. So it does need to be changed, and I would find it most useful to have the actual numbers since there are actual numbers. I mean, ideally it sounds like it would be updated if the kiosk configuration were changed. But for the user, it needs to be both specific and accurate and how it gets there is beside the point.

**Comment by urapadmin** [comment]
### @ test kiosk 0.11.9
- [ ] done as requrested

**Comment by luizaogs** [comment]
So there isn't the "more than 10" in ton at the moment but my understanding from the comments above is that "more than 10" isn't necessarily the case, so I'm not sure if not including a number there was purposeful or not.

**Comment by urapadmin** [comment]
Indeed, I only added the number in Bunch. That should do.

**Comment by luizaogs** [comment]
Right, then I close this.
