### ISSUE TITLE
director's view banner misbehaves in iOS

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1076]
The director's view banner, where one chooses the date and trench and supervisor, floats strangely on the iPad. When one swipes the very top banner of kiosk up a space opens between that banner and the director's view banner. And then if one swipes up the page of content it scrolls so that one can see it between those two banners, making it look like the lower, director's view, banner is floating. This is not the case in Safari on the Mac, just on the iPad.
![51E8B1B7-961D-475F-88A4-0B13D1507865_1_105_c](https://user-images.githubusercontent.com/49291909/117742261-5909e000-b1d2-11eb-88db-111de5148010.jpeg)

**Comment by urapadmin** [comment]
### kiosk 0.13.13
Major change in layouting strategy! While it should be better on Safari I hope it won't be worse on real browsers since it is made for being used on a desktop and not necessarily for an ipad. 
- [ ] make sure it did not get worse on desktop browsers
- [ ] should be better on iOs Safari

**Comment by luizaogs** [comment]
It's definitely better on iOS Safari - I do not get floating banners. Landscape mode looks perfectly fine, but if I turn it to portrait the little menu in the files widget gets cut off (on the right of the screen below). Not sure if it's something you can change or whether it is worth changing, if you can but I thought I would mention it: 

![IMG_0253](https://user-images.githubusercontent.com/67970402/144248045-31ef4434-2262-4db2-81bd-d9fbc093b1d7.PNG)

**Comment by luizaogs** [comment]
Desktop Safari sometimes has a big gap between widgets but again not sure how relevant this is: 

<img width="1307" alt="Screen Shot 2021-12-01 at 8 06 54 AM" src="https://user-images.githubusercontent.com/67970402/144248805-ff2f15ef-dbd9-4137-9bc2-8e32c0ff0aa3.png">

**Comment by luizaogs** [comment]
Same spacing widget issue on Firefox, but it looks good on Chrome.

**Comment by urapadmin** [comment]
the spacing is more or less my design. The widgets simply do not fill the line so the question is how to align them. "Space between" is one solution and I used it here.

**Comment by urapadmin** [comment]
> It's definitely better on iOS Safari - I do not get floating banners. Landscape mode looks perfectly fine, but if I turn it to portrait the little menu in the files widget gets cut off (on the right of the screen below). Not sure if it's something you can change or whether it is worth changing if you can, but I thought I would mention it.
> 
> Oh and I hadn't noticed this before but you can also see it in the screenshot, that the contexts widget gets slightly cut off in portrait too (but all of the relevant information is visible).
> 

I can live with this for v1 on ipads. In the end this UI isn't made for ipads. It should look fine on Mac Safari and it seems it does, right?

**Comment by urapadmin** [comment]
> Same spacing widget issue on Firefox, but it looks good on Chrome.

That confuses me, though. How can it look good on Chrome? Can you provide a screenshot?

**Comment by luizaogs** [comment]
> > It's definitely better on iOS Safari - I do not get floating banners. Landscape mode looks perfectly fine, but if I turn it to portrait the little menu in the files widget gets cut off (on the right of the screen below). Not sure if it's something you can change or whether it is worth changing if you can, but I thought I would mention it.
> > Oh and I hadn't noticed this before but you can also see it in the screenshot, that the contexts widget gets slightly cut off in portrait too (but all of the relevant information is visible).
> 
> I can live with this for v1 on ipads. In the end this UI isn't made for ipads. It should look fine on Mac Safari and it seems it does, right?

Mac Safari has the spaces but sounds like that is purposeful, so yes.

**Comment by luizaogs** [comment]
<img width="1512" alt="Screen Shot 2021-12-11 at 3 27 12 PM" src="https://user-images.githubusercontent.com/67970402/145692154-568ff950-4df5-4c38-b96f-afe8f930d28b.png">

This is Chrome. No spaces, as you can see.

**Comment by urapadmin** [comment]
you know I always believe you, of all testers, right? I just really need to see it to have an idea what's different in Chrome. Can you please make a screenshot of your whole screen with chrome in full screen and one with Safari in full screen? I wonder if Chrome skips some very outer margin or so ...

**Comment by luizaogs** [comment]
I know :) I'm grabbing screenshots of the same day so you can compare them more easily.

This is Chrome full screen: 
<img width="1512" alt="Screen Shot 2021-12-11 at 6 45 15 PM" src="https://user-images.githubusercontent.com/67970402/145696328-d24f1804-afc3-4d31-810f-ccc24380465e.png">

Safari full screen:
<img width="1512" alt="Screen Shot 2021-12-11 at 6 46 33 PM" src="https://user-images.githubusercontent.com/67970402/145696353-1b5a842d-9911-45a1-9ea3-f12030d5a9b1.png">

<img width="1512" alt="Screen Shot 2021-12-11 at 6 47 14 PM" src="https://user-images.githubusercontent.com/67970402/145696357-ca9182db-264f-4763-a2c1-6446e1167748.png">

**Comment by urapadmin** [comment]
I'll keep the difference between Chrome and Firefox in mind: #1272 
But I think it works for V1 and can be closed, unless you object.

**Comment by luizaogs** [comment]
Ha, who am I to object? Just making sure though that you know the spacing is different from Chrome in both Safari and Firefox, since the new ticket only mentions Firefox.

**Comment by urapadmin** [comment]
In my opinion Safari is not a Browser.
But noted.
