### ISSUE TITLE
feature units and survey units missing a connection

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1078]
URAP the real deal 10.5.1. I am looking at the structure of what we set up to deal with Christian's students. I went to the feature unit Wheeler rooms I created. I was surprised to see that they were not "recorded in survey unit Block VIII" because I thought that was what I had done. I added a link in "recorded in" to a few of them. Only then did I step back out to look at that survey unit itself. There are all the feature units. If they are listed in (presumably MADE in) that survey unit, shouldn't they then automatically be "recorded in" that unit when one goes into the feature recording?

**Comment by urapadmin** [comment]
But first you should test if it works in your version, too. I used the playground.

**Comment by urapadmin** [comment]
I think we agree that this can be corrected in Urap without the help of a developer.

**Comment by lbestock** [comment]
And it has been corrected by the archaeologist.
