### ISSUE TITLE
there are windows flying to the dock on MacOs when minimizing the second window

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1080]
or at least I suppose that is what is going on

**Comment by luizaogs** [comment]
Dumb question ... what is the second window and how do I minimize it? There are still things flying to the dock (for example, when I added a dayplan) but I don't know if this is supposed to stop that, too.

**Comment by luizaogs** [comment]
Oh wow if I had known that you could fix this I would have noted it a long time ago. It works! (And if you got an email with my previous comment, since deleted, saying that it didn't work -- I was testing it in an old database. 10.5.2 is good.)
