### ISSUE TITLE
backup and restore need a way to upload and download

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1085]
sometimes I think some sort of download manager that does all the downloads for everything could be worth a central institution.
And plugins and all other parts just tell that download manager their destinations and their triggers. 

But this here is about downloading a backup file from Beset and uploading it for a restore

**Comment by urapadmin** [comment]
see also #1118

**Comment by urapadmin** [comment]
this is solved with #1118: The download manager allows access to the backup folder if a filemanager directory like this is configured:
![image](https://user-images.githubusercontent.com/38838314/123561024-507f6000-d7a6-11eb-91ce-ba4c1bb1737a.png)

Note that configuring filemanager directories is only available for users with the "manage server" privilege!

**Comment by luizaogs** [comment]
This is cool!
