### ISSUE TITLE
contextual descriptions appearing twice?

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1092]
Not sure if related to #974, but file repository shows the same contextual description twice even if the image only shows up once in the database and definitely only has that description once. Kiosk 0.11.8, happens in both USTP and PVD.

![image](https://user-images.githubusercontent.com/67970402/118361117-e2fdd400-b557-11eb-96f3-297cd4de8e29.png)

**Comment by urapadmin** [comment]
perhaps it is because there are two of them?

**Comment by urapadmin** [comment]
Monkeys, I mean.

**Comment by urapadmin** [comment]
so cute

**Comment by luizaogs** [comment]
Ha!! There are actually around 6 of them (very difficult to photograph at once), and I want one.

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/118379443-5f200800-b5a8-11eb-97b2-b7839b82cf73.png)
You must be onto something...

**Comment by lbestock** [comment]
(Sorry.)

**Comment by luizaogs** [comment]
That gets a laugh react.

**Comment by urapadmin** [comment]
you made the tree-time description up to mock me, right?

**Comment by lbestock** [comment]
Mock you? Definitely not. I did make it, but to show appreciation for your own joke and to send you the turtles we saw the other day.

**Comment by urapadmin** [comment]
### @test kiosk 0.11.9
All the animals should be still there but 
- [ ] descriptions from the same record type appear only once

**Comment by luizaogs** [comment]
Yup.
