### ISSUE TITLE
Cannot add workstation

### ISSUE THREAD

**Issue by cmrice-arch** [urapadmin/kiosk#1100]
![image](https://user-images.githubusercontent.com/68063513/118815929-b4496b80-b87f-11eb-9699-136a9468533f.png)

**Comment by urapadmin** [comment]
I suppose that is USTP, right? That is a side effect (and there are many others) of USTP being on such an old version in comparison to USTP-TEST. Currently you can use the actual USTP only to look at the file repository and to download existing workstations. What are you guys trying to do? If you just make your self familiar with the latest state of affairs, I suggest you participate in ustp-test. If you want to start, let's talk about your schedule and moving ustp-test to ustp.

**Comment by urapadmin** [comment]
continued in email ...
