### ISSUE TITLE
team dialog out of size on ipads

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1102]
the team dialog needed scrolling on ipads. That should really not be necessary.

**Comment by urapadmin** [comment]
that I cannot confirm on an ipad with 10.5.2. Looks okay on mine. I might have misunderstood where the issue occurred.

**Comment by lbestock** [comment]
Photo here in 10.5.3.
![image](https://user-images.githubusercontent.com/49291909/118886554-1c6f7000-b8c7-11eb-8c97-d30076594227.png)

**Comment by urapadmin** [comment]
Ah, that's starting it in portrait mode. That is only half supported.

Am 19.05.2021 um 17:25 schrieb lbestock - ***@***.***:

**Comment by lbestock** [comment]
You know what's really weird about this? If I open the team configuration dialog in landscape mode, and then rotate to portrait, it is fine. And then if I close it and reopen it, still in portrait, it is also fine. The problem only occurs when I open it for the first time in portrait. And I have a sense of deja vu - I think I have discovered that before. Well, maybe we should have a single ticket to fully support portrait mode, and simply refer to all particular issues that have arisen there. And then close individual tickets, like this one. But that is a developer call so I kick it back your direction while I sweat bullets about meeting Kevin tomorrow.

**Comment by urapadmin** [comment]
the fully support portrait mode (with rotation even) ticket you may file at filemaker's ticket system, not here. Filemaker does not support this properly.

**Comment by urapadmin** [comment]
I don't see what I could possibly do about this. This filemaker showing a window as a "card" and it should just work.
We have to live with this.

**Comment by urapadmin** [comment]
I close this because it won't-happen
