### ISSUE TITLE
define timezone per workstation

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1103]
Currently the expected timezone for a workstation is set by the server depending on the server's timezone. 

We need to set the timezone per workstation on the kiosk side.

**Comment by urapadmin** [comment]
### @test kiosk 0.11.9
- [ ] in the field manager when creating a workstation you can now state the time-zone in the format GMT+/-hh (if you are in Iran you can also state something like GMT+/-hh:mm)
- [ ] the field manager also allows to change that when using "edit workstation" from the workstation actions dialog
- [ ] when leaving the field empty the server's time zone will be used as a default (that is how it has always been so far)
- [ ] when preparing the workstation for the field this setting should determine how the recording system reacts

**Comment by luizaogs** [comment]
SO COOL.
