### ISSUE TITLE
modules/ceramic now decides which pottery processing method to use

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1107]
so far we had only Christian's warecode approach to pottery. Ingineous as it may be, not the whole world is ready for it, so we have an alternative for s'urachi and USTP will have a different approach, as well.
To account for different ceramic modules we have this configuration key now:
So far we have two modules: the "classic" warecode approach is "pottery_processing" and the new s'Urachi style module is 
"su_ceramics".

Of course, they cannot and must not be used parallel! Either a project is using the one or the other. This ticket should just make sure that Uronarti and PVD are using the pottery_processing approach.

### @test recording 10.6.2
- [x] modules/ceramics decides what happens when hitting the ceramics button in "registrar and specialists"

**Comment by luizaogs** [comment]
PVD is good, I can't test Uronarti. Not sure if this is enough to close this one (I did try both configurations to see if the ceramics module would change and it did).

**Comment by urapadmin** [comment]
No, I think this is okay. I close it.
