### ISSUE TITLE
the ghost of Nuraghe S'Urachi

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1108]
Sorry for the terrible title for this but I couldn't resist. After downloading 10.6.2 the automatic site that comes up is Nuraghe S'Urachi, but after I click on either PVD or Playground it disappears from the list. And if I log out and log back in PVD comes up automatically. 

Hence, a ghost.

**Comment by urapadmin** [comment]
I saw the ghost, too. And fixed it rather manually. So keep this open for a version later than 10.6.3

**Comment by urapadmin** [comment]
### @test recording 10.6.3
- [ ]the ghost of Nuraghe S'Urachi should have found its peace now

**Comment by lbestock** [comment]
I, too, saw him fleetingly earlier today. But he seems now to be departed for good, and I do hope at peace.

**Comment by luizaogs** [comment]
👻
