### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1109]
Uh ... help? Filemaker is closed and has been closed. This is USTP test 0.11.9.

![image](https://user-images.githubusercontent.com/67970402/119267689-b1bb7e80-bbbd-11eb-9f1c-f5da0097e155.png)

**Comment by luizaogs** [comment]
Perhaps of note both here and in the weird error mentioned in #441 is that it seems to go away after a bit. But I haven't tried exporting or importing again (in #441) in case you need logs.

**Comment by lbestock** [comment]
Different process with different error message but related to the same presumed crash of Filemaker all stressed out by our amazing levels of Sunday testing.
![image](https://user-images.githubusercontent.com/49291909/119267989-e7ad3280-bbbe-11eb-8474-fbc4bd9e512b.png)

**Comment by urapadmin** [comment]
That's a good one. It looks as if Luiza instead of pasting an image into the image container pasted the filename- Dumb Filemaker absolutely accepts that and then tries to make the text an image. When exporting that image it reports a even dumber filename and that is why the export stopped (which is my legacy dumb) and from that moment on a cascade of side effects unfolded. 
Cool.

I have now attended to both the dumb filemaker filename and my dumb stopping in the middle of export with a message box we cannot see on Beset.

**Comment by luizaogs** [comment]
Weird! I noticed I had done that accidentally and deleted that record, but I guess that wasn't good enough...

**Comment by urapadmin** [comment]
Perfectly fine on your side. It is just that we don't delete images from the gallery once they are in there. We just delete them from the container in the record type. The idea was that we rather deal with a few crap images than losing a single one. 
You would have still been able to find the image in the gallery (but, forget it, that wasn't easy even knowing it was there).

**Comment by urapadmin** [comment]
@luizaogs Your workstation file on Beset is manually fixed so that it can be imported (you have to chose "import again" from the options)

### @test recording 10.6.2
- [ ] This should not bother us again, no matter what a user tries

**Comment by luizaogs** [comment]
You know, if the user is me I don't know if that's true :) The Luiza vs. images saga continues.

**Comment by urapadmin** [comment]
because I was too slow :o)

**Comment by urapadmin** [comment]
now I am there

**Comment by urapadmin** [comment]
so you may try again

**Comment by luizaogs** [comment]
I did import again, so time for synchronization. For this one -- is there a way to test it or can we assume that no one else is going to manage doing what I did?

**Comment by urapadmin** [comment]
did you really? I did not see a thing here on the server.

**Comment by urapadmin** [comment]
could you just do it again, for my peace of mind?

**Comment by luizaogs** [comment]
Ok wait, I don't see an "import again" option so just did "import recording data" -- should I be clicking on something else?

**Comment by urapadmin** [comment]
sorry, My confusion. In a former version it was called "again". It seems it isn't anymore.

**Comment by luizaogs** [comment]
Ha ok well it is now importing [again].

**Comment by urapadmin** [comment]
good. This time I saw you :o)

**Comment by urapadmin** [comment]
so you may synchronize. Which might prolong the Saga.

**Comment by luizaogs** [comment]
Ha ha I can't wait...

**Comment by urapadmin** [comment]
but don't prepare workstations. I have to update first.

**Comment by luizaogs** [comment]
I won't. Synchronization was successful, it seems.

**Comment by urapadmin** [comment]
now you may marvel at your image in the file repository. You find it if you paste "e6a1033e-0d4f-454a-b575-c554507b1bd7" into the description.
Did housekeeping or synchronization mention the file?

**Comment by luizaogs** [comment]
Ah yes, I'm very familiar with the octopus.

Yeah it did, I'm pretty sure -- there were a gazillion warnings.

**Comment by urapadmin** [comment]
### @test recording 10.6.2
- [ ] This should not bother us again, no matter what a user tries

10.6.2 is now rolled out on Beset/PVD

Since this is something that can and will absolutely happen again one day, particularly now that people are using bloody windows filemaker (which is so bad with images), you are welcome to derail the system again with strange images that aren't any.

**Comment by luizaogs** [comment]
I'm supposed to mess up images on purpose now? I was born for this particular test.

**Comment by urapadmin** [comment]
Yes, go for it. We find these wonderful bugs that way.

**Comment by luizaogs** [comment]
Do you need to do whatever you did on PVD to USTP for that to work properly now, too, or is it ready to go?

**Comment by lbestock** [comment]
My god you guys wrote an epistolatory novel to one another through github while I was drafting a letter to Sheffield. I like your party better than mine. Time for ice cream.

**Comment by urapadmin** [comment]
ustp-test is up at verson 10.6.3 now, too. So that's ready to go.

**Comment by luizaogs** [comment]
Ok I did a lot of weird stuff and synchronization still worked, so I think this can be closed? I took screenshots of the synchronization warnings and housekeeping details (even though I think you can access this yourself in kiosk? I wasn't sure):

![image](https://user-images.githubusercontent.com/67970402/119366917-72556680-bc7f-11eb-844d-f42317fcd69c.png)
![image](https://user-images.githubusercontent.com/67970402/119366929-76818400-bc7f-11eb-84ad-00828017556f.png)
![image](https://user-images.githubusercontent.com/67970402/119366990-84cfa000-bc7f-11eb-9cbe-62a73fd21f00.png)
![image](https://user-images.githubusercontent.com/67970402/119367000-86996380-bc7f-11eb-908e-639c7cf2f7ed.png)
![image](https://user-images.githubusercontent.com/67970402/119367006-88fbbd80-bc7f-11eb-8f89-d2af4d9f78c6.png)
![image](https://user-images.githubusercontent.com/67970402/119367014-8ac58100-bc7f-11eb-983c-67d0537ab541.png)
![image](https://user-images.githubusercontent.com/67970402/119367021-8c8f4480-bc7f-11eb-9fb1-e2be4b1a5e6f.png)
![image](https://user-images.githubusercontent.com/67970402/119367029-8e590800-bc7f-11eb-9d6b-482659165dc5.png)
![image](https://user-images.githubusercontent.com/67970402/119367037-9153f880-bc7f-11eb-8e29-a0e0c537af17.png)
![image](https://user-images.githubusercontent.com/67970402/119367049-931dbc00-bc7f-11eb-917e-586d4fc464f2.png)

**Comment by urapadmin** [comment]
oof.
Well, what we can say is that the import is pretty robust at this point :o) It does not get derailed by a user with a mission to bring down the system. 

But now test has this huge number of images that are corrupt and they need to be deleted or they will bother us forever :o)
I will make a couple of new tickets coming out from that log

**Comment by urapadmin** [comment]
the easiest thing is to select all files tagged broken in the file repository and bulk delete them (using the star buttons and the trash can, which we can do now).
That does not catch the corrupted files, though.

**Comment by urapadmin** [comment]
did it
