### ISSUE TITLE
file picking: establishing a new context rule that should turn PBA to dummy did not do so

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1110]
Laurel made correct file picking rules that would have turned everything in "PBA" to dummies. When she downloaded her workstation the images were still there. This comes out of #file pic
They were executed correctly BUT because there was not a single change otherwise in the images table the new resolutions were not processed by filemaker because that script was not even started. 

this came out of #1000

**Comment by urapadmin** [comment]
### @kiosk 0.11.10
I did something about it. Changes in file picking rules should now be detected

**Comment by luizaogs** [comment]
I'm testing something else but noticed that images in PBA were now dummies so thought I would mention it here. I just downloaded a new database but am still in PVD 0.11.9, rather than 0.11.10.

**Comment by urapadmin** [comment]
that is okay, I did not actually roll 0.11.10 out to pvd but changed this one thing to test it there myself.
0.11.10 is now on its way to all of them...

**Comment by lbestock** [comment]
Works.
