### ISSUE TITLE
gallery button in dayplans only appears after another image is inserted

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1112]
I'm trying to screw up images for #1109 (and having fun, as you might imagine) and realized that the gallery button is only showing up in dayplans after I insert an image, which essentially means that I can't insert an image from the gallery without first adding something new. Seems odd?

**Comment by urapadmin** [comment]
so mean. This exists four times:
- [ ] simple excavating
- [ ] excavating
- [ ] pedestrian survey
- [ ] feature recording (not excavation/feature recording!)

**Comment by luizaogs** [comment]
I'm mean?! I mean yeah, I'm mean. But this is good now.
