### ISSUE TITLE
housekeeping: corrupt images need to be tagged much like broken images are

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1113]
so that it is possible to find them in the file repository
otherwise this horror would not be manageable:

![image](https://user-images.githubusercontent.com/67970402/119366917-72556680-bc7f-11eb-844d-f42317fcd69c.png)
![image](https://user-images.githubusercontent.com/67970402/119366929-76818400-bc7f-11eb-84ad-00828017556f.png)
![image](https://user-images.githubusercontent.com/67970402/119366990-84cfa000-bc7f-11eb-9cbe-62a73fd21f00.png)
![image](https://user-images.githubusercontent.com/67970402/119367000-86996380-bc7f-11eb-908e-639c7cf2f7ed.png)
![image](https://user-images.githubusercontent.com/67970402/119367006-88fbbd80-bc7f-11eb-8f89-d2af4d9f78c6.png)
![image](https://user-images.githubusercontent.com/67970402/119367014-8ac58100-bc7f-11eb-983c-67d0537ab541.png)
![image](https://user-images.githubusercontent.com/67970402/119367021-8c8f4480-bc7f-11eb-9fb1-e2be4b1a5e6f.png)
![image](https://user-images.githubusercontent.com/67970402/119367029-8e590800-bc7f-11eb-9d6b-482659165dc5.png)
![image](https://user-images.githubusercontent.com/67970402/119367037-9153f880-bc7f-11eb-8e29-a0e0c537af17.png)
![image](https://user-images.githubusercontent.com/67970402/119367049-931dbc00-bc7f-11eb-917e-586d4fc464f2.png)

_Originally posted by @luizaogs in https://github.com/urapadmin/kiosk/issues/1109#issuecomment-847102446_

**Comment by urapadmin** [comment]
### @test kiosk 0.11.10
Since the file repository is not only dealing with images but with all kinds of files, I cannot tell a corrupt image from a file that just is not an image. So:
- [ ] images that are corrupt should be tagged "NOT_AN_IMAGE"
- [ ] files that are not images are tagged the same
- [ ] if an image gets repaired (e.g. by uploading a proper image in the edit file dialog in the file repository) and housekeeping (or synchronization) runs again, the tag should go away automatically

**Comment by luizaogs** [comment]
When trying to replace the image in the file repository I got this:

![image](https://user-images.githubusercontent.com/67970402/119389652-4dbeb600-bca2-11eb-8c96-8d8fa87afeff.png)

And the image goes from octopus to broken file in the file repository after that, too:

![image](https://user-images.githubusercontent.com/67970402/119389689-59aa7800-bca2-11eb-82e9-28c43e0c72f9.png)

**Comment by luizaogs** [comment]
Oh, in case you need to find those two: 3740ffb2-52d5-4f5f-9988-3956c61039bc and 3cef97ac-3118-4497-9c18-abc67dc3cfff

**Comment by urapadmin** [comment]
Have I ever mentioned that I hate windows as a server operating system? This is likely to happen in all projects, so I have to grant additional privileges to all projects. Hmpf.

**Comment by luizaogs** [comment]
:) You have mentioned that before, yes.

**Comment by urapadmin** [comment]
you should be able to do this now in pvd

**Comment by urapadmin** [comment]
no, you still can't

**Comment by urapadmin** [comment]
this is more complicated than it seemed. I can replace other images in pvd, just not the NOT_AN_IMAGE images. So this needs some deeper digging.

**Comment by luizaogs** [comment]
Ok, I shall leave you to it!

**Comment by urapadmin** [comment]
### @test 0.12.2 
Hard to reproduce because the first iteration of the error was fleeting, so it appeared only once and after that the file could be replaced. But I understand why and have applied a few changes to suppress that. Once I was able to get the error repeatedly on a single image I was able to find out what access privilege on windows was missing. So this is for documentation: 
- It seems that IIUSRS needed modification rights (only, how was it able to modify anything in that directory without that?!?):
![image](https://user-images.githubusercontent.com/38838314/124365353-b3aa4000-dc47-11eb-9f4c-b258a4e4d36a.png)

- [ ] So I am not totally convinces this is solved. Please do what you were doing to produce these NOT_AN_IMAGE images in the first place and test again if it works properly now.

**Comment by urapadmin** [comment]
- [ ] If this solves the issue I have to make sure that all other projects have the correct privileges on windows level, too.

**Comment by luizaogs** [comment]
Worked! Not sure if I should close it before you check your own box above so I will not.

**Comment by urapadmin** [comment]
I have documented this in the installation notes for IIS in the wiki

**Comment by urapadmin** [comment]
#1181 follows up on this.
