### ISSUE TITLE
synchronization log: separating line above a log line that has ***** in it.

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1114]
We are talking about the success line in the log that separates housekeeping from synchronization. But the possibility to create a separating line using a code like "*****" can be of general use.

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/1084#issuecomment-847114500_

**Comment by urapadmin** [comment]
### @test kiosk 0.11.12
- [ ] there is now a blank space and a separating line between synchronization and housekeeping

**Comment by urapadmin** [comment]
just a not for the developer: Instead of ***** as a marker, a log line with a simple "-" and nothing else creates the said line.

**Comment by luizaogs** [comment]
Hmm, I see the line but I think it's in the wrong place? 

![Screen Shot 2021-06-22 at 8 57 36 AM](https://user-images.githubusercontent.com/67970402/122920581-eeeb6b80-d337-11eb-80a9-8182d4579c8c.png)

**Comment by urapadmin** [comment]
the line comes after synchronization has been completed. The rest is indeed aftermath. So that‘s okay.
