### ISSUE TITLE
disable workstations

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1117]
instead of deleting them one could disable certain workstations when they are not in use. Synchronization, prepare and all the stuff would ignore such a workstation.

**Comment by urapadmin** [comment]
this is useful enough to activate it again for v1

**Comment by urapadmin** [comment]
see also #1116

**Comment by urapadmin** [comment]
### @test: kiosk 0.11.12
- [ ] Workstation can be deactivated no matter of their state by clicking on them and choosing "deactivate" from the advanced options
- [ ] deactivated workstations do not partake in any of the bulk operations (prepare all workstations etc.)
- [ ] deactivated workstations can only be reactivated or deleted
- [ ] deactivated workstations show slightly translucent in the field manager

**Comment by luizaogs** [comment]
(this is very cool)
