### ISSUE TITLE
uploading database just shows 100% but does not give a real success response

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1120]
and I expected that. I could swear that once one got a success response.

**Comment by urapadmin** [comment]
hm. That does not happen locally in the development environment. Is that a Beset issue only?

**Comment by urapadmin** [comment]
no, not even that. It does not always happen at least on Beset. I just got a correct response on urap-test

**Comment by urapadmin** [comment]
definitely happens for urap on Beset and with the same file size that works locally.

**Comment by urapadmin** [comment]
hm. the line "        workstation_click.reload = true;" failed because workstation_click.reload is not defined. 
But wrapping it in a try/catch solved the issue.

**Comment by urapadmin** [comment]
### @test 0.11.13
- [ ] upload on URAP should end with a final notice that the download was successful

**Comment by lbestock** [comment]
(This is a hilarious ticket. In the space of half an hour you sang yourself a song with a chorus of "hm"s and then ended with a verse that makes no sense, for upload to end with a message about download. And then you went to meet a package delivery.)

**Comment by urapadmin** [comment]
This bug is now understood. This was a relic of the old workstationsmanager which is not loaded as a plugin in urap anymore.
