### ISSUE TITLE
newly created locus with multiple errors initially did not show up in director's view

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1121]
Came out of testing #31. Originally, when I was trying to see if errors showed up with the red icon in the director's view, I synchronized after opening a new locus while leaving it without the description, type, and opening date. It didn't show up in the director's view at all. After I went back in and added a type and the opening date, only leaving the description missing, it did show up in the director's view with a red icon as it should have. 

Not sure if that is purposeful -- if the locus shouldn't show up in the director's view if it was only created and no information was added to it -- or not, so I note it here.

**Comment by urapadmin** [comment]
no, that sounds very wrong. With "it didn't show up .. .at all" you mean the locus itself did not show up or it showed up but without the red icon? 
It really should appear if you chose that days date in the director's view. 
Could it be a Timezone issue? You create a locus in a timezone different from that of the server.
And remember that the Director's View shows the locus only if the last modification of that locus (or one of its relations or image) was on the selected day. If all locus changes occurred later again it would show only on that date.

If none of this gives you a hint what might have been the issue, please do it again until you are in Director's View again and a locus you expected does not appear. Then leave it and tell me which locus so that I know where to look.

**Comment by luizaogs** [comment]
The locus itself did not show up, and it only did show up after I had added the type and opening date. But no, I don't think it's any of what you say here because other loci I created at the same time showed up, and after I added information to that same locus it also showed up. I'll retrace my steps and try this with a new locus later today and let you know.

**Comment by luizaogs** [comment]
Right, just did it again, same issue: 

I created three new loci in Playground, in unit LA test: LA test-004, LA test-005, and LA test-006, and added different levels of information to see what might happen.

For LA test-004 I just added a recorder to see if adding information other than the three categories that create errors (type, opening date, and description) would make a difference. 

For LA test-005 I added nothing at all.

For LA test-006 I added a recorder, a locus type, and an opening date (did not add a description). 

If you look at the director's view for today you will see LA test-006 there as it should be, with the red icon pointing to the fact that it still needs a description. But you will not see LA test-004 nor LA-test 005, I presume because none of those three error categories were filled out for either of them (or at least, this is the only pattern that I can see). Or maybe it is because they have no opening date?

**Comment by urapadmin** [comment]
I will find out on the basis of your test data.

**Comment by urapadmin** [comment]
this can concern arch1900, so I add Anna

**Comment by urapadmin** [comment]
Okay, I see this has nothing to do with the quality control messages. 
Loci without a type are suppressed. And that is true for both LA test-004 and -005 but not for -006. If I amend the type LA-004 shows up. I'll have to dive a bit deeper to find out WHY this is happening.

**Comment by urapadmin** [comment]
### @test kiosk 0.11.11
Should look like this now:
![image](https://user-images.githubusercontent.com/38838314/120892219-7e411100-c60d-11eb-96fd-b2855bf89132.png)
And it should show the correct quality control hints

**Comment by urapadmin** [comment]
ah. my favourite Brazilian tester is still on it. Good to see you :o)

**Comment by luizaogs** [comment]
Ha! Olá :)

**Comment by luizaogs** [comment]
I thought this was fixed but I just had the same problem with context LA-018, which didn't show up in the director's view at first, only after I added a type. Not sure if best to reopen the ticket or open a new one...

**Comment by urapadmin** [comment]
first I'd like to test if this is really the same issue. There can be other reasons why a locus does not show up and adding a type might have affected those reasons. Can you describe the case in question a bit more and perhaps try to reproduce the issue?

**Comment by urapadmin** [comment]
well, I reopen it anyhow, we can close it again when we know more.

**Comment by luizaogs** [comment]
I created locus LA-018 to test #1072. At first I didn't add anything to the locus. Imported and synchronized the database, nothing in the director's view. Since I remembered that the type had been a problem before, I then downloaded it again and added the type, imported and synchronized. It appeared in the director's view at that point, and if you go on it now you'll see that the other warnings are still there as they should be, but the type is recorded. 

I can try testing again -- would something like I did above be helpful, or do you want me to do something different?

**Comment by urapadmin** [comment]
okay. The description helps me to reproduce it myself and examine it live. Thank you.

**Comment by lbestock** [comment]
Is #1210  related to this? At least it's a type issue.

**Comment by urapadmin** [comment]
### kiosk 0.13.6
hm. Scary how some things pop up again. This was indeed again an issue with loci that don't have a type. It is fixed, again.

**Comment by urapadmin** [comment]
by the way: For some reason I explicitly suppress loci of type SU entirely here. I am not so sure why, but there it is.

**Comment by luizaogs** [comment]
Seems good now!
