### ISSUE TITLE
command to prepare workstation pends forever

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1122]
PVD 0.11.10. Happened a couple of days ago, too, but I thought it was a problem with my internet but now it's happening again so I don't think so. Workstations get stuck in "pending" after I try to prepare them, and they seem to stay there indefinitely unless I stop the job.

**Comment by luizaogs** [comment]
Oh, would resetting help? Well I won't do it now in case you need to see whatever is happening.

**Comment by urapadmin** [comment]
in the Hotel Lobby. Perhaps just refreshing your Browser or logging in / out helps. Sometimes one just doesn‘t get the progress reported anymore.

**Comment by urapadmin** [comment]
no, Brown has restarted the server again and we have to restart a part of it manually. Can‘t do that in the next hours.

**Comment by luizaogs** [comment]
There's no rush of course, just thought you should know.

**Comment by urapadmin** [comment]
I sure should since that affected all projects. It is restarted now so I close this.
