### ISSUE TITLE
Context Type Addition?

### ISSUE THREAD

**Issue by cmrice-arch** [urapadmin/kiosk#1126]
Can we add "Structural" to the list of context types for Vacone?

**Comment by urapadmin** [comment]
yes, you can do that yourself:
1. download a workstation if not already done
2. log in as admin (pwd admin)
3. in the admin pane on the start page you find "locus types"
4. add a new record and add your information. E.g. like this:
![image](https://user-images.githubusercontent.com/38838314/120824163-28de0480-c526-11eb-9582-9479b43c3161.png)

that will add a new locus type that you can select after creating a locus. But that locus type has no additional fields to record. Not sure, what "structural" is, so I can't say if any of the available field sets help you. However, you can select a predefined field set from the list box. The short id should be self explanatory.

If you need a different set of fields to record with your context type that would be an extension I'd have to provide.

**Comment by urapadmin** [comment]
oh, forgot what might be obvious: After your have created your new locus type you must synchronize this workstation to make it available to all future downloads.

**Comment by cmrice-arch** [comment]
Success!
