### ISSUE TITLE
date of creation for unit displays as Latin only

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1128]
Observed in ARCH 1900 10.5.3. When creating a unit and inputting the date via the clock button, the date has the usual format: 6/5/2021. When one then opens that unit, however, the date of creation is shown only in Latin: 5 VI 2021. That is the case whether or not "show additional Latin date" is configured. I think we want all date fields to display the same way, and not everyone will use Latin dates or understand what that means. So that field should be changed to show the US style dumb date, and should get the additional line below interpreting it into Latin if that's configured. Not quite a bug, but not quite a request either, so I'll let you figure out how you want to file it.

**Comment by urapadmin** [comment]
What I cannot acknowledge here is that if you have configured use_latin_date to be nope, that you still have a latin date. I don't. The field shows either the normal date or - if configured - the latin date.

Why does it seem to do it differently than other fields? Well, it is not an input field. Only input fields have the additional latin date.

**Comment by lbestock** [comment]
The confusion arose because Latin dates exist in two different places in configuration. In labels and in visibility (the latter being the one I was using that confused me here). Are they both necessary, or redundant?

**Comment by lbestock** [comment]
If I set "show additional latin date" in visibility to "yup" while "use Latin dates" is set to nope then I get European style Arabic numeral dates, not Latin dates, as the additional dates (so 26.7.2021). Is that what is expected? I can see it might be desired but it is not intuitive to get there from a combination of nope and yup for displaying Latin dates.

**Comment by urapadmin** [comment]
configuration keys are not necessarily meant to be intuitive, yup and nope for sure are not -> user's manual. The "show additional latin date" controls whether or not the additional label under an input field appears at all. The "use latin dates" controls whether or not dates in either those labels or in labels that are without an input field show in latin format. The combination you created just does not make any sense and so should not be applied in the configuration.
