### ISSUE TITLE
new config key: visibility/allow_change_material_type

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1129]
### @test recording 10.7 
this config key controls whether or not the material can be changed after a collected material has been created

**Comment by lbestock** [comment]
Works and is funny to test in S'Urachi since of course the material type has become part of the unalterable identifier. So you then get xxxB (plaster) which should not be. But also needs to be. So I definitely set it back to "nope" in lightspeed for this version we will give Peter.
