### ISSUE TITLE
new config key: valuelist_su_ceramics_prepros_cat_1 / valuelist_su_ceramics_prepros_cat_2

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1130]
### @test: recording 10.7
valuelist_su_ceramics_prepros_cat_1 and valuelist_su_ceramics_prepros_cat_2 under valuelists are the two valuelists used in the su-style ceramics preprocessing in collected material

**Comment by lbestock** [comment]
Not just extant, extant and working as expected.
