### ISSUE TITLE
new identification function "idgen_material"

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1135]
generates an archaeological identifier on the basis of a material selection as described here [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:context_identification_-_generation_functions](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:context_identification_-_generation_functions)

**Comment by urapadmin** [comment]
### @test recording 10.7
When creating a new collected material in SU a material selection should pop up and the result should be an identifier that meets the s'Urachi requirements for a bag label.

**Comment by lbestock** [comment]
This is another one of those "oh that's a consequence of the whole package becoming such a package that hadn't occurred to me". That an identification method could be based on material selection. But I do not understand how this results in the proper code being applied. One will set codes separately like one assigns ranges to workstations is what the "other_code=O"?

**Comment by lbestock** [comment]
Well without realizing I was coming to understand it, I have successfully implemented the codes S'Urachi actually uses, so this here can be called a clear success and closed.
