### ISSUE TITLE
count and weight in second stage diagnostic processing for SU are text fields

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1145]
And should I think be numerical so that totals can be easily arrived at?

**Comment by urapadmin** [comment]
oh yes, that‘s bad.

**Comment by urapadmin** [comment]
Wait. You mean in the ceramic analysis  that is accessible through the registrar pane? That is just a 100% copy of their own filemaker database. I have not changed anything there. There is no dedicated weight at all.

**Comment by urapadmin** [comment]
In the preprocessing (which I call the part that is attached to collected material) I have at least made sure that bloody filemaker does not accept a letter for a number, which it happily did.

**Comment by lbestock** [comment]
I meant in the part you made:
![image](https://user-images.githubusercontent.com/49291909/121264020-7e971180-c884-11eb-96ef-835dec7289d5.png)

**Comment by urapadmin** [comment]
ja. Welcome to filemaker. Those are number fields and filemaker allows you to enter text into it. 
Not anymore in 10.7.1
