### ISSUE TITLE
s'Urachi opening a new ceramics SU to analyze leaves the last record visible

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1147]
Hard to explain but confusing.
I create a fragment record in one SU.
I then want to move to recording fragments from a different SU, so I go up to the little icon that lets me choose a new SU. I choose it. 
My last made record stays visible even though I have just opened a new SU that has no records in it. The banner reflects the confusion, having switched to the SU I just chose but still having the fragment number of the previous fragment in a different SU up there.
Choosing a new SU to analyze should result in a blank - anything else is confusing.
![image](https://user-images.githubusercontent.com/49291909/121255069-fa8b5c80-c878-11eb-9c34-7b78a3b03c45.png)

**Comment by urapadmin** [comment]
### @test 10.7.1
- [ ] That's done. 
- [ ] but there were similar issues when going in from the start menu after a former selection was still active. When coming in to the module nothing should be selected at all.
