### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by cmrice-arch** [urapadmin/kiosk#1149]
We keep getting this error: 
[image](https://user-images.githubusercontent.com/68063513/121370924-21926e80-c90b-11eb-9708-0d2b3b10d7c6.png)

I thought we had fixed it by allowing network sharing, but it keeps happening and seems not to be consistent. I have double checked that I have the correct file and it has absolutely been opened and modified.

**Comment by urapadmin** [comment]
We? As in all of you? Or is this about a single workstation?

This is usually pretty strong evidence that the file that had been successfully uploaded (you did see the upload going up to 100%, right?) is really not the file that you worked in. Can you tell me what you last changed in that file so that I can double check if that change is in there? (please don't upload again for the moment)

And how does what kind ofnetwork sharing play into this?  Did you have to enable network sharing in filemaker?

**Comment by urapadmin** [comment]
and what does it mean that it does not seem to be consistent? Can you elaborate on that?

**Comment by cmrice-arch** [comment]
It's happened to me several times, and also to James. On consistency, it will eventually upload, but it's not clear why it has uploaded successfully that particular time (same file, just trying repeatedly after logging out, opening and closing file again, etc.)

I got a warning that I had not enabled network sharing when I opened FileMaker for the first time, and thought that might be the issue so I enabled "Share with FileMaker Clients". 

The easiest change to look for would be a context under Trench 5.

**Comment by urapadmin** [comment]
which workstation are you using?

**Comment by urapadmin** [comment]
I mean the one that causes trouble right now

**Comment by cmrice-arch** [comment]
Candace's laptop.

**Comment by urapadmin** [comment]
The network sharing - who knows, why filemaker keeps asking this - is not related. 

This is really odd, we have never had a behaviour like this in our tests. The database I find on the server is marked indeed as not having been opened, so the server is correct in its reaction. When I opened that very database using your account the marker was correctly set to "has been opened" right away and if I uploaded this now, it would presumably work.

The last contexts I see changed here are: 1323 (more or less empty deposit without even a recorder) and 1262, structural, (Waterprrof plaster). Is that correct?

**Comment by urapadmin** [comment]
IF you reenter the database please go to the configuration and into the section "system" where you should find a key "has_been_opened". Is that set to true?

**Comment by cmrice-arch** [comment]
Ah, 1323 is one that I entered to test if it was working. And it was part of the upload for which I got the error.

**Comment by cmrice-arch** [comment]
And yes, it is set to true

**Comment by urapadmin** [comment]
ja, the database is from around 9:30 and the changes have been applied around 10:30 or so. What I really do not understand is what circumstances different from our usual test scenario keep the has-been-opened marker from getting set.

**Comment by urapadmin** [comment]
then please upload this very database now.

**Comment by cmrice-arch** [comment]
Done, and uploaded fine this time.

**Comment by urapadmin** [comment]
seems it works now

**Comment by cmrice-arch** [comment]
Weird

**Comment by urapadmin** [comment]
Agreed. I have no clue, honestly. But you know now what to look for. 
Before you upload again next time, please look at that marker. If it isn't set to true, the upload would fail exactly the way you keep seeing. Should you go there at any time and see it set to false, please close filemaker immediately and send me the database via email. The marker gets set when you log in with your account in filemaker. 

Wait, do you, perhaps get any messages after the login? Something about timezones or whatnot? Or are you transported directly from login to the start page?

**Comment by cmrice-arch** [comment]
I get no messages after login. It goes directly to the start page.

**Comment by urapadmin** [comment]
I have a hunch. The marker is being set reliably only if the "logout and close" button is used. If filemaker is closed with the windows X or via the taskbar or any such thing, it is likely that the marker does not get set. 

I'll give you a new intermediary version ...

**Comment by urapadmin** [comment]
yup. Version 10.3.something b is installed now for ustp. Let's see if that helps in the next rounds.

**Comment by urapadmin** [comment]
### @test recording 10.7.3
This is for the next regular release, I have already rolled out this feature to an intermediary ustp version. 
- [ ] Test if the "has_been_used" marker in config/system gets reliably set when entering a freshly downloaded database. Do it immediately after download, don't use "logout and close" in between.,
