### ISSUE TITLE
cannot prepare for field USTP

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1152]
In attempting to download other databases to test #1151 (um, and to see if I could upload my fancy drone QR code photo from ARCH 1900 today) I have run into inabilities to download or prepare for the field. On ARCH 1900 Beset that was stated to be a timezone issue and I thought little of it since the master isn't online anyway - I would have texted to ask you about it but you are (trying to be) asleep. But then with USTP I got this:
![image](https://user-images.githubusercontent.com/49291909/122299275-c690e680-cecb-11eb-8bd6-7a0d2b1986af.png)

And that struck me as weird and also as potentially related to the #1151 problem itself. I won't even pretend to attempt to prepare or download a workstation other than my own from a project that is actively using it, but if I can't then my guess is Candace and Tyler are running into problems, too. And there is a suspicious plethora of workstations at "synchronized, needs preparation". So: added to this ticket - are you guys able to prepare workstations or do you get the same error I get above? And also will you guys please take a look at #1151 and see if the gruesome bug encountered there is one you have run into in your latest edition? It's new and nasty.

**Comment by lbestock** [comment]
I am able to prepare and download URAP, however.

**Comment by cmrice-arch** [comment]
Hmm, Tyler and I are able to prepare and download. But I tried Connor's since it's not in use anymore and it would not fork.

**Comment by urapadmin** [comment]
This here (and the issue with Connor's workstation) is just a legacy issue. Those workstations were old ones and I just deleted them. And created Laurel's again and everything is fine,

**Comment by urapadmin** [comment]
the arch1900 server is not set up properly for preparing workstation 
etc. You cannot use it.

Am 17.06.2021 um 00:00 schrieb lbestock - ***@***.***:
