### ISSUE TITLE
broken FM file

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1153]
I downloaded URAP and it is a big file - 633MB (unexpectedly big since I set the file picking to dummy). It took a long time, as usual, both to prepare and to download. Normal. I can't open the file, and it says it is damaged, which has never happened to me before:
![image](https://user-images.githubusercontent.com/49291909/122391955-75233e80-cf41-11eb-81ba-96ebeae335a9.png)

FM Go 19.2.2 but that shouldn't be an issue.

**Comment by lbestock** [comment]
Tried a different workstation for my Mac and had more or less the same problem except that it is a much smaller file, so file picking was applied. But still tells me it is damaged and cannot be opened, telling me to use the recover function. Can this be an effect of having changed a filepicking rule while a workstation in the group was in the field? 

On the laptop I was able to run recovery, as FM asked me to. I did so and got this message:
![image](https://user-images.githubusercontent.com/49291909/122393542-f929f600-cf42-11eb-8375-a1a1a251a493.png)

And that file I am able to open, though of course not use since it's got the wrong name.

**Comment by urapadmin** [comment]
Please be more precise. Which workstation exactly was the first one. Was that in the default group? Were they both in the default group? And did you prepare both of them while the rule for default was set to dummy?
I don't understand how one workstation can turn out so big (unless it was prepared at a much earlier time when the rules were different) and the next one is small.

That's for that. As for the filemaker issue: Great. Filemaker is getting less and less reliable. I suppose the group's template is kaputt. Please try the option "reset recording group" on one of the workstations of that recording group. But before you can see it that workstation needs to be in state "synchronized". And all other workstations of that group need to be in state "synchronized", too, for it to succeed. 

After that the group's template is replaced by the original template and I suspect that the error is gone. In which case this is a step that needs documentation for the admin.

**Comment by lbestock** [comment]
The first workstation was Laurel's iPad and the second RI Hall 101, both in default. I had reset Laurel's iPad and prepared for the field after resetting the file picking rule I believe, but I cannot swear to the order only that I would have understood why the order mattered. You don't believe it yet, and your disbelief makes sense to me. So now I will try the reset thing.

**Comment by lbestock** [comment]
Worked!

**Comment by lbestock** [comment]
Whoa then I get on my iPad and I am wondering if I have a cache problem or something. I haven't even tried to download yet but when I log in this is what the field manager looks like, and this is not what the field manager should look like:
![image](https://user-images.githubusercontent.com/49291909/122433216-03a8b780-cf64-11eb-9fed-48510a3e5fa0.png)

The statuses of all the default workstations are correct but those floating downloaded messages scare me - why are they where they are and why are they so long ago?

**Comment by urapadmin** [comment]
because you are on a mac, squeeze your browser window to a problematic width and my layout has flaws. 
But also, you need to give me more information, really. What browser is this? 
It might be safari. Then you are looking at the download labels that belong higher up. So you are seeing the Swansea downloads. If those dates scare you, talk to Christian. 

This is how it looks when it looks right: 
![image](https://user-images.githubusercontent.com/38838314/122434358-50f24c80-cf97-11eb-9b4b-aa5000a94822.png)

Except that now you have downloaded again. 
So no cache problem, no issue at all, just a little layout flaw.

**Comment by lbestock** [comment]
But I successfully downloaded a nice small URAP from my iPad workstation and so at least this whole thing seems to be gone except that you want to document the reset of workstation group thing for admins.

**Comment by lbestock** [comment]
Downloaded AND OPENED.

**Comment by urapadmin** [comment]
What worked? 
Can the original issue be closed?

**Comment by lbestock** [comment]
Yes.

**Comment by urapadmin** [comment]
except for filemaker destroying the files bit by bit. Hmpf.

**Comment by lbestock** [comment]
(And I was on Safari on the iPad, and yup, those are Christian's dates.)

**Comment by urapadmin** [comment]
at least you know now what to do if it happens at this stage (after downloading). It is not a good solution to recover a downloaded but corrupted file and then work in it. Always go back, reset the recording group and prepare a new file. All workstations that stem from that recording group would be corrupted.

**Comment by urapadmin** [comment]
Safari on the iPad is crap.

**Comment by urapadmin** [comment]
dumb crap

**Comment by lbestock** [comment]
Oh no I just ran into a version of this again. I downloaded my workstation (ldb_mac, PVD, kiosk 0.12) and it worked just fine. Then I reset the workstation (only the workstation, not the group). Defined a new file picking rule. And then "PVD2021.fmp12" is damaged and cannot be opened.

**Comment by urapadmin** [comment]
well, at least you know now what to do

**Comment by urapadmin** [comment]
clear error messages or screenshots are really helpful, though. I can only suspect that this is filemaker itself telling you that the database is damaged.

**Comment by lbestock** [comment]
I took one, just hadn't uploaded it. 
![image](https://user-images.githubusercontent.com/49291909/124201856-17e1ce00-daa7-11eb-9d3e-bd15f9529916.png)
Yes, FM itself telling me the database is damaged.

**Comment by urapadmin** [comment]
Nothing I can do about it. You must reset the recording group and 
prepare your workstation again.

Am 02.07.2021 um 02:01 schrieb lbestock - ***@***.***:

**Comment by urapadmin** [comment]
and then please close this again

**Comment by lbestock** [comment]
Helped to be able to reset all the workstations collectively first. Done. Fine.

**Comment by urapadmin** [comment]
and there we are again. This time it has hit urap and it happened repeatedly.

**Comment by urapadmin** [comment]
found something: Source and Destination had a difference of 4 bytes and I wonder if maybe filemaker is too slow closing the file before it gets copied. I have raised the waiting time up to 3 seconds (which is really a hack). After  copying the template to a workstation, source and destination will be compared to make sure they have the same size now. At least that should give us an error in kiosk instead of a broken filemaker file.

**Comment by urapadmin** [comment]
- [ ] I should try to close the filemaker file explicitly. There is a fm_doc attribute in FileMakerControlWindows so I could do that.

**Comment by urapadmin** [comment]
### @test kiosk 0.13
This might indeed solve the issue, in which case we don't have filemaker screwing up its own file but just filemaker limping behind. Unfortunately all we can test here is whether or not or occurs again. If so, please tell me right away.

**Comment by lbestock** [comment]
Hmpf I will in fact close this; we'll reopen it if we run into it again but there is no test to perform.
