### ISSUE TITLE
QR code unreadable

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1154]
Granted it was pretty small, in a photo at not very high resolution, and pretty glarey. I have just come to expect the QR code to work, and when I noted in a text that it had not I was asked to make a ticket. So: here is a ticket :) Honestly I would probably chalk this one up to a photography problem not a software problem.
![DJI_0039 (1)](https://user-images.githubusercontent.com/49291909/122431274-4d909e00-cf62-11eb-9a46-4e8a1fbfc7da.JPG)

**Comment by urapadmin** [comment]
It is not quite a software problem but it is also not super glarey. Rather smushed. So one thing one should keep in mind is that one should wipe the ipad before using it as a qr code. But I will still one day look into this one and see if I can squeeze more out of it. It does not look totally lost to me.

**Comment by urapadmin** [comment]
is that the closer photo? There was another one, that also did not work, you said.

**Comment by lbestock** [comment]
I didn't even try the farther away one - that was the one that I texted you yesterday from the field, and you noted that there was a qr code in it. I wasn't trying to make that a qr code photo, it was just left over still there from the lower down shot.

**Comment by urapadmin** [comment]
give it to me here.

**Comment by lbestock** [comment]
A bunch of them here. I only tried the one; perhaps some of the other closer ones will work without further adjustment.
![Photo_6553639_DJI_39_jpg_4304748_0_2021616155948_photo_original](https://user-images.githubusercontent.com/49291909/122435913-68fda800-cf66-11eb-8b0d-a4babcd7c6f2.JPG)
![Photo_6553640_DJI_40_jpg_4218176_0_20216161600_photo_original](https://user-images.githubusercontent.com/49291909/122435921-6b600200-cf66-11eb-9089-178c4104f94d.JPG)
![Photo_6553641_DJI_41_jpg_4163140_0_202161616040_photo_original](https://user-images.githubusercontent.com/49291909/122435928-6bf89880-cf66-11eb-9f83-aa6f62adea70.JPG)
![RemoteMediaFile_6553639_0_2021_06_16_15_59_48](https://user-images.githubusercontent.com/49291909/122435934-6d29c580-cf66-11eb-9dca-a56e8628076a.JPG)
![RemoteMediaFile_6553640_0_2021_06_16_16_00_00](https://user-images.githubusercontent.com/49291909/122435939-6dc25c00-cf66-11eb-8789-dc6bf548c4bf.JPG)
![RemoteMediaFile_6553641_0_2021_06_16_16_00_40](https://user-images.githubusercontent.com/49291909/122435946-6ef38900-cf66-11eb-996b-9f6132d28b1e.JPG)

**Comment by urapadmin** [comment]
please give me correct and complete error messages as kiosk reports them. "not readable" might have just meant that the configuration wasn't correct. See: #1199

**Comment by urapadmin** [comment]
no, the drone's resolution wasn't enough in these cases (and jpeg is not a good format since it is not lossless).
![image](https://user-images.githubusercontent.com/38838314/132418058-bc6c83fa-3f94-468a-9253-2ef66b0bd8df.png)
