### ISSUE TITLE
sync manager safari does not show the layout correctly

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1156]
Whoa then I get on my iPad and I am wondering if I have a cache problem or something. I haven't even tried to download yet but when I log in this is what the field manager looks like, and this is not what the field manager should look like:
![image](https://user-images.githubusercontent.com/49291909/122433216-03a8b780-cf64-11eb-9fed-48510a3e5fa0.png)

The statuses of all the default workstations are correct but those floating downloaded messages scare me - why are they where they are and why are they so long ago?

_Originally posted by @lbestock in https://github.com/urapadmin/kiosk/issues/1153#issuecomment-863366755_

**Comment by urapadmin** [comment]
why they are so long ago is something I can't tell anymore. But the layout issue can be tackled.

**Comment by urapadmin** [comment]
iOs 15.1 still has this bug. Apple is unbelievable.

**Comment by urapadmin** [comment]
iOS 15.1 (and lower) Safari messes up the "new" css grid. Apple. I switched to flexbox.

**Comment by urapadmin** [comment]
### kiosk 0.13.13
should work now in Safari (and still in all other Browsers, of course). Please check on Mac Safari.

**Comment by luizaogs** [comment]
Looks fine (I looked at iOS Chrome and Safari, and desktop Chrome, Safari, and Firefox).
