### ISSUE TITLE
permanent download workstation

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1162]
In order not to give every single user a single login just to download stuff a workstation that can permanently be downloaded (but never uploaded) would be useful. -> arch1900

**Comment by urapadmin** [comment]
### @test 0.12.1
- [ ] we have a new "options" field now for filemaker workstations. It takes a semicolon - separated list of options (not blanks between the options!)
- [ ] there is only one real option now: PERMANENT_DOWNLOAD. When switched on workstations can be downloaded over and over again. 
- [ ] such a workstation will never offer the upload option

**Comment by luizaogs** [comment]
Just to check: it also should not show that it's in the field, yes?

**Comment by urapadmin** [comment]
that is correct. The objective here is to enable a bunch of students to download the same filemaker db from thr same workstation as often as they like.

**Comment by luizaogs** [comment]
Tis working, then.
