### ISSUE TITLE
pdf image upload unexpected error

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1168]
I attempted to upload an image with no checked boxes about how to find context or time to URAP (dangerous, but I would have deleted it). I did not expect it to fail and I do not really understand the message. This might be a ticket about a message needing more information, not a bigger problem, but I cannot tell.

![image](https://user-images.githubusercontent.com/49291909/124530717-1122c600-dddb-11eb-9df8-18ca5a3cef8e.png)

This is on LDB's Mac, in kiosk 0.11.12. Happened with PVD 0.12.3, too, but I cannot isolate what makes it happen. I thought at first I might have tried to upload pdfs that weren't actually on my computer, were cloud files in dropbox. But I discovered quite to my surprise that those I can actually upload successfully; I see them in the dialog box when I am choosing files to upload as having 0 bytes, and then I choose them and they upload properly and are there, and then it is clear that kiosk triggered a two step thing - downloading it to my computer (where subsequently it is no longer 0 bytes) and uploading it to the file repository. So, that's quite cool. But it means I haven't a clue as to why I am sometimes getting that message.

**Comment by lbestock** [comment]
(It's also not an image that should exist already in URAP, so that can't be the reason.)

**Comment by urapadmin** [comment]
please give me the pdf

**Comment by lbestock** [comment]
[Scan May 12, 2019 at 1.56 PM.pdf](https://github.com/urapadmin/kiosk/files/6771489/Scan.May.12.2019.at.1.56.PM.pdf)

**Comment by urapadmin** [comment]
That was the filename. Spaces in filenames. Not my friends. 
### @test 0.12.4
- [ ] spaces and whatnots in the filename will work now

**Comment by luizaogs** [comment]
Tried the same file in PVD, worked.
