### ISSUE TITLE
typos in mass tagging menu

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1169]
Annoyingly picky Luiza is back. Sorry. 

I believe it should be "tags none of the marked files HAVE" though I always struggle with this (damn English), and "others" does not need an apostrophe.

![Screen Shot 2021-07-08 at 12 53 59 PM](https://user-images.githubusercontent.com/67970402/124954721-c5476b00-dfec-11eb-8159-f8088143fab0.png)

**Comment by urapadmin** [comment]
others is a clear case, of course. 
The plural / singular question about "none" is a funny debate, even an ontological debate: Is "none" one or many? Some claim that etymologically "none" comes from not one and think that makes it singular (still debatable) others claim that it is a myth that none comes from "not one". The humanities in a nutshell, I'd say.
Here we are in software development and so my pragmatic conclusion is: A grammatical case so debatable should not be on a UI. So I will rephrase :o)

**Comment by luizaogs** [comment]
Ha, that’s why it always confuses me! I think if you only had “none” in there you could definitely use either verb, but since the noun marked files is plural you need the plural verb, otherwise it looks odd. Or at least, that is what tipped me off.

**Comment by urapadmin** [comment]
doesn‘t „none of“ usually comes with a plural?

**Comment by luizaogs** [comment]
I think it still depends on the noun that follows it? If you said, for instance, “none of it,” you’d still want a singular verb.

**Comment by luizaogs** [comment]
Oh wait, I was still asleep. Did you mean that you usually need a plural noun with "none of"? Not necessarily, as above.

I used to really like grammar, but that was when I still remembered the right terms and all. No longer.

**Comment by urapadmin** [comment]
what would it refer to? Make a full sentence please (since we are discussing it…)

**Comment by luizaogs** [comment]
Since I just had cake for breakfast, let's use that: Luiza's mom ate none of the cake because Luiza ate it all herself (not true, but you get the idea).

**Comment by urapadmin** [comment]
good. Cake here is sort of an uncountable noun. Let‘s fet back to our origin: None of the cake Luiza eats h a s calories. Right?

**Comment by luizaogs** [comment]
Ja (a funny example, and I wish it really did not have calories...)

**Comment by luizaogs** [comment]
None of the cake pieces Luiza eats have calories (pieces=have).

You're right, and I still get yelled at for not eating enough too so will have cake with ice cream for dessert.

**Comment by luizaogs** [comment]
So now I'm reading about this rule of course, and apparently "none of the marked files has" WOULD work if you wanted to stress each individual file rather than the group of files. But that seems more confusing than helpful to me.

**Comment by urapadmin** [comment]
and that is the case that is debated. One grammar says you should use in this case either singular or plural depending on what „fits better. Ha ha. 
What about „not any of the cake pieces Luiza eats …“ which serves - one could argue - the same role of none. While „no cake pieces Luiza is eating have“ .. 
Does „none of the cake pieces“ allow you to eat only one?

**Comment by urapadmin** [comment]
that is along my line of understanding. I would argue (not vehemently, though) that I would use „none of the“ particularly in cases when I want to stress every single file. It is like a selector in logic. None of is never None so you select a few any one of which h a s a certain attribute.

**Comment by luizaogs** [comment]
I think the comparison between not any (which refers to a group, as far as I understand it) and none depends on whether you think none means "not one" :)

Because file is a countable noun, I (and I think others) will always think it weird to see "files has," so I suppose in this case it depends on whether you want to be grammatically correct -- though both singular and plural are technically correct here, even if your aim is to stress every single file -- or if you want the option that will _look_ correct.

**Comment by lbestock** [comment]
I will bake a cake this weekend and neither of you will be here to eat it with me (look, English still has a dual sometimes, though we usually forget that). It might mean none of the cake will be eaten since I like baking them more than eating them.

I agree it will always look weird to see "files has" and so, though in general I am a stickler for agreement and this is definitely one that keeps me up at night sometimes and I really like this conversation. In fact I think I would avoid it by saying "not one of the files has". Or maybe even better "Tags found on none of the marked files".

**Comment by luizaogs** [comment]
Send me the cake! I will eat it.

"Tags found on none of the marked files" makes my confused brain much happier.

**Comment by urapadmin** [comment]
That i’ll rephrase was already agreed upon. I just like to confuse your brains.

In German it would be Tags, die keine der Dateien hat. Hat being singular. Maybe that is why I have a different tendency. What is the Portugese version?

**Comment by lbestock** [comment]
I know you already agreed (and that you like to confuse my brain). But you can't expect me to operate at the level of the general without my confused brain trying to find solace in a specific solution! Now I want to throw lots of commas in it. The German has a comma. Of course.

**Comment by urapadmin** [comment]
Commas are great. English is such a muddle because of its indeterminate comma rules. only you must not assume my commas are correct. (In this case it is).
Now my brain ponders on indetermined vs. indeterminate. I must stop.

**Comment by luizaogs** [comment]
Well now my confused brain is more confused because Portuguese is confusing. I would go with "tags que nenhum dos artigos marcados tem" which is also singular (têm would be the plural).

**Comment by urapadmin** [comment]
:) I was hoping for that.

**Comment by lbestock** [comment]
Wait there's one thing I really don't get. Why must you stop??

**Comment by luizaogs** [comment]
Yes, feel free to continue. Not much confuses my brain these days which means that I am bored :) This was not boring.

**Comment by urapadmin** [comment]
„How I’d love to infect at least one soul with some kind of poison, worry or disquiet! This would console me a little for my chronic failure to take action. My life’s purpose would be to pervert.“

(Fernando Pessoa - can‘t find it in Portugese, dammit)

**Comment by luizaogs** [comment]
"Ah, mas como eu desejaria lançar ao menos numa alma alguma coisa de veneno, de desassossego e de inquietação. Isso consolar-me-ia um pouco da nulidade de ação em que vivo. Perverter seria o fim da minha vida."

This is why you need a Brazilian on your team.

**Comment by urapadmin** [comment]
who presumably just went to the shelf and opened the Book of Disquiet at paragraph 65. Right?

**Comment by luizaogs** [comment]
...yeees?

**Comment by lbestock** [comment]
What if, thus infected, one experiences the disquiet of one's soul not as perversion but with ever renewed awe and gratitude? Has the infector then failed?

**Comment by urapadmin** [comment]
any Brazilian would presumably not work in such cases (nor in most others). But you know that.

**Comment by urapadmin** [comment]
told from my German translation „Perversion“ does not seem to be an accurate choice (Or my German „Verderben“ isn‘t). One should be able to read and sound out such a text in its original. Alas, even if one teied one might get to the reading but hardly to the sounding out.

**Comment by luizaogs** [comment]
I doubt many Germans have Fernando Pessoa on their shelves :) 

"Perverter" in Portuguese has a similar meaning to that in English, but I don't think that's the full meaning of the word as intended here. That section ends with "Mas vibra alguma alma com as minhas palavras? Ouve-as alguém que não
só eu?" which in English would be something like "But does any soul vibrate with my words? Does anyone listen to them, other than me?"

So no, I wouldn't say the infector failed -- I would say he would perhaps be pleasantly surprised at the results.

**Comment by urapadmin** [comment]
It might be shelved way more often than opened. A bit like the Ulysses. There are different reasons for owning it and reading it. 
Is it a "popular" text in Brazil? Do you read it in school?

**Comment by urapadmin** [comment]
I wish I were able to actually "taste" the physically of his prose. I mean the sound and the haptic quality. When I was studying Borges poems they left me stone-cold in part because I have absolutely no feeling for the rhythm and linguistic structure of the language (not even when listening to it). And it would be the same with Pessoa. In English I can feel a "mouthful" of language.

**Comment by luizaogs** [comment]
I’m not sure how popular it is, actually. We did read chunks in school but not the whole thing. We focused on the “classics” (so lots of Machado de Assis, José de Alencar, Eça de Queirós).

I would offer to read it to you some day but it doesn’t sound like that would be very helpful :) Alas. Portuguese sounds really beautiful, in my opinion, but it is hard (even for me, sometimes).

**Comment by urapadmin** [comment]
###  @test 0.13
The trivial end note:
- [ ] simpler wording applied
