### ISSUE TITLE
Cannot import workstations

### ISSUE THREAD

**Issue by Christian-Uronarti** [urapadmin/kiosk#1172]
Error message while trying to import uploaded workstations:

Exception in Import Worker: Attribute error File Maker work station object has no attribute "has option"

![image](https://user-images.githubusercontent.com/84924268/125252046-d98eaf00-e2ef-11eb-9207-74e836c14760.png)

**Comment by urapadmin** [comment]
![image](https://user-images.githubusercontent.com/38838314/125269946-7c075c00-e309-11eb-805c-09f4617f07ab.png)

**Comment by urapadmin** [comment]
see #1173

**Comment by urapadmin** [comment]
Collision between projects with different versions on one server. 
Currently all I can do is use the URAP Master Control for all projects - that will make the test project dysfunctional. 
see #661

**Comment by urapadmin** [comment]
import is running again, but when importing your workstation, I get:
![image](https://user-images.githubusercontent.com/38838314/125271264-d523bf80-e30a-11eb-9665-1bf98067e4da.png)
Which might just be correct or might be a hint that you uploaded the wrong file

**Comment by urapadmin** [comment]
That solved the first issue. But it lead to a new one:
