### ISSUE TITLE
Proper error message png

### ISSUE THREAD

**Issue by Christian-Uronarti** [urapadmin/kiosk#1173]
![image](https://user-images.githubusercontent.com/84924268/125252706-93861b00-e2f0-11eb-92e2-6dc3e203969a.png)

![image](https://user-images.githubusercontent.com/84924268/125252766-a39dfa80-e2f0-11eb-9844-4d223a13ac0c.png)

**Comment by urapadmin** [comment]
Your first github bug ticket! 
It is to early to open a bottle, but I will in the evening.

(Update coming up...)

**Comment by urapadmin** [comment]
This is closed due to being a duplicate. The proper ticket is #1172
