### ISSUE TITLE
Lot cannot be selected for CM in PVD

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1176]
Testing CM director's view stuff and so creating a bunch of CM in PVD 10.6.3 on my Mac. I first created the CM, and then realized I didn't have lots defined. So I went back and defined some lots, and then went back into my CM. I am unable to add lots to the CM - this looks like a field I can put something in, but I cannot click in it.

![image](https://user-images.githubusercontent.com/49291909/125452932-90557065-4cd5-4107-b142-fc6db3c08c56.png)

This happens also if I create a new CM after the lots have been created.

I CAN, however, create a CM from within the lot and then the lot is properly:
![image](https://user-images.githubusercontent.com/49291909/125453245-dca1b9ef-07f6-4645-b712-065ad35abde4.png)

So that just got lost somewhere, and the ability to assign a lot to a CM created from CM, not from within the lot, needs to be restored.

**Comment by luizaogs** [comment]
'Tis back.
