### ISSUE TITLE
Import/synchronization issue: 'Master Control is not up' error message

### ISSUE THREAD

**Issue by aes1884** [urapadmin/kiosk#1183]
When I open Kiosk (using the virtual machine server) to import workstations, I get an error message that reads 'Master Control is not up' and says that workstation export and import will not be available.
![IMG_82E94C793A06-1](https://user-images.githubusercontent.com/68443221/126701167-9a24181d-5ff0-4841-8e97-cedd25f487e5.JPEG)

**Comment by urapadmin** [comment]
in rare circumstances that can be just a timing problem (particularly with that kiosk version). 
Go to administration and you should see in one if the first lines something like MCP version 0.1 or so. Or you can just try and prepare your workstations. It won‘t work without Master Control.

**Comment by aes1884** [comment]
Both uploading and preparing workstations worked fine, so it seems like this isn't interfering with regular use.
