### ISSUE TITLE
display of narratives wonky on iPad

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1187]
Weird grey and white spaces not where they belong in narratives. No effect on function that I note - when I click the narrative it turns all white again. But it’s not expected and makes me nervous when I just ran into #1151 again.
FM go 19.3.1.
iOs 14.6.
![39BBA890-2241-4CFC-A1F8-DAE3DE5D9BD9](https://user-images.githubusercontent.com/49291909/126879705-8968eb7f-e2fb-4b65-b8f6-6bdae7ef7e15.png)

**Comment by urapadmin** [comment]
this looks weird, indeed. But it does not help me much. Does that happen repeatedly even after you close filemaker? Does it happen anywhere else? Can you provoke it? Etc.

**Comment by lbestock** [comment]
No, no, and no. So, hiccup not bug. I hate those!

**Comment by urapadmin** [comment]
so do I because these are definitely filemaker or iOS bugs and I won't be able to do much about it, anyway. But we must collect all similar events and see if a pattern evolves.

**Comment by urapadmin** [comment]
@aes1884: Anna, I add you to this ticket because I would like you to have an eye on this particular but such phenomena in general in filemaker.

**Comment by urapadmin** [comment]
@luizaogs: Once the project has delivered your new device, please keep an eye on this phenomenon. We have two of those that make me nervous but they have never been reported by anyone but @lbestock

**Comment by luizaogs** [comment]
Well have not run into this at least, so far (Filemaker Go 19.3.1.22, iOS 14.4.2, PVD 11.5).

**Comment by luizaogs** [comment]
Since you're now looking into the FM wonkiness I will say that I have not run into this while testing in the new iPad at all (FM 19.3.1.23, iOS 15.0.2).

**Comment by urapadmin** [comment]
@lbestock: Have you ever seen this again?

**Comment by urapadmin** [comment]
if not, let's keep calling this a hiccup close it.

**Comment by lbestock** [comment]
I have not seen it again. Hiccup.
