### ISSUE TITLE
cannot add material to CM, collection method field disappeared

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1190]
In testing #1176 I realized that I couldn't add the material of the CM any longer. Also, the collection method field disappeared: 

![Screen Shot 2021-07-26 at 9 47 59 PM](https://user-images.githubusercontent.com/67970402/127077467-8d64c62a-c43f-4851-be60-9d05bd854e61.png)

**Comment by urapadmin** [comment]
upsala. Might be a configuration issue. Probably some s'Urachi remains made it into pvd.

**Comment by urapadmin** [comment]
Indeed, those are s'Urachi extensions.
"allow_change_material_type" has to be set to nope 
and
"show_collection_method" to yup in pvd. 
I'll leave it to you to synchronize that.

**Comment by luizaogs** [comment]
Done, but I think "allow_change_material_type" needs to be set to yup? A clarification for the user manual.
