### ISSUE TITLE
small finds page accessible for non-small find CM numbers

### ISSUE THREAD

**Issue by aes1884** [urapadmin/kiosk#1194]
When using back and forwards arrows on a collected materials page (the ones either side of the +), it is possible, if you are on the small finds tab, to access a small finds page for a CM number that isn't a small find. E.g., MB10-009-64 is checked as a small find. If I am on the small find tab for MB10-009-64 and click the back arrow, it takes me to a small find tab that is totally functional for MB10-00-63, even though MB10-009-63 is not checked as a small find. Seems like something that could cause problems at some point.

**Comment by urapadmin** [comment]
### @test v 11.1
fixed for 
- [ ] stepping through collected materials using the previous and next buttons 
- [ ] and using the selection box
