### ISSUE TITLE
finding images by date in file repository

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#120]
I would like to be able to order images by date and page through all images this way.

**Comment by urapadmin** [comment]
ordering by date is already available. With pagination you can step backwards (or forward depending on the sorting you choose) in time. What you cannot see easily is the date of a photo without clicking on it. I will add it to the description.

**Comment by lbestock** [comment]
I like it so much I might want the date to be displayed even if the sort is by excavation context, too, though in that case it would go below the context rather than above.

The question remains if date should be a searchable field itself, not just a way of sorting. I have to think about that. I jump to thinking "yes!" but that's because date was my overarching organizing principle on paper.

**Comment by urapadmin** [comment]
My answer would be no. There are plans for a sidebar like the one you know for instance from booking.com. Once you search for somethign you have several groups of filters on the left that help you to narrow down the results further. Date would be one of those. So you would be able to see after a search all the dates that have at least one image that matches you search and you can just click on the date or dates of your interest. The same thing would be possible with excavation context and whatever else would make sense in such a sidebar. It is just a somewhat larger task again. Won't be soon.

**Comment by urapadmin** [comment]
We also must not forget that searching for images is currently often a substitute for searching the data itself. I suspect the more natural way one day should be to search the data somewhere and then see what images are connected to that data. Just a reminder that we must not turn the file repository into some kind of eierlegende Wollmilchsau.

**Comment by urapadmin** [comment]
you are still thinking about it....

**Comment by lbestock** [comment]
I am done thinking about it. I await the sidebar, which sounds very helpful.
