### ISSUE TITLE
error in preparing workstation

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1201]
I am trying to get Leah up and running as she has again expressed interest. I made her a user in both kiosk and in the FM file and then uploaded that and synchronized. I created a workstation. I have encountered the following at 6:30pm Providence time when attempting to prepare her workstation (this is the second failure; the previous one said it had been cancelled by a user but I hadn't cancelled it). 

![image](https://user-images.githubusercontent.com/49291909/132594362-a738da36-796d-42a8-bc09-043ede94b0bd.png)

**Comment by lbestock** [comment]
Next time worked.

**Comment by urapadmin** [comment]
that is a phenomenon I have seen when filemaker had not properly closed itself after an operation. Happens rarely and is usually gone after a few attempts. Unfortunately a hiccup
