### ISSUE TITLE
listbox with suggestions does not make suggestions if there is a value

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1203]
We have that e.g. when creating a workstation: The default recording group is predefined and so opening the selection box shows no entries. Can that be optimized with awesomplete?

**Comment by urapadmin** [comment]
in the particular instance I can always show all entries by using a filter on awesomeplete () => true. In that case always all recording groups will be shown in the list and still the matches will be shown.

For other selections it really depends on the length of the list. Tags, e.g. must be filtered or one would never see the Z tags.

**Comment by urapadmin** [comment]
### @kiosk 0.13.16
- [ ] all recording groups should be visible in the drop down list.
- [ ] In bulk file import ("a ton") the volume selection should not be filtered anymore
- [ ] the restore dialog keeps being filtered because the list of files can grow quite long
- [ ] the list of tags in the file repository keeps being filtered for the same reason

**Comment by luizaogs** [comment]
Probably shouldn't be testing this because I have questions but I realized that belatedly. Is the "volume selection" in bulk import the local path field? And by filtered you mean that one needs to first type something into the search box for results to appear, yes?

**Comment by urapadmin** [comment]
you know that questions are a good thing, right? 
You are right, "volume selection" was nonsense. I meant the local path. And the issue with these awesomplete fields (that's what the kids call them) is that once there is a value in the edit field the list shows only those entries that match the value in some way. If you select an entry from the list and then open the list again, it contains only that one entry until you delete it from the edit field. And that is often rather useless. 

So: When I say "should be filtered" this behaviour is what we want (usually because the unfiltered list would just be too long). When we don't want it filtered it should always show the complete list and only highlight those entries that match the input value.

**Comment by luizaogs** [comment]
Well it seems like awesomplete is working awesomely (sorry, I couldn't resist).
