### ISSUE TITLE
reference has been changed to device not user

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1205]
Places where there should be a reference to a user seem to have been changed to a device. I do not have time right now to be systematic in looking for where this is, but I have been in URAP and noted it all the places I have been going. An example:
![image](https://user-images.githubusercontent.com/49291909/133439972-47c958f2-194b-4bd2-ad37-54bba662404d.png)

And it is the case in the director's view right now, too. This looks like there is CMK as well as Christian's iPad, but only Christian's iPad leads to actual records.
![image](https://user-images.githubusercontent.com/49291909/133439887-cf5daae2-0729-442d-94a6-8939727d067a.png)

**Comment by lbestock** [comment]
This is an old database. 10.7.1 (which, I think the release history is not up to date for URAP on the wiki).

**Comment by urapadmin** [comment]
this is the case with the urap data that has been entered prior to, I think, last year. Should not be the case with current data.

**Comment by urapadmin** [comment]
see #883
This cannot be solved for existing data (simply because the device does not translate into a user).
