### ISSUE TITLE
ceramic processing modules confusion

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1207]
Possibly the confusion is me getting into this for the first time in a bit, and because that is possible I will go to bed soon. But I think some wires might be crossed with modules and so I will record this.

I am in PVD 11.1.
I created a CM for ceramic. (Note: ceramic -diag was not an option in PVD.)
I went to ceramic processing so I could process my record and test ceramic images and was told:
![image](https://user-images.githubusercontent.com/49291909/133950807-46e27436-4322-48ba-884f-2877f3be32aa.png)

I was confused as diagnostics are not part of PVD processing. So I went to configuration modules and it looks to me like SU ceramic stuff is turned off and I should not thus run into the problem with processing: 
![image](https://user-images.githubusercontent.com/49291909/133950838-e38e0561-b677-48c0-8b26-9ac4a155d1fe.png)

**Comment by urapadmin** [comment]
PVD needs some additional configuration at this point. This has been introduced with su:

The configuration key "show_only_this_material_in_pottery_selection" under "visibility" needs to refer to the material that appears in the pottery selection. For PVD that would be "ceramic" for SU that was "ceramic - diag." and that is what slipped into the PVD config when it was introduced.

So, no bug, just at this point pretty detailed configuration of the ceramics processing.

**Comment by lbestock** [comment]
It let me process Omar as ceramics once configuration changed. Not a bug.
