### ISSUE TITLE
qc_flags and qc_rules get modified without being changed due to a wrong default value

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1208]
Perhaps a legacy issue? At least the qc_rules and qc_flags tables have the string "null" in the modified_by field. I am not entirely sure where it comes from but I will convert it to a real null with a migration script. Let's see if that helps.

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/85#issuecomment-927170768_

**Comment by urapadmin** [comment]
### @test kiosk 0.13.5
- [ ] synchronization should not show modifications in qc_rules or qc_flags anymore if there weren't any in filemaker. See #85 for the log.

**Comment by luizaogs** [comment]
Just got the "7 modified lines" again, in 0.13.5 after only adding three empty dayplans.

![Screen Shot 2021-09-26 at 8 21 25 AM](https://user-images.githubusercontent.com/67970402/134807856-1a9ecd63-02ab-4142-8e20-6a6c7e693f77.png)

**Comment by urapadmin** [comment]
yes, I can reproduce that. Needs another look.

**Comment by urapadmin** [comment]
### @test kiosk 0.13.5 and recording 11.3
- [ ] I found a real bug in the recording part that was responsible. I hope there isn't anything else. Quite a line of bugs here.

**Comment by luizaogs** [comment]
Looks good now.
