### ISSUE TITLE
correcting for missing data when an import is not done properly

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#121]
I failed to tell an import to get the date from the EXIF data. Now there are all these files, some with excavation context so difficult to delete and reimport, that have no date. Since I want to be able to sort all images by date in the file repository, these images are now a problem. Since there are a lot of checkboxes with the import, the likelihood is high that such mistakes will be made again.

**Comment by urapadmin** [comment]
either needs the possibility to delete all these images again with a bulk operation
or the general possibility to rewind an import

**Comment by urapadmin** [comment]
at least this needs bulk delete. Then it would be possible to filter by import tag and then check and delete the results. See #20

**Comment by urapadmin** [comment]
the idea is this:
- [ ] if you used the automatic tag for the import or assigned a unequivocal tag yourself, all the imported files - and only those - are shown in the file repository.
- [ ] here you can easily mark them all (you have to do that for every page if there is pagination, though)
- [ ] and then bulk delete the marked files.

That is not as convenient as something like an "undo" but it should do for v1.
