### ISSUE TITLE
Getting gibberish instead of readable stuff

### ISSUE THREAD

**Issue by Christian-Uronarti** [urapadmin/kiosk#1216]
![image](https://user-images.githubusercontent.com/84924268/135659364-71c1862a-df2d-4cb0-88a1-3a622c597740.png) 
 I get gibberish instead of readable stuff - when I copy and paste it here it becomes legible.... is this a FMP or URAP problem? 
 the above becomes 

"Block II adjoins Block I to the north. Block II is nearly square, measuring 18.5 meters wide and 17.5 long. It comprises Rooms 63 to 81. This is one of the four blocks in the fort which were clearly the first built and the greatest in importance, and between which the less important barrack rooms, storerooms, shops, and subsidiary offices were arranged. The exact purpose of this block is not clear, but it may well have housed administrative offices. Rooms 63-81 excavated December 26th 1928 to December 29th 1928. - Dunham, 1967, 6 and Wheeler, Unpublished Diary, 28/29 p236-240."

**Comment by urapadmin** [comment]
must be a local issue. I downloaded your workstation and everything looks alright on my computer. And I have never seen anything like it before.,

So bunch of questions:
- what operating system are you on, what filemaker version are you on, what device is that
- did that occur after a fresh download or did you reopen a database and it was there all of the sudden
- have you tried to restart that device and try again
- were there any updates, upgrades, changes to the computer's configuration beforehand? 

This looks like a code page issue, so filemaker thinks you are in a different country or some such. Please check your international and keyboard settings if everything there is normal. But first of all I would just restart the think and try again.

**Comment by urapadmin** [comment]
here is a bit on how to check the language and keyboard settings: 
[https://answers.microsoft.com/en-us/windows/forum/all/windows-10-english-system-text-show-as-gibberish/93cd572c-886e-419b-8889-531cff288223](https://answers.microsoft.com/en-us/windows/forum/all/windows-10-english-system-text-show-as-gibberish/93cd572c-886e-419b-8889-531cff288223)

**Comment by urapadmin** [comment]
and here is a filemaker specific issue connected to adobe reader on windows:
[https://support.claris.com/s/article/Some-fonts-are-replaced-with-an-unreadable-tmp-font-1503693084454?language=en_US](https://support.claris.com/s/article/Some-fonts-are-replaced-with-an-unreadable-tmp-font-1503693084454?language=en_US)
Here I would suggest installing the latest filemaker pro update (19.3.2). Start filemaker pro without a database and then go to the menu help -> check for updates.

**Comment by Christian-Uronarti** [comment]
thanks for that - in the meantime I had downloaded the latest version of FMP and that did the trick!
________________________________
