### ISSUE TITLE
locus relations without flickering and without side effects? (error type 1)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1250]
coming out of #1249: This here is locus relations since it is the worst.
 
let's try a new take with deferred updates.

**Comment by urapadmin** [comment]
### recording 11.6.1

- [ ] should only show one delayed flicker and work properly on ipads
- [ ] I suppose drag & drop does not work, hm?

**Comment by lbestock** [comment]
Drag and drop cannot be tested on iPads at all - would you like me to test it on the laptop?
I tried this on three iPads simultaneously.
Not done with the test yet, but a few notes.
First, all three iPads returned this message during locus relation, after the type was successfully created and when I had tried to define the "to context". All accepted the locus relation after I hit "OK"
![image](https://user-images.githubusercontent.com/49291909/141662209-9c579812-1f53-4151-b43c-59195cefca0e.png)
Second, ldbipad gave me an error type 1. Looked blank, I went to a different tab and returned, and then the image was there.
Black iPad and Purple iPad were just fine. 
Image is in the gallery no problem.

**Comment by lbestock** [comment]
Whoops, that was not the image in question.

**Comment by lbestock** [comment]
Very similar with the next step of the test: adding a photo from the popup using the camera.
I got the same error message twice, after adding "to context" and after actually taking the picture. 
![822ED012-F829-4961-9735-6DB92BBE8122_1_105_c](https://user-images.githubusercontent.com/49291909/141662473-87357730-8be7-4632-aa67-08b550d17414.jpeg)
I also then got an error message about drag and drop not being supported, though of course I am not dragging and dropping as that is not possible on the iPads. 
![image](https://user-images.githubusercontent.com/49291909/141662482-f9250b1a-f498-492c-9e4f-35a72621afaf.png)
The images were not where they should be on my iPad, rather that locus relation and all the others were blank (an error 3 - we need this list of errors on all tickets where relevant because I forget which is which constantly). You can see this already on the "drag and drop" error on the image above, which is from my ipad. The other two allowed me to see the images already while giving me that message.
Stuff is in the gallery as proper.

**Comment by lbestock** [comment]
I will not finish this test tonight - I failed to get a file-picked one and the gallery test is going to be a nightmare without it and I am clearly not at my testing best.
For the records all ipads are running 11.6.4, iOS 15.1, FM Go 19.3.1.23
Purple (fine so far on this test) is mini 4
Black (fine so far despite being the previous Luiza machine) is iPad (6th generation)
LDB's iPad (the unhappy one) is mini (5th generation)

**Comment by lbestock** [comment]
When I close all the other apps running in the background my iPad behaves just like the other ones to this point.

**Comment by urapadmin** [comment]
in fact if you get that message about the obsolete function there is. o point in testing any longer since there is old code running. I have to look into that first.

**Comment by urapadmin** [comment]
### recording 11.6.5
Let's start this all over again, I simply missed several places where I had to change from the old the new method.

**Comment by lbestock** [comment]
Lots of doing, no provoking of type 1 errors or anything else. On the black iPad. I get no errors anymore and it's a lot faster and less flickery than before and I wonder if in the end figuring out this nightmare is going to have made things better not just in a specific fix sense but overall.

**Comment by urapadmin** [comment]
please test this with FileMaker go 15.4 before we call it done

**Comment by luizaogs** [comment]
So even though the flickering is delayed here I still get the flashing menu. Just for the record...

**Comment by luizaogs** [comment]
Got this when trying to add a "bonds with" relation for LA-006 and LA-010: 

![IMG_0252](https://user-images.githubusercontent.com/67970402/142115715-8e8642d4-c501-44a5-868c-21a12e11ce83.PNG)

The image was added, but I note that this was an image added through the gallery so maybe that's what triggered the message?

**Comment by luizaogs** [comment]
The rest is all fine here.

**Comment by urapadmin** [comment]
this ticket replaced #799

**Comment by urapadmin** [comment]
nope, there was still an error. I will address that new one in a new ticket: #1278

**Comment by urapadmin** [comment]
### @test 
for how to test image containers: [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=how_to_test_an_image_container](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=how_to_test_an_image_container). 

- [ ] should work but depending on what one does there might be two flickers (when changing the type there will be two).
- [ ] I suppose drag & drop does not work, hm? I would just live with it.
- [ ] more important: There should be no error types 1 no matter how often you do this
- [ ] inserting from the gallery should work, too.

**Comment by luizaogs** [comment]
Uh oh, nope: error type 1, which I have not hit in a long long time. The image was there once I quit FM and came back.

**Comment by urapadmin** [comment]
hmpf. The log is not necessary, it has never helped with error 1.

**Comment by urapadmin** [comment]
### 11.6.16
- [ ] okay, here I definitely forgot to activate the delay. Please try again if the 1 is gone.

**Comment by mcornacchia25** [comment]
It all seems to be working properly for me. All of the images show up with the proper labels in the gallery and behave as expected when I delete them.

**Comment by luizaogs** [comment]
Everything is working properly on the iPad. Let me see about drag and drop on my laptop...

Drag and drop does work on my laptop, and the image is properly in the gallery with the identifiers as it should be.

**Comment by urapadmin** [comment]
puh. I am glad this was not a new error 1. @lbestock: your turn!

**Comment by lbestock** [comment]
Works just fine for me on the iPad (which is running a zillion apps in the background), tested according to the plan and repeatedly. So, happy new year everyone! I'll close a ticket!
