### ISSUE TITLE
Survey: filemaker shows blank panel over UI after inserting an image (error type 1)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1252]
next image container: survey. 

my todo:
- [x] develop add_*_to_cache_deferred method
- [x] change primary image container to add_*_to_cache to add_*_to_cache_deferred
- [x] change sec. image container to add_*_to_cache to add_*_to_cache_deferred
- [x] change image_gallery_select_image to using add_*_to_cache_deferred
- [x] change method behind description field to using add_*_to_cache_deferred

**Comment by urapadmin** [comment]
### recording 11.6.2
- [ ] schematic test needed

**Comment by luizaogs** [comment]
Is this the treehouse? I thought it was the running foot? Just making sure I’m looking at the right thing.

**Comment by urapadmin** [comment]
that was a copy-and-paste mistake. The tree house is feature recording, this here is the running foot.

**Comment by luizaogs** [comment]
I am able to provoke the script issue here, too.

**Comment by luizaogs** [comment]
And I get the menu flashing between flickers, as discussed in #1251 .

**Comment by luizaogs** [comment]
Other than those two potential issues, everything is working as it should.

**Comment by urapadmin** [comment]
### @test 11.6.6
as for the strange windows: see #1253. That should be fixed.
the menu flashing in between I would accept for the time being. BUT I have lowered the delay between inserting the image and the delayed cache operation. So please try again.

**Comment by luizaogs** [comment]
I don't even get the menu/keyboard flashing between flickers anymore, so this seems to have gotten rid of that.

**Comment by luizaogs** [comment]
Everything is working here (and I can't provoke the script thing any longer). Do we close it?

**Comment by urapadmin** [comment]
if you think it is fine and functional and you cannot provoke an error. Yes.

**Comment by urapadmin** [comment]
I reopen this because of #1251.

**Comment by urapadmin** [comment]
### @test 11.6.17
We have to test this again from scratch because of a bug I found. There should be exactly ONE flicker and all should work, of course.
- [ ] Also, I attended to what was indeed still slightly different between dayplans and feature recording photos: The keyboard flashing should be the same as in dayplans. (Same goes for survey unit photos). They should behave similarly.

**Comment by luizaogs** [comment]
This is also all working for me.

**Comment by lbestock** [comment]
Works for me. @mcornacchia25 I forgot to add you to this one, too, it seems. If it works for you, you may close the ticket.

**Comment by mcornacchia25** [comment]
All seems to be working.
