### ISSUE TITLE
collected material photos: filemaker shows blank panel over UI after inserting an image (error type 1)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1254]
This here is for the image container in cm photos.

- [x] change add_*_to_cache method to the deferred strategy

**Comment by urapadmin** [comment]
### recording 11.6.3 
- [ ] apply test scheme

**Comment by luizaogs** [comment]
Clicking the plus sign to add an image currently opens the keyboard (because the cursor is going to the description field). I can minimize the keyboard and then add the image normally, but do you want the keyboard to appear then?

I'm also getting the flashing keyboard here between flickers. I know you said you accept that, but I'm noting it since it's no longer occurring in #1251 and #1252, after you reduced the delay.

**Comment by luizaogs** [comment]
The rest is working here (gallery, popups, etc.).

**Comment by urapadmin** [comment]
so reducing the delay might make this invisible but it might also provoke error type 1 again. I'll wait before I reduce the delay everywhere until we know a bit more about the latest error type one.

The behavior after clicking the plus button is different with more or less all plus buttons. I am too tired of filemaker to go through all those buttons and standardize the results. I just accept it as long as it doesn't lead to an error.

**Comment by lbestock** [comment]
So this needs full image testing treatment by Laurel and Meghan, and is moved back to test.

**Comment by urapadmin** [comment]
### @test 11.6.17
Sorry we have to test this again because of a bug I found. There should be exactly ONE flicker and all should work, of course.

**Comment by urapadmin** [comment]
> Clicking the plus sign to add an image currently opens the keyboard (because the cursor is going to the description field). I can minimize the keyboard and then add the image normally, but do you want the keyboard to appear then?
I am not sure how coherent we are in other lists, but the idea here is to jump to the description first so that users are motivated to type one. We get a lot of images without a description.

**Comment by luizaogs** [comment]
> > Clicking the plus sign to add an image currently opens the keyboard (because the cursor is going to the description field). I can minimize the keyboard and then add the image normally, but do you want the keyboard to appear then?
> > I am not sure how coherent we are in other lists, but the idea here is to jump to the description first so that users are motivated to type one. We get a lot of images without a description.

I don't think this happens elsewhere because it caught my eye here, but never mind then!

**Comment by mcornacchia25** [comment]
When I used the FileMaker delete button on an image here, a message pops up saying "Error This button requires a field to be active. Tap a field to make it active." When I click OK, the image deletes and works properly in the gallery. Otherwise, everything is working with just one flash.

**Comment by luizaogs** [comment]
Oops, I just reported the error Meghan mentions above in a new ticket (#1295).

**Comment by luizaogs** [comment]
The rest is all working for me.

**Comment by urapadmin** [comment]
okay, let's follow the deletion problem up in #1295 so we can close this here as soon as Laurel's test comes out the same

**Comment by urapadmin** [comment]
> > > Clicking the plus sign to add an image currently opens the keyboard (because the cursor is going to the description field). I can minimize the keyboard and then add the image normally, but do you want the keyboard to appear then?
> > > I am not sure how coherent we are in other lists, but the idea here is to jump to the description first so that users are motivated to type one. We get a lot of images without a description.
> 
> I don't think this happens elsewhere because it caught my eye here, but never mind then!

I do mind in #1298. For the ticket here we can ignore it.

**Comment by lbestock** [comment]
My test came out precisely the same in all respects. Closed.
