### ISSUE TITLE
singular and plural in site notes

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1261]
Yes, I'm back with my singulars and plurals. Not mentioning this will drive me nuts so I'm mentioning it, but definitely feel free to kill me for it (and/or ignore it completely). 

If we were being grammar sticklers (...sorry), we would probably want the "1 notes" on the top left to be "1 note" until a second note is added. And in the count for site note images on the right, we would probably want "3 notes".

![IMG_0247](https://user-images.githubusercontent.com/67970402/141698546-14232f4c-f5db-423b-b9f7-4444d245a158.PNG)

**Comment by urapadmin** [comment]
noted :o)

**Comment by urapadmin** [comment]
for you and some rest for you head: ### 11.6.14
But there will be other parts of the fm database where this is not fixed, I am sure.

**Comment by luizaogs** [comment]
I am sure I will annoyingly point them out if I see them.
