### ISSUE TITLE
ARCH1900 Kiosk malfunctioning: 'Kiosk is in emergency state'

### ISSUE THREAD

**Issue by aes1884** [urapadmin/kiosk#1268]
One of my students just alerted me that the ARCH1900 Kiosk is showing an error when he tried to access it. I'm getting the same error: 'Kiosk is in emergency state'. See the screenshot for the full message.
<img width="956" alt="image" src="https://user-images.githubusercontent.com/68443221/144339553-250cde4a-62f3-403d-ae70-53df56702319.png">

**Comment by urapadmin** [comment]
yes, I am aware of the issue. Does anybody need the server urgently?

**Comment by aes1884** [comment]
I don't think so. Final projects aren't due until the 15th, and I told the student who alerted me to the problem to just note in his draft if there were images that he wanted to download from Kiosk but didn't currently have access to.

**Comment by urapadmin** [comment]
but you will need it again this semester, right? We are having a little trouble behind the scenes ...

**Comment by urapadmin** [comment]
well, I have sidestepped the current issue and it should work again, but it is not entirely in my hands for how long ...

**Comment by aes1884** [comment]
Yes, I will need it again this semester. I anticipate students wanting to download from the file repository for their final projects. And thanks for getting it fixed, even temporarily. I'll let those who were having problems know that it is available now but may not be later.

**Comment by urapadmin** [comment]
this is now permanently fixed.
