### ISSUE TITLE
Import DH's DB

### ISSUE THREAD

**Issue by Christian-Uronarti** [urapadmin/kiosk#1271]
![image](https://user-images.githubusercontent.com/84924268/145724686-57f51722-518e-43c0-9374-5428eafd04ff.png)
 
Hi guys - I am having issues importing the data from Delyth's database. In fact, if you could try and do this for me that would be brilliant.  Neither I or alex have done any changes so you could simply reset those too

Cheers
CK

**Comment by urapadmin** [comment]
I will. Argh. That happens if Brown forces us to reinstall half of the server. Sorry for that.

**Comment by urapadmin** [comment]
And would that be it for the rest of the year? Delyth or Lottie or you do not need a new database, right?

**Comment by Christian-Uronarti** [comment]
that is right - you can do your xmas housecleaning then!

**Comment by Christian-Uronarti** [comment]
thanks!

**Comment by urapadmin** [comment]
done.
