### ISSUE TITLE
site_notes: site_map empty instead of showing file picking proxy

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1274]
Site maps got replaced by file picking with dummy images.

When in site (entered through gear) the file picking image is there for playground, which is correct.
But in site notes that is not the case. The site image is just empty and accessible. That is wrong.

**Comment by urapadmin** [comment]
### @test 11.6.10
- [ ] should be fixed

**Comment by luizaogs** [comment]
This is good!
