### ISSUE TITLE
site maps: new alternative flicker free approach

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1276]
### @test recording 11.6.10
- [x] apply test scheme
- [x] make sure in particular that the deletion issue in #1255 does not occur again

should you wonder about image error numbers: https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=how_to_test_an_image_container#special_types_of_image_container_errors

This should be behave the same in site maps accessed through the gear icon and through site notes. 

🎁 There is a new file maker go version, by the way.

**Comment by lbestock** [comment]
Well, I can't mess up the image error numbers again because I cannot provoke an error. Also these flickerless images are so fast. So fast and flickerless. I have tried it on one iPad. Since I have quite a few lying around now I will try it on some others before this gets closed. Hold your breath: next is The Black iPad.

**Comment by lbestock** [comment]
Flawless.

**Comment by urapadmin** [comment]
needs @luizaogs, clearly.

**Comment by lbestock** [comment]
You'll note that I did not close it!

**Comment by luizaogs** [comment]
Getting the same issue with the deletion here (currently in the gear part of site maps) as what I just reported in #1256: image deleted through FM menu stays in the gallery but we also get an empty container with the old identifier from that image. I realized with this one that if I add a new site map the empty container with the identifier that was left over from deleting the image through the FM menu disappears, I wonder if because it gets filled by the new image?

**Comment by luizaogs** [comment]
Huh, it gets weirder. Here using the "no map" button to delete the image did not delete the image in the gallery (hooray) but it also did not delete the identifier, and I get a blank container below that image: 

![IMG_0255](https://user-images.githubusercontent.com/67970402/146087221-48d9d7bd-1ab3-4095-b39e-176f00e14f95.PNG)

**Comment by luizaogs** [comment]
All of this above is also happening if I use the site map containers going in through site notes.

**Comment by luizaogs** [comment]
The rest is fine as far as I can see. FM Go 19.4.2.202 and iOS 15.1.

**Comment by urapadmin** [comment]
### @test 11.6.11
Please try how it is with this version.

**Comment by urapadmin** [comment]
we could be back now to the original delete issue in #1255

**Comment by urapadmin** [comment]
🛌

**Comment by luizaogs** [comment]
Hmm, the 11.6.11 change worked in site note images but I'm testing the gear part of site maps right now and it's not working yet. Deleted an image in the regular container using the FM menu and the image is gone from the gallery but I get the empty container with the site identifier.

After I added another site map (still in gear, but this time through the popup) that empty container with the identifier lost its identifier, so now it's just blank, and the new image is below it with its proper identifier. Using the FM menu to delete that new image in the popup resulted in the same thing: no image preserved in the gallery but an empty container with the identifier.

**Comment by luizaogs** [comment]
Going in through site notes: same results as above, both for the deletion with the FM menus in the regular container and the popup (which doesn't work yet) and the deletion with the non-FM menu ("no map"), which works properly.

**Comment by urapadmin** [comment]
it is so not fun.

**Comment by urapadmin** [comment]
### 11.6.12 
okay, this time I found a real error in my code that slipped in with the last changes. It is fixed and on desktop site maps look good to me now. But that does not mean a thing these days ...
- [ ] deletion good now
- [ ] everything else still working

**Comment by luizaogs** [comment]
Hey, it's working! All of it, as far as I can tell. 

But I don't know if you want me to close this yet so I will not.

**Comment by lbestock** [comment]
Alas, it is not working perfectly for me.
Site map through gear.
When I have made an original site map and then go to delete it by using the "replace" function in the menu (not pop up), my original image is removed from the gallery entirely.
If I use the delete function in the same menu, the proper thing happens and the image just loses its identifier in the gallery. It stays there, identifierless, after I add a new photo to the image container in which it had originally been put.

**Comment by urapadmin** [comment]
that sounds like the intended behaviour (see wiki about how to test image containers)

**Comment by lbestock** [comment]
Argh I thought there was no situation in which an image that had been in the gallery should be removed from the gallery, only its identifiers broken. I will go read it again, for the second time today, with eyes crossed.

**Comment by lbestock** [comment]
I see, up there in how they should work. OK. Then, this seems good to me.

**Comment by lbestock** [comment]
And I clarified the language in the testing steps because I had been reading those while testing and still made the mistake.

**Comment by urapadmin** [comment]
### @test v11.6.18
I reopen this after changes I made because of #1293. 
This needs only a quick new test to see if it still does what it should.

**Comment by luizaogs** [comment]
Works.
