### ISSUE TITLE
FM admin "recording methods" broken

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1282]
Somewhere along the line the "recording methods" button in the admin tab has gotten broken. Pressing it now results in getting stuck here:
![image](https://user-images.githubusercontent.com/49291909/147977947-c7a8facb-9d6c-4b69-8082-ec1371d4ed0c.png)

If I quit the app and then start it up again I am right back there. What works is to use the menu from the down arrow in the upper left corner to get to "close file".

(Being mad about Brown doesn't make me want to stop working on the project, even on the contrary. But I would not have chosen to find a FM bug for you.)

**Comment by urapadmin** [comment]
### @test 11.6.21
I have changed it so that it opens in an ipad compatible mode but it is really rather for the configuration phase on desktops computers.
