### ISSUE TITLE
Udate to WT-Forms 3.0.1: Input fields and labels are broken

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1283]
here especially in the file import
![image](https://user-images.githubusercontent.com/38838314/148621702-64a9f9f5-578b-48ac-86d2-45b56435d4fc.png)

Needs some work on the code basis to be compatible with the new WT-Forms

**Comment by urapadmin** [comment]
### kiosk v0.13.14
This should look normal again. And everywhere else in kiosk the labels of input fields, checkboxes or any other control should look normal, too.

**Comment by luizaogs** [comment]
I checked the file import, file repository input fields -- all working

Can't check workstation creation currently because I am unable to create any at the moment (see #903), so not closing this yet.

**Comment by luizaogs** [comment]
Labels in workstation creation are fine, too.
