### ISSUE TITLE
s'Urachi ceramics image container not deleted from gallery

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1289]
I have reconfigured PVD to have s'Urachi style ceramics so I can test this.
Deleting an image using the menu removes the image from the gallery, too, but interestingly not the image container from the gallery. The identifier is gone. I checked that it really was gone both by closing and reopening the file and by using the popup to put an image from the gallery into a new image container. It let me use this image to populate the new image container, with the proxy and everything, but no image. Here is what the gallery looks like:
![image](https://user-images.githubusercontent.com/49291909/147981059-834e1a7e-df68-40ba-82f0-703dfc4e6b9b.png)
Deleting the record using the trash button instead of the image using the menu does the proper thing - image still in gallery, context removed.

_Originally posted by @lbestock in https://github.com/urapadmin/kiosk/issues/1258#issuecomment-1004364228_

**Comment by urapadmin** [comment]
### @test 11.6.17
We have to test this again because of a bug I found. There should be exactly ONE flicker and all should work, of course.

**Comment by luizaogs** [comment]
Still having this issue in 11.6.17.

**Comment by urapadmin** [comment]
this waits for #1296 to be closed. Then I will tackle it.

**Comment by urapadmin** [comment]
### 11.6.21
This should be solved now. If not, leave it open, we will test this again when s'Urachi becomes a real project again.

**Comment by urapadmin** [comment]
by the way I have also changed the layout here. The s'Urachi layout is different from our usual layouts in the way that it scrolls. But for the images that makes little sense here because of the back and next buttons. So I have reduced this to show a single image but made the image container a bit bigger.

**Comment by luizaogs** [comment]
Yes, it's solved, but now we get a different error message popping up (different than that in #1304). Clicking on ok leads to a proper deletion in the gallery, so I guess the message itself just needs getting rid of.

![IMG_0271](https://user-images.githubusercontent.com/67970402/151606795-d01b51ee-8e11-4177-807f-e66cc17da6df.PNG)

**Comment by urapadmin** [comment]
🌵

**Comment by urapadmin** [comment]
### @test 12.6.22
jetzt aber ?!?

**Comment by luizaogs** [comment]
ja
