### ISSUE TITLE
locus quality control: description marked red although locus has a description

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1291]
if I first open a locus that lacks a description I get a description with a red background - correct.
if afterwards I immediately switch to a locus that has a description the red background remains - false.

**Comment by urapadmin** [comment]
### @test 11.6.17
The issue here was that as soon as the description qc rule would fire for one of the loci, all loci would react to it. 

- [ ] only the locus that actually lacks the description should mark the description label red.

**Comment by luizaogs** [comment]
Works.
