### ISSUE TITLE
feature photos (dayplans): changing the description is flaky

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1293]
A weird thing about changing descriptions, though: I tried changing it for two images and those did not change in the gallery. Then I added a bunch more images to try and provoke errors and added some more descriptions and those I can change and they change properly in the gallery as well -- going back to the ones that had not worked and changing them again works now, too. So basically something was going on and I cannot provoke it again currently but am noting it here in case someone else wants to see if it pops up as an issue for them, too.

_Originally posted by @luizaogs in https://github.com/urapadmin/kiosk/issues/1251#issuecomment-1011412711_

**Comment by luizaogs** [comment]
I also ran across this in su ceramics (mentioned in #1258).

**Comment by urapadmin** [comment]
@test #11.6.17
- [ ] Everybody: Please attack this on your respective devices. Maybe you can find some pattern or a hunch. 
- [ ] Try to focus on how you leave the description field, for that is what triggers the delayed operation. Where did you click next and did that change the behaviour?

**Comment by luizaogs** [comment]
Just got this again in su ceramics, again on the second image. I clicked outside of the container, as usual, and the description did not update in the gallery. Tried the same thing with the fourth image, same problem. Added a new image (the sixth in the list), which appeared properly in the gallery. That description did change in the gallery successfully.

**Comment by urapadmin** [comment]
but you did not have it here, did you? I have not paid attention to su ceramics again.

**Comment by luizaogs** [comment]
In features, you mean? Not in 11.6.17 but since I am not really sure what triggers it (besides the coincidence that it has been happening when I try to change it for the second image in a list) who knows, really.

**Comment by urapadmin** [comment]
is the delayed flash happening before this happens or not? 
Where exactly is "outside of the container"? It can make a difference if that's somewhere in the header or right next to the image container.

**Comment by luizaogs** [comment]
Just tried again, could not provoke it in either features or su ceramics. Argh. But when it does happen there is no flash at all, and I always (I'm pretty sure) click on the far right of the screen rather than in the header.

**Comment by urapadmin** [comment]
perhaps @lbestock or @mcornacchia25 have more luck attacking it

**Comment by mcornacchia25** [comment]
I've tried adding and editing descriptions in every combination I can think of and it's all working as expected in the gallery. I will say that I have accidentally a couple times just closed the keyboard when I'm done typing a description which has no flash and does not update the gallery. But as soon as I touch into any other field, the flash triggers and the gallery is updated.

**Comment by lbestock** [comment]
Oh I just had a really funny permutation of this! I made four images (in feature dayplans). I gave them all descriptions as I was making them. Only after I had made all four did I go to the gallery to check them out. They all have the same description, which they should not of course. It is the description of the second of the four images I made if that helps, and I went straight to the gallery after describing the fourth one (the description does not actually show up in the list until one has clicked somewhere else, so I did not get to see it there before I went to the gallery, but the other three all had their proper descriptions in that list).

**Comment by urapadmin** [comment]
can't reproduce this on Windows, as usual. I have to look at it in fm go.

**Comment by urapadmin** [comment]
but I am pretty sure it is an issue with the delay. You do something in between the image and the cache operation and that screws it up. I can screw it up by clicking on the + button while I am still in the description field. That makes the delayed operation fire but at the same time a new image is being created. Depending on the particular timing I guess this can go wrong in many ways.

**Comment by urapadmin** [comment]
### @test 11.6.18
before I attack the ipad myself, I try something else here again in dayplans: Dayplans (not matter where) don't use the delayed cache operation anymore but a version that works without a delay but a switch. It is fast enough on Windows to not show but it might look funny on fm go. Let's give it a try.

- [ ] Alas, it needs a full container test (not everywhere, though. It should suffice to test it in "feature")
- [ ] and you should have more coherent results with changing the description 

This is not a solution for anywhere else, though. locus photos or collected material photos might have the same description issues but it seemed that these issues were bound to dayplans.

**Comment by luizaogs** [comment]
Before I test the whole thing here: in feature dayplans, the switch is definitely visible (it switches back to the feature landing page). It is quite quick but threw me off at first and it sounds like you didn't see it at all on Windows. Let me know if you want me to test the rest or if you want to take a look at the timing!

**Comment by urapadmin** [comment]
### @test 11.6.20
To tackle the irritating back and forth I have added a little "please wait" overlay during the operation. Does that help?

**Comment by luizaogs** [comment]
I think you mean welcome to Antarctica :)

I hadn't done the full container test because I wanted to ask about the switch, so I'll check it all again when the next version comes out.

**Comment by luizaogs** [comment]
Works for me! And I think the please wait panel does help (I made sure it shows up in all dayplans).

(I say this as I test under a zillion blankets)

**Comment by lbestock** [comment]
Now testing in a blizzard from here (but no blankets, a lovely fire instead.)
This is working for me, with again a complete image container test and a lot of futzing around with image descriptions. I will close it.
