### ISSUE TITLE
cm image deletion error message

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1295]
Not sure if you really want this to be a new ticket (?) but since it's related to deletion rather than the image container, here we are.

When using the FM menu to delete a cm image I got the error message shown below, but after clicking "ok" the image was deleted properly and remained in the gallery without its identifiers, as it should. This is the case with both the FM menus in the popup and the primary image container.

![IMG_0270](https://user-images.githubusercontent.com/67970402/149589637-e36c0eca-e046-4320-b44a-d1b2bb879c78.PNG)

**Comment by urapadmin** [comment]
### @test recording 11.6.18
- [ ] does not happen on Windows, of course, so I tried something that might help.

**Comment by urapadmin** [comment]
forget it. Still there.

**Comment by urapadmin** [comment]
### @test recording 11.6.19
- [ ] got him
