### ISSUE TITLE
images: Clicking a plus button to add a new image should NOT go to the description first

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1298]
> > Clicking the plus sign to add an image currently opens the keyboard (because the cursor is going to the description field). I can minimize the keyboard and then add the image normally, but do you want the keyboard to appear then?
> > I am not sure how coherent we are in other lists, but the idea here is to jump to the description first so that users are motivated to type one. We get a lot of images without a description.

I don't think this happens elsewhere because it caught my eye here, but never mind then!

_Originally posted by @luizaogs in https://github.com/urapadmin/kiosk/issues/1254#issuecomment-1013492575_

**Comment by urapadmin** [comment]
I think to motivate excavators not to forget about an appropriate description we should always activate the description field first after somebody added an image container with a plus button (at least where applicable)

**Comment by lbestock** [comment]
I wonder if we can do this better, because I do remember being irritated by it as well. When I make an image container, the first thing I want to do is in fact to take the image, and that is what I always expect. To describe an image before the image exists is counterintuitive. But I agree that we hate all the blank image descriptions. Can we make they keyboard pop up in the image description after an image, not an image container, is added?

**Comment by urapadmin** [comment]
> I wonder if we can do this better, because I do remember being irritated by it as well. When I make an image container, the first thing I want to do is in fact to take the image, and that is what I always expect. To describe an image before the image exists is counterintuitive. But I agree that we hate all the blank image descriptions. Can we make they keyboard pop up in the image description after an image, not an image container, is added?

we have had that before and it was reported to be annoying that the keyboard pops up after inserting an image. To me it reads like making descriptions is annoying at this point. To get to an end with this I will stop the + buttons from going to the description everywhere where I can catch it.

**Comment by urapadmin** [comment]
- [ ] site notes
- [ ] dayplans (several places)
- [ ] locus photos
- [ ] collected material photos
- [ ] warecode ceramics
- [ ] s'Urachi ceramics

**Comment by urapadmin** [comment]
### @test 11.6.21
I checked all the above containers and it was in fact only collected material where the description would have gotten the focus after adding a container. That should be fixed now.

**Comment by luizaogs** [comment]
Hmm this problem is fixed but we are back to a flashing keyboard  when adding the image, which you had resolved in #1254.

**Comment by urapadmin** [comment]
oh this myriad of little nuances around every single of these containers kills me. Apparently that must have been fixed in the popup but not in the main image container, where I simply forgot it.
#### 11.6.22
fixed now?!?

**Comment by luizaogs** [comment]
Yup.
