### ISSUE TITLE
😱 image container error types

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1301]
special types of image container errors

Here is the list of error types we have seen too often in image containers to believe they are gone:

1 - blank screen - that's the worst. FM (and not only the image container) is covered by white with things still happening underneath the white sheet (we know that from the menu that pops up). Although I think I might have seen reports suggesting the opposite I would say this is temporary. ONLY When CLOSING FM (not switching to a different app) and going back the white sheet is gone and the image there.

1b - Same as 1a but it is enough to switch to a different app and back to filemaker to have access to the UI again. IT IS NOT ENOUGH for both type 1 errors to switch to a different part within the filemaker app (most of the time you are not even able to try).

2 - blank container. Here the image does not immediately appear in the container it was inserted into. This comes in two variations:

2a. temporary: the image is there after leaving the form and going back. So the image has been inserted but isn't displayed at times. Usually it suffices to click on the header of the form or leave the current form and come back or switch tab panels to refresh the screen. Then the images reappears.

2b. permanent: the image isn't there, even after leaving filemaker (something that so far only Luiza seems to be encountering). So it seems the image really has not even been inserted (the most mysterious of all of them).

3 - blank list: the other images in a list (we have seen that only in dayplans) turn to white - that only happens temporarily, so when leaving FM and going back they are there (so we know they have been inserted just sometimes they are not displayed).

see also [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=how_to_test_an_image_container&s[]=image&s[]=error&s[]=type#special_types_of_image_container_errors](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=how_to_test_an_image_container&s[]=image&s[]=error&s[]=type#special_types_of_image_container_errors)

**Comment by urapadmin** [comment]
we close this when we think image containers are finished.

**Comment by lbestock** [comment]
Just for the sake of completion, I got a 3 today in URAP style ceramics. As with all my recent 2s, the problem disappeared when I went and closed all the background apps that had mysteriously become active on my iPad since I last tested less than a day ago.

**Comment by urapadmin** [comment]
> Just for the sake of completion, I got a 3 today in URAP style ceramics. As with all my recent 2s, the problem disappeared when I went and closed all the background apps that had mysteriously become active on my iPad since I last tested less than a day ago.

then please file it in a ticket for URAP Style ceramics, unless there is already an open one for that image container

**Comment by urapadmin** [comment]
I also think 3s should only be reported if they occur more than just somewhere on occasion. Those filemaker hiccups will keep happening. Only if it comes up repeatedly or is even reproducible we should make it a ticket.

**Comment by urapadmin** [comment]
🥳 🎉 🎈 I declare the image container crisis successfully suffered.
