### ISSUE TITLE
error message on deleting an image container from s'U ceramics

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1304]
Image container testing. I used the garbage pail button to delete the image record for an image in s'U ceramics. The image container was properly deleted, and the image remained in the gallery as one would want. But right after I hit delete I got this error message.
![image](https://user-images.githubusercontent.com/49291909/149599317-90aa4ad0-ad1b-4f14-9588-ec23a08d69b8.png)

I hit OK and it flashed and I got the error message again. The second "OK" made it disappear.

**Comment by urapadmin** [comment]
together with #1289

**Comment by urapadmin** [comment]
hmpf. Does not happen on windows.

**Comment by urapadmin** [comment]
@lbestock : Confirmation, please.

**Comment by lbestock** [comment]
Does not happen, whether one or many images.
