### ISSUE TITLE
No link to gallery/test log in pedestrian survey while in test mode

### ISSUE THREAD

**Issue by mcornacchia25** [urapadmin/kiosk#1305]
In both pedestrian survey/grab and pedestrian survey/transect there does not appear to be a link to either the image gallery or test log while in test mode. I checked and the buttons are there in both feature/feature recording and excavation/locus recording.

**Comment by urapadmin** [comment]
see also #1303

**Comment by urapadmin** [comment]
### @test 11.6.18
should be fixed
