### ISSUE TITLE
create new workstation broken in Kiosk 0.13.15

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1308]
Hmm I am unable to create a workstation currently. I cleared the cache in case that had anything to do with it, but it didn't help. Neither filemaker recording nor file export ones work -- after I click the check button nothing happens (but the button disappears and reappears, so it looks like something should have).

_Originally posted by @luizaogs in https://github.com/urapadmin/kiosk/issues/903#issuecomment-1017026874_

**Comment by lbestock** [comment]
I have this problem, too.

**Comment by urapadmin** [comment]
### @test
and fixed. Was just an old library version on Beset, so no new kiosk version here.

**Comment by luizaogs** [comment]
Yep, working.
