### ISSUE TITLE
Locus relations error: can’t update the image of the opposite relations

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1327]
switch_off_menu: Switched the menu off. isMasterDb = yup
switch_off_menu: Switched the menu off. isMasterDb = nope
close_temp_window  temp_window was not open to begin with.
switch_off_menu: Switched the menu off. isMasterDb = nope
switch_off_menu: Switched the menu off. isMasterDb = nope
Error in qc-rule : not implemented: Unflag flag if related record does not exist
Error in qc-rule : not implemented: Unflag flag if related record does not exist
Error in qc-rule : not implemented: Unflag flag if related record does not exist
..._trigger_opposite_relation: no locus was related before.
activate_temp_window: opened layout locus_relations in NEW window  temp_window on iOS
..._trigger_opposite_relation: new opposite relation has uid AE3FEEC0-AC45-4ADD-9154-E785538ABC5D
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saved image data null
add_locus_relation_to_cache_deferred: single image with param OnObjectModify, $$cache_done=
is_cache_update_needed: image is there in OnObjectModify but record is not-> DONT process cache
add_locus_relation_to_cache_deferred: doing nothing.
image_validate: field img
image_validate: going to locusRelationHidden
add_locus_relation_to_cache_deferred: single image with param , $$cache_done=0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_locus_relation_to_cache_deferred: after sub call row_nr is 1 relation uid is D472B81A-CFC9-4437-80AE-DD01AD59373B
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context locus_relations/D472B81A-CFC9-4437-80AE-DD01AD59373B
delete_images_from_identifier_cache: deleting recording_context locus_relations/AE3FEEC0-AC45-4ADD-9154-E785538ABC5D
add_locus_relation_to_cache: before sub call row_nr is  relation uid is 
locus_relation_set_image_uid: $locus_uid='8dc2308e-17ab-41b3-a148-5c3a805d9f38', $locus_related_uid='d5899905-32a1-4af2-a8e0-df603fe37c76', $uid_sketch='7F353236-3FB6-4A8F-B4B0-21F87E06CD16'
add_locus_relation_to_cache_deferred_operation: locus_relation_set_image_uid returned 1
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saving image data for field
add_locus_relation_to_cache_deferred: single image with param OnObjectModify, $$cache_done=0
is_cache_update_needed: image is there in OnObjectModify -> process cache
add_locus_relation_to_cache_deferred: after sub call row_nr is 1 relation uid is D472B81A-CFC9-4437-80AE-DD01AD59373B
image_validate: field img
image_validate: going to locusRelationHidden
add_locus_relation_to_cache_deferred: single image with param , $$cache_done=1
is_cache_update_needed: OnValidate with CACHE_DONE-> DON'T process cache again
add_locus_relation_to_cache_deferred: doing nothing.
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context locus_relations/D472B81A-CFC9-4437-80AE-DD01AD59373B
delete_images_from_identifier_cache: deleting recording_context locus_relations/AE3FEEC0-AC45-4ADD-9154-E785538ABC5D
add_locus_relation_to_cache: before sub call row_nr is  relation uid is 
locus_relation_set_image_uid: $locus_uid='8dc2308e-17ab-41b3-a148-5c3a805d9f38', $locus_related_uid='d5899905-32a1-4af2-a8e0-df603fe37c76', $uid_sketch='7F353236-3FB6-4A8F-B4B0-21F87E06CD16'
add_locus_relation_to_cache_deferred_operation: locus_relation_set_image_uid returned 1
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
Error in qc-rule : not implemented: Unflag flag if related record does not exist
..._trigger_opposite_relation: no locus was related before.
activate_temp_window: opened layout locus_relations in NEW window  temp_window on iOS
..._trigger_opposite_relation: new opposite relation has uid E54BF09B-A068-4B03-A0E4-20D24659A6FD
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saved image data null
add_locus_relation_to_cache_deferred: single image with param OnObjectModify, $$cache_done=1
is_cache_update_needed: image is there in OnObjectModify but record is not-> DONT process cache
add_locus_relation_to_cache_deferred: doing nothing.
image_validate: field img
image_validate: going to locusRelationHidden
add_locus_relation_to_cache_deferred: single image with param , $$cache_done=0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_locus_relation_to_cache_deferred: after sub call row_nr is 1 relation uid is 770DEF74-20C7-45CF-9E8C-02E1B7380480
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context locus_relations/770DEF74-20C7-45CF-9E8C-02E1B7380480
delete_images_from_identifier_cache: deleting recording_context locus_relations/E54BF09B-A068-4B03-A0E4-20D24659A6FD
add_locus_relation_to_cache: before sub call row_nr is  relation uid is 
locus_relation_set_image_uid: $locus_uid='8dc2308e-17ab-41b3-a148-5c3a805d9f38', $locus_related_uid='97467ece-10b6-4bed-996c-3fa6ae144595', $uid_sketch='E2E7F48D-BC86-4891-8138-E9A0636E2B81'
add_locus_relation_to_cache_deferred_operation: locus_relation_set_image_uid returned 1
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saving image data for field
add_locus_relation_to_cache_deferred: single image with param OnObjectModify, $$cache_done=0
is_cache_update_needed: image is there in OnObjectModify -> process cache
add_locus_relation_to_cache_deferred: after sub call row_nr is 3 relation uid is 3ae14d68-e7a1-4ad4-9ef7-c7062dbde8b2
image_validate: field img
image_validate: going to locusRelationHidden
add_locus_relation_to_cache_deferred: single image with param , $$cache_done=1
is_cache_update_needed: OnValidate with CACHE_DONE-> DON'T process cache again
add_locus_relation_to_cache_deferred: doing nothing.
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context locus_relations/3ae14d68-e7a1-4ad4-9ef7-c7062dbde8b2
delete_images_from_identifier_cache: deleting recording_context locus_relations/0a349313-64dc-4253-87a5-44afcfd541c6
add_locus_relation_to_cache: before sub call row_nr is  relation uid is 
locus_relation_set_image_uid: $locus_uid='8dc2308e-17ab-41b3-a148-5c3a805d9f38', $locus_related_uid='b436de93-3d3d-4a96-84e5-e596d305ec73', $uid_sketch='b7a78404-dd7d-46a1-a503-6a0e9961c1b5'
add_locus_relation_to_cache_deferred_operation: locus_relation_set_image_uid returned 1
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
..._trigger_opposite_relation: there was a relationship but the type was changed
..._trigger_opposite_relation: because of the change the former relationsship will be deleted
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
..._trigger_opposite_relation: new opposite relation has uid AE603260-29F3-45DE-8E51-69FD83198C31
..._trigger_opposite_relation: $json_param={"cur_locus_related_uid":"AE603260-29F3-45DE-8E51-69FD83198C31","cur_locus_uid":"770DEF74-20C7-45CF-9E8C-02E1B7380480","identifier":"PBA-010","record_description":"PBA-010 cut by PBA-003","recording_context":"locus_relations","uid_image":"E2E7F48D-BC86-4891-8138-E9A0636E2B81","uid_recording_context":"770DEF74-20C7-45CF-9E8C-02E1B7380480","uids_recording_context":"770DEF74-20C7-45CF-9E8C-02E1B7380480"}
..._trigger_opposite_relation: $json_param_opposite={"identifier":"PBA-003","record_description":"PBA-003 cuts through PBA-010","recording_context":"locus_relations","uid_image":"E2E7F48D-BC86-4891-8138-E9A0636E2B81","uid_recording_context":"AE603260-29F3-45DE-8E51-69FD83198C31","uids_recording_context":"AE603260-29F3-45DE-8E51-69FD83198C31"}
activate_temp_window: opened layout file_identifier_cache in EXISTING window  temp_window
add_image_to_cache: an error 504occured -> record reverted.
activate_temp_window: opened layout file_identifier_cache in EXISTING window  temp_window
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
Error in qc-rule : not implemented: Unflag flag if related record does not exist
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saving image data for field
..._trigger_opposite_relation: no locus was related before.
activate_temp_window: opened layout locus_relations in NEW window  temp_window on iOS
..._trigger_opposite_relation: new opposite relation has uid 86ECFA46-2B48-40CC-B3BE-1DE1E1842833
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saved image data null
add_locus_relation_to_cache_deferred: single image with param OnObjectModify, $$cache_done=1
is_cache_update_needed: image is there in OnObjectModify but record is not-> DONT process cache
add_locus_relation_to_cache_deferred: doing nothing.
image_validate: field img
image_validate: going to locusRelationHidden
add_locus_relation_to_cache_deferred: single image with param , $$cache_done=0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_locus_relation_to_cache_deferred: after sub call row_nr is 1 relation uid is 82CB3EE7-8BD9-46D3-9D30-13D1C2194DA9
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context locus_relations/82CB3EE7-8BD9-46D3-9D30-13D1C2194DA9
delete_images_from_identifier_cache: deleting recording_context locus_relations/86ECFA46-2B48-40CC-B3BE-1DE1E1842833
add_locus_relation_to_cache: before sub call row_nr is  relation uid is 
locus_relation_set_image_uid: $locus_uid='8dc2308e-17ab-41b3-a148-5c3a805d9f38', $locus_related_uid='63c50e37-bcb2-4078-98fc-0b8111aff1b8', $uid_sketch='DDBA4E3B-6DE5-4717-BD34-45A0FE6F10BB'
locus_relation_set_image_uid: error 401 when updating image in opposite locus relation.
add_locus_relation_to_cache_deferred_operation: locus_relation_set_image_uid returned 0
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saved image data null
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saving image data for field
add_locus_relation_to_cache_deferred: single image with param gallery, $$cache_done=0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_locus_relation_to_cache_deferred: after sub call row_nr is 1 relation uid is 82CB3EE7-8BD9-46D3-9D30-13D1C2194DA9
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context locus_relations/82CB3EE7-8BD9-46D3-9D30-13D1C2194DA9
delete_images_from_identifier_cache: deleting recording_context locus_relations/86ECFA46-2B48-40CC-B3BE-1DE1E1842833
add_locus_relation_to_cache: before sub call row_nr is  relation uid is 
locus_relation_set_image_uid: $locus_uid='8dc2308e-17ab-41b3-a148-5c3a805d9f38', $locus_related_uid='63c50e37-bcb2-4078-98fc-0b8111aff1b8', $uid_sketch='DDBA4E3B-6DE5-4717-BD34-45A0FE6F10BB'
locus_relation_set_image_uid: error 401 when updating image in opposite locus relation.
add_locus_relation_to_cache_deferred_operation: locus_relation_set_image_uid returned 0
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saved image data null
save_image: enter for img
save_image: saved image data null
add_locus_relation_to_cache_deferred: single image with param gallery, $$cache_done=0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_locus_relation_to_cache_deferred: after sub call row_nr is 1 relation uid is 86ECFA46-2B48-40CC-B3BE-1DE1E1842833
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context locus_relations/86ECFA46-2B48-40CC-B3BE-1DE1E1842833
delete_images_from_identifier_cache: deleting recording_context locus_relations/82CB3EE7-8BD9-46D3-9D30-13D1C2194DA9
add_locus_relation_to_cache: before sub call row_nr is  relation uid is 
locus_relation_set_image_uid: $locus_uid='63c50e37-bcb2-4078-98fc-0b8111aff1b8', $locus_related_uid='8dc2308e-17ab-41b3-a148-5c3a805d9f38', $uid_sketch='DDBA4E3B-6DE5-4717-BD34-45A0FE6F10BB'
add_locus_relation_to_cache_deferred_operation: locus_relation_set_image_uid returned 1
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist
save_image: enter for img
save_image: saving image data for field
save_image: enter for img
save_image: saving image data for field
add_locus_relation_to_cache_deferred: single image with param OnObjectModify, $$cache_done=0
is_cache_update_needed: deleted image in OnObjectModify -> DON'T process cache
add_locus_relation_to_cache_deferred: doing nothing.
image_validate: field img
image_validate: restoring data in field current_locus_relations_image::img
image_validate: going to locusRelationHidden
add_locus_relation_to_cache_deferred: single image with param , $$cache_done=0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_locus_relation_to_cache_deferred: relation 82CB3EE7-8BD9-46D3-9D30-13D1C2194DA9 has no sketch.
add_locus_relation_to_cache_deferred: after sub call row_nr is 1 relation uid is 82CB3EE7-8BD9-46D3-9D30-13D1C2194DA9
activate_temp_window: opened layout file_identifier_cache in NEW window  temp_window on iOS
delete_images_from_identifier_cache: deleting recording_context locus_relations/82CB3EE7-8BD9-46D3-9D30-13D1C2194DA9
delete_images_from_identifier_cache: deleting recording_context locus_relations/86ECFA46-2B48-40CC-B3BE-1DE1E1842833
add_locus_relation_to_cache: before sub call row_nr is  relation uid is 
locus_relation_set_image_uid: $locus_uid='8dc2308e-17ab-41b3-a148-5c3a805d9f38', $locus_related_uid='63c50e37-bcb2-4078-98fc-0b8111aff1b8', $uid_sketch=''
locus_relation_set_image_uid: error 401 when updating image in opposite locus relation.
add_locus_relation_to_cache_deferred_operation: locus_relation_set_image_uid returned 0
closed temp window  temp_window.
Error in qc-rule : not implemented: Unflag flag if related record does not exist

**Comment by lbestock** [comment]
The fmp12 file is uploaded

**Comment by urapadmin** [comment]
### @test 11.6.24
Laurel got an error message that the reverse relation could not be deleted or so. It should not happen again now that #1329 and #1330  are fixed.
