### ISSUE TITLE
locus form: Moving between loci should switch to tab Observation in case of a qc error

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1331]
If quality control finds an error it shows the locus relations tab (and others) disabled. That is why moving to a locus with a qc error must switch to the observations tab when hitting a locus with a quality control error.

**Comment by urapadmin** [comment]
### @test kiosk 11.6.25
- [ ] Stay in locus relations with a green quality control button and then switch to one that is red and the tab should change.
- [ ] As long as you move between green loci the tab should not change
- [ ] Should work with both the arrow buttons and the selection box.

**Comment by luizaogs** [comment]
This is all working.
