### ISSUE TITLE
recording data is not commited in UrapSQLDb when SQLAlchemy tries to access it

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#177]
concrete case: New unit with new images. When the images are saved to the file repository during synchronization the check whether they refer to a correct excavation context failed. The reason is that this check uses sqlalchemy. The new excavation contexts are present only in the transaction of the UrapSQLDb connection. That is indeed an issue. It seems I should not use sqlalchemy in any part of the synchronization.

**Comment by urapadmin** [comment]
That is a real problem. I will have to eliminate sqlalchemy more or less everywhere in the filemanagement. 
For the time being I rather add a parameter to upload that does not doublecheck the contexts during synchronization.

**Comment by lbestock** [comment]
ja, it is also a problem in combination with synchronization. I need to get rid of that crap.

**Comment by urapadmin** [comment]
connecting sqlalchemy with the psycopg2 database connection is still not working properly. Somewhere importing files is committing the whole synch transaction, so that there is nothing to roll back when it comes to that.

**Comment by urapadmin** [comment]
it appears I forgot to set commit=False when calling contextual_file.upload.
