### ISSUE TITLE
first bulk operations: delete / tag / assign identifier

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#20]

**Comment by urapadmin** [comment]
see #694. Assigning an image to an identifier has to work for a single file first.

**Comment by urapadmin** [comment]
first of all we need a mechanism to mark images.

**Comment by urapadmin** [comment]
### kiosk 0.8.27
This is what we have:
- [ ] marking single images by clicking on the star (or the identifiers)
- [ ] marking all images with the star in the tool bar
- [ ] unmarking all images with the empty star in the tool bar
- [ ] toggling the star of all images to the opposite state using the half star in the tool bar
- [ ] deleting the marked images by clicking on the trash icon in the tool bar.
- [ ] while the markers survive pagination changes they are completely reset when fetching the images again by clicking on "Click to fetch 'em".

**Comment by urapadmin** [comment]
bulk tagging and bulk assigning of contexts is not part of the 0.9 milestone. I open two new tickets for them:
#928 and #929.

**Comment by lbestock** [comment]
This is so great and so intuitive that I figured most of it out testing the bulk delete ticket before reading the more complete stuff here.
