### ISSUE TITLE
new plugin: log viewer

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#227]
here we can also give a possibility to cut the log: see #11 
If this takes too much time, at least downloading the log (as a zip?) or even opening the log folder on the server could help.

**Comment by urapadmin** [comment]
we have #752 now that should do it for a while

**Comment by urapadmin** [comment]
there it is, even for v1. 
### kiosk 0.13.12
- [ ] in administration / logs you find a glasses icon that opens the log in the new log viewer
- [ ] the log viewer structures the log in chunks of 300 lines and shows those chunks and their time span for you to select
- [ ] you can switch logs on and off by type with the four buttons in the toolbar. Debug (the bug is not hiding bugs but debugging messages) is off by default. The other thre are on by default.

**Comment by urapadmin** [comment]
it does not load MCP_8472_Fri_221021-1740.log, presumably because it is too small:
[MCP_8472_Fri_221021-1740.log](https://github.com/urapadmin/kiosk/files/7455200/MCP_8472_Fri_221021-1740.log)

**Comment by luizaogs** [comment]
Oops, I hadn't realized you had labeled this as a bug when I saw it on the testing pane. But the check boxes above are all working.

**Comment by urapadmin** [comment]
yes, please leave it open because of the logs with only one line in them. Those never load.

**Comment by urapadmin** [comment]
Although it works okay, there is a reoccuring error in the log:
![image](https://user-images.githubusercontent.com/38838314/140416389-e9cde8b8-b304-4c99-b027-fb7505e3e988.png)

**Comment by urapadmin** [comment]
### kiosk 0.13.13
scary version number but it should fix those issues from above:
- [ ] logs with only one line show properly (they usually have about 150 bytes or so)
- [ ] the urap_xxx_logs don't show the UrlForPublisher.route error for logviewer.logviewer-show anymore.

**Comment by luizaogs** [comment]
I tried a bunch of the smaller ones (so I assume of one line) and they just load forever and don't actually appear. The other ones are fine. 

And I can't test urap.

**Comment by luizaogs** [comment]
JUST KIDDING you haven't released this.

**Comment by urapadmin** [comment]
No, I haven't :o) But I will add another feature to test when it is finally released:
- [ ] when scrolling through a log the toolbar and hour selector stay put

**Comment by luizaogs** [comment]
Everything is working other than the urap specific thing that I cannot test, alas.

**Comment by urapadmin** [comment]
this can be closed from my point of view
