### ISSUE TITLE
Locus Type cannot be selected

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#231]
After configuration of ARCH1900 I cannot select a locus type - it's blank. That is not configurable, so not sure what happened to break it. But I did configure the value list for locus_type_other and maybe that is related?

**Comment by urapadmin** [comment]
This isn't a bug, it is a feature. As soon as this template gets turned into a real database somebody downloads, the locus types will be there. They are part of the data, not of the configuration.
