### ISSUE TITLE
enable / disable infos in log view

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#233]
It is good, that one can see all the additional infos when the log view is shown by a job (talking about javascript after a job has been executed with warnings), but it would be better to be able to reduce it. Make a checkbox [] Show additional information or some such.

**Comment by urapadmin** [comment]
### kiosk 0.8.27

**Comment by lbestock** [comment]
If this is for a non-developer to test she needs more instruction.

**Comment by urapadmin** [comment]
after any of the workstation operations that show a spinning globe (fork, export, etc...) a result page comes up and shows you what happened. That page was very long since it showed all the detals.
In the new version it has a checkbox "show details" that is unchecked by default and hence the information is reduced to warnings and errors. If you check the box you get all the merely informational and perhaps even some debug lines as well.

**Comment by lbestock** [comment]
I was going to say it was really still pretty long, but then I clicked "show details" and it got much longer indeed.
