### ISSUE TITLE
synchronization will block if a file is uploaded and the sync transaction is still pending

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#245]
which is a result of using bloody sqlalchemy. see #177

**Comment by lbestock** [comment]
a quick way out would be to decide what do to at all with the file synchronization. Should a file issue really block the whole synchronization? That needs a different issue

**Comment by urapadmin** [comment]
for the time being I managed make sqlalchemy use the same connection as UrapSQLDb. That way they also act within the same transaction and the block goes away.
