### ISSUE TITLE
what to do if a file has a problem at the end of synchronization? 

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#246]
Currently the system tries to roll everything back (as far as that is even doable). But that causes deadlocks. see #245. But in general: what should we do?

**Comment by urapadmin** [comment]
as a first step I will add options to the synchronization dialog (the one that asks whether or not synchronization should start now). The default is that they are switched off and that is how synchronization should run. Only if an error occurred and it has to run again, the option can suppress certain issues: [x] drop images that cause import issues. [x] drop duplicate images.
