### ISSUE TITLE
file repository: clicking return while editing images results in something we do not want

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#247]
Discovered while editing tags. LKH subsequently discovered that return functions fine when nothing is edited. But if something has been edited, return closes the edit window and returns to the file repository but has wiped out the search one was working within. And does not save the changes made in the edit window.

**Comment by urapadmin** [comment]
hm, I cannot produce that behaviour in chrome or firefox on windows. Is it possible that only safari is doing it?
