### ISSUE TITLE
running two fork_export tasks parallel leads to the first failing

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#248]
and stragely it fails because there are double as many entries in the workstation_fm_image_transfer table as there should be. So the two processes seem to interfere somehow

**Comment by lbestock** [comment]
in arch1900 we should at least make sure that jobs are refused if there is already a job running. If nothing helps, the kiosk.lock needs to be used again.

**Comment by urapadmin** [comment]
ja, with the use_local_thread attribute for jobs we only made that kinda sure. If flasks uses two processes, it would not help. I am still not even sure if it helps within a single threat. It needs to use the general store as a lock, that's the only thing that works. And that is open.

**Comment by urapadmin** [comment]
I have done away with a sqlalchemy issue that might have caused this problem. Needs testing if it is actually gone now.

**Comment by urapadmin** [comment]
also belongs to #512 and #129

**Comment by urapadmin** [comment]
needs the external job management planned for jolly jobber.
