### ISSUE TITLE
filemaker automatic creation of locus relations in related locus

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#249]
Discussed much earlier and not sure if it has a ticket anywhere yet. When locus 2 is recorded as above locus 1, there should be automatically generated in locus 1 a relation below locus 2. The utility of this for analysis was demonstrated to me today when I needed to know the relations of all the layers hit in one of our deep little pits in FA to the wall - I needed to know at what point the layers started running under the wall instead of against it. I only wanted to look at the wall locus to know that, not each individual one. (And to know which loci were involved easily I would have needed to see the tag FA Sondage 3.)

**Comment by urapadmin** [comment]
the plan is rather to do that as a part of synchronization and not in filemaker itself. Means, in the trench the counterpart would not appear automatically. But it would be there after the next synchronization.

**Comment by urapadmin** [comment]
see also #321

**Comment by urapadmin** [comment]
the plan to do that after synchronization is far from sufficient because that way deleted relations would be readded. No, it needs to be done in filemaker and during synchronization only accidents or legacy issues can be tackled in only one way: If there is a relation, make sure there is a counterpart and that it matches. In filemaker we do the same but we also make sure that if a relationship is deleted then its counterpart is deleted as well.

**Comment by urapadmin** [comment]
done in filemaker. Needs very systematic testing!

**Comment by urapadmin** [comment]
### @test
Needs a thorough test. Automatically generating, deleting and managing the reverse relation means, e.g.:
- what if I change the related locus of an existing relationsship? The original reverse relation must be gone, the new one must be established
- what if I change the type of an existing relationsship? What if I change the type in the reverse relationsship? 
- what if I change the type of an existing relationsship but the reverse relation already has that type of relation but to a different locus (in fact that is perfectly ok. A locus can be covered by two different loci). But "perfectly fine" means it should be allowed an the two relations should not interfere with each other. 
- etc.... (this is just what came to mind quickly)

**Comment by lbestock** [comment]
It all works. At least all the tests you have imagined here. It is really neat, and also very helpful.
