### ISSUE TITLE
make the file repository stop jumping around when one clicks on or inputs things into different search fields

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#250]
This actually drives me so nuts that it compromises the usability of the file repository. Fields that I need to click on move while I'm using it. I keep trying to tell myself it is not an actual bug and I should just deal with it, but it so consistently makes me angry that I no longer succeed in telling myself that.

**Comment by urapadmin** [comment]
I am not even sure why you tried to tell you that, frankly. If the UI causes issues there should be a better solution. So please report such things. bug or not.
