### ISSUE TITLE
in FM on the laptop when switching between loci using the dropdown menu, fields do not update

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#251]
Not sure how to describe coherently. I am tagging loci in FM on the laptop. I am switching between loci using the dropdown menu at the top. I tagged FA-055 as FA Sondage 3. Then I went to FA-054 to tag it the same way, and it looked like it was already tagged. That made no sense. Then I went to another FA locus and it, too, looked like it was already tagged. When I clicked elsewhere on the screen it disappeared, but that is a bug - I thought something was tagged that wasn't and that I wanted to tag. Until I figured out that it just displayed the tags from the previous locus, not what was actually there, I was not tagging stuff.

**Comment by urapadmin** [comment]
ok, this happens really only in the tag section. That one does not get updated properly when changing between loci via the listbox. The other controls on the same page DO get updated properly. When Laurel moved the mouse (not even over the tag portal), filemaker updated the tag portal. I suppose it needs a bunch of update/refresh triggers, perhaps even delayed by a timer.

**Comment by urapadmin** [comment]
does it happen in the ipad, too?

**Comment by urapadmin** [comment]
not happening on windows, though. But I added a precautionary step that might solve it on macs, too.

**Comment by urapadmin** [comment]
the precautionary step has made things slightly better on MacOs, but not really good. It can still take a few seconds until filemaker updates the tag section. It is not critical because it will definitely update it as soon as one tries to manipulate data. 

On the ipad the issue does not exist. So I close this.
