### ISSUE TITLE
filemaker tag analysis: search from list of assigned tags instead of typing tag name

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#256]
Right now in tag analysis one does not see a list of assigned tags but must type in the tag name. And particularly since it is case sensitive, this is not ideal. When tags are created they are also given groups - would be most helpful to be able to see tags and groups and choose that way.

**Comment by urapadmin** [comment]
at first glance this read as if you overlook something. Please show me.

**Comment by urapadmin** [comment]
yes, you did. Because of the + Icon. We have to change that to something more intuitive.
Also one cannot really read what is in the tag list because of bloody filemaker.

**Comment by urapadmin** [comment]
I do not agree with the more intuitive only because you overlooked something. Users need to learn their software. But I changed the button icon to something that does not interfere with the other + button that appears if only a single tag is selected.
I deem the issue closed.
