### ISSUE TITLE
custom regex definitions for arch1900

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#258]
means: The format of how loci / cm / units are represented needs to be taught to kiosk. But it is the same as in urap, right? "Unit-locus-collected-material"?

**Comment by urapadmin** [comment]
do it for uronarti, too: Open up the unit designator for A-z, 0-9 of variable length.

**Comment by urapadmin** [comment]
did it. Now it needs to be tested: File imports should accept something like "fooble-001" as a locus and also "fooble-001 with description" whereby "with description" would be the description for the image.
This is only relevant when importing files from outside the recording system.

**Comment by lbestock** [comment]
Will the file import accept anything, or only something that already exists in the recording system?
