### ISSUE TITLE
a real gallery in filemaker

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#28]
A basic gallery function in filemaker might make sense. And if it had an option to jump to the table context that would make some people very happy. But in fact this is something the web UI will do anyhow - later on. But until then the filemaker version would make a difference and isn't too much work.

**Comment by urapadmin** [comment]
we have that for a couple of versions now, accessible on the start page. 
Needs a test, though.
@test v.8.9.17

**Comment by SamKimball-BrownU** [comment]
So, I am 99.9% sure that you are referring to the image gallery that is accessible via the button on the start page. If that is the case, it is working entirely as intended and as any image gallery should.

However, from the first part of the ticket: "to jump to the table context"
I'm not exactly sure what this is meaning. I assume this just describes what we now call the search function.

Basically, **resolved**, but just sending it back to you to confirm.

**Comment by urapadmin** [comment]
ah, I myself forgot about that part. There was the idea to jump from the gallery to the recording data that refers to the image (the term table context has changed a lot. We have called it a recording context after that and now call it a record type). 
However, I open a new ticket for that feature and close this one here.
