### ISSUE TITLE
toasts appear in the wrong place in edit workstation dialog

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#311]
appear on top, which is strange, given where one clicks. What about under the button or some such?

**Comment by urapadmin** [comment]
### kiosk 0.8.27
it appears right above the buttons now. That should at least make sure that one does not overlook the messages.

**Comment by lbestock** [comment]
What are toasts? How do I test this?

**Comment by urapadmin** [comment]
a toast is the little floating message that appears in kiosk in many situations when a big dialog is overkill. It either gives you a short result or asks a yes no question.

You test this by going to the said dialog in kiosk and see where questions appear. Only I just realize that we are in the wrong ticket here. I have not changed that for the workstation dialog BUT for the file edit dialog. New Ticket: #940.
This here is still open.

**Comment by urapadmin** [comment]
In the new field manager the toasts are free floating. So the issue is obsolete.
