### ISSUE TITLE
generate counterparts for locus relations 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#321]

**Comment by urapadmin** [comment]
see also #249

**Comment by urapadmin** [comment]
this is a bigger task because before I can do it at all I have to think about how and when such things are triggered.

**Comment by urapadmin** [comment]
### @test
Needs a thorough test. Automatically generating, deleting and managing the reverse relation means, e.g.:
- what if I change the related locus of an existing relationsship? The original reverse relation must be gone, the new one must be established
- what if I change the type of an existing relationsship? What if I change the type in the reverse relationsship? 
- what if I change the type of an existing relationsship but the reverse relation already has that type of relation but to a different locus (in fact that is perfectly ok. A locus can be covered by two different loci). But "perfectly fine" means it should be allowed an the two relations should not interfere with each other. 
- etc.... (this is just what came to mind quickly)

**Comment by lbestock** [comment]
This is so cool!
