### ISSUE TITLE
admin: reset filemaker template

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#323]
given that we now reuse the filemaker template over and over again this is what we need:
- store the original filemaker template separately
- copy it before first use
- provide method to reset all filemaker templates (the central and those of the export groups) to the empty filemaker template.

see also #322 which  must not only update but also reset the filemaker templates.

**Comment by urapadmin** [comment]
### @test 0.11.1
- [ ] there is an option "reset recording group template" or some such in the workstation's action dialog now
- [ ] the option should throw an error if not all workstations that share the same recording group of the workstation you clicked on are in "synchronized" state.
- [ ] if there is only one workstation that is currently doing something (like forking, which is when the ws is still officially in synchronized mode) the reset option should refuse to run.

**Comment by urapadmin** [comment]
perhaps a few words for the purpose of this option:
  - the way it is triggered (by selecting an individual workstation) is temporary until we have a ui for recording groups
  - resetting a template sets the whole recording group back to the point where one also starts if there is a new update of the recording system (I just replace the filemaker template in these cases). 
  - After resetting fork encounters an empty template file and so it just exports all relevant images and records. When a template is used again, fork only adds what has changed since the last fork. And that is the main purpose for this reset option: If images seem to be missing or the data in the recording system looks weird, resetting the template can be one way to eliminate a bunch of possible issues. 
  - resetting is not destructive. Nothing is being deleted that cannot be fully rebuilt.

**Comment by luizaogs** [comment]
Works.
