### ISSUE TITLE
images missing in filemaker

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#332]
Noticed missing images in dayplans in MJ's version. Four Abi drawings and two photographs, all present properly in the File Repository, did not make it into that FM file somehow. Photograph shows two different versions of the FM file open simultaneously to show the difference.
![IMG_6052](https://user-images.githubusercontent.com/49291909/67957406-efb41480-fbcb-11e9-8086-a56e5ffd18a4.JPG)

**Comment by urapadmin** [comment]
I can reproduce that, in even a worse version with the copy of the virtual machine I have with me, but that one is lacking a recent file repository. I have to wait until I am back with the proper file repository. My suspicion is currently that only thumbnails are missing. Needs further investigation before we import MJ's data.

**Comment by urapadmin** [comment]
Those images are NOT in the virtual machine at all. I suspect that we have imported them into the local hillside server after we copied it to the virtual machine. That is bad and I can only hope that only the images are affected. Also questionable: where did Laurel get this fm database from?
