### ISSUE TITLE
additional locus popped up from who knows where

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#333]
Locus FA-060 I have no recollection of. It is blank aside from one locus relation. I don't even know if it is a problem or an artifact of someone just pushing buttons they shouldn't have.

**Comment by urapadmin** [comment]
I do not have an FA-060 at least in my development database. It ends with FA-059. I have to look at it in Providence, but I suspect that it is indeed something that happened long after the field.

**Comment by urapadmin** [comment]
The locus also is not in the master database of the virtual machine. It must have been entered in the database you are looking at. Which in future you should specify so that I have any idea where you are.

**Comment by urapadmin** [comment]
I deem this done because it can't be reproduced.
