### ISSUE TITLE
file repository: cannot change parameters of search

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#349]
Having done a search for images in kiosk with the parameter set to small thumbnail, I fetched my images. Now I want to change the thumbnails to medium and cannot. In fact I cannot figure out how to get medium thumbnails at all currently even for a new search. Nor can I figure out how to change the "sort by" parameter. Both drop down menus are there with their possibilities but selecting the possibilities no longer changes the sort or size (presumably got lost when the jumping around was fixed).

**Comment by urapadmin** [comment]
same as #350

**Comment by urapadmin** [comment]
fixed both in online and vm version
