### ISSUE TITLE
Tags in FM: we need a place to describe what the tag is

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#374]
"FA Sondage 3" doesn't make sense without a description. We need a place to put that description.

**Comment by urapadmin** [comment]
The description for the tag itself goes in the field tag description which is now available in the tag input dialog. The tag description will be displayed whenever there is a tag selection. However, there is also a description of the tagging itself ("why did I choose this tag for this locus in particular"?). The two mustn't be confused.
