### ISSUE TITLE
context numbers from groups

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#386]
numbering in USTP is supposed to happen within a number range per group, with group, I guess depending on the unit? Or the device? That's unclear and needs discussion.

**Comment by urapadmin** [comment]
needs #397

**Comment by urapadmin** [comment]
see #399

**Comment by urapadmin** [comment]
### @test
Best tested in a real-life ustp scenario.
We decided currently on using the workstation-id given to the workstation in kiosk. That id is used to partition the numbering lists. Be aware that the id is case sensitive.

**Comment by lbestock** [comment]
Testing this needs two different workstations running the same test.

**Comment by lbestock** [comment]
Leave in testing right now. There are bugs that have been found in idgen_group that have to be attended to first. Test after #516 and $496 are closed.
