### ISSUE TITLE
free context numbers

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#387]
last year's season already has context numbers. Those would need to be entered freely.

**Comment by urapadmin** [comment]
see also #386

**Comment by urapadmin** [comment]
see also #399

**Comment by urapadmin** [comment]
possible now with the new free input numbering

**Comment by lbestock** [comment]
And faking Candace putting in legacy data was the first time I really saw how both having the default context identifying method and the ability to override it in a unit were necessary. Done. Good.
