### ISSUE TITLE
show the created_by and modified_by fields on all forms? 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#389]
or at least on those forms that do not have their own modified by fields.

**Comment by urapadmin** [comment]
ok, new plan: we make a "recorded by" (and I will make that term customizable) in narratives (where we already have it), excavation loci, collected material and small finds. 
I make the "modified by / date" visible almost everywhere but that field cannot be changed.

**Comment by urapadmin** [comment]
### @test 9.2.1 where you should find the modified-by label so far:

- [ ] locus upper right corner: shows the modification date of the locus data (but beware: changing something in one of the detail fields of the locus type does not change this date!)
- [ ] locus - every lot should have one
- [ ] locus - every locus photo should have one
- [ ] relations - every relation should have one

**Comment by SamKimball-BrownU** [comment]
Issue: does not appear on site map when entered via gear menu. It does show up when entered via note.

**Comment by SamKimball-BrownU** [comment]
issue: in locus photos, you cannot click on the tag to see more info

**Comment by urapadmin** [comment]
### v9.3,3
fixed

**Comment by SamKimball-BrownU** [comment]
Issue:

Very subtle, but the site map, when replaced with a new photo, does not update the time that it was last changed. You have to fully delete it and then add a new image in order for the changes to be reflected. See screenshots below

The initial state:
![image](https://user-images.githubusercontent.com/61027113/87237231-558ea800-c3b9-11ea-8407-08bf2d8ecddc.png)

After replacing it, I get this popup, with the CORRECT time (the current time) 
![image](https://user-images.githubusercontent.com/61027113/87237246-6d662c00-c3b9-11ea-976d-b03a13933447.png)

I click either cancel or ok (it doesn't make a difference to the results)

The time last modified still shows the original state. 

![image](https://user-images.githubusercontent.com/61027113/87237256-8c64be00-c3b9-11ea-90e6-2fd753f304f0.png)

Again, if you completely remove the image and then add a new one, then it will behave correctly. This happens to site map in both menus.

UPDATE: Also happens with site note photo. Would be worth checking all the associated image containers.

**Comment by SamKimball-BrownU** [comment]
Issue with locus/contexts is resolved.

**Comment by urapadmin** [comment]
every single of those bloody little labels is individually wired to the database, and even twice: what the label shows when it is clicked is individual from what it shows as a label. The issue was not that I confused created and modified timestamps, I used the wrong table (site instead of site_notes), which can make the difference even more subtle. 
Another not fun detail about image containers... Thorough testing is necessary here, but it does not have priority, because errors in those little labels are minor (in comparison to the big bugs we keep finding).

**Comment by urapadmin** [comment]
as for the proxy message see #695

**Comment by urapadmin** [comment]
happens with site note photo? That one I don't understand since site note photos do not have such a label.
I looked at site notes themselves but that looks ok to me.

**Comment by urapadmin** [comment]
### v9.4
should be fixed for all image containers. In the end there was - apart form individual mistakes I made, too - a systematic issue: When an existing photo got changed, it was in fact only the image record that changed and not the record that refers to the image. E.g. There are several locus photo records and they all refer to an image record (the gallery). Changing an image means changing the image in the gallery but the record that refers to it stays the same. With a new image, as your tests have shown, it is different. Here the referring record actually changes.

Now I explicitly trigger a modification of the referring record to have the date and the user updated. BUT: I had to do that again for every individual image container and so there was plenty of opportunity to confuse or forget something.

**Comment by SamKimball-BrownU** [comment]
As far as I can tell, this is all resolved.
