### ISSUE TITLE
do the structural concordance

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#396]
as documented [here](https://www.meritaten.net/urapdev/doku.php?id=concordance#ustp_concordance)

**Comment by urapadmin** [comment]
### @test
structural means database structure: Are all the input fields that ustp wanted there?

**Comment by lbestock** [comment]
I think this is in fact good. Scenarios won't test it better than looking at the sheets, and that we have done and input actual contexts and not run into absences.
