### ISSUE TITLE
get away from pieced-together archaeological contexts to archaeological contexts per record

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#397]
This is big but it seems the best way to simplify things and get away from the constant need of puzzling together an archaeological context across records. Every record that has an archaeological context will save the complete number from now on. An example: Currently the URAP# is pieced together using the tables collected_material, locus and unit. From now on we will save the whole archaeological context in the collected material.

**Comment by urapadmin** [comment]
This has several steps:
- [ ] site
- [ ] unit
- [ ] locus
- [ ] collected material
- [ ] pottery
- [ ] feature units
- [ ] survey units

**Comment by urapadmin** [comment]
related to #439

**Comment by lbestock** [comment]
I am not sure what testing this entails?

**Comment by urapadmin** [comment]
### @test
Will be tested with real life scenarios. Basically this refers to everywhere where an archaeological context is shown, e.G. locus number, unit number, urap#, pottery-number. So all identifiers that we write on bags, labels etc. are now created differently than they had been in previous version. Testing them means to make sure they are correct.
