### ISSUE TITLE
customizable numbering methods 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#399]
numbering should be configurable This is to do:
- [x] idgen_serial for numbers
- [x] idgen_serial for alphabet
- [x] idfmt_concat for numbers
- [x] idfmt_concat for alphabet
- [x] idgen_input
- [x] idfmt_input
- [x] use default numbering method from constants
- [x] use numbering method from unit
- [x] locus
- [x] collected material
- [ ] pottery
- [x] unit
- [x] feature unit
- [x] survey unit

**Comment by urapadmin** [comment]
###@test
This can be closed as soon as all kinds if numbering scenarios for all kinds of projects have been successfully tested.

**Comment by lbestock** [comment]
See #516 recently. I'm not sure how to close this or where to keep it. Close it? That customizable identification methods exist is now the case, but we run into problems with them that lead to individual tickets when running scenarios.
