### ISSUE TITLE
numbering method for group numbering

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#404]
- [x] idgen_group for ustp

**Comment by urapadmin** [comment]
double with #386

**Comment by urapadmin** [comment]
### @test
Just test if taking numbers from (a) predefined numbering list(s) work. Might need a more complex scenario.

**Comment by lbestock** [comment]
See also now #496 where problems occurred assigning two different idgen_group s to the same workstation (problem was in lists not in identification methods).

**Comment by urapadmin** [comment]
I think we had a bigger problem in #443

**Comment by lbestock** [comment]
See now also #516.

**Comment by lbestock** [comment]
I think the bigger problem or different issue you mentioned was #470? But that really is a separate issue. 

But this here itself works. I have tested it by making separate identification lists from serial numbers for CM and context. Properly applied, no problems.
