### ISSUE TITLE
workstation definition

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#419]
currently one has to define a workstation by selecting ipad and low. The whole definition will be abstract one day but maybe not before USTP. So I should get rid of the current ui at least in favour of a simpler solution.

**Comment by lbestock** [comment]
Yup. Candace created herself the wrong kind of workstation, and so had I, because I forgot about this.

**Comment by urapadmin** [comment]
#0.8.4
as the smallest of "improvements" I made the controls user's should not use anymore invisible and disabled.
