### ISSUE TITLE
allow changing numbering methods for units if admin is logged in

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#423]

**Comment by urapadmin** [comment]
see also #425 which can make changes impossible no matter if one is an admin or not

**Comment by urapadmin** [comment]
### @test

- [ ] First of all make sure that the configuration setting visiblitity/show_unit_numbering_methods allows unit-specific numbering methods at all. 

- [ ] Then make sure that normal users can see but not modify the settings if a unit already has a locus
- [ ] Normal users should be able to modify the settings as long as a unit is not in use
- [ ] Then make sure that you can change the settings even if the unit is in use when logged in as admin

**Comment by lbestock** [comment]
Good on the admin side, needs work on the normal user side. Normal user does not have access to the unit settings at all and I do not see where in configuration to turn it on.

**Comment by urapadmin** [comment]
test descriptions can never be too detailed:
First of all make sure **while logged in as admin** that the setting visibility/show_unit_numbering_methods is turned on. Logged in as user you don't even see the configuration button. The log in as normal user:
- [ ] Make sure that normal users can see but not modify the numbering method if a unit already has a locus
- [ ] Make sure that normal users can modify the numbering method if a unit does not have a locus
- [ ] Make sure that the numbering methods are invisible if (again set while an Admin) the configuration setting is set to "nope".

**Comment by lbestock** [comment]
Thank you for more detailed instructions.
