### ISSUE TITLE
use correct numbering method according to unit type

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#424]
that was not the case so far when creating units from the start page

**Comment by urapadmin** [comment]
### @test
If feature units and excavation units have different numbering methods for unit, locus and collected material, make sure that new numbers are actually generated according to the unit type specific numbering method.

**Comment by lbestock** [comment]
Ran into a problem with CM.
Test case on Alice (which, in fact, needed to be called alice in the workstation ID in the identification list) in URAP database.
Created an identification function similar to USTP to get serial numbers for locus from a list assigned to the workstation.
Was able to create units with different identification functions for locus (I did this as two excavation units set separately, not as a feature unit and an excavation unit with different defaults).
Loci created and identified properly.
CM identified properly in the unit with the URAP structured function.
CM NOT identified properly in the unit with the serial number function. In that case it was given just a locus number as the CM number, and in fact not the locus number of the locus in question so I have no idea how it did that:
![image](https://user-images.githubusercontent.com/49291909/76331614-bf8d2880-62c5-11ea-89f0-463a3317413e.png)

Important to note: the identification method that copies content is not even defined in this case so it should not have been possible for the USTP non-unique numbering of CM to occur.

**Comment by urapadmin** [comment]
please show me a screenshot of the identification method and a screenshot of the config settings for identification.

**Comment by lbestock** [comment]
(I'm still in the same version on URAP, which is 8.9.9)

Configuration settings:
![image](https://user-images.githubusercontent.com/49291909/79074510-cb9c4980-7cba-11ea-8e80-9df23e59e986.png)

Identification method:
![image](https://user-images.githubusercontent.com/49291909/79074515-d8b93880-7cba-11ea-81de-33c28aad58e2.png)

**Comment by urapadmin** [comment]
I cannot reproduce that. Please give me that database.

**Comment by urapadmin** [comment]
fixed in 8.9.12.
