### ISSUE TITLE
Unit to header even when not included in structured number

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#434]
Now that we can take the unit out of the locus number, the header does not tell us what unit we're in. Is there an easy way to have that? I would not be bothered to have it redundantly at URAP.

**Comment by urapadmin** [comment]
added Unit in excavation and collected material

**Comment by lbestock** [comment]
I see it in excavation. I do not see it in collected material. It should also be added in loci.

**Comment by urapadmin** [comment]
honestly? It should be there.

**Comment by lbestock** [comment]
Still not in Loci. But the Site is, so maybe just the wrong thing got up there?
![image](https://user-images.githubusercontent.com/49291909/75100089-4dafa200-5597-11ea-99f4-fca839ae1f80.png)

**Comment by lbestock** [comment]
And it is in Collected Material now.

**Comment by urapadmin** [comment]
should be fixed in recording system 8.9.6

**Comment by lbestock** [comment]
Fixed.
