### ISSUE TITLE
automatic fix of locus relations after synchronization or somewhere

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#435]
see #249 This is the kiosk side of it. In fact this would be needed only for urap (and khpp) because that's where we already have locus relations without their counterparts. But as a general "repair" feature it cannot hurt if kiosk makes generally sure after synchronization that all relations have their proper counterparts.

**Comment by urapadmin** [comment]
#321 is a duplicate of this here.

**Comment by urapadmin** [comment]
and it is needed for all projects because the filemaker part that manages the relations will never be perfect. I expect it to produce fragments on occasion.

**Comment by urapadmin** [comment]
### @test: kiosk v0.7.2
for khpp: see #611

**Comment by lbestock** [comment]
This is not really testable now given that FM automatically makes the relations. We will close this and wait to see if we run into problems.
