### ISSUE TITLE
Unit ID assignment failure

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#442]
I cannot set a unit ID ("trench/area") in unit creation when I have made a feature unit currently. Testing on LDB's Mac on 11 Feb 20. Screenshot.
<img width="1484" alt="Screen Shot 2020-02-11 at 2 18 31 PM" src="https://user-images.githubusercontent.com/49291909/74270754-bb2b1b00-4cd9-11ea-9056-5bc2f6c7fab9.png">

**Comment by lbestock** [comment]
Hm that got messed up in the last round. I also can't create another excavation unit now.

**Comment by urapadmin** [comment]
It could be healed locally by re-assigning the same numbering functions in the configuration dialog again (they were assigned!) My hunch is that maybe the import of the numbering methods creates new uids?

**Comment by urapadmin** [comment]
no, the issue is that filemaker stores uids uppercase and postgres turns them into lowercase. In the configuration the uppercase selection remains. When querying the identification method the uppercase uid does not match the now lowercase uid anymore. I have to always query those uids case insensitive to their case.

**Comment by urapadmin** [comment]
### @test
Found the bug. That should not happen again: After synchronization numbering should just work fine.

**Comment by lbestock** [comment]
Appears possibly differently bad, but I still cannot create a unit of any kind. Steps followed with screenshots of what happened (and this is using the file I downloaded on Thursday evening after the false alarm synchronization panic, so should be since you made the changes):
Clicked on the + to create a new unit. Got this (mostly fine, but why the pop-up image box thing?):
![image](https://user-images.githubusercontent.com/49291909/75099603-82205f80-5591-11ea-9bcf-92cd1cf5818c.png)
Clicked out of that but did not yet click in any actual box:
![image](https://user-images.githubusercontent.com/49291909/75099609-98c6b680-5591-11ea-9b3d-40f650f1eb28.png)
Clicked OK. Then clicked + in "Unit":
![image](https://user-images.githubusercontent.com/49291909/75099625-ae3be080-5591-11ea-95ce-f6496454d562.png)

**Comment by lbestock** [comment]
Hm, in USTP I was able to do it. Though I still got the "actions" thing popping up.

**Comment by urapadmin** [comment]
usually something like this is caused by a dumb field order. I changed that. Please try again.

**Comment by urapadmin** [comment]
see #495

**Comment by lbestock** [comment]
Appears all to be taken care of by changing of field order, addition of invisible mask for the background button, and updating iOS.
