### ISSUE TITLE
unable to enter a unit previously created

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#444]
Home page, drop down list of units, all can be selected but some don't give me the trowel button to enter them.
![UNADJUSTEDNONRAW_thumb_6](https://user-images.githubusercontent.com/49291909/74365429-1887a080-4d9c-11ea-96ad-5ab84ca5b9a4.jpg)

**Comment by urapadmin** [comment]
we found out that you assigned unit type and method that did not match. An improvement would be to keep you from saving a unit with a combination of the two that does not work.

**Comment by urapadmin** [comment]
the new ticket is #446
