### ISSUE TITLE
Locus tab mislabeled

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#459]
The locus tab is labeled "s" though the configuration setting is set to call a locus a locus.
![image](https://user-images.githubusercontent.com/49291909/74989349-1eb9f480-540e-11ea-9c16-c8d004f74cbc.png)

**Comment by urapadmin** [comment]
what went wrong with #418? I thought I gave all units the right terms.

**Comment by lbestock** [comment]
I also just noticed in clicking around that this is true for Unit FA but apparently not for other units. Do you need me to go through systematically and figure out if there are others and which?

**Comment by urapadmin** [comment]
no, this is a clear case and has to do with legacy Uronarti data.

**Comment by urapadmin** [comment]
should be fixed by kiosk 0.6.1 (and a subsequent new export of workstations).

**Comment by lbestock** [comment]
Hey! It's fixed!
