### ISSUE TITLE
drop down menu on tag definition/category not working

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#468]
Making new tags and enjoying being able to put their descriptions in under registrar/define tags. But the drop down menu for "category" does not work. I made three in different categories. It would autoinfill for me after I typed the first letter of an existing one if I wanted, but it will not give me the list as it should.

**Comment by urapadmin** [comment]
I cannot reproduce that under windows. Need a screenshot. We are talking about the "define tags" dialog here, right?

**Comment by lbestock** [comment]
Cannot be reproduced now in either URAP or USTP - I suspect it was a problem related to the need to update iOS.
