### ISSUE TITLE
unit creation annoyance

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#469]
I get the error warning all the time about units needing to have ID defined as a value. As in, if go to create a unit and I enter the excavator but have not yet given the unit an ID, it flashes the warning at me (and asks me if I want to revert all the fields after I click out of the warning). The warning should only happen when one clicks the check button to actually create the unit - until then, one is just filling things in in whatever order and that's fine.

**Comment by lbestock** [comment]
Now with 100% more images.
First I click the + to create a unit. I get this:
![image](https://user-images.githubusercontent.com/49291909/75194310-dfe5b080-5725-11ea-91ce-16901a1f539b.png)
I click on grey background space to close that menu, and get this:
![image](https://user-images.githubusercontent.com/49291909/75194335-eecc6300-5725-11ea-90b5-fb794c2dc3bb.png)
I click OK and get this:
![image](https://user-images.githubusercontent.com/49291909/75194388-04da2380-5726-11ea-9543-4c2c19b887ea.png)
I click no! And then I am able to call my unit whatever I want to call it.

**Comment by lbestock** [comment]
And see #442 which is where I made the original screenshots - we didn't find it because it was an older ticket I returned to you after testing still ran into problems, not a new ticket.

**Comment by urapadmin** [comment]
should be fixed now at v8.9.6

**Comment by lbestock** [comment]
Gorgeous. Everything seems to be taken care of.
