### ISSUE TITLE
Filemaker crash when using dropdown menu to change term for locus

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#473]
After creating new site, and defining new pedestrian survey, I tried to change the term for locus (or at least used that drop down menu). However, I didn't actually change anything (left default selection) and clicked off of menu. It then reverted back to information about a different site (western desert), and froze. Had to kill filemaker in task manager. I suspect it has something to do with reverting changes.

**Comment by urapadmin** [comment]
Hi Sam! Nice to meet your first ticket! I have a question, though: What exactly do you mean with "clicked off of menu". 
Were you able to reproduce the behaviour? It always helps if repeating steps actually repeats the bug.

**Comment by urapadmin** [comment]
oh, and what are you using, currently? Filemaker Go or Filemaker on MacOs or Filemaker on Windows?

**Comment by SamKimball-BrownU** [comment]
Hey! sorry that the ticket was a bit rushed, it was near the end of the meeting. When mean "clicked off of menu" I mean that I just clicked somewhere on the background, i.e. not within the drop-down menu. I am using Filemaker on Windows

I was able to recreate something similar (although not quite what I remember, but maybe I absentmindedly clicked through the pop-up)

1. use admin account
2. create new pedestrian survey (in my case, it is in a test site SS1 - Eastern Desert)* 
2.b. make sure you have not defined the Unit ID yet
3. click anywhere on grey background (i.e. not on a ui element)
4. There should be a Pop-Up that reads: "id" is defined to require a value, but it is not available on this layout. Use another layout to assign a value to this field.
5. click ok on pop-up from 4
6. a new pop-up reads "revert all changes to this record since it was last entered"
7. Click revert

It then populates the form with information from Unit F017, a circular stone structure (feature) from the Western Desert site. Filemaker becomes non-responsive and must be killed in task manager.

If the Unit ID is defined, then this problem no longer exists, and I can click anywhere on the background with no problem. 

*just tried it and it works with creating new features/excavations as well

**Comment by urapadmin** [comment]
that is a bad bug but a very helpful ticket to find it! One last thing: It is always a good information for me to tell me the exact version number you are testing with (you find it on the start screen).

**Comment by SamKimball-BrownU** [comment]
The version is 17.II.2020/v8.9.3

Thanks!

**Comment by urapadmin** [comment]
### @test 
Hopefully fixed in 8.9.5.
That filemaker crashes is a filemaker bug. Can't do anything except prevent the situation. That a background click triggers saving the record is one of those filemaker stupidities I was able to prevent. 
So from now on it should not be possible anymore to reproduce the situation.
