### ISSUE TITLE
delete collected material - but only if it is empty!

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#474]
means, it should not be a small find, it should not have photos and it should not have pottery attached to it.

**Comment by urapadmin** [comment]
### @test recording 9.6.1
a collected material can be deleted as long as it does not have a small find record, a photo or pottery attached. 
The delete buttons are in the collected material lists:
- [ ] locus recording (excavating)
- [ ] locus
- [ ] feature recording
- [ ] survey

**Comment by lbestock** [comment]
Testing in recording 10 on PVD on iPad mini. I get the same "error: access privileges do not allow you to perform this action" as I got when trying to delete a locus.

First I tried this when signed in as ldb. Then I got that message immediately.

I then tried signed in as admin. When I press the trash button as admin I get the popup asking me if I am sure I really want to delete this CM. When I say "yes" I get the privileges error again, just one step farther down the road.

**Comment by urapadmin** [comment]
From now on we have to be over-precise when it comes to "as admin". There are two admins: One is our app-admin (the one you type in in our own new login screen) and one is the filemaker-admin (the one we have always had and is still there for special purposes). I do understand you meant the app-admin here and then the error is a clear case and 
### fixed in  10.0.1

**Comment by lbestock** [comment]
I think I need this explained to me, though you have clearly understood what I did and (#932) appear to have taken care of the immediate problem.

**Comment by urapadmin** [comment]
you might want to attend to #378 which is the major feature of this milestone, anyhow.

**Comment by lbestock** [comment]
Tested in PVD with small finds and photos and nothing, but not with pottery yet.  I am not sure what "locus" separate from locus recording in excavation means, but the other three are tested with the variables mentioned and work just fine, no more error messages.

**Comment by urapadmin** [comment]
that was a copy & paste error. it should have been simply "excavating". There is a cm list in excavating and there is a cm list in the locus form.

**Comment by lbestock** [comment]
There isn't really a CM list in excavating though, or at least not a composite one. It is just the list from the last-specified locus. If one tries to click that tab when one first enters the excavation pane and one has not yet specified a locus, one is told one must specify an active locus. In which case isn't deleting something when I arrive at it that way really the same as deleting it when I arrive there through the context? The list and banner look identical. And deletion works as expected.

**Comment by urapadmin** [comment]
I don't understand. How is the list of cm for the last specified locus not a CM list? That is exactly the same cm list you find in the locus form. And yes, deleting something there is exactly the same thing as if arriving at that list in the context (locus form). 
I don't understand.

**Comment by lbestock** [comment]
I think it is mutual misunderstandings; since it is exactly the same thing and not at the unit level and needs to have an actively specified locus first it doesn't register for me as a different thing than the list accessed through the locus directly and I thought I must be missing something. But now I understand you and it's simpler than I thought and all works fine.
