### ISSUE TITLE
new configuration setting: cache_only_direct_image_links

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#476]
this controls if a bigger "identifier - image - cache" has to be build:

If a project uses hierarchical identifiers then a smaller cache is fine, because when one searches for "FI" one also finds images from "FI-001" and from "FI-001-1" simply because FI is part of all the identifiers. All we need to cache in this case is one relation between an image and FI-001 and one relation between FI-001-1 and its image.

If a project does not use hierarchical numbers, this configuration setting has to be set to "nope" and so a much bigger cache is built. To keep the example from above: The cache would have the relationship between FI-001-1 and its image but also between that same image and FI-001 and again that same image and FI. Only that way we are able to find the image no matter if the user types "FI", "FI-001" or "FI-001-1".

The image-identifier-cache will be bigger and creating it will take longer for such a project.

**Comment by urapadmin** [comment]
### @test
For URAP this should be set to "yup". Test if a collected material, say "FI-001-1" is found by typing "FI", "FI-001" and, of course "FI-001-1" in the gallery.

For USTP this should be set tot "nope". Test if a collected material in a context also turns up if its trench id is the search term in the gallery.

**Comment by lbestock** [comment]
For Laurel, when you're doing #479 as well because you'll need the server up and running. The configuration setting to change is found in identification.

**Comment by lbestock** [comment]
Tested in 8.9.12 USTP with nope set. Works just fine for CM and context photos. But a search in the gallery for the unit name does not return the images that are in dayplans, and it should. (Also dayplan is not an option in the recording context dropdown in the gallery search.)

**Comment by urapadmin** [comment]
I suggest assigning this to Sam, who has been testing file-identifier-cache issues anyhow. This is most likely due to general issues with image containers. Let's wait until all image containers are tested to be working properly. And if that is ok, we can test this particular case here.

**Comment by urapadmin** [comment]
### @test
don't bother. This is already deprecated. In kiosk 8 / recording 10 building a whole file-identifier-cache on export to filemaker will be unnecessary.
