### ISSUE TITLE
create a new file identifier cache at the end of the first export of a workstation after a new sync 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#479]
After a synchronization the file identifier cache is obsolete and needs to be rebuilt. That can take more than a minute but is only needed once after a synchronization. Subsequent exports to filemaker don't need to repeat it until a new synchronization makes it necessary again.

**Comment by urapadmin** [comment]
### @test
Easy to test: There should be a longish step at about 70% of the "prepare download" phase (the second phase of "prepare for field". But that step should only occur for the first workstation that is prepared for the field and not at all for any others. Only after a synchronization the step is needed again, but again only once. 
see also #476 which determines how long the step takes. If set to "yup", which means the project uses hierarchical identifiers, the step should be a bit faster than without the setting,

**Comment by lbestock** [comment]
This one has to be Laurel.

**Comment by lbestock** [comment]
Lightspeed - it's lovely.
