### ISSUE TITLE
safe mode for synchronization

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#48]
A safe mode for synchronization would prevent records from being deleted, which can be helpful in some cases.

**Comment by urapadmin** [comment]
might not so much be a safe mode for the whole synchronization but more that a single workstation (the one with the issues) is treated differently than the others: No deletions and perhaps even no modifications of existing records?

**Comment by urapadmin** [comment]
for v1 I would still want at least the coarse version of a safe mode: No deletions at all.

**Comment by urapadmin** [comment]
### kiosk 0.13.4 
- [ ] the safe mode checkbox is not greyed out anymore and can be activated
- [ ] when synchronization runs in safe mode it shows a warning for every table (record type) in which records would have been deleted without safe mode
- [ ] when safe mode is not on deletions are carried out as usual

**Comment by urapadmin** [comment]
the other idea to control the safe mode on workstation level gets a new post v1 ticket

**Comment by lbestock** [comment]
I think you rolled this out already in 0.13.3 (at least - the checkbox is checkable) so we can test it now.

**Comment by lbestock** [comment]
OK weird. I could check it when I first went there, and I then ran synchronization. There was nothing to synchronize so it told me so.
Then I gave it something actual to synchronize by downloading, adding data, etc. And now indeed I can't any longer check the safe mode box - it's greyed.

**Comment by lbestock** [comment]
PVD 13.5 where it is well and truly rolled out.
Tells me what was not deleted, as expected. And stuff is there as it should be when I download again.
When I delete and then run synchronization without safe mode it deletes things without telling me. So, proper.
