### ISSUE TITLE
show kiosk version in header

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#480]
Because I have to get used to referring to the kiosk version so that testers know if kiosk version and fix of an issue match

**Comment by urapadmin** [comment]
upper right corner

**Comment by lbestock** [comment]
How do I test that as a user?

**Comment by urapadmin** [comment]
Once you get a kiosk version >= 0.6.1 and actually test kiosk you should find the version hint in the upper right corner.
