### ISSUE TITLE
idfmt_input must allow for prefix and postfix

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#481]
using these formatting parameters for the idfmt_input formatting function should work as expected:
prefix=_some prefix_
postfix=_some postfix_

**Comment by urapadmin** [comment]
fixed. was really a bug. Works now in 8.5.6

**Comment by lbestock** [comment]
How do I test this? I think I need help from LKH to write a good testing scenario for the identification methods.

**Comment by urapadmin** [comment]
### @test
Well, you test it by creating an identification method that uses free input as function. 
An then you use it without prefix and suffix (it should work), 
then you assign a prefix.
then you assign a suffix (but not a prefix),
and then you assign a prefix and a suffix. 
When the user is asked for an identifier by this method and types in "BBB", the method puts the prefix in front and the suffix behind the BBB.
