### ISSUE TITLE
chaos in unit creation with arch_context / unit_id etc. 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#482]
Needs cleaning up Bloody unit-id. Use idfmt_input with a prefix and you see that all kinds of different identifiers are at play.

**Comment by urapadmin** [comment]
### @test
Forget about the bug description. This can be closed as soon as normal archaeological scenarios in ustp and urap are successfully tested.

**Comment by SamKimball-BrownU** [comment]
I suppose we could probably close this one now?

**Comment by lbestock** [comment]
I think so? Lutz, does testing via scenario in PVD and testing via me having made a bunch of the new survey and feature units in URAP satisfy you on this?
