### ISSUE TITLE
unit-id already in use but it isn't in fact

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#483]
when editing an already existing unit with an id, say "123", which does not have a locus so far, so that the unit-id can still be changed:
Changing it to the same "123" gives the message that "123" is already in use by another unit. But that is not correct since it is in use by the same unit. In this case no error message should appear at all.

**Comment by urapadmin** [comment]
### @test v8.9.7

- [ ] when adding a unit with an id that is indeed already in use by a second unit, an error should occur
- [ ] edit the unit id (needs free input) and don't change it but hit Ok. That should work fine and no error should occur because the unit id is in use but by the same unit and not a second one.

**Comment by lbestock** [comment]
Wait, this says it should be updated in v.8.9.7 but I just tested it in v.8.9.6 and it seemed problem free so maybe I am not understanding.

**Comment by lbestock** [comment]
it's fine
