### ISSUE TITLE
Hitting “return” in unit creation ID name causes problems 

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#485]
Naming the unit. I hit return, and that moved the cursor to the next line rather than accepting the name and closing the dialog box. Then of course the name was the wrong format, with its extra line, so I got an error message: 
![252AE5D9-AFD3-4169-8595-0FEDF236C884](https://user-images.githubusercontent.com/49291909/75613602-843c6e00-5afd-11ea-814d-e5d70d83178d.png)

**Comment by urapadmin** [comment]
no hitting return anymore in the free input dialog.
