### ISSUE TITLE
new image handling in collected_material_photo

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#489]
apply the test for image containers to collected material photo

**Comment by urapadmin** [comment]
https://www.meritaten.net/urapdev/doku.php?id=how_to_test_an_image_container

**Comment by SamKimball-BrownU** [comment]
Nasty error window when using popup to input images, but after dismissing it it works as intended
![image](https://user-images.githubusercontent.com/61027113/76472959-7aecb480-63cd-11ea-90cb-0b28c4684f73.png)

update: also shows up when adding an additional image

**Comment by SamKimball-BrownU** [comment]
Note: see https://github.com/urapadmin/kiosk/issues/487#issuecomment-597931520

Otherwise working as intended (certainly in collected material photo it is). Backspace does not delete entry, just the photo in the entry. I believe this is acceptable behavior.

**Comment by urapadmin** [comment]
I suspect this was due to a different bug that screwed up the current unit when going to a collected material. As a result no unit was known and that caused the nasty error window. 
In other words: try again with v8.9.10.

**Comment by SamKimball-BrownU** [comment]
Resolved! Functioning as intended.
