### ISSUE TITLE
Filemaker crash when defining new relationship between loci

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#491]
Version: 17.II.2020/ V8.9.3

Steps To Reproduce:
1. create a couple of loci (just for testing this, it will work with predefined loci)
2. define a new relationship
3. choose a locus in the "to locus" drop down
4. try to choose type of relationship

Filemaker then crashes and must be force closed. Work is not lost and is still there on restart.
Works as intended if type of relationship is chosen before the "to locus" option so maybe not initialized?

**Comment by urapadmin** [comment]
I was not able to reproduce the crash itself but I got at least stuck in the field, which might cause some filemaker version to crash. 
The field can be left now. Is the crash gone, too?
