### ISSUE TITLE
handling of file respolution rules should not use the excavation_context anymore

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#492]
see here https://www.meritaten.net/urapdev/doku.php?id=table_context:

... the field does play a role in the mechanism of file_resolution_rules. It is one of the informations to which a file resolution rule can be attached. That allows, for instance, to deliver the high-resolution version of an image to a specific excavation context only. Let's assume that in general all images that are transfered to an ipad are low-resolution images. But in unit CC the team is currently working on very detailed maps, which are needed in high resolution. By establishing a rule bound to the excavation context “CC” the images connected to this unit can be delivered in high resolution, overriding the general low-res rule.

**Comment by urapadmin** [comment]
currently recordingworkstation does not give any of the contexts to UrapFileResolutionRules().get_resolution anymore because there isn't one context any longer. The method needs to accept multiple contexts one day. But that does not have any priority since we have never used this feature.

**Comment by urapadmin** [comment]
this can live now in v1 only. It is not in use so far and I have done everything to make sure it does not cause any problems.

**Comment by urapadmin** [comment]
This should be obsolete now, no?

**Comment by lbestock** [comment]
We use file-picking now and can accomplish the task outlined in the original ticket, so from my perspective yes.
