### ISSUE TITLE
cannot assign two different identifier lists to the same partition

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#496]
Attempting to make different identifier lists with separate sets for idgen_group. One exists and is successfully used for identifying loci (contexts in this case: USTP) with partition ldbipad.
![image](https://user-images.githubusercontent.com/49291909/75905550-0afd8d80-5e13-11ea-860f-8568b559d66c.png)

I wanted to create a second one for collected material. I created the identification function by copying the existing idgen_group, telling it to use the list "collected material numbers". I then went to identifier lists and attempted to create that list for the function to use. I was able to title the list properly, but when I attempted to assign it to the partition ldbipad I received an error message:
![image](https://user-images.githubusercontent.com/49291909/75905714-5ca61800-5e13-11ea-8e29-74b8532c586d.png)

**Comment by urapadmin** [comment]
should be fixed. Make sure that it does not let you define the same partition twice in the same list!
