### ISSUE TITLE
image gallery context blank

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#497]
Black iPad image testing in USTP v. 8.9.7.
In the image gallery the drop-down menu that should give recording contexts is empty though there are a lot of images with recording contexts:
![image](https://user-images.githubusercontent.com/49291909/75923311-c8e44400-5e32-11ea-88ad-088382964ee2.png)

**Comment by urapadmin** [comment]
should be fixed in v8.9.9
