### ISSUE TITLE
site or site_map as recording context? Decide!

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#499]
it seems to be different between filemaker and kiosk

**Comment by urapadmin** [comment]
I decided on site. Because that is what the recording context for a site map was before. In other words.
###@test
means that after inputting a site map it should appear in the gallery when limiting the recording context to "site"

**Comment by urapadmin** [comment]
### @test v.8.9.13
no, that is not correct. It has to be "site". So: Entering a new image into a site should now appear in the gallery under recording context "site".

**Comment by lbestock** [comment]
Yes, "site" is for "site map" in the gallery and "site note" is for "site note" and it all seems proper to me.
