### ISSUE TITLE
option to copy existing information when creating new identification method

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#502]
Many new identification methods are modifications of existing identification methods. For those less familiar with how to create them (and even for those who really understand) it would be easier and less likely to result in errors to create a new method by copying the most similar old one, then slightly changing the parameters and changing the name.

**Comment by urapadmin** [comment]
### 9.6.1
-[ ] there is a new copy button now next to the + button

**Comment by lbestock** [comment]
Does not work properly on the iPad:
![image](https://user-images.githubusercontent.com/49291909/108014040-09ed4e00-6fdb-11eb-80f5-4fe5cd5ff382.png)

**Comment by lbestock** [comment]
Or at least, I was confused to get that dialog box? But the resulting created method has copied the functions properly. When I try to copy one with parameters it does indeed copy those, too, but it does the same thing of popping open that action window. So a cosmetic problem.

**Comment by urapadmin** [comment]
### 10.0.2
and why the heck does filemaker open a popup window on an image container you are not even allowed to change? Argh. 
Well, it should not happen any longer.

**Comment by lbestock** [comment]
It does not. Now I can celebrate this feature.
