### ISSUE TITLE
update file container to new handling in pottery 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#504]
and get rid of excavation context and table context etc.

**Comment by urapadmin** [comment]
duplicate: #561

**Comment by urapadmin** [comment]
### @test v9
all done, the pottery image container should pass all the typical image container tests. Note that this one exists only in a popover.

**Comment by SamKimball-BrownU** [comment]
So I have enabled pottery processing (it was under visibility btw), and added some ceramics to a context, and marked them as "C" or "C!", but still nothing appears in pottery processing. Am I missing something?

**Comment by urapadmin** [comment]
Pottery Processing might need some instructions. It is a but special. You start the processing of a bag of collected material by choosing the collected material number:
![image](https://user-images.githubusercontent.com/38838314/82124667-9201a700-976e-11ea-9d21-80be5d629117.png)

You see the round button next to the Urap#? IT opens the list of collected material with material type ceramics. If you see a little pot next to the identifier in this list it tells you that for this collected material the processing had been started earlier. So you won't see a pot in the beginning, but you should see collected material numbers.

After you select the cm you'll be asked if you want to start processing - you do.
And now you can process. Since you only want to test the image gallery, go straight to the end of the line, the camera button opens a popup. Pottery processing manages several images per line within the popup, which means, that the usual combination of no-popup image container and popup does not exist here. You only have the popup to test. All image containers are slightly different, sheesh.

**Comment by urapadmin** [comment]
changing the description does not change the description of the image in the file identifier cache

**Comment by urapadmin** [comment]
rest is ok.

**Comment by urapadmin** [comment]
no, it was not. the image proxy field was not updated correctly. In none of the image containers. So this needs a new thorough test, this time with img_proxy.

**Comment by urapadmin** [comment]
### v9.1
