### ISSUE TITLE
update image container to new image handling in inventory 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#505]
should just mean that a proper backspace handling is necessary. Inventory images are not connected to recording data.

**Comment by urapadmin** [comment]
### @test v8.9.18
that image container does not support the gallery and does not affect the file-identifier-cache. So testing is limited to inserting an image and deleting it (in which case it should not be deleted from the gallery but the container should empty, as usual).

**Comment by lbestock** [comment]
Not totally sure I understood the test. I will describe what I did and what happened and if it tested the way you want, close the ticket.

- Created two inventory items, with images.
- Went to gallery - both images were there (with no information).
- Back to inventory, deleted one of the images.
- Back to gallery - image was gone but container was still there.

I THINK that means it tested as you wished.

**Comment by lbestock** [comment]
I was wrong about what was supposed to happen, and tested this before I got 18. So, total uselessness. Goes to Sam, who does all the image stuff, to be tested when we have the new version.

**Comment by SamKimball-BrownU** [comment]
Mostly functional, except drag-and-drop operations don't actually tag it as "inventory," and no drag-and-drop warning is issued. Pretty subtle issue that I'm glad I caught.

**Comment by urapadmin** [comment]
there's nothing like stubborn, systematic testing. 
### v9.0.5: drag & drop should be fine now. 
There is one case I don't care for here: The "inventory" tag stays with the image in the gallery if the image is deleted from the container using backspace/del/cut etc.

**Comment by SamKimball-BrownU** [comment]
Resolved, except no drag and drop warning issued. Everything is functional on drag and drop operations, so closing ticket.

**Comment by urapadmin** [comment]
reopened because image proxy was not set correctly.

**Comment by urapadmin** [comment]
### v9.1
should be set properly.
