### ISSUE TITLE
filemaker-related steps don't work on Beset

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#512]
and the only solution would be if the filemaker tasks are handled by a process that is external from the iis processes. Connected by a task queue. see also #129

**Comment by urapadmin** [comment]
and the only solution would be if the filemaker tasks are handled by a process that is external from the iis processes. Connected by a task queue. see also #129

**Comment by urapadmin** [comment]
see #129

**Comment by urapadmin** [comment]
### kiosk 0.8
The full synchronization cycle should work now on Beset. This here is NOT about whether the results are correct, this here is about whether the steps are accessible and run at all.

**Comment by lbestock** [comment]
The full synchronization cycle works on Beset, tested on  USTP. I don't know what jobs are and the wiki page has been created but not written, but nonetheless this can be closed.
