### ISSUE TITLE
error producing identifier from list for workstation

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#516]
I am rusty but this seems like it should not happen. I set an identifier list for the partition alice. It allowed me to produce a first context identifier "1". It did not let me create the second context, giving me an error message you see below. The partition was defined as having identifiers 1-1000 so "2" should not have been a problem...
![image](https://user-images.githubusercontent.com/49291909/78462228-27087f00-769e-11ea-9e34-2bdde40b8f84.png)
![image](https://user-images.githubusercontent.com/49291909/78462230-2bcd3300-769e-11ea-9be0-b941978b368f.png)

**Comment by lbestock** [comment]
If you want the identification method:

![image](https://user-images.githubusercontent.com/49291909/78462278-79e23680-769e-11ea-99c8-f9cd9aa924aa.png)

**Comment by lbestock** [comment]
For reference I am in v.8.9.10 on Alice (obviously that).

**Comment by urapadmin** [comment]
nothing rusty about it. Looks like a bug to me, too.

**Comment by urapadmin** [comment]
### @test: v.8.9.11
fixed for ustp and urap.
