### ISSUE TITLE
filerepository file download must include context identifiers

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#517]
that needs more thinking and some refactoring of KioskContextualFile so that this uses actual KioskContext. It should be changed together with a  transfer of functionality from ModelFileRepository.FileRepositoryFile to KioskContextualFile.

**Comment by urapadmin** [comment]
Just uses the FileIdentifierContext. No more refactoring than that.

**Comment by urapadmin** [comment]
### @test V0.6.9 
When downloading a file from the edit file dialog the filename should contain all primary context identifiers and if available the context-independent description. A candid (no identifiers) should only use the context-independent description or if nothing is available the file's uuid as filename.

**Comment by lbestock** [comment]
This is really cool.
Tested just fine as expected for URAP. 
Works as expected for USTP, too. Very cool. Their stupid numbering system means no way to distinguish between context and CM photos by file name, but that is their fault.
