### ISSUE TITLE
'serial_context_per_device' - Unable to create any context/loci/etc with old copy of USTP

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#518]
USTP Version 8.9.10, windows

A week ago this problem did not exist.

Basically, I am able to create new sites/trench areas in USTP, but that is about the limit of what I can do. For excavations, this is what it looks like:

![image](https://user-images.githubusercontent.com/61027113/78922013-731b4100-7a5b-11ea-9745-0ca4f9e65c82.png)

For surveys, the same popup comes when I just try to access the newly created survey (pressing the "foot" button)

![image](https://user-images.githubusercontent.com/61027113/78922101-95ad5a00-7a5b-11ea-83e8-5a59f3c805b6.png)

I can dismiss this and access the survey, but this is what happens:

![image](https://user-images.githubusercontent.com/61027113/78922151-aeb60b00-7a5b-11ea-8ea1-754f4ecfa8a1.png)

Tried changing the default context identifiers in the creation of the units, but it did not help. Could not find a work around. Will try downloading new copy and seeing if that resolves the issue. Issue has not happened with URAP v8.9.9

Note that I am in a different time zone, so this may be causing the problem

**Comment by lbestock** [comment]
A configuration issue: it's using an identification method that relies on a list that hasn't been configured. So what you need to do is to configure the list, making sure that its name is the one the method seeks ("context numbers"). The relevant identification method is already configured and looks like this:
![image](https://user-images.githubusercontent.com/49291909/78927570-1d4f9480-7a6d-11ea-8ab7-669519fba3e5.png)

From the home screen go to the admin tab and choose the identifier lists button on the right.

Create a new identifier list. Call it context numbers.

"Partition" refers to your device. You're skimb so call it that (it's all case sensitive by the way and this is easy to screw up, but one only has to do it once per project in real life). 

The next two fields are the range. Set it from 1 to 999 or some such. 

(The function accomplished by this seeming complexity is that two people on different iPads can be working at the same time and not assign the same number twice - it's workstation dependent in that case, and your workstation would have 1-999 and mine 1000-1999, etc. Only some projects need this, those who have context numbers that are not unit bound. So URAP defines numbers very differently.)

**Comment by SamKimball-BrownU** [comment]
Resolved! This fixed it, although I will have to get used to the USTP numbering system
