### ISSUE TITLE
record types (recording contexts) should be customizable in the recording system

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#519]
because they are now in kiosk. It is confusing that in filemaker things are called "locus_photo" and in kiosk it is "context photo".

**Comment by urapadmin** [comment]
### @test v8.9
see here: https://www.meritaten.net/urapdev/doku.php?id=manuals:user_manual:selected_configuration_topics_filemaker#names_of_record_types

- [ ] Test if giving record types new names affects the gallery. Test the list selection and the image details
- [ ] I think, the gallery is the only place in the filemaker app where record types (formerly recording context or table context) surface. If you find other parts of the app that mention record types, that would be a bug.

**Comment by lbestock** [comment]
Two questions for discussion, noted here so I don't forget them: 

1) the second part of the test is not testable. Let's keep a running list in the wiki or some such of things that are not tests but for which testers need to keep an eye out?

2) what are the implications for the File Repository of changing the name of a record type?

**Comment by urapadmin** [comment]
as for 2.: None. The File Repository has a different mechanism to configure names for the internal record types. We'll test that in a different test (I don't even know, yet, how to test such things when it comes to Kiosk). But internally the record type is always managed as "locus_photo" and it is only on the user interfaces that those terms are translated into a different name. In other words: If you select "context photo" in the gallery, "locus_photo" is stored in the database. So changing the terms in filemaker has no implications for the file repository.

**Comment by urapadmin** [comment]
as for that second part of the test: Now that the tag analysis shows you the identifier and the record type of an image we have a new case where the correct project-specific record type identifier has to appear. I don't have a good idea how to organize testing so that this is on the radar while the software evolves. Difficult. The wiki won't help, I fear, because nobody reads it regularly.

**Comment by urapadmin** [comment]
can we close this?

**Comment by lbestock** [comment]
Yes.
