### ISSUE TITLE
No lots in USTP?

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#520]
Is USTP supposed to have lots? (when switched to not-simple excavating)
I assume not but just want to make sure.

**Comment by urapadmin** [comment]
Whether or not USTP has lots depends on the configuration setting in visibility/use_lots. But I believe ustp is configured to have no lots indeed.

**Comment by SamKimball-BrownU** [comment]
Checked the configuration settings and confirmed. Just wanted to make sure! Thanks.
