### ISSUE TITLE
Images in dayplan not searchable when popup is used to give description

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#521]
USTP 1.9.11, Windows 10

![image](https://user-images.githubusercontent.com/61027113/79054654-52461d80-7c0c-11ea-8150-84abf8795769.png)

Images in dayplan not searchable by description or identifier when the popup is used to enter description (highlighted in the screenshot). Issue confirmed to not exist elsewhere, only in dayplans.

**Comment by urapadmin** [comment]
fixed in V8.9.12

**Comment by SamKimball-BrownU** [comment]
So now there is a whole host of problems with dayplan images now, although I suspect they are all stemming from one issue. I created a couple new tickets just so that you can organize better. 

As for this, dayplan images are now unsearchable by description no matter what way you do it. See Ticket #529 for further explanation

See also #530 for further issues.

**Comment by SamKimball-BrownU** [comment]
Additional: Images in dayplan are only given they identifier of the excavation unit, not the site

**Comment by urapadmin** [comment]
### v8.9.14: all the other issues here should be solved now

**Comment by SamKimball-BrownU** [comment]
Resolved. Tested in both simple and non-simple excavating.
