### ISSUE TITLE
deleting site note image deletes other references to it, or rather the image itself

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#523]
**When deleting the site note images that were added through gallery, they are also deleted everywhere else they are used.** When searching for it under identifiers that should be there (say from the dayplan, not the site note), a record pops up, but does not show the image. This seems like a good clue? See below. 

![image](https://user-images.githubusercontent.com/61027113/79056474-9ccf9600-7c1c-11ea-83eb-b442db98f195.png)
GAL3 is the image I deleted in the site note. It should still be here, but was deleted when I deleted the image in the site note.

![image](https://user-images.githubusercontent.com/61027113/79056487-bcff5500-7c1c-11ea-9faa-0ef746bfdff9.png)
This is what happens when you then search for GAL3. 

The correct behavior happens when searching for it under site note identifiers.

I think that this behavior is related to the behavior in #471, I would guess related to image handling in Site records as a whole

**Comment by urapadmin** [comment]
another one I can neither reproduce in my own nor in your database. This gets a but worrisome. Hoping for a different filemaker version...

**Comment by urapadmin** [comment]
can you please double check if this still happens in v8.9.12? Many general changes to image handling might have eliminated this.

**Comment by SamKimball-BrownU** [comment]
So this particular issue is resolved, but see issue 1 on my latest update to #452

> Issue 1: When [site note] images are added through the gallery, they are not given site identifier (and are thus not searchable)

So I don't think I could really adequately test this. So I think I should probably leave this ticket open and just double check that it is resolved later

**Comment by SamKimball-BrownU** [comment]
Resolved.
