### ISSUE TITLE
squiggle___bum for unit id's

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#526]
I assume you know about this, but in USTP, when creating new units (trenches/survey units), when you put in the trench/area code, it is augmented by squiggle in the front and bum in the back (see screenshot). Pretty comical at least

![image](https://user-images.githubusercontent.com/61027113/79295701-f2b37080-7e9e-11ea-92bf-2f4fb511ebe7.png)

**Comment by lbestock** [comment]
Yeah that was me testing if prefixes and postfixes worked with a free input
identification method. And then forgetting to turn it off again.


Laurel Bestock
Associate Professor of Archaeology and Egyptology
Director of Graduate Studies, Joukowsky Institute for Archaeology and the
Ancient World
Brown University

https://blogs.brown.edu/archaeology/fieldwork/uronarti/

**Comment by urapadmin** [comment]
not a bug

**Comment by SamKimball-BrownU** [comment]
Resolved.
