### ISSUE TITLE
wrong context type displayed in banner in CM

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#527]
Created a CM in USTP 8.9.12.
Noticed that the information in the header is not accurate - it is trench PDQ and it is context 0013 but context 0013 itself is not architecture:
![image](https://user-images.githubusercontent.com/49291909/79362412-90955280-7f14-11ea-8a0a-6741eb7cbec3.png)
![image](https://user-images.githubusercontent.com/49291909/79362479-a86cd680-7f14-11ea-9e43-405384765505.png)

**Comment by urapadmin** [comment]
### fixed in 8.9.17
