### ISSUE TITLE
Dayplan Image Descriptions cause nasty errors

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#529]
So, whenever I try to give a description to dayplan images (by any method, in popup or not), there is a nasty window that appears. It seems to be the back end of file maker showing itself.
![image](https://user-images.githubusercontent.com/61027113/79383756-597e6b80-7f2b-11ea-9243-dbef3c2e6567.png)

What I would suspect is happening from a software perspective is that instead of the image description being given to the entry, an entirely new entry is created that is effectively a copy of the previous one, just with the new description. This leads to problems with not having a unique identifier.

There are several popups that follow, screenshots below.

![image](https://user-images.githubusercontent.com/61027113/79383906-9a768000-7f2b-11ea-90c0-0546b29db23f.png)

![image](https://user-images.githubusercontent.com/61027113/79383929-a3675180-7f2b-11ea-81a4-fc3d3940f8d0.png)

![image](https://user-images.githubusercontent.com/61027113/79383950-ae21e680-7f2b-11ea-994f-9fd9bfa90a3e.png)

After choosing "revert" on all of these, the nasty database disappears, and the description is visible. However, images are not searchable by that description. This is all of course following the workaround for another ticket that I am about to write, see comment below this for number/link

**Comment by SamKimball-BrownU** [comment]
HOWEVER I will say that this is all using the workaround from #530, so this is likely to be fixed when working through that error.

**Comment by urapadmin** [comment]
### v8.9.14: all issues here should be solved now

**Comment by SamKimball-BrownU** [comment]
Resolved.
