### ISSUE TITLE
Unable to add images in dayplan, workaround found

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#530]
When trying to add the first image in a new unit or in a unit where all dayplans have been deleted (any method other than gallery), this popup is given

![image](https://user-images.githubusercontent.com/61027113/79384535-ac0c5780-7f2c-11ea-90e9-f85d0d5afc56.png)
 
this popup happens 2x

then this one
![image](https://user-images.githubusercontent.com/61027113/79384581-c6463580-7f2c-11ea-8530-ef20003cbbcf.png)

If gallery is used, then this is the result

![image](https://user-images.githubusercontent.com/61027113/79384777-1fae6480-7f2d-11ea-9514-2c71425f6f75.png)

WORKAROUND:

If an empty dayplan is added, then you can resume normal operation with all subsequent new dayplans, see below

![image](https://user-images.githubusercontent.com/61027113/79384999-7ddb4780-7f2d-11ea-8552-b1e340d22780.png)

**Comment by urapadmin** [comment]
Please send me this database. I can neither reproduce this in the development version nor after I downloaded the workstation you got from Beset.

**Comment by urapadmin** [comment]
nope. Can't reproduce this even in the database you've send me. So this is what I do:
Open "squiggleExCbum" unit, go to dayplan, delete all dayplans.
Add a new dayplan,
click on image section and add an image with "insert file ..." - image appears.
Add a description -> description appears. 
Result:
![image](https://user-images.githubusercontent.com/38838314/79420022-01288780-7f86-11ea-9b0c-dbc700e28d67.png)
Look into gallery shows correct entry in file-identifier-cache:
![image](https://user-images.githubusercontent.com/38838314/79420090-2c12db80-7f86-11ea-9b5f-912276dda255.png)
Can you think of anything that we do differently?

**Comment by SamKimball-BrownU** [comment]
see #524 , I think I somewhat solved it. Are you logged in as sgk or admin?

**Comment by SamKimball-BrownU** [comment]
give me a minute and I will test to see if workaround solves this problem as well

**Comment by SamKimball-BrownU** [comment]
Try logging in with sgk, and you should be able to reproduce.

Logging in with admin produced the results you see, i.e. things function properly.

**Comment by urapadmin** [comment]
yes, I can reproduce this one as well.

**Comment by urapadmin** [comment]
### v8.9.14: all issues here should be solved now

**Comment by SamKimball-BrownU** [comment]
Resolved owing to the fact that non-admin accounts can no longer delete dayplans.
