### ISSUE TITLE
using backspace or del in dayplan list does not work properly

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#536]
USTP 1.9.11, Windows 10

this is the area that is selected when I use backspace, a popup happens and then it deletes
![image](https://user-images.githubusercontent.com/61027113/79053917-8fa7ac80-7c06-11ea-95b7-1802d1451afb.png)

If no further images are added, then it still appears in the preview. See image below.
This is after deleting record using backspace
![image](https://user-images.githubusercontent.com/61027113/79053996-34c28500-7c07-11ea-8273-d95d4d1fcfe3.png)

_Originally posted by @SamKimball-BrownU in https://github.com/urapadmin/kiosk/issues/487#issuecomment-612505007_

**Comment by urapadmin** [comment]
### @test: fixed in v8.9.14
DEL and Backspace are not allowed here at all. Only the little red button is supposed to delete a dayplan.
I suppress the two keys now. I hope there isn't a third key that deletes a record. One never knows with filemaker.

**Comment by SamKimball-BrownU** [comment]
Fix has happened in simple excavations and in non-simple. I tried a couple other things to try to delete dayplans (ctrl+x, right clicking), but none worked. 

Only admin has ability to delete dayplans but I believe this is intended behavior. 

Resolved.
