### ISSUE TITLE
cross-table migration: all replfield_uuid fields in urap and ustp need to be set to the default "gen_random_uuid()"

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#538]
that was not the default behaviour of the replfield_uuid() instruction before, but now it is.
But for the legacy data only a cross-table-migration can fix this.

**Comment by urapadmin** [comment]
### @test: needs kiosk v.0.6.11
The best way to test this is to import a file. If that works, the uids are generated properly, as should be the case.

**Comment by lbestock** [comment]
LDB test this in URAP local server when kiosk is updated.
