### ISSUE TITLE
tif import does not create thumbnails

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#539]
cannot save C:\notebook_source\urap\server\kiosk\kiosk\sync\sync\file_repository\cache\master\a66d65d8-f03e-4f0c-942e-ec7ef99d978c.jpg with format JPEG: Exception OSError('cannot write mode RGBA as JPEG')

**Comment by urapadmin** [comment]
### 0.8.16
fixed. TIFS and other formats that use transparency can be processed now. They get a white background.

**Comment by lbestock** [comment]
Works, import to recording system on the iPad.
