### ISSUE TITLE
drop tags.table_contexts from filemaker database

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#542]

**Comment by urapadmin** [comment]
### @test v8.9.16
test defining and using locus tags

**Comment by lbestock** [comment]
Creating tags is fine - I can do it (as LDB registrar) either under registration, define tags, or in a locus, interpretation, tags, edit tags. 

Using is broken. The "select tag" window is empty even though three tags in two categories have been defined. I can see those all if I go into "edit tags" but also there the arrow key doesn't result in applying the tag - it just closes the dialog box.
![image](https://user-images.githubusercontent.com/49291909/80291091-88a98f80-8718-11ea-8c11-6f1ea2b83ee6.png)

What it looks like despite having three defined tags.

**Comment by urapadmin** [comment]
### @test v8.9.18
Should be good.

**Comment by lbestock** [comment]
Nope, same problem. Can't get the list of tags nor apply one.

**Comment by urapadmin** [comment]
ah. I was in the wrong place. fixed in locus interpretation now, too.
