### ISSUE TITLE
delete files in from_workstation\workstation\files before import from workstation

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#545]
just do it. It can lead to confusing images. In my case I inserted a jpg into a dayplan. Then synchronized. then inserted a png into the same dayplan and because the old jpg was still in the files folder during the next synchronization it tried to use that jpg again instead of the png that was in the same folder but not picked by the os. So the formerly changed files must not be in there any longer.

**Comment by urapadmin** [comment]
### @test:
That is a hard one. 
- Create a new dayplan and enter a jpg first. Give the dayplan a description.
- Go through synchronization cycle and create a new file for the workstation
- into that same dayplan insert a file but this time it must be a png.
- synchronize that change
- search for the file in the file repository and make sure that the last file you inserted is there in that dayplan (use the description to find it).

**Comment by lbestock** [comment]
LB test this one with the URAP server running so you can do all the synchronizing yourself and on the Mac for file type control. So wait until the URAP server is updated.
