### ISSUE TITLE
apply logged in user to file import

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#548]
see #5, here for file import only. 
When importing files, with either upload or bulk import, the recording user of the currently logged in user should be used for the modified_by and even created_by (which we don't have) fields.

**Comment by urapadmin** [comment]
done in Kiosk v.0.7

**Comment by urapadmin** [comment]
### @test v 0.7
whenever a file is being imported, either with the upload method or a bulk import from the local filesystem, the modification date and the modified_by information should be set to the actual date and the currently logged in user (rather to the recording user-id connected to the kiosk user).

**Comment by lbestock** [comment]
When I tested this and called it done it was because in the file repository the information in the upper right corner looks right to me - it has modified by ldb for a photo I imported yesterday. But indeed I just checked and back in the recording system that same photo is sys.

**Comment by urapadmin** [comment]
that is not possible. I suppose that is again a confusion between the image record and the record type the image is connected to. You can't see the modified_by of an image in the recording system as you cannot see the modified_by of the record type it is connected to in kiosk. An example: You see modified_by of the dayplan record in the recording system but you do not see the modified_by of the image that is assigned to that dayplan record. With images there are always two records involved: the image record and the recording record. In Kiosk you only see the image record. In fact the information in the upper right corner of the file edit dialog is confusing rather than helpful to normal users.

**Comment by urapadmin** [comment]
I tested again locally and it works on the image front. The image itself gets my initials (to be observed only in the edit file dialog in the upper right corner). 
So this here can be closed from my perspective.

**Comment by urapadmin** [comment]
but point me into another direction: What about the modified_by of the recording records we create? 
Different ticket:

**Comment by urapadmin** [comment]
### @test
please test this one more time on some server and then close it.,
