### ISSUE TITLE
error in unit creation v.8.9.15

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#551]
Clicking the + button to create a unit results in the following error message:
![image](https://user-images.githubusercontent.com/49291909/79988883-30a32c80-847d-11ea-9b29-51d580256bbd.png)
Clicking OK results in the same error message coming back a second time.
Clicking OK a second time clears the message and takes one to unit creation, where one can successfully create excavation or feature units but not survey units (see #550). 
v. 8.9.15 on Alice, USTP wiped clean version.

**Comment by urapadmin** [comment]
hm. now the error is gone or does it resurface? What's the identification method?

**Comment by urapadmin** [comment]
can't find anything (nor can I reproduce it), except that I am already on 8.9.16. So please try it with the new version.

**Comment by lbestock** [comment]
Still present and behaving exactly the same way on Alice in 8.9.16.

**Comment by urapadmin** [comment]
### in 8.9.17
got it. Visible only on ipads. Should be fixed
