### ISSUE TITLE
previously created features change ID method of hidden locus when config changed

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#553]
In testing #420 I hit another bug.
8.9.16 Alice USTP signed in as LDB with registrar status, switched out to admin to change a setting, came back in again as LDB.
Created two features, no problem, one from home and one in a survey unit. Could enter these features.
Came in as admin to switch ID method for hidden locus feature to free input to test #420. Came back as LDB. Created a new feature from within the survey and indeed cannot enter it, with the proper error message and all.
BUT I also can't enter the previously created feature units. I get the same error message from them. And then I went back in as admin and switched the ID method back to from a context list, and then all three of my features are accessible. So they have whatever ID method is currently configured as a whole, not the method used when they were created. Should that be?

**Comment by lbestock** [comment]
Whoa don’t touch this for a bit - it gets even weirder if I put some data in these features and I need to figure it out systematically for you.

**Comment by urapadmin** [comment]
I move this to the testing project so that it does not get overlooked anymore.

**Comment by lbestock** [comment]
Systematically testing shows that nothing is wrong. Previously created features that were not given any information change their ID function and so become unenterable, as new features are. But anything with information in it already keeps its original ID functions and can be entered just fine.
