### ISSUE TITLE
Adding images via gallery leads to drag and drop warning in dayplan

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#554]
USTP 8.9.16 / Windows 10
Log in doesn't matter (works on admin/registrar accounts)

Steps to reproduce:
Get to the point where you can add new day plans
Add new dayplan
open image popup and add image via gallery

You then receive the normal popup that you should get when dragging and dropping images, see below.

![image](https://user-images.githubusercontent.com/61027113/80031138-e5097680-84ae-11ea-932a-ae43696522fa.png)

**Comment by urapadmin** [comment]
### fixed in 8.9.17

**Comment by SamKimball-BrownU** [comment]
Resolved
