### ISSUE TITLE
test permissions in kiosk

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#555]
### needs v0.7:
here is how to: https://www.meritaten.net/urapdev/doku.php?id=how_to_test_privileges_in_kiosk
and these privileges are available so far:

- [ ] test privileges 
- [x] enter administration
- [x] backup
- [x] restore
- [x] manage users
- [x] modify data
- [x] download file
- [ ] develop
- [x] synchronize
- [x] edit workstation
- [x] prepare workstation
- [x] download workstation
- [x] upload workstation
- [x] create workstation

**Comment by lbestock** [comment]
Close #514 when you close this.
