### ISSUE TITLE
replace refresh of the file-identifier-cache during export with kiosk's file-identifier-cache

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#557]
currently filemaker has its own local file-identifier-cache. Updating it during export_to_filemaker takes too long. The goal is to use the data from the file-identifer-cache in kiosk and just transfer it to filemaker as a normal data table. To do that some translation of fields and fieldnames is necessary because the two tables are not equivalent.

**Comment by urapadmin** [comment]
it was not aaaas big a task as I feared. But it needs testing. The Gobbledygoock Error reappeared. Had not seen it since PEtra. It occurs if an empty string is exported from kiosk to a filemaker field. I was able to suppress it by using Null instead, but it remains weird.

**Comment by urapadmin** [comment]
### kiosk 0.7.4, recording 9.2
Hard to test. What this does is it exports the identifer - image relations as processed by kiosk to filemaker. Until now, filemaker would have computed them at the end of the preparation of the workstation, which lead to the long task "updating file-identifier-cache" when preparing a workstation. The new transfer is much quicker. 
The result should be that the gallery works as before, so you find all your images under the same identifiers as before. In fact, it should even work a bit better because the kiosk file identifier cache is more comprehensive. e.G. it includes tags. So you will find a locus image if you search for a locus tag that locus is tagged with. 

The best technical test would be to create a bunch of images in all kinds of record types, make snapshots of the file identifier cache, synchronize and prepare a new filemaker file. And then compare the new file identifier cache to the old one. I am not sure if that is doable. You could also just look around and see if everything looks plausible enough.

**Comment by lbestock** [comment]
How do I create a snapshot of the file identifier cache?

**Comment by urapadmin** [comment]
that's a good question. The easiest way might be to just keep the filemaker database and compare it with the next one that comes out synchronization and preparing the workstation.

**Comment by lbestock** [comment]
Wait and see if anyone has a problem. Closed until they do.
