### ISSUE TITLE
locus_photos change image container to state of the art handling

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#558]

**Comment by urapadmin** [comment]
### @test: v8.9.18 should be final now
new image handling with drag & drop etc. now in place for locus photos, too. I also updated the image description for image tests once more, mainly to give an example what things look like if they are correct: https://www.meritaten.net/urapdev/doku.php?id=how_to_test_an_image_container#what_to_test

**Comment by SamKimball-BrownU** [comment]
Everything working as intended, including drag and drop

Nice!

**Comment by urapadmin** [comment]
reopened because image proxy was not set correctly.

**Comment by urapadmin** [comment]
### v9.1
sheesh.
