### ISSUE TITLE
bugs and features - update image container

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#564]
oops, there is an image container I had totally forgotten about. Needs improved though limited image handling, as well.

**Comment by urapadmin** [comment]
### @test v9
This is a very simple container. It has not gallery and does not affect the file-identifier-cache. It does this:
[ ] adding images tags them as "bug_report_snapshot" 
[ ] deleting images does not delete them in the gallery (nor does it remove the bug_report_snapshot. That is lazyness on my front, it would be more coherent to delete the image if it isn't used in a bug report. Perhaps some day... At least the container must make sure that not empty image is left in the gallery.

**Comment by SamKimball-BrownU** [comment]
It is a bit weird that it is included in the gallery, but working as intended. Closed.

**Comment by urapadmin** [comment]
reopened because image proxy was not set correctly.

**Comment by urapadmin** [comment]
was not an issue here.
