### ISSUE TITLE
delete images from the gallery

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#567]
currently there is no way to delete images from the gallery. For normal users it will stay that way. But for testers, developers and perhaps on occasion admins it might comes in handy.

**Comment by urapadmin** [comment]
### @test v9
There is a red button now in the gallery in the image details in the upper right corner of the little thumbnailish image. That button should not be visible for normal users.

**Comment by SamKimball-BrownU** [comment]
Confirmed not visible for normal users when not in testing mode. It is visible and fully functional for admins and when in test mode. 

Working as intended!
