### ISSUE TITLE
test file repository

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#569]
### kiosk v0.7
This is one of those long test issues that should perhaps be cut into many. 
The search mechanism of the file repository has changed entirely behind the scenes. These are the visible improvements:
- locus tags count as identifiers now. So one can search for "Wheeler Room something" or whatever.
- if an image belongs to more than one context it will be found in all of them. So an image that has been put in a dayplan of FA and a dayplan of CC is found under both identifiers.
- the thumbnails provide information for all contexts an image belongs to
- the edit file dialog now shows all contexts as well

How the file repository should behave
Which image is returned in which context is due to a context definition in the background. It is configured to work like this, currently
- site identifiers only result in site maps and site note images
- the unit context comprises dayplans, locus photo images and collected material photos
- putting in a locus identifier returns locus photos, locus relation sketches and collected material photos
- a collected material identifier leads to collected material photos and pottery images
- a pottery identifier results in pottery photos only

Images without contexts
- inventory photos should be found without contexts and the tag "inventory": BUT that is only true for inventory photos added with the new v9 recording system
- bugs and feature screenshots can be found without context but under the tag "bugs_and_feature_image" or some such (look at the list of tags)

**Comment by lbestock** [comment]
Incomplete test so far because KHPP does not use locus tags or pottery. But back to you because searches by contexts that are unit names, and searches by contexts that are locus names, failed to return locus relations in kiosk 0.7.2. (This is what I was testing on the URAP server which is not updated - 0.7.1 searches in those contexts DID return locus relation images.)

I checked to make sure there were locus relation images for the contexts I was searching and there were, so I expected them to come up in the general context  search.

**Comment by urapadmin** [comment]
I cannot reproduce that even on khpp.arch-kiosk. If I search for "D09.1-009" or "D09.1" I get locus relations back. 
In general you help me a lot if you write with clarity and by giving at least one concrete test example.
I also think, we should branch off tickets whenever you find a bug out of this bigger test. Otherwise this will become an endless ticket.

**Comment by lbestock** [comment]
It's much weirder than that! New ticket being made, with full description and screen shots.

**Comment by urapadmin** [comment]
see #618 and #617

**Comment by lbestock** [comment]
It is ever so slightly confusing to a user that one finds locus tags under context, not under tag.

All works perfectly.

**Comment by urapadmin** [comment]
> 
> It is ever so slightly confusing to a user that one finds locus tags under context, not under tag.
> 
That comment gets lost if you just add it to some ticket that you close afterwards. Please make a new ticket, if it is a real point. I think it is at least a topic to be referred to in the user's manual. So I tag it thus.
