### ISSUE TITLE
file-import now with new context management

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#570]
### kiosk 0.7
This is huge again. The file-import before kiosk 0.7 was entirely depending on Uronarti specifics like locus etc. Now it follows context definitions and hence works in ustp, too. This is what should happen:

- in URAP everything should work normally. But there are some special cases I have dropped. E.g. when importing a file "CC.jpg" from a folder "FA" with both guessing the context from the folder and the file, in former times this would have lead to a conflict. Now the file identifier wins over the folder identifier, so CC it would be. Conflict detection in the file import is so project specific that I have dropped it entirely. Users have to make sure that their import structure makes sense. 
- from now on the file import does not check if the form of an identifier is syntactically correct but checks only if the identifier actually exists in the database. So you can only import something like "9812387" if that number is used as an identifier for some record type in the database.
- Identifiers can be ambiguous now. If the file import runs into an identifier that belongs to two different contexts, it refuses to import it. e.G. a project could have a unit "1" and a locus "1". It cannot be decided to which context an image "1.jpg" belongs and hence it cannot decide to which record type the image should be assigned.

This really needs some systematic testing. I am not even sure if we have properly documented all the options in the file import. Perhaps we should take the opportunity and do that.

**Comment by lbestock** [comment]
Let's talk about this together with paper and pen and map out a strategy - I will miss stuff if I try to do it alone.

**Comment by lbestock** [comment]
Tests to perform:
File upload but you don't need to test this with import.
USTP and a hierarchical CM one.
Mix of existing and non-existing contexts to make sure the latter are refused.
Test ambiguous identifiers and make sure they are refused.
Does USTP (the actual project) HAVE CM photos? How do they structure their small finds, with  numbers?

**Comment by lbestock** [comment]
Well, I will add you to some USTP tickets, Luiza, but frankly they're difficult ones and I am not sure, without having worked with USTP before, that you will make even the slightest sense of this!

**Comment by lbestock** [comment]
USTP indeed is refused because of an ambiguous identifier, as we would want.

**Comment by lbestock** [comment]
Yup USTP is good (aside from the fact that their numbering system means they have no ability to get images into loci or CM without the gallery...) Rejects unknown contexts, rejects ambiguous contexts, accepts known unambiguous contexts.

**Comment by lbestock** [comment]
And it works for structured numbers, too. I am worried that my tests were too quick given that the ticket calls itself very complicated and in need of very structured tests, so I am hesitant to close it. But my tests for PVD and USTP worked as expected.
