### ISSUE TITLE
list box with identifiers and record types in file repository

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#572]
The "identifier" field should get a list that fetches a list of identifiers and the context they belong to. Selecting such an identifier would lead to using only that one context and not others?
Needs some thinking...

**Comment by urapadmin** [comment]
at least a list of available identifiers would make sense. The thing with the context might be a bit hard for the query.

**Comment by urapadmin** [comment]
that wasn't fun because of #1218: The whole javascript approach is just totally outdated at this point. I hate javascript.
But:
### @test kiosk 0.13.8
when typing at least two characters into the identifier a helpful awesomplete box opens and shows you what exists (well, but not more than ten items at a time).

**Comment by luizaogs** [comment]
Is this the context search box? I don't see an identifier box? If it is the context box I am not getting any awesomplete action (like what happens with tags); if I type something there it only brings up contexts I've searched for before.

**Comment by urapadmin** [comment]
ja, this is about context identifiers. I do suspect it is a cache issue in your case. Please refresh your browser's cache: ctrl+F5 in windows is the fastest. The mac version I can never remember. Google will help, I am sure. And then please try again. It had helped me.

**Comment by urapadmin** [comment]
this awesomplete box does not have a drop down button. It will open once you have typed at least 2 characters that appear in at least one context identifier.

**Comment by urapadmin** [comment]
I could give it a drop down button if you think that makes more sense?! I just see that also the layout has changed since it is an awesomplete.

**Comment by luizaogs** [comment]
Ha yeah you're right, caches. Works. I think this is better than a dropdown? To me a dropdown implies that I'll be able to see all of the options (as with the record type box), which isn't the case here.

**Comment by luizaogs** [comment]
When you say that the layout has changed, do you mean the placement of the box? Because I just noticed it is a bit misaligned, not sure why: 

![Screen Shot 2021-10-05 at 7 52 55 AM](https://user-images.githubusercontent.com/67970402/136026235-38373962-7923-4784-b1de-5e751e72f391.png)

**Comment by urapadmin** [comment]
I agree about the drop-down. That is why I decided against it. And 800+ identifiers in a list is just not very helpful.
And yes, the alignment changed. Who know why. Hmpf. New ticket. This here can be closed, I guess?

**Comment by luizaogs** [comment]
Yup.
