### ISSUE TITLE
hidden locus not hidden in feature CM

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#576]
Logged in as ldb, not in test mode, can see the context in CM in a feature which should not be the case:

![image](https://user-images.githubusercontent.com/49291909/80646046-05e74400-8a3a-11ea-9b78-aaf62deea395.png)

Also happening in URAP, as are the visible red boxes on the right that shouldn't be visible.
Both v9 on Alice.
![image](https://user-images.githubusercontent.com/49291909/80647212-1993aa00-8a3c-11ea-8935-ce9a407c7022.png)

Also happening for CM in a new survey unit in URAP, and in displaying previously entered data for CM in an actual feature unit:
![image](https://user-images.githubusercontent.com/49291909/80647529-a0e11d80-8a3c-11ea-9bf0-64befd070603.png)

**Comment by urapadmin** [comment]
### fixed in 9.0.3
