### ISSUE TITLE
Typo - Archaeologicalical Significance in image gallery

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#577]
This is super minor but there is a typo in the image gallery

![image](https://user-images.githubusercontent.com/61027113/80663219-fcb99f80-8a58-11ea-988d-c8e074096bdd.png)

I don't really know what to label this. It's not really a bug, and it's pretty small. But, I wanted to get it documented anyway

**Comment by urapadmin** [comment]
we are humanists, we care for correct spelling :) Will be fixed ...

**Comment by urapadmin** [comment]
### fixed in 9.0.3
