### ISSUE TITLE
Gallery shows former results in dayplan without search term in box, then doesn't

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#579]
v9, windows 10

Steps to reproduce:
Add a dayplan (doesn't matter if blank)
Use the gallery in the dayplan to search for some image
![image](https://user-images.githubusercontent.com/61027113/80665310-b36c4e80-8a5e-11ea-8f59-99cdd8e51a3d.png)
close that window and open up the gallery again. You should see the RESULTS from your previous search, but nothing in the search bar (note that this will update if you make any changes to images, such as deleting or renaming)
![image](https://user-images.githubusercontent.com/61027113/80665334-caab3c00-8a5e-11ea-9b01-20421f78d8b1.png)

If you close out of this and open gallery again you can just see all of the images in the gallery.
![image](https://user-images.githubusercontent.com/61027113/80665501-44dbc080-8a5f-11ea-8db3-827e041afdfd.png)

However, if you actively apply new filters, it resets you back to the beginning of this little cycle.

I think if the search box were to just show previous filters (which are still being applied in the results), that would solve most of the problem. But then again, it seems that on the nth time you open the gallery, it only uses the filters that you actively applied the (n-1)th time. Make of that what you will.

**Comment by SamKimball-BrownU** [comment]
related to #535 ????

**Comment by SamKimball-BrownU** [comment]
Note: Also happens in site notes and site maps

**Comment by urapadmin** [comment]
#### fixed in 9.0.2
Going to the popover gallery from an "add from gallery" button should now always erase the filters and show all images. 
Going in from the start menu shows the last filter (applied either in the popover gallery or in the start menu gallery) and the correct results of that filter. see #535

**Comment by SamKimball-BrownU** [comment]
Works as intended, with one exception, that I am unsure is even a "bug" or needs correcting, honestly it seems like useful behavior.

To replicate:

1. use "add to gallery" to access gallery
2. search for some images
3. close out (either x out or press back button at top left)
4. Open up new "add to gallery"

Then, the gallery will be scrolled down to the topmost result from the previous search term. Honestly, this seems pretty convenient in the field; when you search for one thing, it would likely be convenient to have the gallery already scrolled there, so that you don't have to search for it again.

Moving it back to you just so you are aware that it is happening, but I think this is good behavior.

**Comment by urapadmin** [comment]
### v9.0.4
tried it several times. Indeed, the gallery starts somewhere else than on top. But I cannot confirm that it is the topmost image of the previous search. Looked a bit too contingent to me in order to be useful. I changed the behavior: The gallery starts always with the first record.

**Comment by SamKimball-BrownU** [comment]
Resolved in excavation dayplans at least, will test in surveys and features

**Comment by SamKimball-BrownU** [comment]
Resolved everywhere. Nice.
