### ISSUE TITLE
formatting request in locus tab

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#596]
Can we make the space for locus name larger at the expense of the date of definition? Now that not all projects use simple short names for their units, a unit-based locus number takes up more space than is available and I can't see my locus numbers.
![image](https://user-images.githubusercontent.com/49291909/80927181-ee75c700-8d69-11ea-92da-400970347050.png)
(Possibly this is a test issue, but it isn't the first time I've run into it testing and I think it might be an issue down the road for real?)

**Comment by lbestock** [comment]
Worse and with less room to play in CM, of course.

**Comment by lbestock** [comment]
Forget it. People shouldn't name units stupid things.

**Comment by urapadmin** [comment]
You know, that also would have to write it on tags and such. I think everything longer than the khpp units / collected material identifiers is close to useless. Though, let's see what Zach requests will be. His approach sounded worse.
