### ISSUE TITLE
takes two clicks to get into some fields, even though they are highlighted at first click

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#597]
This is undoubtedly a FM annoyance and I think maybe one we've run into before. I'm encountering it now in KHPP v.9 on Alice - crucially, I have the keyboard shrunk, which seems to make a difference. When I click a field that needs text entry sometimes I need to click twice before I can start typing. This is annoying because in most cases the field is already highlit after my first click, so I think I'm fine and I type a lot and then find it hasn't actually done anything. Not sure if it counts as a bug or a request - it is a Filemaker stupidity. There seem to be two things necessary to trigger this:

- I need to have the keyboard shrunk - the full size keyboard doesn't create this problem
- The keyboard needs to be open before I go to that field. So if the keyboard is invisible and I click on locus description and call up the keyboard, then it works just fine with one click.

**Comment by urapadmin** [comment]
I suppose there is very little I can do. Might even be an iOS issue. Does it appear for all kinds of fields? Input fields, multiline input fields, selection fields?

**Comment by lbestock** [comment]
All types of field seem to need the double click. It's much more notable and annoying with ones where one types. Where it doesn't happen is with the auto input things - if I click a person or a clock then LDB or the time is put in on one click, without the keyboard disappearing (it disappears on the second click for a drop down menu). But in those fields if I click in the field instead of on the auto input button then yes, even there it takes two clicks.

**Comment by lbestock** [comment]
Also does not happen with checkboxes (so materials for feature recording - can click no problem)

**Comment by urapadmin** [comment]
Does this ipad have the latest filemaker go and ios updates? I have a 
hunch that we had that issue but some updating solved it.

Am 03.05.2020 um 21:30 schrieb lbestock - notifications@github.com:

**Comment by lbestock** [comment]
Well golly. Updating the iOs currently.

**Comment by urapadmin** [comment]
not addressed in Filemaker 19. It even got kind of worse. I got many refresh issues when using the floating keyboard. Lists that do not close etc. The clicking twice is in fact only necessary when moving between controls that need the keyboard. When clicking on something that does not have a keyboard (an image e.G.) I only need to click once to get into a text field from there. Totally incoherent and for sure beyond my control.

**Comment by urapadmin** [comment]
this is filemaker. I have never found any way to deal with this. Defeated.

**Comment by lbestock** [comment]
Hm. Hm. This seems to be fixed somehow.
