### ISSUE TITLE
make lots invisible in feature CM for projects that have lots

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#599]
Lots are not relevant for features, with their hidden loci, so one should not pretend one can choose them:
![image](https://user-images.githubusercontent.com/49291909/80931363-57b80300-8d87-11ea-8d59-4ce1aeb2e166.png)

They should NOT be made invisible in survey, though - there lots are the way you connect CM to a specific transect, as the transects are lots.

**Comment by urapadmin** [comment]
### @test: v9.01: 
this is more complicated than it looks. This is how lots should behave:
for projects that don't use lots:
- [ ] no lots in the collected material list in excavation, feature, survey or locus
- [ ] no lots in collected material
- [ ] if method "transect" is used for survey lots appear in collected material in that unit  - in the list and in the collected material view.

for projects that use lots:
- [ ] no lots in the collected material list in feature and survey
- [ ] lots in the collected material list in excavating and locus
- [ ] lots in collected material
- [ ] if method "transect" is used for survey lots appear in collected material in that unit - in the list and in the collected material view.
