### ISSUE TITLE
deleting locus relation hiccup

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#601]
Testing KHPP 9.0.1 on Alice. In a unit with two loci. I made one proper locus relationship. I made a second and tried to assign it to its own locus, and of course received the proper error message. So I tried to delete it, and  that didn't work: 
![image](https://user-images.githubusercontent.com/49291909/81097830-6fea6800-8ed6-11ea-9152-4134499a87f3.png)

I particularly appreciate an error message that tells me that the error should not occur!

(I repeated the steps because there was an unexpected screen in between, copied below now.)
![image](https://user-images.githubusercontent.com/49291909/81097942-a2946080-8ed6-11ea-9b6f-5a33be587418.png)

The first time I got that I hit continue, which is when I got the lovely error message. The second time I hit cancel and got the alarming: 
![image](https://user-images.githubusercontent.com/49291909/81098039-cb1c5a80-8ed6-11ea-8717-860e324a904a.png)

Which you didn't want me to get to, certainly.

**Comment by urapadmin** [comment]
### fixed in v.9.0.2
