### ISSUE TITLE
insertion of number that doesn't belong in feature

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#603]
KHPP 9.0.2 transect walking.
![image](https://user-images.githubusercontent.com/49291909/81207185-29ab0c80-8f9b-11ea-8b02-5c642c554325.png)
There is an extra three down there in the totals line that is not a total of anything. It appeared when I was putting in the counts for metal, so presumably has a link to that somehow.

**Comment by urapadmin** [comment]
### v9.0.3
fixed
