### ISSUE TITLE
images are small in containers for loci

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#604]
Bizarrely small images. The jpgs are not large files, but in other image containers similarly sized jpgs are sized for display to take up the whole container.

![image](https://user-images.githubusercontent.com/49291909/81209025-eef6a380-8f9d-11ea-9f34-a4cab954f312.png)

**Comment by urapadmin** [comment]
hm. I am a bit surprised. The image container was set to "reduce to fit", which would suggest that this is the original size of the image. You have not by any change put in a thumbnail or so?
Anyway, I have set it to "reduce or enlarge to fit" now in 9.0.3.

**Comment by lbestock** [comment]
Works in locus photo. (They weren't thumbnails but they were only about 500kb each, so definitely lower resolution than we usually deal with.)

The same fix should also be applied to Site Map images.
