### ISSUE TITLE
several cross-table-migration script files have to be imported using import

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#605]
it should even be possible to import more migration script files by using import from within the migration script. The whole import mechanism needs to be absolutely flexible so that "external()" isn't really needed anymore. 
Currently it seems I can only reference a single cross-table-migration script from within the main dsd3 file.

**Comment by lbestock** [comment]
see #607

**Comment by urapadmin** [comment]
done. It will get tested over time ...
