### ISSUE TITLE
delete images available to registrar - should it be?

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#608]
KHPP 9.0.2 Alice signed in as ldb with registrar status. The delete button is there for images. The reason it confuses me is that I am not sure it was there before - I thought not - and then I hit a mistaken set of keys and I think that is when it appeared?

![image](https://user-images.githubusercontent.com/49291909/81245382-d2c92580-8fe2-11ea-9168-36aa0db66ffd.png)

**Comment by lbestock** [comment]
I'm even moderately sure it wasn't there - now I get the two empty red outlines in an empty image container that I do not remember being there just recently (and full when I fill the image container, and that is even a shift from just a moment ago??? I logged out and logged in again.) I think I was trying to hit shift command 4 to get a screen shot for the tiny type and then triggered this change.

![image](https://user-images.githubusercontent.com/49291909/81245780-e628c080-8fe3-11ea-8337-62db14655d63.png)

**Comment by urapadmin** [comment]
I don't see what the change might have caused. It is a bit disconcerting to see on your notebook that the scripts are available - in Windows there is no menu. So perhaps you have hit something that triggered a script that set the MasterDb status. But that is a shot in the dark. 
I have changed the test for MasterDb status now and got rid of old and obsolete 2015 code. 
Now:
- [ ]the little red trash can should appear only for the admin (and the developer). 
- [ ] The date in the image thumbnails and the red border fields should appear only if test mode is on
- [ ] New: The little red trash can can be made accessible to all registrars with the new config key visibility/show_dayplan_delete_registrar.

**Comment by urapadmin** [comment]
I knew we already had a ticket for this: #475 can be closed, too, if this here works.

**Comment by lbestock** [comment]
All fixed even the red boxes! Pain in the tuchas to test, indeed.
