### ISSUE TITLE
images are small in containers for site map

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#609]
Same issue as #604 which was successfully addressed.

**Comment by urapadmin** [comment]
### v9.2.1
this is really rather a test issue. Usually site maps are really not so small. 
Fixed it nonetheless in the relevant image container.

**Comment by lbestock** [comment]
Sam: test it by using a small image.

**Comment by SamKimball-BrownU** [comment]
Resolved, as far as I can tell. I used a small image, and it filled up the entire container.
