### ISSUE TITLE
file repository not showing all images it should from a search

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#617]
KHPP file repository searched D09.1 with record type defined as trench/area
Search says 121 images, I fetched 'em.
Dayplans when looking at FM for KHPP also indicate that there should be 121 images matching this query.
But when I sort for age to check if the images are the same, the early images aren't there. It seems like there should be another page of images that is missing, but it says there is only one page.

If I switch the sort order to earliest first, I find the images I was missing and now the late ones are excluded.

**Comment by urapadmin** [comment]
### fixed 0.7.2
yes, no new version because I only had to replace a single file. Wasn't worth it. Did it for khpp and ustp.

**Comment by lbestock** [comment]
Is not fixed - same problem. But now see #618 - I think it's a pagination problem.

**Comment by urapadmin** [comment]
### fixed second attempt.
