### ISSUE TITLE
pagination problems in file repository

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#618]
The file repository does not generating pages of images properly.

In testing if the file repository for KHPP produced proper results, you and I had different experiences with the return of locus relation images and I think this is why.

I searched D09.1. It said 249 images and I fetched them. I carefully scrolled through the images and did not see a single locus relationship image. I searched D09.1 with locus relations defined as the record type and saw that I should have seen 7 such images. You could not reproduce this problem. The issue is that at the TOP of the screen it says there are three pages of photos:
![image](https://user-images.githubusercontent.com/49291909/81623846-a5092580-93c2-11ea-8835-6536efee36ba.png)
But at the BOTTOM (this is just scrolling down, no reloading or anything) it says there are only two pages of photos:
![image](https://user-images.githubusercontent.com/49291909/81623913-d1bd3d00-93c2-11ea-93a1-a4aeda6b8ae6.png)
So I had scrolled through two pages of photos and not seen a single locus relationship photo, and when I was at the bottom it seemed to me that there was no additional page of images to look at. But if I go up and choose the third page, which I can only do from the top of the screen, lo and behold I find all the locus relationship photos. 

That's definitely the problem in #617, too - it shows two pages of images at the top, but at the bottom only one and so I cannot click to the second page from the bottom and assumed there was not one.

**Comment by lbestock** [comment]
In my excitement at figuring it out, I did not give you the right screen shots. I searched D09.1 and sorted by context. So all the locus relation images were on the third page. Here is what the start of that looks like:

![image](https://user-images.githubusercontent.com/49291909/81624201-9cfdb580-93c3-11ea-91fd-932c5d94e36e.png)


And here is what the end of page two looks like, with no indication I can get to a page three:

![image](https://user-images.githubusercontent.com/49291909/81624312-d504f880-93c3-11ea-905d-a9e3009fcdd1.png)

**Comment by lbestock** [comment]
Cool problem. Also in URAP - if there are multiple pages of images there is always one more tab at the top than the bottom, so 5 pages of FA photos according to the top, 4 pages at the bottom (where one much more likely needs it!)

**Comment by urapadmin** [comment]
fixed on khpp, ustp and local urap. Unless I forgot one of them. - no new version again. Still 0.7.2

**Comment by lbestock** [comment]
Fine for URAP. Can't finish testing KHPP until #619 is dealt with.
