### ISSUE TITLE
can see red boxes on feature creation

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#620]
see #431, same issue different place. Logged in as ldb to URAP on alice 9.0.4, I get the red developer box when creating a feature or viewing the list of features from within a survey unit. You don't want me to.
![image](https://user-images.githubusercontent.com/49291909/81755662-5c677000-9487-11ea-8750-42607f4a3952.png)

**Comment by urapadmin** [comment]
### fixed in 9.0.5

**Comment by SamKimball-BrownU** [comment]
I believe I have seen this one other place, assigning myself just so I have something to remind me to look; feel free to close this ticket whenever though

**Comment by SamKimball-BrownU** [comment]
Resolved. I think you just forgot to close this, but I went and double checked.
