### ISSUE TITLE
long name of site still used in URAP on test server

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#621]
You had wanted to correct the long names to the abbreviations, but on the home page of the recording system it's still messed up.

**Comment by urapadmin** [comment]
is that still the case?

**Comment by lbestock** [comment]
It's fine now on the real URAP at least. I can't look at anything on the URAP test server because it has become s'Urachi and is throwing me a GMT error. But I'm pretty sure this here is done - I haven't seen it for ages.
