### ISSUE TITLE
wrong identifier seems to lead to an indefinite "calculating..."

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#624]
If you use an identifier that does not exist you get the red dotted frame around the identifier but the "calculating..." stays (although calculation is done). As soon as the identifier is correct everything works fine. It is harder to see if you type an unknown identifier and then play around with other things like record type or so. As long as the identifier is not correct, the "calculating..." does not go away, no matter what else you do. 

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/619#issuecomment-628748881_

**Comment by urapadmin** [comment]
### fixed in kiosk 0.7.3

**Comment by lbestock** [comment]
It even returns the message that the identifier is unknown rather than the more usual "no files meet your criteria" and that strikes me as helpful.
