### ISSUE TITLE
error in add image to cache pottery photo

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#626]
Pottery processing URAP 9.0.4 (not intending to test pottery processing but getting set up for image upload tests).

I created two lines for pottery processing. The first line had no pottery number. I hit camera to input an image. I drew my image and received the following error message:
![image](https://user-images.githubusercontent.com/49291909/82155584-f5113d80-9843-11ea-8640-107223249a50.png)
However, the image is in there when I go back.

I then went to make an image for my second processing line, which does have a pottery number, and there I did not receive the same error.

I repeated these steps in a different CM and the error again was repeated only with the processing lines that had no pottery numbers.

**Comment by urapadmin** [comment]
I don't really know what to do here. I will assign the pottery number only if it exists otherwise the collected material number leads to the pottery photo.

**Comment by urapadmin** [comment]
only that a complication follows: all images attached to a line that does not have a pottery number have to change if the line gets a pottery number. I make that a new ticket. This here is just about whether or not the photos are handled correctly if there is no pottery number.

**Comment by urapadmin** [comment]
### fixed?
This should be fixed in #628
