### ISSUE TITLE
context that exists is unknown to the file repository

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#629]
Kiosk 0.7.3. Having both synchronized and uploaded images with recently created contexts in unit QA in URAP 9.0.3 wiped of real data, I have unexpectedly discovered that the file repository thinks QA does not exist. Though it has a bunch of images QA, QA-001, etc.

![image](https://user-images.githubusercontent.com/49291909/82158095-aff50780-9853-11ea-9344-c9b7016de527.png)

In fact I cannot find any contexts that it DOES think it recognizes.

**Comment by lbestock** [comment]
This might explain #627? If the contexts aren’t known, it couldn’t import them even if it read the QR code? But then it must have known the contexts from the exif import, because it accepted those images and labeled them properly.

**Comment by urapadmin** [comment]
a cache issue. Restarting the urap server helped immediately. That is a bit harder to trace. For your tests it should help you for the time being to restart the server if you miss something like this.

**Comment by urapadmin** [comment]
I am not sure if this is still an issue with current kiosk versions. I give it back to test.

**Comment by lbestock** [comment]
I can't replicate it at least, including with a newly created context.
