### ISSUE TITLE
pottery photos have to be rewired if they get a pottery number afterwards

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#630]
only that a complication follows: all images attached to a line that does not have a pottery number have to change if the line gets a pottery number. I make that a new ticket. This here is just about whether or not the photos are handled correctly if there is no pottery number.

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/626#issuecomment-629872699_

**Comment by urapadmin** [comment]
for the time being I hope that kiosk will correct this issue as soon as kiosk's own file identifier cache is exported to filemaker. See #557. That an image won't have the full pottery number attached to it IN THE GALLERY until the next synchronization is something nobody will find out too soon.

**Comment by urapadmin** [comment]
ja, this is soooo difficult and an over the top effort in filemaker that I won't do it. At this point kiosk mends it after synchronization.

- [ ] So if a line has two images but no pottery number and then gets the pottery number after the two images had been attached to it, the gallery will not reflect that change. (the images are there but without the pottery number). When synchronizing that workstation and preparing it afresh, the pottery number should be there right away.

**Comment by lbestock** [comment]
As described and expected post kiosk synchronization. And really, that should be enough.
