### ISSUE TITLE
Syncing: Should I be able to do it for ustp?

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#637]
Should I be able to synchronize for USTP? Signed into my account (sgk)

![image](https://user-images.githubusercontent.com/61027113/84688152-7a9c1200-af04-11ea-8cb8-065b09cd930b.png)

I can still upload data and such.

In general, I think it would make sense to have one account without privileges, and one account with privileges, if you are worried about testing syncing.

**Comment by urapadmin** [comment]
Oh, hi Sam! No, the dialog is right, you do not have the necessary privileges to synchronize (nor do any of the steps to prepare or import a workstation). You are set up only for uploading and downloading, just like a normal field worker would be.
Perhaps, one day I won't show the synch option if the privileges aren't there ...
ldb has the "operator" privileges necessary to synchronize and do all the steps with the workstations.
