### ISSUE TITLE
configure kiosk terms to match FM terms for projects

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#645]
Currently kiosk search terms are the URAP ones; that needs to be customizable and so needs to be configured in the server by LKH. For instance, "locus photos" makes no sense in USTP - needs to be "context photos".

**Comment by urapadmin** [comment]
we have done that, no?

**Comment by lbestock** [comment]
I don't know? It is right on the PVD server but for USTP, which is up to date kiosk at 0.8.4, record types include locus photos and locus relations and USTP has contexts, not loci. What is the mechanism by which kiosk learns those terms? Is it something a director has to set or does it come from the configuration in Filemaker?

**Comment by urapadmin** [comment]
it is a kiosk config. Apparently I have not configured it for them. Will do...

**Comment by urapadmin** [comment]
done. 14.VII.
