### ISSUE TITLE
make "excavator in charge" a configurable label

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#646]
Not all units are excavated and not all projects have excavators in charge. USTP would like the "excavator in charge" for units to be able to say "recorded by". This is what is seen in FM and so clearly different than the also needed #388 which will behind the scenes note who records absolutely everything.

**Comment by urapadmin** [comment]
see #648

**Comment by urapadmin** [comment]
### @test v9.2.1 
There is a difference between what we call now a supervisor (defined already on unit creation level) and the fields that specify who recorded a certain information, like a narrative, a locus etc. Not necessarily the same person. So: 

- [ ] we have a customizable term for supervisor now ("label_supervisor") 
- [ ] the term appears in unit creation/edit
- [ ] the term appears in excavation under "unit" tab (simple excavation mode, too)
- [ ] the term appears in feature units on the first tab
- [ ] the term appears in survey units on the first tab

**Comment by SamKimball-BrownU** [comment]
Issue: changing label_supervisor does not change the term in unit creation/edit. It still just remains supervisor. The field, i.e. who is considered supervisor DOES indeed show up in all of those places. But the actual label of "supervisor" remains as supervisor. It did not change to superdupervisor when I changed label_supervisor.

**Comment by urapadmin** [comment]
### 9.4.2
should be fixed now

**Comment by SamKimball-BrownU** [comment]
Indeed it is. Nice.
