### ISSUE TITLE
coordinates button does not vanish in USTP, although the coordinates field is invisible.

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#647]
happens only in simple excavation mode: While there are no "coordinates" in tab unit, the resize-button that would open a popup is still visible.

**Comment by urapadmin** [comment]
### @test v9.2.1
fixed

**Comment by SamKimball-BrownU** [comment]
I was a bit confused on the issue here, but then I tested it in ustp and saw what you meant. This problem is resolved.
