### ISSUE TITLE
File Repository does not recognize context after synchronization

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#651]
Added records to USTP V9.2 on Alice. Synchronized. All the images were there and if one clicked on the images one saw that they were given the proper context. However, searching for the context (we used 695 as an example because I was also testing QR code uploading of CM from 695, which failed, see #627) resulted in being told the context didn't exist. Lutz had an inkling about the cache. He forked, and that solved the problem in the instance, but it shouldn't be happening.

**Comment by urapadmin** [comment]
### 0.8.2
I tried something. Should be better now. The synchronization log should say something like "rebuilding file-identifier-cache" and then "********** synchronization aftermath finished **********".

**Comment by lbestock** [comment]
#696 is basically this again and suggests that it is not fixed

**Comment by urapadmin** [comment]
because I misunderstood. I have to refresh a different cache: the identifier cache.

**Comment by urapadmin** [comment]
### kiosk 0.8.15
that should not happen anymore. If an image registered under a new identifier (that was not known to the system before this synchronization round) enters the system through synchronization, the file repository should know about that identifier immediately afterwards.

**Comment by lbestock** [comment]
Test April 2021 with ARCH 1900.

**Comment by luizaogs** [comment]
Works.
