### ISSUE TITLE
stuck in a dialog box in kiosk/admin/housekeeping

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#652]
Clicking around I hit "housekeeping" and got the following dialog box:

![image](https://user-images.githubusercontent.com/49291909/85636774-60bea580-b64f-11ea-853c-e532d534dd75.png)

Fine, but I can't close the dialog box either by clicking the X button or by clicking the X at the upper right corner, so my only options are to close the browser window or run the thing. Happened when both on an iPad and on my Mac. V.0.8.1.

**Comment by urapadmin** [comment]
### fixed in 0.8.2
