### ISSUE TITLE
error in export URAP

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#655]
First attempt to get the real URAP file on the recently configured local server. Connection no problem, creation of workstation no problem. Fork no problem. Export failed. (I did the "prepare for field" two-in-one button.)

![image](https://user-images.githubusercontent.com/49291909/85753904-a7a5ad00-b6da-11ea-9ebc-6fb42fc4f9f8.png)

**Comment by lbestock** [comment]
Tried now just to export it, since it already forked. And the list is much shorter and quite different, with more red up at the top.
![image](https://user-images.githubusercontent.com/49291909/85754841-6792fa00-b6db-11ea-9ac4-c1933cb4c37b.png)

(Can you get these logs easily now? I've forgotten if I need to copy them for you.)

**Comment by urapadmin** [comment]
should be fixed.

**Comment by lbestock** [comment]
Failed.
![image](https://user-images.githubusercontent.com/49291909/85773167-90bb8680-b6eb-11ea-98c0-f289185b52a4.png)

Now I'm trying to restart the whole process, including forking, and I am spinning at 0%.

**Comment by lbestock** [comment]
Argh and then I got it going again, by quitting FM on the local server. But it stalled at 84% during  images. And then it looked finished, but was not.

**Comment by lbestock** [comment]
Next error.
![image](https://user-images.githubusercontent.com/49291909/85788850-97ea9080-b6fb-11ea-8600-0e55fe446289.png)

**Comment by urapadmin** [comment]
clear case of temporary and local filemaker hickups. I started the same process and it ran immediately. Restarting the server helps in such situations almost always.

**Comment by urapadmin** [comment]
should this occur more often, I might have to set the timeout for the amending the file-identifier-cache up. Reminds me that there is a ticket I keep forgetting to file: #656.
This here, though, can be closed, I suppose.
