### ISSUE TITLE
restore with selection of available filenames

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#659]
since there is no access to the server's filesystem, restore should show what filenames are available in the configured backup path.

**Comment by urapadmin** [comment]
### v0.8.3
The input field can still be used as an input field. It is possible to input a file with 

- [ ] either full path and filename or 
- [ ] only filename if the file is in the standard restore directory.
- [ ] the files in the standard restore directory are listed by the dropdown
- [ ] the dropdown allows to select one

**Comment by lbestock** [comment]
Please explain for me to test.

**Comment by urapadmin** [comment]
If those checkboxes mean nothing to you, I guess, I'll better explain that in person.

**Comment by lbestock** [comment]
Your file went kaputt. You need to go to administration and go to restore from the previous backup, and tell it what to do. Don't do this until Lutz has configured the backup properly on PVD.

**Comment by lbestock** [comment]
This all appears to be working except for one problem, which is not primarily this but is familiar: the dropdown list limitation problem. I have backed up. I go to restore, and the dropdown list has only 10 items and none of them are my most recent backup. Can one make it so that list sorts by time? This might in fact be a real problem - the names of backups are confusingly similar and one would expect to backup to the latest backup and that it would be top of the list and it would be quite a shock to accidentally back up to the wrong version.

**Comment by urapadmin** [comment]
- [ ] order filenames by date/time

**Comment by urapadmin** [comment]
### @test kiosk 0.14.1
The most recent backup files should now appear on top. 

Note that this is not only a simple selection box. You can also start typing and that way you'd get all of the files matching the pattern you type. So if you know you want a backup from 01.07.2021, you can type this pattern and the list will be reduced to files from that date. Within that list the files will be sorted by the file's timestamp in descending order:

![image](https://user-images.githubusercontent.com/38838314/151489069-51a2aae1-eed3-4fd1-91c7-5539f85f2ba7.png)

**Comment by luizaogs** [comment]
Just looked at this in PVD and it does seem to be mostly working, but there was also a file out of place in the list (see below, one backup from 2021 snuck in above a few from 2022). So I thought I would note it but if that is irrelevant this can be closed.

<img width="796" alt="Screen Shot 2022-01-28 at 8 27 02 AM" src="https://user-images.githubusercontent.com/67970402/151564239-59b55f35-0e5d-4c93-87e2-0b15daa85153.png">

**Comment by urapadmin** [comment]
ja, I saw that, too. Can't say why it has a 2022 timestamp, but it has:
![image](https://user-images.githubusercontent.com/38838314/151631988-bbf77f1b-a2a6-47d7-876f-5df24430380c.png)

**Comment by urapadmin** [comment]
so this is okay.
