### ISSUE TITLE
filerepository: selecting a tag from the list does not refresh the number of images ...

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#660]
I have to press tab or something first. Unnecessary.

**Comment by urapadmin** [comment]
### 0.8.4
fixed

**Comment by lbestock** [comment]
Not quite sure what you mean by "tag from the list"? There is no list with tags that I can see. If you mean updating automatically when record type is switched then that does update automatically and this can be closed.

**Comment by urapadmin** [comment]
file repository: tag selector. It opens a list of available tags if you start typing (and if Beset does not have a hiccup at the same time):
![image](https://user-images.githubusercontent.com/38838314/87577246-e07de400-c6d2-11ea-9b57-76aef968647a.png)

**Comment by urapadmin** [comment]
and it was here that one had to press some kind of key after selecting a tag from that list.

**Comment by nvd2** [comment]
It automatically refreshes the number of images when a tag is selected now.
