### ISSUE TITLE
file import filter - date and time of an uploaded file are wrong

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#67]
the date of the file is not taken correctly. It appears that instead one gets the current date just with 00:00:00 as the time.
LK: Time is cared for, but the problem that the date is the current date is due to the upload. The file loses the properties when being uploaded and saved to the temp directory

**Comment by urapadmin** [comment]
so what shall we do? Not use this filter in upload?

**Comment by urapadmin** [comment]
let's try to send date and time as separate json attributes.

**Comment by urapadmin** [comment]
### v0.8.27
that was a tour de force. 
Keep in mind that the file's modification date will be the "date and time of creation" in the edit file dialog and NOT the record's modification date (in the header of the edit file dialog). And take care to actually use "get date from file":
![image](https://user-images.githubusercontent.com/38838314/106517793-f607ff00-64a6-11eb-976c-dc3ffe5b9f51.png)

**Comment by lbestock** [comment]
Works.
