### ISSUE TITLE
new unit selection on start page with filter

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#673]
if we have a ton of feature units the current list gets out of hand. We need a different approach here. It shall be a list that shows not only the unit identifier but also type and method. It should also be possible to filter the list so that e.G. only excavation units are visible.

**Comment by urapadmin** [comment]
### recording 8.9.2
We have that selection now. The filter filters the unit term we assign to units. That way we can distinguish between Trench, Area, Block, Unit, Feature, Survey etc. by using a single word. Not all that useful for a project where all units are called "unit" no matter what type they are, but I suppose that's rather rare.

**Comment by lbestock** [comment]
No problem at all to hit it, even on a mini.

**Comment by urapadmin** [comment]
really? even if the buttons are next to each other? I vary the position according to type to make it less likely to hit the wrong button. The problem is: If you don't notice that you hit the wrong button and you are eager to type, you might find out long after you made a new locus in the wrong unit.

**Comment by urapadmin** [comment]
please try again under excavation conditions before you close this.

**Comment by luizaogs** [comment]
Do you mean actually excavating here or is mock excavating good? Was going to assign this to myself to test on the iPad but if that's not sufficient I will not.

**Comment by urapadmin** [comment]
I think if you sit in a chair at your desk you are less likely to hit the wrong button anyhow. But in the sand, sweating or freezing (choose yours) with all the sand in your face ...

**Comment by luizaogs** [comment]
Or battling scorpions, worms. Well I shall leave this one, then.
