### ISSUE TITLE
make sure features and survey units are called the right thing and have the right icon

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#674]
### v9.2.2
Please look around and make sure, that the different units, like excavation, features and survey units are called what is configured in labels\standard_term_for (they get this term on creation, so changing the config setting afterwards won't change existing units).
- [x] the terms should be correct where ever there is a list or a label. e.G. in tab headers, in the form header, on the first page of the unit form, you name it
- [x] there is also often an icon next to the unit identifier that visualizes the kind of unit: We have one for pedestrian (boots), feature (castle) and excavation (trowel). Make sure they are always correct everywhere.
- [x] make sure that this is true for units that are created on the start page but also for feature units created form a survey unit or from an excavation/feature-recording unit.
- [x] makes sure that icons and terms are also correct if you jump into units from within tag analysis.

**Comment by lbestock** [comment]
So much better than Anatolian archaeology are big tickets that require someone meticulous who understands configuration and has a stake in feature icons! I'm putting Oren on this one, too. It's a hell of a ticket for a newbie but I'm asking that the two of you please be in touch (on the side, not through github) to walk through the stages of this one so that Oren can learn about testing.

**Comment by osiegel14** [comment]
This sounds perfect. Luiza beat me to the punch and reached out to set up a
meeting tomorrow afternoon before the larger team meeting. I'm excited to
get started!
All best,
Oren

**Comment by luizaogs** [comment]
We're going through the ticket in parts so there might be more, but we just realized that for excavation/feature recording units we get the trowel as the icon on the trench area menu on the start page but then we have the treehouse on the actual form (both on the first page of the form and in the header). Not sure if you meant to have both and we're also not really sure which would work best in this case. You don't really need screenshots for this but I'm adding them anyway to show Oren. 

![image](https://user-images.githubusercontent.com/67970402/88706618-1b264a00-d0df-11ea-9476-ba201e306674.png)
![image](https://user-images.githubusercontent.com/67970402/88706629-1e213a80-d0df-11ea-899f-a64eb31e939b.png)

**Comment by luizaogs** [comment]
This next thing is really more a question than an issue. While checking if things were labeled correctly in tag analysis we noticed that collected materials for survey units and features have a weird floating "context" label in the header: 
![image](https://user-images.githubusercontent.com/67970402/88708356-8a04a280-d0e1-11ea-8c5e-ff66951b971a.png)

This is not the case for collected material in actual contexts, of course, since in those forms the context number goes in that space: 
![image](https://user-images.githubusercontent.com/67970402/88708469-b02a4280-d0e1-11ea-9963-68adcfc6d70d.png)

Not sure if this is purposeful or not, since survey units and features are not actually contexts. If this is an actual issue and I should open a separate ticket for this just let me know!

**Comment by luizaogs** [comment]
Also tested if changing the standard term would work for future units for fun because it wasn't on the checklist and indeed it does! And previous units were not changed, hooray.

![image](https://user-images.githubusercontent.com/67970402/88714292-98a38780-d0ea-11ea-9f80-eea1bae8e3fa.png)

**Comment by urapadmin** [comment]
This is indeed not an optimal ticket because it is a bit diverse. I try to answer:
1. The tree house should be the icon everywhere where you have a feature identifier, so that is correct, if I understand your comment right.
2. It looks strange because it is called a "Trench" which it should but that was just a wrong selection at unit creation
3. that you can see the invisible locus or even a hint that there is a locus involved with features and survey units is indeed a bug and needs a ticket. Even a milestone 9.5 ticket since that is something that should long be solved. So go for it.

**Comment by luizaogs** [comment]
For 1 and 2 -- so then should the icon for the excavation/feature recording in the menu be the tree house as well? That's what seemed incorrect. What caught our eye wasn't that the tree house looked weird with "trench" (which I indeed selected incorrectly) but that the trowel showed up for feature recording in the menu.

**Comment by luizaogs** [comment]
Also I suspect you know this but there are two different icons for pedestrian survey (one has one foot and the other two).

**Comment by urapadmin** [comment]
no, I did not know that :o) You know, I chose those icons on Uronarti in the tent and given the heat and all I wasn't sure about how many feet I see. I will leave this as a quirk for a while.

**Comment by urapadmin** [comment]
> 
> 
> For 1 and 2 -- so then should the icon for the excavation/feature recording in the menu be the tree house as well? That's what seemed incorrect. What caught our eye wasn't that the tree house looked weird with "trench" (which I indeed selected incorrectly) 

> but that the trowel showed up for feature recording in the menu.

Hm. No. Not really. The treehouse is for feature units themselves. I admit that the trowel is not great for feature recording but the treehouse isn't either. 
@lbestock: Why did we invent the excavation/feature recording units? I can't remember

**Comment by luizaogs** [comment]
Well on that note the header for excavation/feature recording forms says "digging" which we were also somewhat confused about.

**Comment by urapadmin** [comment]
no kidding. I did not even see that anymore.
Suggestions? Digging - which is an old relict from times of the very first version could be "feature recording" ?!?
I really don't know anymore why we needed the whole excavation/feature recording thing.

**Comment by luizaogs** [comment]
Maybe feature recording would work? Would you then also change the "digging" in locus recording to "locus recording"? Har har. Maybe obscure too but I usually crave consistency.

But yeah the purpose of the excavation/feature recording unit type is not very clear to me currently so I might be missing something.

**Comment by urapadmin** [comment]
Here is our answer as to what the purpose of the excavating/feature recording method is:
https://github.com/urapadmin/kiosk/issues/789#issuecomment-665675211
Laurel puts in Wheeler's old legacy excavation (!) in. But since we don't have Wheeler's locus records but rather features (his rooms), we needed to collect features instead of loci. Apart from that we needed the normal excavation recording form, with dayplans, narratives and all. And that is why I used the simple excavating form and extended it to show features instead of loci.

So much for the history

**Comment by urapadmin** [comment]
You may crave consistency where ever you want but not when it comes to my "digging" :o) Next you want me to standardize my buttons in message boxes. Back to Ok and Cancel? Never! 

But I give you "feature recording" as a title instead of digging when that's what the unit is about. That isn't optimal either (because, well, the real feature recording happens in the feature unit) but for 9.5 it should do and this ticket can be closed.

**Comment by urapadmin** [comment]
### v9.4.7
This is half fixed:
- [ ] excavating/feature recording units now have "feature recording" as a title

What isn't fixed is that the excavating/feature recording units have a trowel icon on the start page but a treehouse icon in the recording form. They should not have either, they would need something new (and in fact also a different term than feature recording. That's for a new ticket after 9.5:

**Comment by urapadmin** [comment]
and please read through this rather longish thread and make sure I did not miss any hint to an issue

**Comment by luizaogs** [comment]
I see no other issues, so closing this.
