### ISSUE TITLE
new feature recording in excavation units oddity in the list of features

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#676]
![image](https://user-images.githubusercontent.com/49291909/86519537-9a3ea000-be09-11ea-8201-32074c6b117f.png)

Creation of my first new feature from within an excavation unit. I was not expecting to see type FortressRoom. That happens regardless of whether or what "type" is chosen for the feature once I start to record it. That is not how the similar lists of features created from survey units behave. I also note that it formats wrong. Both the recorder and the feature type are notably higher on the line than the other information. I'll get you a shot when I have more rooms made, too.

**Comment by lbestock** [comment]
Oh yes sorry V. 9.3 on my laptop.

**Comment by urapadmin** [comment]
### fixed in 9.3.1
