### ISSUE TITLE
type strangely small in feature description

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#677]
![image](https://user-images.githubusercontent.com/49291909/86519871-0e2e7780-be0d-11ea-9f77-6f4666911057.png)

9.3  on mac laptop. Inputting text into the feature description of a feature created from within a new style excavation unit and the type is the wrong size.

**Comment by urapadmin** [comment]
### fixed in 9.3.1

**Comment by nvd2** [comment]
Sorry I'm a bit confused about this ticket. Would you want me to test if this bug no longer happens in the new version?

**Comment by lbestock** [comment]
Yes, that's exactly it. The ticket was created because someone noticed a problem. The developer fixed it and marked it as fixed in 9.3.1 (which you need to know to make sure you're testing it in a version that includes the fix, but you are - you've got 9.4 now). So all you do is try to repeat the error and if it's not there any more, you can close the ticket.
