### ISSUE TITLE
changing configuration of CM identification method for a unit did not apply the change

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#678]
I forgot to set CM ID to free input when defining unit Block VIII. I logged in as admin, deleted the one CM I had made in a feature of that unit, went to the settings of the unit, and changed the configuration thus:
![image](https://user-images.githubusercontent.com/49291909/86520191-b3e2e600-be0f-11ea-86f9-6213043ed822.png)
I logged out as admin and in as ldb.
I went back to my feature and created a CM.
It was numbered automatically according to its locus (the previous configuration, and still the general configuration for CM ID method).

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/86520207-e5f44800-be0f-11ea-88a4-6d90d15eb421.png)

**Comment by lbestock** [comment]
Oh my god I need a break that was supposed to be this:
![image](https://user-images.githubusercontent.com/49291909/86520217-f9071800-be0f-11ea-82a1-d5c848c17c7d.png)

**Comment by lbestock** [comment]
As a test I went in and changed the configuration method of feature CM to free input at the general configuration level. That works, so it's just this boutique override that is buggy.

**Comment by urapadmin** [comment]
you are entering the collected material in the feature unit, not to the excavation unit. The number comes from the feature unit. It is there that you have to change i!

**Comment by urapadmin** [comment]
nope, that does not look like a bug, just a misunderstanding.

**Comment by lbestock** [comment]
OK phew. I think I need a  break.
