### ISSUE TITLE
deleting a feature from the feature selection in survey actually deletes the feature: not good

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#680]
what should happen is that only the link between the survey unit and the feature is dropped. The feature itself should still be available (and could be linked again, see #679 ).

**Comment by urapadmin** [comment]
### fixed in 9.3.1
- [ ] the red trashcan icon is now a red minus 
- [ ] it just drops the connection to the feature. The feature remains in the database.
- [ ] test also in excavation / feature recording

**Comment by myjaylee1123** [comment]
Function works. Also tested if deleting link between a feature and a feature in excavation/feature recording would get rid of both links, and it does. Can always be re-linked.

Do we want to be able to delete features at all? The buttons are right next to each other, and although it's obvious that it's a link and a plus sign, may be good for there to be a confirmation for making a new feature within the excavation unit (so we don't have a million random empty features floating around)
