### ISSUE TITLE
after having created a new survey unit and entered it, the record is not ready

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#681]
"something nasty happened ... " when clicking on collected material
Same in feature units. When leaving the form and reentering everything is fine.

**Comment by urapadmin** [comment]
### fixed in 9.3.1
This is how the error exactly occured: 
- create a new unit with type "feature" / "feature recording", go back to start.
- select the unit by clicking on the feature button within the list
- the feature form would open but showing the wrong unit
- clicking on anything would lead to the "nasty" error. But only if the wrong unit is not itself a feature!

- [ ] does not happen anymore.

**Comment by SamKimball-BrownU** [comment]
Seems to be resolved. The correct unit is accessed.
