### ISSUE TITLE
a feature can be linked twice by the same survey / feature recording excavation

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#682]
just using the new link button (see #679) twice with the same feature leads to a second, third etc. entry of the same feature. 
That should not be possible.

**Comment by urapadmin** [comment]
### fixed in v.9.3.1
This should neither be possible in 
- [ ] excavation/feature recording
- [ ] survey units
- [ ] feature units

**Comment by lbestock** [comment]
MJ, giving you a bunch of sort of related ones - you're going to become our expert on feature links.

**Comment by urapadmin** [comment]
since #403 is closed, I close this one as well.
