### ISSUE TITLE
cannot apply a tag from the drop down list in tag analysis in a very particular case

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#688]
Ran into this in a real life use situation in which I am heavily reliant on the tags. It is SUCH a weird little particular thing that I would think I was making it up except I tried it several times. There is one particular situation in which I cannot use the drop down list of tags to add a tag to the list of ones to analyze. 

What happened:

I typed FA sondage 2 in and get nothing.
![image](https://user-images.githubusercontent.com/49291909/86841484-fc99d980-c071-11ea-9f57-c74a3db8fa39.png)

I worried that I might have had a capitalization issue. I went to the drop down list. Indeed, capitalization issue!
![image](https://user-images.githubusercontent.com/49291909/86841558-1a673e80-c072-11ea-884e-7ce58f3648e7.png)

I clicked the green button thinking it could just add the right tag to the wrong one. It didn't do anything. So I messed around. I can add a different tag on top of my wrong tag: 
![image](https://user-images.githubusercontent.com/49291909/86841694-3f5bb180-c072-11ea-8fb7-71736406c43c.png)

And I can add FA Sondage 2 by using the drop down menu if I have other nonsense in there already: 
![image](https://user-images.githubusercontent.com/49291909/86841796-631ef780-c072-11ea-8b63-de6d0cd92adb.png)

But something about the wrong tag being too close in name to the right tag prevents me from using the dropdown menu to add the latter to the former. And that is weird. (I can repeat the error using FA sondage 1.) And while it seems kinda small and meaningless, given that I ran into it in a real life working with the system while writing an actual article and it tripped me up, it seems worth making note of.

**Comment by urapadmin** [comment]
### 9.4.2
on of those unbelievable filemaker bugs they ignore since version 6. I found a way around it.

**Comment by nvd2** [comment]
I did not run into this same problem again.
