### ISSUE TITLE
redundant bug report cannon 

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#692]
In Filemaker at the Unit level the bug report cannon is both its own button and behind the hamburger menu:
![image](https://user-images.githubusercontent.com/49291909/86957060-27df0000-c128-11ea-8af4-df9ea4e58543.png)
Home is, too. It's not really a problem, but I would prefer to have the bug cannon only accessible behind the hamburger menu (which is already the case in loci). If anything were to be hanging out easily accessible it should be the QR code generator.

**Comment by urapadmin** [comment]
### v9.3.4
done.

**Comment by lbestock** [comment]
MJ, to get used to testing tickets I throw this one to you. It's super easy, and in PVD2020 we're in v. 9.4 currently so you can test it there. Any questions, ask away - we aim to start closing some of these testing tickets!

**Comment by myjaylee1123** [comment]
![IMG_0329](https://user-images.githubusercontent.com/47072505/87563874-ba822080-c68d-11ea-8377-5a5119157b74.PNG)

The bug cannon is still redundantly available behind both the hamburger menu and outside of it, while the QR code generator still remains hidden in the hamburger menu.

**Comment by urapadmin** [comment]
ah. this is the simple excavating mode. I will never learn that I have to do everything twice. Argh.

**Comment by urapadmin** [comment]
MJ, if something test negatively, please move the ticket to the "back to developer" pane in the testing project or, and that has the same effect, choose "back to developer" from the little drop down right under the project "testing" here in the ticket.

**Comment by urapadmin** [comment]
### fixed again in v9.4.1

**Comment by myjaylee1123** [comment]
It's been fixed for a trench, but not for a survey, as shown below. 
![IMG_0341](https://user-images.githubusercontent.com/47072505/88297141-91850f80-cccd-11ea-8ce3-eab8aa39da6a.PNG)

**Comment by urapadmin** [comment]
### 9.4.2
changed in Survey and Feature. I hope that's it now.
