### ISSUE TITLE
changing the order of photos/plans in "photos" context section

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#693]
I have somewhat forgotten how one excavates (I'm sure it will come back to me eventually). This means that I forgot to upload trench plans to their respective context photos sections when I first opened them, though I had uploaded them as dayplans, but then I wanted them in contexts as well so I added them there. BUT now they're on top of photographs of context closings and whatnot, and since these are preliminary trench plans they really should be the first things in there. I tried moving them down but have been unable to do so -- not sure if that's just me being inept or something that isn't supported by the system. I realize that being able to track exactly when what was uploaded is useful, but if allowing for movement is a possible feature it might be worth considering it for cases such as this? Unless using the "replace" feature to move them around that way is the way to go, but that seems more dangerous to me.

**Comment by urapadmin** [comment]
no moving possible. If this is a valid archaeological thing to do (as opposed to an issue that happens only in test scenarios) we would have to make the attribute that's used for sorting (I think it is the photo's timestamp) accessible for manipulation. That's just the technical side. As for the archaeological site we need Laurel here, I don't entirely understand what the situation is.

**Comment by luizaogs** [comment]
I suppose this is mostly pickiness. It's a bit annoying to deal with when in the field itself (at least for me) but if it is not an issue during analysis it's not a big deal!

**Comment by lbestock** [comment]
I'll take a look at the specific instance once we've synchronized but I'm having trouble imagining that it would be a problem for analysis. It would in fact be a bigger issue in dayplans than in context images to have things not in the order in which they actually occurred. In practice though this has happened a lot with FA stuff, which I'm dealing with now without difficulty.

It raises an interesting test case that might have a real correlate: Lutz, now that we can link narratives to dayplan images, which is a feature I have never used yet and do not entirely understand, what would happen if I needed to link two sets of images and narratives, where their relative order was not the same? As in, narrative A was made before narrative B and so is lower down the list. Dayplan A was mistakenly added later in the day than it was actually made, and so it is atop Dayplan B in the the recording. But narrative A should be linked to dayplan A, and narrative B to dayplan B. Visualized, their links would cross.

**Comment by urapadmin** [comment]
I have no idea. I did this so long ago ... I suggest you try it out.

**Comment by luizaogs** [comment]
I was thinking about this more and realized that my issue with it was really less about the chronological ordering of the images and more about the placement of the sketch itself -- this might be a holdup of what I actually like from paper recording, because there you usually have a designated spot for closing and opening plans and so know exactly where to find them for quick reference later (if you don't lose the paper, that is). Anyway, like I said it's obviously not a big deal if it's not an issue for analysis with Uronarti's much more complex units than those of my nightstand, but it struck me as a significant difference from more traditional modes of recording that I thought I would bring it up.

**Comment by urapadmin** [comment]
can somebody please elucidate on what exactly is wished for here? If paper can do something we can‘t, we should care for it. A little less apollogetic and relativizing language would help at least me to focus :) Think of a ticket as of object recording. You don‘t start your descriptions with „I might be seeing this the wrong way but it‘s reddish ...“. I hope. If I understand what you are missing then I might come up with an idea to support it.

**Comment by luizaogs** [comment]
Ha. Fine, I'll try. 

It would be helpful (for me) to be able to sort context images between sketches and plans, and photographs. So for instance, if I want to see what the context looked like when I first started excavating it and first sketched it out, it would be useful to be able to go straight to that sketch instead of having to scroll through multiple photographs of specific parts of the context or different phases of excavation, etc. Especially if, like me, you forgot to add the sketch first thing and so now it's in the middle somewhere, between photographs and potentially other sketches. That's what I meant as the difference with paper recording -- there I know where the sketch is (or sketches are, if there are multiple sketches of different phases of the context) and don't have to scroll through a bunch of other stuff to get it. I don't know how possible this is to do, but even "tagging" sketches vs. photographs inside the photos tab of specific contexts might be useful, or maybe separating the two.

**Comment by urapadmin** [comment]
my first Idea here is that we could add something more general. Let‘s call it a pinboard. It exists only in your local recording system and you can pin images at it (on it?!?). And you can access it from whereever you are (through the menu in the header). 
Would that serve your purpose? It is a bit like using your fingers as bookmarks in a photo album.

**Comment by luizaogs** [comment]
Oh yes, I think so! And then you can unpin and pin things as you move through different lots, too. Yup, I like it.

**Comment by urapadmin** [comment]
you‘ll have it.
(one day).

**Comment by luizaogs** [comment]
Yay!

**Comment by urapadmin** [comment]
it's there: #709 
If that helps you with the original issue then please close this one here,

**Comment by lbestock** [comment]
Luiza, please test this one in the next round of excavation recording.

**Comment by luizaogs** [comment]
Closing this one because the pinboard is great (thank you, Lutz) and leaving #709 open for now because some things still need to be checked.
