### ISSUE TITLE
unexpected box about proxies after creating locus image

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#695]
After creating a locus image in URAP on ldbmac 9.3.2 things looked fine. And I think they are fine. But when I clicked on something to leave that image, I got a funny message:

![image](https://user-images.githubusercontent.com/49291909/86982037-478d1d00-c156-11ea-9e69-c0c556752d00.png)

**Comment by urapadmin** [comment]
### v9.4
fixed

**Comment by lbestock** [comment]
Wow what a crappy ticket. I can't test it properly because I never recorded how I got that image into the container, and clicking "something" is vague. It's a new locus but clearly was an image already in the system. I assume I used the gallery. In any case I do not get this message when using the same computer and adding images either through the gallery or input, and then clicking on the side of the frame of the FM window.
