### ISSUE TITLE
erroneous message that the identifier is unknown

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#696]
File repository 0.8.4 on the local server. I had just synchronized, after having made a new locus (and a bunch of other stuff). I searched the file repository for the locus, and got the very funny return that the identifier is unknown but ALSO got the images I should have gotten from the search. Obviously I didn't click 'fetch em so I don't even know what I did to make them appear! Maybe hit return? I think this is related to something we have had before but my brain, it is mush.

![image](https://user-images.githubusercontent.com/49291909/86982303-eade3200-c156-11ea-9f0e-dab50add921c.png)

**Comment by lbestock** [comment]
Ja it looks a lot like #651 to me except that now the images are found and it's just the statement about the context being unknown that hangs around. And it is mouse-clicking on that wrong message, as though the message were the correct one, that gets me to the images.

**Comment by urapadmin** [comment]
the file import might suffer from the same issue? see #714

**Comment by urapadmin** [comment]
in fact this is a duplicate of #651

**Comment by urapadmin** [comment]
closed because of duplicate
