### ISSUE TITLE
local server unexpected cancelation of job

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#697]
Downloading URAP from the local server. It was repeatedly stuck, as so often happens (why does the file repository work fine but the workstation manager think the server needs resetting?) So I restarted the server and things seemed to be working fine. I went to  take a shower while it was forking and came back to this message:

![image](https://user-images.githubusercontent.com/49291909/87049538-1ac71d00-c1cb-11ea-8c8e-7fe5b0437c21.png)

I certainly didn't stop the export while I was in the shower. It's highly unlikely that you did so while you were getting off a train in Bremen. So what happened?

**Comment by urapadmin** [comment]
`>[9768/3996: filemakercontrolwindows.DEBUG at 2020-07-09 09:16:41,173]: FileMakerControlWindows.sync_internal_files_tables: deleting outdated or modified records in images
>[9768/3996: filemakercontrolwindows.DEBUG at 2020-07-09 09:16:41,426]: FileMakerControlWindows.sync_internal_files_tables: adding from images_load to images
>[9768/3996: filemakercontrolwindows.DEBUG at 2020-07-09 09:17:44,938]: FileMakerControlWindows.sync_internal_files_tables: 2442 records in images
>[9768/3996: filemakerworkstation.ERROR at 2020-07-09 09:17:44,938]: Exception in Workstation.export_to_filemaker: A user has cancelled the process.
`
Is suspect that was a timeout, interpreted as a cancellation by the user. It's urap, so the data is huge and there is a gap of more than a minute when adding from images_load to images. I might have to raise that timeout but above all I should at least log that timeout.

**Comment by urapadmin** [comment]
### 0.8.16
puh. That is much more intricate at this point than expected. I am not even sure where the timeout occurs, but I suspect MCP gets impatient. There is a hard-coded timeout for the job pulse in mcpjob.py: 60 seconds. That would fit (only I usually use 60 seconds).
So I'll set that up to 120 and then we'll see. 
That is a solution for the immediate issue.

**Comment by urapadmin** [comment]
the real issue has moved to the new ticket: #839

**Comment by lbestock** [comment]
No trouble at all with URAP when I changed file picking back to make all contextuals low res. So 477MB and forked and prepared in three minutes, without hiccup.

Three days ago I would have said you were right that I wouldn't use file picking in the field. I am not so sure. Really the difference in speed is so great.

**Comment by lbestock** [comment]
Hmpf happened again. Is it significant that the FM bar is always at 50% when it stalls?
![image](https://user-images.githubusercontent.com/49291909/111208802-9cb0e680-85a1-11eb-8af2-12864609baa7.png)

**Comment by urapadmin** [comment]
yes, it is. The step before timed out. I close this since it is about the old workstation manager and I have meanwhile raised the timeouts. if it comes up again, file a new ticket.
