### ISSUE TITLE
some images broken in file repository (tragic)

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#701]
I decided to look at the file repository (because I totally know what that is!) and noticed that several of my images were broken (e.g., LA-001 Trench plan with location of walls). Upon closer inspection it became clear that the broken images are all either Touchdraw plans or annotated photographs. Upon yet closer inspection it also became clear that those were images I had put in twice. The "trench plan with location of walls," for instance, is in the dayplan but also in the photos section of contexts LA-001, -002, -003, -004. 

Here is evidence that the trench plan is indeed there in Filemaker: 
![image](https://user-images.githubusercontent.com/67970402/87102529-973c1900-c228-11ea-909f-45cede7a8d09.png)

And here is its tragic absence in the repository: 
![image](https://user-images.githubusercontent.com/67970402/87102590-bcc92280-c228-11ea-818e-11611d33791e.png)

Could it be that I tried to upload the same image twice??? Yes, I think so.

**Comment by lbestock** [comment]
Tragic is when Hamlet gets rained out.

This, this is just a gallery issue. To save the trees, the system stops you from putting the same image in twice anew. You can instead create a link to the image, which looks to you like the image is in there twice (or three times, whatever). But the image itself only gets stored once, and fewer trees die and the file stays a more reasonable size.

I'm putting Sam and user manual on this because explaining this is critical or projects will get these broken links. And we'll leave it open so Lutz sees it, too.

For the time being, once you've downloaded again to your ipad you can go back to the images (they'll be broken now too in Filemaker for you). Insert the old image using the gallery instead of your photos. And then once we synchronize all will be right.

**Comment by SamKimball-BrownU** [comment]
Noted! Also, would like to say that this isn't tragic, this is great! Issues like these are great to know about! Good to run across them now, so that they can be fully included.

**Comment by urapadmin** [comment]
this is not just a gallery issue. If Luiza has put in the same image twice synchronization should have failed. Did it?

**Comment by lbestock** [comment]
Not that I noticed. Indeed, not at all or at least not in the end? I think I had to tell it to synchronize twice? But I assumed it was a server hiccup and made no note of it I'm afraid. Now certainly we have everything synchronized.

**Comment by urapadmin** [comment]
﻿
you can‘t ignore that. You would have had to set the synchronization option to drop those images. And you would remember that.

**Comment by lbestock** [comment]
Yeah no I definitely did the simplest synchronization without setting any options. We will repeat our steps tomorrow and give you more information then.

**Comment by urapadmin** [comment]
The logs support that Luiza inserted the same photos twice multiple times. It is correct that they are not imported. What ISN't correct is that synchronization did not fail. Apart from that: There were errors during synchronization and they were pointing to a real issue:

> Synchronization.synchronize_files: Something went wrong: workstation logsipad, identifier d566e4b9-2090-4b46-abb3-a25eee54941c
> Synchronization.synchronize_files: Something went wrong: workstation logsipad, identifier 84b9e85c-8042-416a-af50-503279729263
> Synchronization.synchronize_files: Something went wrong: workstation logsipad, identifier cdafcf02-66ee-4907-a151-b6bc0aecf0b7
> Synchronization.synchronize_files: Something went wrong: workstation logsipad, identifier 25ba5ffb-89d1-4d76-88bd-05a4d50a9783
> Synchronization.synchronize_files: Something went wrong: workstation logsipad, identifier 52c0ee65-33bc-4afc-9606-2475dc8a4f5f
> Synchronization.synchronize_files: Something went wrong: workstation logsipad, identifier 5762efae-bca8-42ab-a22c-00451ac43364
> Synchronization.synchronize_files: Something went wrong: workstation logsipad, identifier 166a0f96-8075-4b7f-b3a1-0e4da1dfa9e3
> 

It is important to take the synchronization log seriously even though some errors are often non-issues. I know that one tends to dismiss the whole thing immediately but particularly in our test scenario I would prefer not to get into that habit. Please have an eye on the logs and report. It will at the very least train you to understand them better and might lead to some FAQ or so in the user's manual.

**Comment by urapadmin** [comment]
So the real bug here is: If the same image is input twice synchronization should stop unless run with the option to drop such images.

**Comment by urapadmin** [comment]
and one day: #441

**Comment by lbestock** [comment]
Since you have the logs and can see what  happened, you do not need us to repeat this today and document better our steps, correct?

**Comment by urapadmin** [comment]
correct

**Comment by urapadmin** [comment]
### v0.8.5
first of all I have fixed the bug. Means, 
- [ ] if an image has been entered in filemaker twice synchronization will report this as an error and fail. 
- [ ] if the option "drop duplicate images" is set when synchronization is started, synchronization will still report warnings and errors about the file but succeed. 

BTW. The ultimate sign that synchronization finished despite error messages is the line "Synchronization.synchronize: commit successful."
If synchronization failed, the opposite line occurs: "UrapSQLDb.rollback: Rollback of UrapSQLDb!"

**Comment by SamKimball-BrownU** [comment]
@lbestock to test this, I can upload a couple duplicate files when I do my archaeological scenario

**Comment by SamKimball-BrownU** [comment]
I "accidentally" uploaded a dayplan image twice. So, synchronization should fail (hopefully)

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/87879924-a60a9480-c9bb-11ea-943b-0237af7c6249.png)
Failure log related to this.

**Comment by urapadmin** [comment]
yes. We already have a ticket that about simplifying the log (The UnboundLocalError should not appear here). But the relevant message here is:

>[4704/3824: synchronization.ERROR at 2020-07-19 10:49:58,652]: Synchronization.synchronize_files_v2: e:\test\kiosk\sync\sync\filemaker\from_work_station\alice\files\58fbc15f-c997-443f-a03f-c63c878d9582.jpg could not be uploaded to file repository because the same file is already in there.
>[4704/3824: synchronization.ERROR at 2020-07-19 10:49:58,652]: Synchronization.synchronize_files: Something went wrong: workstation alice, identifier 58fbc15f-c997-443f-a03f-c63c878d9582

It tells you the reason (same file already in here) for the error and in the next line the culprit. 
see #441

Can't find the ticket about simplifying the logs, so there is a new one: #754

**Comment by lbestock** [comment]
I believe this can be closed now.
