### ISSUE TITLE
a confusion of button locations and how to move around in tag analysis

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#702]
I am using tag analysis in real life analysis of Unit FI, URAP. I am working on ldbmac, Filemaker v.9.3.2.

I encountered something that I first thought was a bug but then realized after repeating my steps twice to grab screen shots for you is probably not a bug at all but a confusion arising from the location of buttons when photos are expanded in tag analysis.

I clicked on one photograph in tag analysis and used the little expander button, the one that looks like three stacked pieces of paper, to expand it. 

![image](https://user-images.githubusercontent.com/49291909/87204226-4bde4500-c2d2-11ea-86d3-e1608fe10c1b.png)

Having seen my fill, I clicked the little X button up to the right, and it collapsed as I expected. I then had the photo list again. (The problem: that button isn't supposed to close the photograph, its supposed to clear the tag from the search. But I can't see that that is what it does when the photo is open, so I mistook its purpose.)

What's odd is that it in fact did close the photograph, and clear the search term from the "enter tag" box, but it did NOT clear the list of photos from my original tag search. This is what it looked like afterwards:

![image](https://user-images.githubusercontent.com/49291909/87204459-daeb5d00-c2d2-11ea-977c-88dd94f07e16.png)

So I did not in fact notice I had cleared the search, and I clicked on a second photograph and expanded it the same way. However here when I was done with it I noticed there was no X button. (Which now I get it, of course not, there was no tag term in the search box to X out.)

![image](https://user-images.githubusercontent.com/49291909/87204149-1df90080-c2d2-11ea-8777-b3f7c70cbe2f.png)

I clicked on the menuish looking button there instead and it cleared my list of photographs and gave me the list of possible tags, which of course is what it should do. It just all confused me the first time or two around. Having the photo pop open large enough so that it covers the X button would prevent the confusion; it might be better if that box cannot be cleared if one is looking at a photo, not just because it's confusing but because it's an action in the background as it were. And perhaps having a separate X button that was clearly to close the photo would make me more comfortable. (It seems I get confused at closing things by just clicking elsewhere, rather than having defined "close me" buttons, a lot.) Having the results list of photos clear when the tag box is cleared would also make sense, and in fact this happens already if one is in just the list of photos, not looking at one blown up.

**Comment by urapadmin** [comment]
I think I should also invent a clear filter symbol and get rid of the X. Unfortunately I am limited in controlling what parts of a screen are covered by the photo. I‘ll try.

**Comment by urapadmin** [comment]
### 9.3.3
Looks a bit strange to me and is a bit hacky. I hope it works on ipads and macs:
- [ ] if a popover opens in tag analysis the two filter buttons disappear.
- [ ] and reappear of the popover closes

**Comment by lbestock** [comment]
Tested on ldbmac and works fine.
Tested on ldbipad and works fine.

A "for Laurel" feature appreciated by the one it is for.
