### ISSUE TITLE
a request in tag analysis

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#703]
I use tag analysis all the time now. I have tag analysis in one place open and the file repository in another and the article I am writing in another, and this is how I work. My appreciation for this tool you have built goes up constantly while I'm using it like this. 

Right now there is a feature that would be helpful in tag analysis, but I'm not sure if we actually want to build it into FM or just know it's coming when we get analysis in kiosk.

I would like to be able to sort the photos in the same ways I can in the file repository, so oldest first, or youngest first, or by context. I would also like to be able to see the context next to the photograph when in list view: 

![image](https://user-images.githubusercontent.com/49291909/87206292-6b2ba100-c2d7-11ea-8fa5-2e609d136937.png)

Thank you.

**Comment by urapadmin** [comment]
### v9.4
You got it all, except for flipping between sorting order (increasing / decreasing order). That would need a terrible hack and it is already pretty hacky in there.

**Comment by lbestock** [comment]
This is really helpful all around. I am using it smoothly and with appreciation while writing this morning.

Two small tweaks requested:
If there can be only one sort order for date, could we reverse it so most recent is at the top instead of earliest? This is the sort I am using most right now but I am finding myself always wanting the latest stuff most and so scrolling quickly to the bottom, then going slowly back up. I have tried to think of what types of questions one might be asking when using this tool, so as not to let my current need override what would be more common. But I think more questions about final state of things than about initial state of things will be approached this way, so reverse order makes sense.

Would it be possible to get the date on there, too, as well as context and record type?

**Comment by urapadmin** [comment]
I cannot easily give you the earliest on top because I have to decide on ONE sort order and if it is decreasing and you would sort by context it would be decreasing as well. And then you would presumably complain in the other direction. 
Changing that would need the same terrible hack I mentioned earlier.

**Comment by urapadmin** [comment]
### 9.5.3
- [ ] date added to photo list
