### ISSUE TITLE
give all popovers a close button in the upper left corner

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#707]
same with popups, so the difference between a popover and a popup is not important here. All dialogs popping up above a form need a little close button in the upper left corner

**Comment by urapadmin** [comment]
- [ ] unit selection on start page
- [ ] tag selection in tag analysis

- [ ] what have I missed?

**Comment by SamKimball-BrownU** [comment]
So I have a bit of a problem with the X on the unit selection: it is very easy to accidentally hit "logout and close", especially on the ipad

**Comment by SamKimball-BrownU** [comment]
on site notes, the x is clipped off by the border of the image popover frame

**Comment by SamKimball-BrownU** [comment]
Missing in locus relations image popup

**Comment by SamKimball-BrownU** [comment]
Missing in locus tab, at bottom under tab "photos", in those photo popups

**Comment by urapadmin** [comment]
> 
> 
> So I have a bit of a problem with the X on the unit selection: it is very easy to accidentally hit "logout and close", especially on the ipad

### 9.4.2 I have removed the [x] from that particular popover

**Comment by urapadmin** [comment]
> 
> 
> on site notes, the x is clipped off by the border of the image popover frame

### 9.4.2 
should be ok now

**Comment by urapadmin** [comment]
> 
> 
> Missing in locus relations image popup

### 9.4.2
fixed

**Comment by urapadmin** [comment]
> 
> 
> Missing in locus tab, at bottom under tab "photos", in those photo popups

### v9.4.2
that was the case only in simple excavation mode. fixed now.

**Comment by SamKimball-BrownU** [comment]
One more nitpick with site note images: It's hard to touch the actual X. Instead, I end up pressing on the actual image container, because the x overlaps a bit, at least visually. There's not enough spacing there for my fat fingers

**Comment by SamKimball-BrownU** [comment]
> One more nitpick with site note images: It's hard to touch the actual X. Instead, I end up pressing on the actual image container, because the x overlaps a bit, at least visually. There's not enough spacing there for my fat fingers

Same problem with locus relation image popup

**Comment by SamKimball-BrownU** [comment]
I like the spacing/etc of this one.

> > Missing in locus tab, at bottom under tab "photos", in those photo popups
> 
> ### v9.4.2
> that was the case only in simple excavation mode. fixed now.

**Comment by SamKimball-BrownU** [comment]
It seems that any container that might have an image title is good, but ones that don't do not have that same spacing at the top (because there doesn't have to be space for the title). Anyway, the X itself is everywhere.

**Comment by urapadmin** [comment]
> 
> 
> One more nitpick with site note images: It's hard to touch the actual X. Instead, I end up pressing on the actual image container, because the x overlaps a bit, at least visually. There's not enough spacing there for my fat fingers

### v9.4.5
fixed

**Comment by urapadmin** [comment]
> 
> 
> It seems that any container that might have an image title is good, but ones that don't do not have that same spacing at the top (because there doesn't have to be space for the title). Anyway, the X itself is everywhere.

it only seems that way. It is not a technical issue but rather me who tried to keep the image as rectangular as possible and with a title that behaves a bit differently. The only useful titles are the descriptions of the images themselves and I agree that the spacing you like is the most useful spacing. I try to change that bit by bit whenever I catch one of them but this here can be closed unless there are missing close buttons.

**Comment by urapadmin** [comment]
ok, new ticket #788 gives you a place to note more layout observations on these popover images.
No priority, so don't test systematically at this stage. Just a place to note when you happen to see something,

**Comment by SamKimball-BrownU** [comment]
This ticket is good. The x exists everywhere I could find in testing. There are a million places I might have missed, so I will keep my eye out, but for now, I will close this and move any complaints about layout to #788
