### ISSUE TITLE
background windows opening when inputting collected material photographs

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#708]
When inputting photographs for collected materials during survey (collected materials associated both with the general unit and with specific features) a window opens into what seems to be the background of the software (see screenshot below). This also happens when typing in the descriptions for the photographs, but only if the description is written after the photo is inserted (I tried both ways).

![91B8F9DD-565D-4B07-871B-60AD1762EF1D](https://user-images.githubusercontent.com/67970402/87232424-ea2ee100-c38c-11ea-850d-03e2825be25f.png)

This happens every single time a photo or description is added (see caveat about descriptions above) and so by the end of surveying I had 22 of these windows open. 

![2BFD8174-CF8D-40C1-A124-0FF870F23175](https://user-images.githubusercontent.com/67970402/87232449-324e0380-c38d-11ea-8f1a-f6d8c711798d.png)

I figured out how to get out of them by clicking on the arrow next to “file_identifier_cache,” see first picture — which allows me to go back to the database. But I cannot close them, or at least I don’t know how to do so. By clicking on the blue arrow on the top left, a menu appears (see screenshot below). 

![7461B1BF-C3B5-445E-BCD4-8D235DA142A3](https://user-images.githubusercontent.com/67970402/87232507-9f619900-c38d-11ea-9fb2-7e808b53e29d.png)

If I click on “close file,” I get this: 

![9311E955-8374-4B3F-8D65-D3185ADFC437](https://user-images.githubusercontent.com/67970402/87232569-cd46dd80-c38d-11ea-9a0c-c26bfcae48b4.png)

“OK” and “cancel” don’t do anything and I’m too scared to hit “revert” without knowing what it might do. I logged out of the database to see if it would get rid of these but they didn’t go away and now I can’t get back to the database. The option “launch center” in the menu takes me to the FM menu, but clicking on the file only takes me back to these windows — I can’t log back in. 

Help?!!?!

**Comment by urapadmin** [comment]
well, that's a nasty bug and I can't tell what it is right now. But to get back into the database at all, I suggest you close filemaker. Just in case you are not familiar with it: Means, double click the ipad's home button to get into the open processes and swipe it off the screen.

**Comment by urapadmin** [comment]
please upload (don't import) that database and let me know once you have done so.

**Comment by urapadmin** [comment]
no, forget it. I can reproduce this with the current template. Don't need the upload

**Comment by urapadmin** [comment]
@lbestock: That was an effect of the strange configuration where collected material looks bound to the unit only (40-1) but is in fact bound to the invisible locus in between that does not occur in the identifier. I can prevent the error but it remains a strange thing. I still have issues recommending to leave the locus out of the identifier.

### v9.3.3
- [ ] the image should be stored correctly now
- [ ] no error message should occur and no windows should be left open (I also took care that that can't happen with other errors, but that is untestable)

**Comment by luizaogs** [comment]
Ah great, closing FM altogether worked. Thanks! Everything looks fine on my end and no more crazy windows in sight, but will this cause issues for synchronization? I don’t have time to re-do the survey but can try to save the images and notes somehow so we don’t lose it all, if you think that is likely.

**Comment by luizaogs** [comment]
Actually, nevermind. I’ll just keep this file after uploading it and if there are issues after synchronizing I’ll get the notes and images from it and transfer them to another copy.

**Comment by urapadmin** [comment]
synchronization will be fine, no need to do it again!

**Comment by lbestock** [comment]
Luiza, please test to see that the same behavior is not repeated. Can test it next time we're actually doing survey.

**Comment by luizaogs** [comment]
No frightening windows have attacked me, so it appears that this particular bug has indeed been vanquished (sorry, I don't like bugs).
