### ISSUE TITLE
pinboard to pin images at

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#709]
the idea is that wherever one sees an image one can pin it at the pinboard. The pinboard itself can be opened on all major forms to have those photos always close at hand.

**Comment by urapadmin** [comment]
### v9.3.4
First version of the pinboard includes:
- [ ] images in the gallery can be pinned
- [ ] the gallery can be filtered down to only pinned images
- [ ] images in locus photos can be pinned (both, the non-popup image and the popup image)
- [ ] the pinboard can be opened with the new button in the header of locus recording
- [ ] the pinboard has a little filter that helps finding a photo by identifier
- [ ] the pinboard can be cleared with the button

** currently only in the complete excavating form: (switch off simple excavating) ** 
- [ ] images in dayplans can be pinned (both, the non-popup image and the popup image)
- [ ] images in the locus photo list below the list of loci can be pinned (both, the non-popup image and the popup image)
- [ ] the pinboard can be opened with the new button in the header

**Comment by urapadmin** [comment]
short explanation how to use this: You find a little pushpin symbol (needle upwards) in the lower left corner of an image container. Clicking it pins the image to the pin-board. It turns green. Click it again and it gets "unpinned".
Eventually this should be possible in all image containers, but currently it is limited to the what I described above.
The gallery has a pushpin button (needle downwards) in the upper right corner that allows it to show only pinned images.
The pin-board itself blends in if you click the pushpin button (needle down) in the header. Currently only in two places (see above). It should be self-explanatory. The thing is only there to look at images. There's nothing you can do with them. But it helps to have images that you need frequently at hand without having to go back where they are stored. The pin-board filter in the gallery also helps you to attach those images to different contexts (dayplan, locus etc.) without having to do a lengthy search for them in the gallery. 
Somebody might write about how to use this productively one day in a manual.

**Comment by lbestock** [comment]
Luiza, more on pinboard testing. Check to make sure all the boxes can be ticked (including the last bit, which is not a box, where it says it should be empty if you log out and log in again.

**Comment by luizaogs** [comment]
So I'm testing this at the moment and have two technical questions: 

1. What is the locus popup image? The locus images can be linked no problem, but I'm not sure what the popup is supposed to be. Is that what you get when you click on "view"? If so that is not pinnable. 

2. How do I turn off simple excavating to test those, if that is something I can do?

**Comment by luizaogs** [comment]
@lbestock -- after today's meeting I know that I can't in fact do the stuff outside of simple excavating, so could you check the stuff that's left to check for that part? I think it all worked but we didn't try the images in the locus photos list and I still don't know what the popup is so don't know if that all works. Sorry for forgetting about this, otherwise I would've asked you to check this then.

**Comment by urapadmin** [comment]
Almost all image containers have a little button that expands them (not the filemaker go view, which does not exist in filemaker on Mac and Windows). You use the same little button if you want to add an image from the gallery. The expanded image is what we call the popover or popup image. Ah, better I make a screenshot:
This is the "not-popup" image with the popup button:
![image](https://user-images.githubusercontent.com/38838314/88220135-e3dd1680-cc62-11ea-8e7c-69ff9c0d342d.png)

And here you have the popup popped up:
![image](https://user-images.githubusercontent.com/38838314/88220252-040cd580-cc63-11ea-9d73-9af0cbb9f6cb.png)

And as you can see, both have the pin button and both should those buttons should work the same way. When testing image containers it is always important to test things in both the non-popup and the popup version.

**Comment by urapadmin** [comment]
you can:
you can always log in as user admin, password admin. 
- Now you have access to the configuration on the start page: 
- go to tab admin and there to configuration
- select "visibility" from the drop down on the upper right corner
- in the key "use_simple_excavating" type the value "yup" to switch simple excavating on or "nope" to turn it off.

**Comment by lbestock** [comment]
I just used this today for the first time in our meeting. I will leave it all to you to test, Luiza, but I did want to note that I think this is extremely useful and likely to be a big help in the field. I know I want to look at my dayplan (and section drawings when  I have made them) constantly and regardless of where I am in the system. To me this seems likely even to solve the problem behind the continued vague longing for specific links between dayplans and narratives. It has never been adequately explained what one might DO if those links existed, or why it's necessary to have them (at least while recording). I doubt that request will ever go away entirely because people (including me) just seem to feel that it should be there, without being able to say why. But the actual function of having easy access to a needed image for reference is now taken care of, and helpfully in a way that goes beyond the dayplan/narrative tab. It's great.

**Comment by luizaogs** [comment]
It is indeed great! Thank you again, Lutz.

I just put it in the back to developer category because it seems to me like the locus popup images are not pinnable in the simple excavation mode (they definitely are in the non-simple mode, or however you call this one). Lutz, I assume above where you were showing me the popup you were not in simple excavation?

**Comment by urapadmin** [comment]
yes, as you can see from the collected material tab. Difference between the two modes is that simple has no collected material and I believe no lots. And the missing pin button is a bug, a tiny one.

**Comment by urapadmin** [comment]
see #766 for switching to simple excavation mode more easily

**Comment by urapadmin** [comment]
### 9.4.2
locus photos should be fine now in both simple and full excavation mode.

**Comment by SamKimball-BrownU** [comment]
Reading this, I am sure you know this, but there is no pinboard in survey yet. That seems to be on your to-do list though. Says a lot of positive things about the feature that I was missing it so much though!

**Comment by urapadmin** [comment]
#765 solves that, Sam

**Comment by SamKimball-BrownU** [comment]
Wow I really need to start reading a bit more before I fire off a comment. Sorry.

**Comment by urapadmin** [comment]
don‘t worry it gets „unübersichtlich“ as we call it. No good english translation. I think „out of hand“ gets close.

**Comment by SamKimball-BrownU** [comment]
I believe the English idiom that comes close would be "lost in the sauce," as the kids say

**Comment by urapadmin** [comment]
like it :)

**Comment by urapadmin** [comment]
the „kids“ from whose perspective? :)

**Comment by luizaogs** [comment]
I was gonna say ... I have never used that in my life (or really heard it actually said not in jest), though I don't really know where I fit in on the "kids" scale either.

**Comment by lbestock** [comment]
I have never even heard it said in jest! But fully intend to adopt it. And probably can't pass for a kid in most contexts any longer.

**Comment by luizaogs** [comment]
I've only seen it in meme contexts, I believe (which itself reflects my place on the kid scale relative to you). I know how much you both love memes, so you should definitely use it as often as possible. In class, etc.

**Comment by urapadmin** [comment]
sometimes it strikes me as a wonder (a good one) that we all can work on a software project together.

**Comment by lbestock** [comment]
For awhile Rose wanted to join the project, and even read the packet in detail. But her biggest interest was in trying to see if she could Rick Roll you guys in a ticket.

**Comment by urapadmin** [comment]
how much?

**Comment by lbestock** [comment]
Oh very nice :)

**Comment by urapadmin** [comment]
just only for you :) What the hack is it?

**Comment by lbestock** [comment]
How intertextual can one get? Rose assured me that everyone under the horrible age of 25 would know what rick rolling is and would be mad to be rick rolled. She had to explain to me what it is (I will not tell you - a man who has never seen a meme does not care about rick rolling. But it gave me the opportunity of telling her about Rick Arschloch, and on that front she laughed.)

**Comment by luizaogs** [comment]
(I've never heard of rick rolling. Had to look it up -- my meme knowledge is clearly not up to snuff. Don't tell Rose.)

**Comment by urapadmin** [comment]
we are going all social media here on Github and there wasn't enough Riesling to keep me from reminding us that we are not using Github properly.
Having done my duty: Ha. What do those kids know of Rick Arschloch. If you have not suffered it you can't really know about it. It is a bit like "if you have not been to war ..." in former generations.

**Comment by urapadmin** [comment]
You are getting old, Luiza! That's how it starts. Later your bones start to ache.

**Comment by lbestock** [comment]
He's stuck in my heaaaaad. Like flashbacks to the war. And I don't have any Riesling to drown in.

**Comment by luizaogs** [comment]
Oh my bones already ache. As does my head, often. (I also note that I have no idea what the two of you are talking about, though I do know what Arschloch means, which I suspect places me right in between you and Rose.)

I'm sure this is the most entertainment GitHub has seen in ages -- we're doing it a favor.

**Comment by urapadmin** [comment]
well, if you must know: Look up Rick Astley (I can't spell him): He himself has quite a bone ache now, I suspect. But when I was young I had to put his records on in the disco because he was in fashion. And we (those who would rather have listened to something else) coined him Rick Arschloch.

**Comment by urapadmin** [comment]
I am ancient,

**Comment by luizaogs** [comment]
Ah, the rick roll guy. I've learned so much today.

**Comment by lbestock** [comment]
Agatha Christie once said something along the lines of "An archaeologist is a perfect partner; the older one gets the more interested he becomes."

**Comment by urapadmin** [comment]
I don't feel real interest, rather pity :o)

**Comment by urapadmin** [comment]
my god. Rick Arschloch is really connected to rick rolling and I understand only a fraction of the wikipedia article on it 

> The meme grew out from a similar bait-and-switch trick called "duckrolling" that was popular on the 4chan website in 2006.

?!?

But while those teenagers use it for their meme or prank or what not I, me myself had been there. Then! At the front!

**Comment by urapadmin** [comment]
I feel a need to repeat:

### 9.4.2
locus photos should be fine now in both simple and full excavation mode.
see also #765

**Comment by luizaogs** [comment]
I did note that update :) I have plans to test it once I can download the database again tomorrow (it's in my to-do list and everything, look at that!).

**Comment by urapadmin** [comment]
Just thought that we all might have gotten a bit lost in the sauce here, so I tried to bind it up. We are open source here! Presumably we have 1K followers.

And now I hit the sack, I am too old to stay up that late,

**Comment by luizaogs** [comment]
....people can see these?! Ha ha ha. Now I understand your constant reminders about using GitHub correctly. Woops.

**Comment by luizaogs** [comment]
So I'm in 9.4.3 and locus popup images are not pinnable in either simple or regular excavation modes, in fact. This is the second 9.4.2 update that doesn't seem to have come through for me (other is ticket #764).

**Comment by urapadmin** [comment]
this thread got longish :o) 
Are we talking about locus photos in the locus form (which is not affected by the simple / full excavation) or the locus photos below the locus list on the excavation form (which is affected by simple / full excavation)? The locus form has an orange header, the excavation forms have a green header.

**Comment by luizaogs** [comment]
Hoho good to know that there's a difference. 

Locus photos below the locus list on the green excavation form: images are pinnable both in regular and popup forms in simple and full excavations.
Locus photos in the orange locus form: not pinnable in popup, pinnable in non-popup.

**Comment by urapadmin** [comment]
### 9.4.4
fixed.
