### ISSUE TITLE
blank image in file repository (not broken) 

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#711]
I have just synchronized PVD, which is currently running kiosk 0.8.4 and has had the latest rollout of Filemaker 8.3.3 delivered to some people. But the two workstations just in from the field had 8.3.2 on them and one had had the entry of a bunch of images that caught the bug #708. After syncrhonization, one of the images thus uploaded appears in the File Repository to be blank. It isn't the broken image icon I'm used to, just blank and cannot be clicked upon. 

![image](https://user-images.githubusercontent.com/49291909/87256736-51b76000-c463-11ea-95f4-1b3cee7f20ce.png)

The synchronization log did have an INFO line I cannot make sense of:

![image](https://user-images.githubusercontent.com/49291909/87256775-7ca1b400-c463-11ea-9b15-772a4e568c2a.png)

**Comment by urapadmin** [comment]
In fact, I suspect that is just one of those hiccups. Beset not answering a request. I see that icon. 
The synchronization message is something I should attempt to, but it is not critical. More interesting is that the is a locus relation that makes problems. I will the whole log before it get lost in the sea of logs ...
But nothing in here is critical. We have 7 broken Luiza images (tag: BROKEN_IMAGE), but I suspect those are the ones from yesterday.

**Comment by urapadmin** [comment]
[MCP_5196_urap_Sun_120720-1738.log](https://github.com/urapadmin/kiosk/files/4909620/MCP_5196_urap_Sun_120720-1738.log)

**Comment by urapadmin** [comment]
this one here is just about the blank image and that is a hiccup. Nothing I can really do about it, currently. I have seen holes elsewhere in the imagery. They usually fill if one repeats the fetch.

**Comment by urapadmin** [comment]
@lbestock: unless you can produce evidence that it is always the same image I would close this particular hiccup as it is covered in other tickets.
