### ISSUE TITLE
request to be able to make QR code photoboard for tags

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#715]
Not needed until there is an actual field season! But this would be helpful. The context of the request: 
I am writing about Unit FI, in which we cut a sondage. By definition a sondage has multiple loci in it. My most useful tags are sondage tags and I am using them all the time in analysis. Currently I was just pulling my hair out that I do not have a good final photograph to publish of FI Sondage 1 that shows the stratigraphy, which would illustrate a point in the article. But in fact I do have such photographs, with QR code boards in no less, it's just that they're dayplans, so they don't pop up in tag analysis, because

oh wait, this is a bigger issue

For tags to get QR codes they would have to be contexts themselves. So the answer here would have been to go in and use the gallery to put the image in at least one of the relevant loci? 

This started as a request and has turned into a needs discussion. Putting Sam on it too because it's not clear if this will or should get a database solution or an instructions to users solution.

**Comment by urapadmin** [comment]
that is not possible. Tags don't store images. So I would not know where to put the image. You either would have to make Sondages something else than a tag (a new type of unit?!?) or we wait until we have a somewhat more flexible tag system that can include more than just loci. But the image would still be bound to either a unit or a locus and that is what the qr-code addresses.

**Comment by lbestock** [comment]
The user way to get around this, which was sometimes but not always done in the last Uronarti season (before this was thought about and thus must qualify as basically intuitive or at least teachable), would be to use the QR board for A PARTICULAR locus, that itself is tagged as belonging to the sondage (or whatever). And/or to add a description and/or context to the photo after import if no QR code is used. I tend not to remember if I should be searching tag or description in the file repository and thus usually search them both to find what I am looking for.
