### ISSUE TITLE
Opened up three different windows of file identifier cache while I was inputting data. 

### ISSUE THREAD

**Issue by nvd2** [urapadmin/kiosk#717]
When I was working on the database it opened up three different windows of the file identifier cache and didn't let me do anything until I hit revert. I'm not sure what I clicked, but all the data I inputted is still there. 
![image](https://user-images.githubusercontent.com/67655037/87334444-a531b880-c50c-11ea-92db-935f7ccf0ab5.png)

**Comment by urapadmin** [comment]
please add the "filemaker" label in future. Apart from that: This issue has been fixed already, see #708.

**Comment by lbestock** [comment]
Nuri, this one is yours to test in the next round of survey recording. Once you've determined that following the same steps as led to your ticket do not any longer lead to the same problem, please close the ticket.
