### ISSUE TITLE
"help button" for instructions on how to structure text nowhere to be found?

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#718]
Interpretation text boxes both in excavation units (in context interpretations) and in survey units (both in overall unit interpretation and interpretations for different features) include the following text: "use the help button for instructions on how to structure text in this field" 

The help button with said instructions is nowhere to be found, unless I just don't know where it is -- in which case I guess Sam should be added to the ticket and the users manual should be tagged?

**Comment by urapadmin** [comment]
@lbestock 
That's a configuation issue. Such buttons do not show if there is no help text. Which I suspect is the case -> Laurel.

**Comment by lbestock** [comment]
Correct, there was none. I have now written one so you can see that it appears after the next round of synchronization.

**Comment by urapadmin** [comment]
since when do we close things before they have been verified?
