### ISSUE TITLE
misspelling in "feature type" options field

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#719]
Welcome to Luiza's picky notes.

In the options for feature type we have "cemetary" instead of "cemetery." Also "e.G." and I don't know if that is purposeful? I'm accustomed to seeing "e.g." but that one is even more minor than the cemetery one.  

(I tagged it as small because to me it seems like it would be a small change, but don't know really.)

**Comment by urapadmin** [comment]
I like Luiza's picky notes. The e.G. shows you that a German must have been in play. We write "z.B." :o)
It is indeed small but you don't need to worry about that label. I use it for myself for days when I feel like tackling small things.

**Comment by luizaogs** [comment]
Ahh I should have known. German capitalization. My bad German becomes worse German very quickly.

**Comment by urapadmin** [comment]
### 9.4.1
but: you won‘t see the fix because it has to be changed in configuration as well under valuelists/valuelist_feature_type. I add Laurel.

**Comment by urapadmin** [comment]
Laurel, I could patch this so that the config key gets updated on all projects but that would override feature types that might have been changed or added on these projects. Do you think anybody ever did that?

**Comment by lbestock** [comment]
The risk is there - it's been a point of discussion. I have changed it in the configuration. I have also, of course,  added tree and stream as feature types.
