### ISSUE TITLE
trowel icon missing in PVD trench layout

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#721]
The unit page, where all the information such as site, trench, etc lines the top above description and purpose, lacks the trowel icon showing that it is an excavation unit:

![image](https://user-images.githubusercontent.com/49291909/87427567-fa260b00-c5ae-11ea-8598-a162a3668337.png)

Feature units and survey units have the appropriate icon there.

9.4, being viewed on ldbmac while Laurel does the director thing.

**Comment by urapadmin** [comment]
### 9.4.1
fixed

**Comment by SamKimball-BrownU** [comment]
Resolved. I wish all tickets were this easy to test. I tested both simple and non-simple.
