### ISSUE TITLE
show identification methods of the default settings when creating a unit

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#723]
When one has set configuration so that identification methods can be boutique adapted during unit creation, the boxes for ID methods are blank when creating a unit even though there are defaults applied. This makes them look like boxes one should fill in, and I've just seen this trip Nuri up - he should have left it blank, but input an incorrect ID method for context:

![image](https://user-images.githubusercontent.com/49291909/87441191-d79ced80-c5c0-11ea-9f8e-27f9749bb06c.png)

It reminds me that even before this I have wished that those boxes were filled in already automatically so that, when creating a unit, one could see what the default is, what one would be changing FROM if one selected a different ID method.

**Comment by urapadmin** [comment]
not as trivial as it seems. I think we should rather think about hiding this from normal users and leave it to admins (or registrars, but you have decided to make more or less everybody a registrar).

**Comment by lbestock** [comment]
And I have decided to configure it as invisible for PVD2020 after the team meeting when I use it to explain to Nuri why he got the numbers he got. A quick short lesson for me in why Leslie's approach isn't always wrong.

**Comment by urapadmin** [comment]
I really think we can leave it at that
