### ISSUE TITLE
extra fields visible in survey unit: grab that should be reserved for survey unit: transects

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#724]
Three fields that are exclusively relevant to transect walking have migrated onto the grab survey page:

![image](https://user-images.githubusercontent.com/49291909/87444058-4af42e80-c5c4-11ea-946c-5933c5bd5ccf.png)

Bearing, visibility, and spacing did not used to be there I think (I'm looking at an old URAP 8.9.3 and they are not there).

**Comment by urapadmin** [comment]
### 9.4.1
it has been the case before but I changed it now.

**Comment by nvd2** [comment]
The irrelevant fields are no longer visible.
