### ISSUE TITLE
features tab turns blue in survey unit only when "interpretation" is selected

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#726]
V9.4 PVD2020 on ldbmac. When clicking through people's survey units to see what they had done, I noticed that the "features" tab turns blue when the "interpretation" tab is selected but not when any other tabs are selected. 

![image](https://user-images.githubusercontent.com/49291909/87444479-d8378300-c5c4-11ea-802e-ed52534bef58.png)

![image](https://user-images.githubusercontent.com/49291909/87444547-eb4a5300-c5c4-11ea-9b94-e9b952dde2e4.png)

And when I noticed it was blue at first I didn't realize it was only when one other tab was clicked and I thought it meant that there were features associated with this survey unit. And I thought that was cool and helpful and I was on the point of making a request out of it, once I figured that was not the case, but the utility of that would be in a director checking up on things (as I am doing) and not for the recording person herself, so nevermind, it's a director view thing.

**Comment by urapadmin** [comment]
the colors should be the same colors the recording forms of that type of data have. collected material is blue, loci orange, features light greenish. see color coding in https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:color_codes&s[]=colors

I just found that the cm tab in locus recording isn't blue but should.

**Comment by urapadmin** [comment]
### v 9.4.1
fixed

**Comment by SamKimball-BrownU** [comment]
Seems to be working in every form, both in simple and non-simple excavating.
