### ISSUE TITLE
small finds tab dilemmas -- visible to all? just to registrar?

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#729]
Let's start with my confusion: when making small finds records, I was super confused for a while and kept writing the object descriptions in the small finds tab and saying something like "description in small find description box" in the collected material record itself. Last night I randomly realized that the tabs are supposed to be used by different people at different times, and so that I should really only be filling out the actual collected material tab and leaving the other one for the registrar. 

Which brings me to questions: should the small finds tab be visible to everyone during excavation, or just the registrar? If the former, I think at the very least it is something that needs to be included in the user manual and it might even be worth adding a note of some sort in the small finds tab alerting the excavator that the registrar should be the one filling that out?

**Comment by urapadmin** [comment]
it should be visible since all users want to read the data of already entered small finds. 
Whether or not users have to be registrars to actually enter data in the tab is a different question.
My opinion is that we should stick with our rather open approach and not hide or control things via privileges. I always think educating our users is better than controlling them.

**Comment by lbestock** [comment]
Right now the help text for small finds description is an info button. If it were the in-field type then it would be easy for me to alert field people that they should not fill it in, but in any case the users manual.

**Comment by urapadmin** [comment]
because nobody ever clicks on a help button

**Comment by lbestock** [comment]
because nobody ever thinks they need help

**Comment by luizaogs** [comment]
Wait, is there currently a help button? Because trust me, I looked. Did not find one. 
(I always think I need help.)

**Comment by lbestock** [comment]
There wasn't at the time because I hadn't written a help text. But it's there now for after the next synchronization.

(And OK I take it back, no one BUT LUIZA ever thinks they need help and generally everybody, including Luiza, is wrong.)

**Comment by luizaogs** [comment]
Hmm we'll agree to disagree on the Luiza-needing-help front. 

And ok good! I think the in-text one is more attention grabbing for sure, but if there is a reason why the help button is preferred in this case I think that + the users manual should suffice.

**Comment by SamKimball-BrownU** [comment]
Related question for Prof. Beefstock: How many small finds would there typically be? Not many, I'd imagine. It seems like the type of thing that someone wouldn't do lightly in the field. If that's the case, I certainly think that a user manual type solution is completely sufficient.

**Comment by urapadmin** [comment]
I don't tend to be wrong.

**Comment by lbestock** [comment]
Some days don't have small finds at all. Some days you are overwhelmed by them. One day in Abydos I found 288 First Dynasty seal impressions in one locus and wrote tags until my hands were sore and was late to dinner.

**Comment by lbestock** [comment]
But yes, it is not done lightly and is one of those things like "do you see the end of this locus where I see the end of this locus?" that is a regular matter of discussion with the director before assigning the designation.

**Comment by urapadmin** [comment]
well, there is nothing to do for me here, so I change this to discussion.
