### ISSUE TITLE
synchronization confusion

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#730]
Syncrhonization just happened at light speed and returned a report that it had had nothing to do. But it most certainly had, and it did it, too.

PVD2020 kiosk 0.8.6, 14 VII 20 at 4:19ish pm. 

Having just made a bunch of configuration and value list changes during a team meeting, I closed FM, uploaded, and imported. Then I synchronized, and it was strangely fast. I scrolled through the report and there were no warnings or anything, just a line saying that there had been nothing to synchronize. It was a bit scary. I then prepared and downloaded again and it looks like everything IS in there, so I am now quite confused.

I caught a screen of the process manager just before a line disappeared:
![image](https://user-images.githubusercontent.com/49291909/87473388-53ae2a00-c5ef-11ea-80af-4a9aa7174e89.png)

**Comment by urapadmin** [comment]
totally ok. It said that there were no files to synchronize, means no images or some such:
```
********** Synchronizing files **********
>[8728/8324: synchronization.WARNING at 2020-07-14 16:16:44,657]: Synchronization.synchronize_files_v2: Synchronization.synchronize_files: Nothing to do, for there are no files to synchronize.
```
