### ISSUE TITLE
unable to open some downloaded images

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#732]
14 VII 20, kiosk 0.8.6, PVD2020

During team meeting I was showing how to search and use the file repository. I opened an image and downloaded it, but it would not open. After the meeting I have been poking around to see if that was repeatable and I have found that it is, and that there are other images I also cannot open after downloading, but I am not able to see a pattern in terms of where the images are or what the filenames are.

![image](https://user-images.githubusercontent.com/49291909/87476303-244dec00-c5f4-11ea-93ad-085fdc308f6f.png)

I used the above sort as practice.
1st image downloads and opens in Photoshop no problem.
2nd image ditto.
3rd image ditto.
4th image ditto.
5th image ditto.
6th image downloads, and I try to open it the same way as the previous ones, and I get this:
![image](https://user-images.githubusercontent.com/49291909/87476561-932b4500-c5f4-11ea-99bc-cd2a48bf228a.png)
7th image same as the sixth. It looks fine in the repository:
![image](https://user-images.githubusercontent.com/49291909/87476622-b229d700-c5f4-11ea-90d5-1ce7a58167f6.png)
But will not open in photoshop. This was the original image I had trouble with. Its name is now 20 (9).jpg but it had just as much difficulty when it was 20.jpg.
Last image, same problem.

You can see in my downloads that they downloaded just fine and have appropriate sizes, and their names really are the same and I cannot understand why Photoshop thinks they have a jpg problem. Next will be to try a different image software to open them.

![image](https://user-images.githubusercontent.com/49291909/87476826-092fac00-c5f5-11ea-9d66-8bf476559ebe.png)

**Comment by lbestock** [comment]
Firefox thinks it has errors, too:
![image](https://user-images.githubusercontent.com/49291909/87477080-80fdd680-c5f5-11ea-90e9-5a7aaae44fee.png)

Preview has no problem and opens it fine:
![image](https://user-images.githubusercontent.com/49291909/87477138-9ffc6880-c5f5-11ea-9183-254f47a87833.png)

Illustrator hates it (but no surprise if Photoshop did):
![image](https://user-images.githubusercontent.com/49291909/87477228-c7ebcc00-c5f5-11ea-8585-15846a8da1b4.png)

Safari refuses.

So only Preview will open this file that everyone else thinks is broken and I have HEIC memories that might be related? But I can't figure out why these photos would be different from the others in this search. Device, context, orientation, nothing seems consistent to divide the working from the not working ones.

**Comment by urapadmin** [comment]
well, see for yourself:
![image](https://user-images.githubusercontent.com/38838314/87479553-000e0180-c62c-11ea-9e24-d80494ac9314.png)
It is so funny that Photoshop on a Mac can't deal with those HEICs. I have no trouble with any of the images on Windows (with HEIC extensions installed). In fact when you download an image it is the raw file that once entered the system. The system never manipulates the original. I would say Nuri is producing HEICs.

**Comment by urapadmin** [comment]
**It's a photoshop bug.** Ha ha. You should tell Adobe!

**Comment by lbestock** [comment]
Ugh and Nuri's got the black iPad which has been to Uronarti and should have been set to avoid this! Well, at least it's a known problem. Last thing is to get Nuri on this thread and ask: Nuri, did you make some of these images from within Filemaker, and make some with the iPad camera and then add them from the photos folder? And then Lutz, what does he do to make it so the iPad is set properly to take jpgs?

**Comment by urapadmin** [comment]
First of all: Those images are ok. Only your Photoshop sucks. Adobe sucks. They have always done so. They are worse even than Apple. All they can do is infest people's computers with Createive Cloud schrott. Affinity Photo e.g. has no issue opening these images, e.G. Even Windows Paint can do it. 

According to the wiki you should always use filemaker to access the camera and NOT import photos from the camera roll. In that case it is even better to have HEICs activated. I am not even sure if one still can deactivate them.

**Comment by urapadmin** [comment]
can you please try to rename one of those jpg files you cannot open in Photosh**  to .heic? I wonder if the extension has any meaning in it all. It should not on a Mac, but shoulds ...

**Comment by lbestock** [comment]
HA HA HA HA. Totally works. It changes the default program to open it in Preview first. But if I tell it to use photoshop, wham, open, no problem.

**Comment by urapadmin** [comment]
ja, there is really not much left to say about Adobe. And I have the feeling that Github is already pointing to their Community Guidelines down there because I already ranted too much. 
Filemaker also sucks (sorry Github) in spitting out something called .jpg although it should be .heic. That is why it is called jpg in the first place. Well, the workaround could at least be mentioned in the users manual. It can very well happen to others, too.
