### ISSUE TITLE
feature should have HEIGHT (m) instead of elevation (m)

### ISSUE THREAD

**Issue by myjaylee1123** [urapadmin/kiosk#734]
![IMG_0332](https://user-images.githubusercontent.com/47072505/87564482-72173280-c68e-11ea-8ca4-4311c9b524fe.PNG)
When putting in a feature, it asks for width, length, and elevation, but elevation should be height.

**Comment by lbestock** [comment]
Great you're making a ticket and I had forgotten this issue indeed in the chaos after our very rich meeting. I'm changing it from kiosk to filemaker (as you encountered it with the recording system, not in the browser) and removing the project - "needs triage" is where Lutz puts tickets after he has fixed them so we can make sure it's really fixed. Takes some getting used to which can only happen through doing.

**Comment by urapadmin** [comment]
we decided to add height rather than replace elevation with it.

**Comment by urapadmin** [comment]
### recording 9.3.1 but also kiosk 0.8.8

**Comment by myjaylee1123** [comment]
![IMG_0346](https://user-images.githubusercontent.com/47072505/88483495-4b7eb480-cf36-11ea-8597-2fe700b4d749.PNG)

While there is both the elevation and height parameter, they appear to be linked. Changing one changes the other. They should be separate parameters.

**Comment by urapadmin** [comment]
### 9.4.4
pretty dumb error. Now fixed.

**Comment by myjaylee1123** [comment]
no longer has this issue!
