### ISSUE TITLE
extra box in checklist feature recording materials with strange behavior

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#737]
In PVD2020 9.4, viewed here on ldbmac.

We created a new material type by configuring the valuelist for this project, since concrete wasn't on there.

In looking at the layout of this to see if it still more or less fit, I noticed an extra checkbox without a term beside it on the upper right, between materials and coordinates. Clicking on it popped up a box with the two checked terms in it:

![image](https://user-images.githubusercontent.com/49291909/87596810-bc180c80-c6be-11ea-8c9a-aed231c1bb07.png)

If I change the checked terms, the terms returned by clicking that box also change. It just shouldn't be there is all. I checked the valuelist to see if perhaps there was a blank line causing havoc, but no such thing.

**Comment by urapadmin** [comment]
### 9.4.1
It has always been like that. The empty checkbox is the "other" checkbox that allows you to add something to the list of checked items. That you see all the checked items is just how filemaker handles such things - nothing I could do about it. 
I have extended the size of that list (it can get longer now if there is space) and I have switched the "other" option off.

**Comment by nvd2** [comment]
The extra box is no longer there and the "other" option is also gone.
