### ISSUE TITLE
viewing of signature sketches in context relations is somewhat glitchy

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#738]
When viewing a sketch done using the signature function in the context relations tab: 

I clicked on "view" to zoom in, as one does, and got this as expected: 

![image](https://user-images.githubusercontent.com/67970402/87686337-c4258a00-c75a-11ea-81d2-0b0cf915864d.png)

Unfortunately, the sketch extends high up on the screen and so a part of it is under the banner with the "Done" button, as you can see in the above screenshot. 

When trying to click on the image to get rid of the banner and be able to see the whole thing, the screen goes black (not attaching a screenshot of that here because, well, you can imagine it). Clicking on it again brings the sketch back as normal, but I still can't see the whole thing unless I hold my finger down on the screen and move it around like a maniac (while moving around it is visible). 

This doesn't strike me as a bug per se (though who am I to know), but I wonder if there is a way around it? I would imagine that some sketches do fill up much of the screen and would be difficult to see well enough in the small icon visible in the general relations tab, so this might be problematic if one is trying to look at a specific relation while in the field.

This is context PBA-005, in case you want to look at it yourself.

(Also, clicking on the image to get rid of the "Done" upper bar works fine on regular photographs, at least from what I've tested in the relations tab itself.)

**Comment by urapadmin** [comment]
I don't have access to that part of filemaker. That is a filemaker glitch. Your alternative is using the popup of the image.

**Comment by luizaogs** [comment]
The popup works fine, so closing this one.
