### ISSUE TITLE
dayplan/narrative link issue(s)

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#739]
Let me start with a caveat that I have absolutely no idea what I'm even trying to do with this dayplan/narrative linking situation. But I was trying to use the paper clip to link two records and instead seem to have linked two of the dayplans? At least, the top two now have a little red line there and I am not sure how that happened:

![image](https://user-images.githubusercontent.com/67970402/87693429-57fb5400-c763-11ea-8794-99c796c29161.png)

I don't see a link between them and a narrative, but I don't know if there should be a visible link in the first place. I know I pressed the paper clip several times (I have no idea how many, and at first it seemed to have failed to do anything at all). As you can see in the screenshot, the paper clip is currently selected. If I press it again, the little red line goes away: 

![image](https://user-images.githubusercontent.com/67970402/87693513-73fef580-c763-11ea-90be-db06e979750b.png)

I remain none the wiser about how to actually do it correctly, of course. I was planning to go in the Playground and play around to see if I can somehow recreate this, but if there are better suggestions I am all ears.

**Comment by luizaogs** [comment]
OH WAIT. Excitingly if I scroll down and THEN press the paper clip the narratives scroll up to the top one, so they are linked it seems. But I still don't know how I did it, and especially not how I linked the two dayplans themselves.

**Comment by luizaogs** [comment]
*** This is mostly for me so I don't lose track of what I'm doing. Ignore it for now.

Ok, now in Playground, I have figured out a few more things (including some weird ones): 

- The images seem to always link to the first narrative, regardless of what narrative is on the screen when I hit the paper clip. Which I guess makes sense if it does this chronologically -- I don't know if being able to link to older narratives would be feasible or of interest? 

- Also, once I put in another image, even if I had a previous link between dayplan and narrative, the new image automatically links as well? How does one keep only the first image linked? You need to track when you click on the paper clip, it seems. Also, the new link overrides the old link. This is all when the red line is there.

- The red line then disappeared (I don't understand why at all, will go back to try and see if I can trace its appearance and disappearance). Interestingly, though, when the red line wasn't showing up and I added another dayplan, the two dayplans -- that weren't themselves linked -- could be linked to the same narrative. 

- The red line then appeared after I added a new narrative and pressed on the top dayplan and then on the paper clip -- now they're ALL connected, and any links that had been made between older narratives and dayplans were gone -- now they are all linked to the top narrative only. And this remains the case whether I click on the first dayplan or the last:

![image](https://user-images.githubusercontent.com/67970402/87702252-8da63a00-c76f-11ea-8d5a-fc7fcbaecda5.png)

An immediate thought is that, barring the fact that I clearly don't know how to use this, it would be helpful to have a visual record of the link on the narrative and the dayplan so one can see what links exist without having to go around messing with the paper clip blindly?

**Comment by luizaogs** [comment]
*** ... still talking to myself.

- Hm. Linked dayplan to a narrative, great, worked fine. But then I added a second narrative and another dayplan and tried linking that. Red line showed up and the link of the first dayplan to the previous narrative disappeared -- both now linked to the top narrative. 

- But then I added another dayplan without also adding a new narrative and got no red line, but the dayplan is still linked to that first narrative as well: 

![image](https://user-images.githubusercontent.com/67970402/87704277-8d5b6e00-c772-11ea-9010-53fb9a273781.png)

- What happens if I add another dayplan and no new narrative? Ok, that's still fine -- not linked to any of the previous dayplans, linked to first narrative: 

![image](https://user-images.githubusercontent.com/67970402/87704503-df03f880-c772-11ea-944e-f3916236d0d8.png)

- What happens if I add another narrative and then another dayplan? Aha! That linked ALL of the previous dayplans. Why?! And now they are ALL linked to the first narrative: 

![image](https://user-images.githubusercontent.com/67970402/87704787-491c9d80-c773-11ea-9232-fbaf9addc237.png)

- What happens if I keep the paperclip selected and then add another dayplan? Hm. Nothing, nothing happened. It was up there without a red line, just like the previous dayplan. Interesting. Ah wait, but then I added a new narrative and now they are all linked. To that new narrative: 

![image](https://user-images.githubusercontent.com/67970402/87705035-aca6cb00-c773-11ea-800f-b3e8a4a3729f.png)

- Adding a new dayplan without a new narrative lets me keep it unlinked from the previous ones, but linked to the first narrative: 

![image](https://user-images.githubusercontent.com/67970402/87705358-2ccd3080-c774-11ea-91c9-7497d0c0352c.png)

- And then if I then add a new narrative, without having the paper clip selected? Yup, lord jesus, now they're all connected: 

![image](https://user-images.githubusercontent.com/67970402/87705532-6867fa80-c774-11ea-96c5-b3dee64c676c.png)

- What if I add the new image, then the new narrative with the paper clip selected? Any difference? Nah. Same confusion.

Is one able to unlink things?

**Comment by luizaogs** [comment]
Alright, Lutz, you can look now. A bit messy but I hope it takes you through what seems to be the issue -- when a new dayplan is added it at first looks fine, but then if one adds a new narrative all the dayplans are then linked to that first narrative (put simply -- the steps above should show you some of the more specific issues). 

A couple of more general thoughts/questions: 
1. Barring the fact that I clearly don't know how to use this, it would be helpful to have a visual record of the link on the narrative and the dayplan so one can see what links exist without having to go around messing with the paper clip blindly, I think. 
2. The images seem to always link to the first narrative, regardless of what narrative is on the screen when I hit the paper clip. Which I guess makes sense if it does this chronologically -- I don't know if being able to link to older narratives would be feasible or of interest?
3. Is one able to unlink things?

**Comment by urapadmin** [comment]
well, I think it is a bit difficult to test something without an idea what it is and how it should work. And in fact that explains most of the headaches. This linking feature is pretty special, not intuitive and needs a lot of explanation. We are still not convinced that it would be useful in a real scenario. The idea was to link the dayplans to the narratives without linking them too tightly. Otherwise I would have just really linked dayplans with narratives and the user interface would just look differently. 
But Laurel wanted to see all of the dayplans in general but also have an idea what dayplans were the ones the author of a narrative was using when writing the narrative. 
And this is how it works:

1. The dayplans react to narratives and not vice versa. So a change will only be visible if you select a different narrative (by putting the cursor into it or some such).
2. the red marker marks all images from the same day as the narrative.

That's it. I must confess that I have not read your whole experiment because you were trying to control the linking and that is not what this does. It just gives you a visual hint which of the dayplans are from the same day as the narrative based entirely on the automatically created timestamps of those dayplans. You cannot manipulate what links together. Makes it hard to test, because you need several days. That's why it is good to test it in a scenario test but with a defined set of expectations :o)

We can then discuss whether or not this is useful and if we can imagine ways to make it more useful (bearing in mind that the recording system is not the right place for analysis)

**Comment by luizaogs** [comment]
Ha yes well Laurel told me to test it without knowing what I was doing. But she did ask us to link two specific dayplans to two different narratives, and if one can't control the linking then that can't be done, no?

**Comment by urapadmin** [comment]
That was just not one of Laurel's better ideas. Some features (hey) are a bit too special to just let users loose on them. And the idea that everything should be intuitive is, well, romantic.

**Comment by urapadmin** [comment]
but at least you made me write down what it actually does (and believe me, I had to look it up in the code). And we could add the user-manual label. And then your efforts were not entirely in vain.

**Comment by luizaogs** [comment]
Yes, I did look for directions yesterday before deciding to look like a crazy person on here :) I'm still a bit confused about its purpose and how it works. At this point I have 16 dayplans and 15 narratives so can see that they are indeed linked to the narratives by day, at least.

**Comment by luizaogs** [comment]
Now that I know how it works -- if one scrolls down and clicks on narratives from separate days that indeed highlights the relevant narratives from that day, but scrolling up seems to confuse it and things don't always get highlighted (though the dayplans do seem to scroll up alongside the narratives). You should probably just download the database once it's in and see if it's working as it should because I am still confused!

**Comment by urapadmin** [comment]
The feature goes way back to 2017:
[](https://www.meritaten.net/urapdev/doku.php?id=ldb_and_cmk_observations_on_using_the_database#database_musings_30_june_2017

Tell me about your confusion. The purpose is really rather for analysis when Laurel and Christian read through the narratives and can't see anymore (months after the excavation) which of the images were the ones the excavator who recorded the narrative had in mind. Often narratives refer to current dayplans - but where in the list of 100 dayplan images (we overuse the dayplan section massively) are the ones the recorder was looking at while writing? Usually it would have been the most recent set of images that were available to her on that day.

**Comment by urapadmin** [comment]
in which case I would rather move it to Laurel. Because testing if it does what I instructed it to do is one thing, testing if it serves the original purpose is another. Also developers are the worst testers of their own code.

**Comment by luizaogs** [comment]
I see. But with the dates we now have on the photographs (I guess that might have been added later?) the link between daily narratives and dayplan from that day is there, no? 

Now that I realize that the red line identifies stuff from the same day I think that is indeed useful, but in my mind it might also be useful to have something visual if a link is desired between a specific dayplan and a specific narrative? Rather than just stuff from the same day. Don't know.

**Comment by urapadmin** [comment]
Laurel, where are we with this?

**Comment by urapadmin** [comment]
I intend to close this. As far as I see it works as intended. Whether or not the intention is something that we find actually useful has not been clarified. But that is not for v1 anyhow.
@lbestock, @luizaogs : You are invited to test it a last time to make sure it does kinda work and then close this here. Or just close this here.

**Comment by luizaogs** [comment]
I checked again and it works (wow, this is a crazy ticket. Apologies). It doesn't do what Laurel wanted it to do for the test scenario but since that wouldn't be for v1 (and I expect that that would be a new ticket?) I'll close this.
