### ISSUE TITLE
deleting a unit as a last means of correcting something might be necessary

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#742]
it has to delete the unit and the loci and the collected material and everything that is related to it. Not trivial.

**Comment by urapadmin** [comment]
### recording v9.6
This is pretty dangerous since it really eradicates all those records (except images). 
- [ ] only the administrator can do it (logged in to the app as admin)
- [ ] it shows all the related records and asks twice whether the deletion should really be done

**Comment by urapadmin** [comment]
we do it for loci, too -> #932

**Comment by luizaogs** [comment]
I tested the first bit but can't do the rest without the admin password. But a question: as soon as I delete the unit the screen goes straight to another unit in the menu, which threw me off a bit. Is that how it should be, or would you want it to go to the home page instead?

**Comment by luizaogs** [comment]
That's not true, I know the admin password. But the question above stands.

**Comment by luizaogs** [comment]
Last thing (sorry, I am scattered) -- should it delete automatically if it has a dayplan? Because it gave me no warnings as admin. The delete button is not visible to me as a regular user if a dayplan exists, however.

**Comment by urapadmin** [comment]
> 
> 
> I tested the first bit but can't do the rest without the admin password. But a question: as soon as I delete the unit the screen goes straight to another unit in the menu, which threw me off a bit. Is that how it should be, or would you want it to go to the home page instead, if that is even possible?

The unit configuration, even though you often enter it with the unit selected on the start page, is for all units. You can at any point use the arrow buttons and switch the record. So when deleting a unit you just end up with the next in line. 

If it puzzled you, I can nonetheless return to the start page after deleting a unit. That way I should also make sure that the once selected and now deleted unit is no longer selected on the start page.

**Comment by urapadmin** [comment]
> 
> 
> That's not true, I know the admin password. But the question above stands, and becomes weirder -- I deleted a Playground unit (LA test) with an associated context record, which worked as you said it would. But then the menu screen went straight to a Providence unit (LA), so it jumped between sites.
> 
> I just tried with another one and it stayed in Playground this time so not sure what is up.

that should not happen, indeed.

**Comment by urapadmin** [comment]
> 
> 
> Last thing (sorry, I am scattered) -- a unit with only a dayplan was deleted with no warnings by me as admin, so I leave the last box unchecked for now. The delete button is not visible to me as a regular user if a dayplan exists, however.

Indeed, I did not check for dayplans. So this is what I check now: dayplans, unit narrative, loci, locus relations, collected material, small finds, ceramics.
