### ISSUE TITLE
should locus relations images carry over to the other locus automatically? 

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#743]
More a question than an issue. If the relation between two loci appears automatically in the other locus when one establishes that relation in one of them, should the photograph/sketch associated with that relation (if there is one) carry over as well? I thought at first they had been, but now I can't remember if I made that up and they are currently definitely not carrying over.

I don't know if there would be a reason not to carry them over, or if this has been discussed already -- to me it seems like it might be helpful. And then if one needed to add a different image one could replace it then?

Also, this just came to mind -- would it be useful to be able to illustrate the same relation with more than one image? I see that one can't add the same relation between the same loci more than once (which makes sense), but what if more than one image, or different types of images, are needed to illustrate it?

**Comment by urapadmin** [comment]
The images must carry over, you did not make that up.

As for several images per relation. That would not not make the UI simpler and it would make the code behind the image (carrying over to the opposite relation) baroque. I would veto it as long as I could.

**Comment by luizaogs** [comment]
Yeah so some are carrying over and some are not: those inserted from the iPad's photos do carry over, but ones taken inside Filemaker do not.

Now that I'm thinking about it I think this happened last time I was excavating as well but I forgot to open a ticket because I wasn't sure what was going on. Well, here it is now...

**Comment by urapadmin** [comment]
you use an ipad here, right? What filemaker Go version is on it? And with ipad's photos you mean that you inserted images from the camera roll instead of taking them in situ?

**Comment by luizaogs** [comment]
Version 18.0.3.325.

And yes for the camera roll (mostly Touchdraw sketches in this case).

**Comment by urapadmin** [comment]
confirmed. 
1. Happens only if the image is created for the first time: It does not happen, though, if a formerly not transported image gets replaced. Then the so far missing other side is updated correctly.
2. does not matter if camera or camera roll the difference is 1.
3. if inserted from the gallery everything is fine
4. no difference between normal and popover container
5. only on ios
6. still exists in FMgo 19

**Comment by urapadmin** [comment]
save_image: enter for img
current_locus_relations_on_modify_image (start): Sketch missing: 0/1
current_locus_relations_on_modify_image: calling add_locus_relation_to_cache
current_locus_relations_on_modify_image: Sketch missing: 0/1
add_locus_relation_to_cache: single image with param OnObjectModify, $$cache_done=0
is_cache_update_needed: image is there in OnObjectModify but record is not-> DONT process cache
add_locus_photo_to_cache: doing nothing.
image_validate: field img
add_locus_relation_to_cache: single image with param , $$cache_done=0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
current_locus_relations_on_modify_image (start): Sketch missing: 0/0

**Comment by urapadmin** [comment]
The difference is whether there is already a locus relation or not. Only a second one produces the issue. The first one always works.

**Comment by urapadmin** [comment]
This part of the recording is a nightmare. I feel I have fixed about 1000 "bugs" here. Mostly filemaker bugs. 
### fixed 9.4.7
@SamKimball-BrownU: This image container needs a thorough image container testing again. And note that this error only occured with a second record in list of relations. So that needs to be added (if it isn't already in there) to the testing method: Always test everything with the first record first and the again with a second or third record. Please open a new ticket for the image container test.

The particular issue here should be resolved and if so, this ticket can be closed.
