### ISSUE TITLE
Tiny text in dayplans

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#747]
On iPad, pvd. I went to enter the description for a dayplan, and then the screen zoomed into that field. I typed the description and then zoomed out, and the text is tiny. See screenshots (if I can figure out how to attach them from iPad)

**Comment by SamKimball-BrownU** [comment]
Let’s give this a shot

https://share.icloud.com/photos/09cyMtoN7DkGHMUp68GLBQjEA

**Comment by urapadmin** [comment]
that sounds like a filemaker bug. Does it happen with the description in the popup as well? 
Does it happen in other forms with dayplans as well (you know, simple vs. full excavation form, feature, survey)

**Comment by SamKimball-BrownU** [comment]
Honestly, I cannot recreate this consistently. The only thing similar, is that the text in survey unit descriptions is always tiny. That is a separate issue it seems, and one that I will make a new ticket for, #786 

I will keep an eye out on this, but I would agree that it seems to just be a fluke of filemaker.

**Comment by SamKimball-BrownU** [comment]
Another instance of this happened. This time in a feature unit. Still unable to figure out how to recreate.

https://share.icloud.com/photos/05IhRqAttAxjYZnxn7VzJzq4Q
