### ISSUE TITLE
How to actually upload qr photos?

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#750]
So, I used my phone to take some photos with a qr code in them. When/how do we upload? I would assume that would happen in afternoon. Is this correct?

**Comment by lbestock** [comment]
Yes, it will happen in the afternoon! And maybe not this afternoon - I'm still trying to decide what to give you guys.

**Comment by SamKimball-BrownU** [comment]
Well, this ticket is fairly useless now. I'm gonna close it, and I will remember to put it in the user manual.
