### ISSUE TITLE
Hide "lots" tab on projects not configured to use lots

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#751]
Having the Lots tab in a unit is a bit of a nuisance, when we aren't actually using them. It would be nice to have it disappear when on a project that doesn't use it.

**Comment by urapadmin** [comment]
tabs cannot be hidden in filemaker - not possible.

**Comment by SamKimball-BrownU** [comment]
Can I close this to reduce clutter?
