### ISSUE TITLE
Error message showed up saying upload was unsuccessful. Did not specify what was wrong. 

### ISSUE THREAD

**Issue by nvd2** [urapadmin/kiosk#755]
I ran into a problem with uploading the data, as I tried to do it a few days ago and it failed. I then made the mistake of not checking if it had been successful with uploading and did not see that it failed. The error message did not say anything about why it didn't work. I forgot to get a screenshot of the failure message.

**Comment by urapadmin** [comment]
And did the upload actually go through? Sometimes it is just that the success-feedback from the server gets lost somewhere on the way. If the upload actually went through, your workstation would show "waiting for import" in the list of workstations.

Also, if the upload went through, your second attempt to upload would have been under "more options"
Did you repeat the upload and then it worked?

**Comment by urapadmin** [comment]
This also has nothing to do with filemaker: please put the filemaker label on ONLY if you actually have an issue within the filemaker recording part.

**Comment by nvd2** [comment]
It didn't go through the first time, but it uploaded the second time I tried. I didn't have to go to "more options" to upload it for the second time.
