### ISSUE TITLE
second upload before synchronization does not trigger "import"

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#756]
See #753, where it was mentioned that failure to trigger a "import" status for the workstation after a second upload might be  considered a glitch. If you will make a second upload between synchronizations impossible, then this is irrelevant. (Is a glitch a bug? A hiccup?)

**Comment by urapadmin** [comment]
well. The issue is that I would not change this if I were the mere admin on this project because under most circumstances it does not do any harm to import twice and can be useful. It is just that one needs to know what one is doing to a degree that a normal admin will never have. I might make it an option for super-admins or some such. I also do not consider this a priority issue.

**Comment by urapadmin** [comment]
see #840

**Comment by urapadmin** [comment]
This is in fact not possible anymore with the field manager. Once an upload has been imported there cannot be a new upload. And that is in fact the safer way to deal with it. 
A superduperadmin can still do it using the console. But there is only one person who even knows what that means, currently 🤔

**Comment by urapadmin** [comment]
so:
### @test 0.13.6
- [ ] no way for a normal admin / user / operator to upload a database AFTER a former upload had already been successfully imported.

**Comment by lbestock** [comment]
When one sees the message in an email, the chin stroking emoji is giant. Wildtester wasn't even a field_worker so superduperadmin can be but a dream for him.

I am a normal admin. I have uploaded and imported but not synchronized. And have no option to upload again, though I still have the import option. So, good.

**Comment by urapadmin** [comment]
### 0.13.7
- [ ] and now I have taken the repeated import option away from you since it makes no sense (the superduper could ...)

**Comment by lbestock** [comment]
And then lightening fast you updated and I can test and thus attest: you took it away from me.
My only remaining question, which does not prevent me from closing this ticket: now that no one but a superduper can do anything between upload and import, does it makes sense to collapse those into one command in the same way fork and export have been?

**Comment by urapadmin** [comment]
no. Two different users with different privileges might do that. That 
would be like combining preparing a workstation and downloading it.

Am 28.09.2021 um 23:53 schrieb lbestock - ***@***.***:
