### ISSUE TITLE
using the "broken_file" tag in file repository does not bring up all broken files

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#757]
There are currently 16 broken files in the file repository, but using the "broken_file" tag to search for them for some reason only brings up 7: 

![image](https://user-images.githubusercontent.com/67970402/87882433-5d140980-c9d6-11ea-8e7e-4acfd5e96570.png)

It seems like the ones actually being brought up by the tag are the ones without context? See #753 for further explanation of broken images (when I get around to putting that in in a couple of hours, that is).

**Comment by urapadmin** [comment]
the broken file tag gets applied only by something called "housekeeping". The admin has to run it first. I will integrate it in synchronization one day.

**Comment by urapadmin** [comment]
I ran housekeeping and now we have 26 broken files.

**Comment by luizaogs** [comment]
Oh that's weird, too -- I counted 20?

**Comment by urapadmin** [comment]
how do you count broken images?

**Comment by luizaogs** [comment]
Oops sorry accidentally deleted my comment.

**Comment by luizaogs** [comment]
I counted them manually while trying to figure out what they were :) see #753 

Anyway, 7 of these are still those first 7 images I had uploaded the first time when I didn't know about the gallery (dated to 8 VII). Do they stay in the system?

**Comment by urapadmin** [comment]
yes. They do until somebody either deletes them or puts an actual image in there.

**Comment by urapadmin** [comment]
I still don't understand where and how you count broken images if not by using the tag

**Comment by urapadmin** [comment]
nevermind. I didn't see #753. OMG.

**Comment by luizaogs** [comment]
Aha, yes. Welcome to the inside of my brain. It's not nice in here.

**Comment by urapadmin** [comment]
If I count in the file repository without using the tag I get to 26 as well.

**Comment by luizaogs** [comment]
Yes -- I hadn't gone as far back as 8 VII (because I thought they would have been gone) so only caught the 20 that were an issue today.

**Comment by urapadmin** [comment]
okay, let's call that clarified at least.

**Comment by urapadmin** [comment]
and this here can be closed because running housekeeping brought up the right number of broken images,
