### ISSUE TITLE
qr code substitute

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#760]
there is this old relict from Petra: insert qr code substitute. Do we want to hold on to it? 
see #19 

But also, when I use it these days I get several error messages first:
![image](https://user-images.githubusercontent.com/38838314/87888152-41871e00-ca2b-11ea-94f1-be687df57a32.png)
and then 
![image](https://user-images.githubusercontent.com/38838314/87888156-4c41b300-ca2b-11ea-8f56-918395ae08d3.png)

and then
![image](https://user-images.githubusercontent.com/38838314/87888160-56fc4800-ca2b-11ea-9bec-a6e3d7410810.png)

and while in one case I actually managed to insert a qr code I wasn't able to do so again.

Until we have decided what to do with it at all we should deactivate it for all projects

**Comment by urapadmin** [comment]
### 9.4.2
- [ ] There is a new configuration key "use_qr_code_substitution" that should be set to "nope" for the time being since qr code substitution simply does not work and isn't implemented on the kiosk site at all
- [ ] exists in simple and full excavation mode
- [ ] if turned on it should at least not produce all these errors and create a proper qr code as an image (but that's it).

**Comment by luizaogs** [comment]
Testing. I'm just a tad confused about the three boxes that are currently unchecked -- you just mean that the qr code substitute used to be visible in all of those places and that it shouldn't be there any longer, right? It's definitely gone now (even if one chooses "yup" in visibility).

**Comment by urapadmin** [comment]
I am puzzled. If they are always gone, even if you turn the use_qr_code_substitution to yup, how did you test the last point? 
The buttons should be visible only if that configuration key is set to yup. And then they should just give you the "not available" message,

**Comment by luizaogs** [comment]
Oops I thought the last point was in reference to the message one gets when turning it on in visibility, which is this: 

![image](https://user-images.githubusercontent.com/67970402/88467206-8df6b180-cea2-11ea-8e64-090b25915b13.png)

This is after I have turned it on in visibility: 
![image](https://user-images.githubusercontent.com/67970402/88467232-d2824d00-cea2-11ea-97df-b8aa5c95a125.png)

Still gone, and that is the case for all of the above.

**Comment by urapadmin** [comment]
ha. interesting. Apparently I already invented a similar configuration key once but never used it. This is the wrong configuration key.
The one you should be using is "use_qr_code_substitution". 
We should get rid of the other one, of course (which is a real problem. There is no mechanism I can use to delete a configuration key in an existing project). But that is a test issue and not important. Just test with the other key.

**Comment by luizaogs** [comment]
How embarrassing, I can't read. It works fine!
