### ISSUE TITLE
NEF QR code upload failure - check other file types too!

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#763]
Coming out of #627 but I make it its own ticket. That was a QR code upload failure that appeared to be because of cache issues. My most recent failure was definitely file type: the same image failed as a NEF and succeeded as a jpg. This was a fully up to date Beset 0.8.7 PVD test just around noon on 22 July 20.

One reason I make it its own ticket is to tell us to plan for CRW (Canon's raw format), too, if that requires extra steps. Lots of archaeologists use Canons. Do we want to think about Olympus, too? Ugh how many raw formats are there at this point and how many people use cameras other than Nikons and Canons?

**Comment by urapadmin** [comment]
well, first of all we would have to organize CRW and ORF files. As far as I can see, we should be able to process them more or less out of the box.

**Comment by lbestock** [comment]
MJ's roommate (who wants to join anyway and has been having passionate debates about context typology) has a Canon DSLR and will give us some of those.

**Comment by urapadmin** [comment]
I can confirm that. OpenCV cannot open NEFs and that's the image manipulation library we are using. I have to convert the raw files first. 
Please test using converted jpgs for a while, I want to wait for the other raw images (Canon / Olympus) before I open this can of worms again.

**Comment by lbestock** [comment]
Sofia I'm adding you to this ticket as we've now discussed taking Canon raw images with QR codes. It was great to hear from you again with questions - glad you're on board. You can reply to this ticket when you have such images; meantime I will try to find a way to get Olympus raw images so we can tackle this all at once.

**Comment by Sboracci** [comment]
I took pictures using the canon raw file type, but they seem to be too large for me to upload to GItHub. Not even a single image is small enough for me to post here, let alone a zipped folder.

**Comment by urapadmin** [comment]
Bloody raw files. They clutter everything. Well, a good opportunity to try kiosk: You can just upload the zip to kiosk. We don't need than two images for the time being. If we can read one of those we should be able to read them all. So please zip two of them and upload them using the file repository and the file import from the menu. Use the Upload option, if the system asks you, and then use these options:
![image](https://user-images.githubusercontent.com/38838314/90550137-d0549b00-e18f-11ea-9a92-4fb4f1d05c50.png)
make sure the "import only files with context" checkbox is unchecked. And please give the import a tag in "assign tag": Just "zip" will do. I'll delete it later, anyhow.

**Comment by urapadmin** [comment]
Did you make raw photos with a qr code from the recording system in them? Not necessary, would just be nice to test later, if they can be recognized automatically.

**Comment by urapadmin** [comment]
This has evolved to be two things. 
The NEF issue is now treated by a different ticket: #842 
the Canon issue is here: #818 

@Sboracci: If you have managed the upload please close this here.

**Comment by urapadmin** [comment]
@Sboracci: Don't worry. We don't need your files anymore.
fixed.
