### ISSUE TITLE
introduce the pinboard in more locations

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#765]
like 
- [x] dayplans simple excavating
- [x] plans and photos feature
- [x] plans and photos survey
- [x] collected material
- [x] site plan (really?)
- [x] site notes
- [x] tag analysis

**Comment by urapadmin** [comment]
### 9.4.2

- [ ] dayplans simple excavating
- [ ] plans and photos feature
- [ ] plans and photos survey
- [ ] collected material
- [ ] site plan (really?)
- [ ] site notes
- [ ] tag analysis

**Comment by SamKimball-BrownU** [comment]
Issue: On site plan/notes, if you tap the pinboard icon in the upper left corner, it shows up as blank.

**Comment by SamKimball-BrownU** [comment]
Issue: Same thing in tag analysis. But only sometimes. I'm gonna mess around in it a little while to see if I can find a consistent way to recreate

**Comment by SamKimball-BrownU** [comment]
Okay fact: If you pin some image in either of these forms, the pinboard will be fine when you open it using the upper left pinboard icon. There seems to be continuity between these two forms, i.e. if you do get it to be fixed in one, then it fixes in both places, and vice versa.

**Comment by SamKimball-BrownU** [comment]
Steps to recreate: 
1. Make sure you have a site with a site note image.
2. Go and pin some image to your pinboard, or multiple images. Whatever. I took mine from SB dayplans.
3. Then go to site notes through clipboard icon on home page. 
4. Pin that site note image.
5. Go to pinboard using top left pin. There should be no images in it. It looks like it was cleared. Ooof.

But still, if you go somewhere that it is working properly, the pinboard content was preserved (for example, going back to a unit)

This happens with both simple and non-simple excavating (it shouldn't matter anyway because we're not in an excavation unit anyway)

For the life of me, I cannot figure out how to recreate the bug in tag analysis, but it was very similar. Hmm.

**Comment by SamKimball-BrownU** [comment]
> Okay fact: If you pin some image in either of these forms, the pinboard will be fine when you open it using the upper left pinboard icon. There seems to be continuity between these two forms, i.e. if you do get it to be fixed in one, then it fixes in both places, and vice versa.

The continuity seems to not be happening any more. Ugh. I'd say it might just be some filemaker weirdness, considering the crash. Ugh.

**Comment by urapadmin** [comment]
"blank" means that the images simply don't show up if I understand correctly. In that case it might be one of filemakers screen refresh glitches. They can be pretty persistent at times and gone at others. Filemaker really sucks. 
However, the only final remedy against that would be to give the pinboard a refresh button that refreshes the screen. 

As for the images: I suspect those were not images you had just put in a file container for the first time right before you clicked on the pin and pinboard? Well, I'll play around with it myself a bit.
Filemaker 18?

**Comment by urapadmin** [comment]
I can't find a way to reproduce this. At least not on Windows. Anyway, I have added a particular refresh instruction for the pin board (in general, I hope it has no side effects) that might battle the issue. Keep an eye on it.

**Comment by SamKimball-BrownU** [comment]
Tested in 9.5 on windows, and on iPad

It occurs on windows too, using the steps I outlined. Here is the resulting blank pinboard

![image](https://user-images.githubusercontent.com/61027113/89451570-0a4e8780-d722-11ea-91fa-c4eca2092fdb.png)


Let's be very very precise with what I do to recreate it:

1. Open up playground, through the clipboard icon.

2. Make sure that there is a site note image there (there should be, it's a pic of my screen that I synced at some point)

3. Open up unit SB in the Providence site, by selecting it and then using the trowel button

4. Go to the dayplan/narrative tab. Pin all the dayplan images (should be 5 of them), not using the popup

5. Return to the playground site, through the clipboard icon

6. Pin the site note image, via the popup

7. close the popup via the x in the corner

8. Open up the pinboard on that page, using the top left pin button. 

9. The pinboard appears empty, even though it's not.

Note that if you go into some other pinboard, it should be fully populated. It's just this one instance.

**Comment by SamKimball-BrownU** [comment]
Another place it is needed: relations popup

**Comment by urapadmin** [comment]
relations as a whole? That one I don't understand. However, I'll add the pinning mechanism to relation images in the popup.

**Comment by urapadmin** [comment]
### 9.5.3
- [ ] pinning introduced in locus relations

**Comment by lbestock** [comment]
Can be tested when #936 is debugged.

**Comment by luizaogs** [comment]
Tag analysis still problematic. I have a bunch of images pinned and I can see them in the pinboard everywhere else, but when accessing the pinboard through tag analysis it's blank. However, if I pin an image IN tag analysis and THEN click on the pinboard I can see the pinboard with all images in it, both the ones I had pinned previously that had not been visible and the one I tagged in tag analysis.

**Comment by urapadmin** [comment]
@luizaogs: This should be okay now, right?

**Comment by luizaogs** [comment]
Yep!
