### ISSUE TITLE
test feature: use simple excavating can be switched ON temporarily 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#766]
### 9.4.2
This is a feature to make testing easier:

if a user is registrar and simple excavating is turned off in configuration a checkbox appears in tab "registrar ..." on the start page. There the simple excavating mode can be turned on temporarily (it does not change the configuration settings and hence does not synchronize to other workstations). 
The temporary setting gets lost when closing filemaker.

**Comment by SamKimball-BrownU** [comment]
Oh thank goodness, this is a very helpful feature.

**Comment by luizaogs** [comment]
Works perfectly, too.
