### ISSUE TITLE
do we want to be able to delete features at all?

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#768]
Do we want to be able to delete features at all? The buttons are right next to each other, and although it's obvious that it's a link and a plus sign, may be good for there to be a confirmation for making a new feature within the excavation unit (so we don't have a million random empty features floating around)

_Originally posted by @myjaylee1123 in https://github.com/urapadmin/kiosk/issues/680#issuecomment-663043947_

**Comment by myjaylee1123** [comment]
Yes, but with a warning. It's easy to accidentally create a blank feature, only to realize you can't get rid of it, and now there's just a useless empty feature floating around.

**Comment by lbestock** [comment]
Consensus is clear that we DON'T want extra features flying around. But these are two different proposed remedies: 1) making it possible to delete them (if there is no information entered), and 2) giving a warning on creation. The current delete button deletes the link to the feature (more precisely: the link between the unit whose features you are viewing and that feature). It definitely should NOT be possible to delete a feature in that view - the potential for confusion is very high if you have both the possibility to remove the link and to delete the feature entirely. The question then is should features be deleteable elsewhere? And where and how then? We have been leery of adding deletions in general and I stand by that principle. I think I lean toward a warning on CREATION of a feature unit to try to head off creation of blank ones (this is how I understand your initial discussion, Lutz). But then, we are talking only about creation of feature units from within excavation feature recording, and creation of feature units within survey units, not creation of units from the start page.

**Comment by urapadmin** [comment]
agreed. It is also not as trivial as it seems to delete features as they are units. I think creating a feature on the start page is a much more present and demanding process for a user and I have doubts that it will ever happen accidentally. That's different with adding a feature in a survey or excavation unit by just clicking on an add button.
So let's give it a warning (in full knowledge what users do with frequent warnings).

**Comment by urapadmin** [comment]
apart from that I will allow an admin to delete a unit that has not been used so far. But in the unit management on the start page.

**Comment by urapadmin** [comment]
### 9.4.4
Warning is implemented. The delete for admins will go to a new ticket.
