### ISSUE TITLE
easter egg: find duplicate images in the gallery

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#771]
There is a super special features for all the troops battling duplicate images: Go to the gallery and to an image that you think might be in there more than once. Open the popup and in the popup you find an easter egg button. Click on it and the gallery will show all the redundant images. 

Why eggs? In German we say: "Etwas gleicht sich wie ein Ei dem anderen".

**Comment by urapadmin** [comment]
### v9.4.2
introduced.

**Comment by luizaogs** [comment]
I'm starting to rack up Luiza-specific features, I see. Makes sense -- I was always the queen of Easter egg hunts. (Thank you.)

**Comment by urapadmin** [comment]
I am not quite the king but at least a friend of funny features. Software development can be quite dry.

**Comment by urapadmin** [comment]
The hardest part was to make an Easter Egg button :o)

**Comment by luizaogs** [comment]
I'll use it first on the random bunny picture that's in there probably ten times. Appropriate :)

**Comment by urapadmin** [comment]
Convergence!

**Comment by urapadmin** [comment]
I should add that this was a poetic reference to Thomas Hardy. (desparate me trying to combine the irreconcilable)

**Comment by luizaogs** [comment]
And here I thought you were making a reference to biological evolution! Fits.

**Comment by urapadmin** [comment]
Is convergence a thing in biological evolution? I learned my evolution in German. Ha.

**Comment by luizaogs** [comment]
'Tis indeed. Something about different species developing similar characteristics, which I thought was very funny in association with my taking part in software development.

**Comment by lbestock** [comment]
And of course archaeology, which is a thief particularly of evolutionary biology, has developed models of divergent and convergent cultural development that are, um, rather problematic. But my mind is in the icy depths of the Atlantic, where the gilt catches no sunlight and only the eye of a curious fish.

**Comment by luizaogs** [comment]
I do like the poem. Keeping sending poetic references my way, please. I don't read nearly as much poetry as I would like.

**Comment by luizaogs** [comment]
Hmmm for this, would the Easter egg only show up after synchronization (but then wouldn't the image be broken already at that point)? Or is it supposed to be here after I insert the two duplicate images? We have two bunnies but no Easter eggs in popups (popups in the gallery itself or in the actual dayplan/locus photos), though plenty of them across the two images themselves:

![image](https://user-images.githubusercontent.com/67970402/88456177-9078ed00-ce49-11ea-99d8-0f524158f37d.png)
![image](https://user-images.githubusercontent.com/67970402/88456216-e51c6800-ce49-11ea-9143-322c52d43922.png)

Since we also have no shortage of broken images in this gallery at the moment I also checked if there were any Easter eggs in those popups but have not found any (am I losing my Easter egg hunt crown?!?).

**Comment by urapadmin** [comment]
the easter egg is always there in the popup in the gallery! There is a button to popup the image. You find special information in that popup and in the lower right corner you find the easter egg button.

**Comment by luizaogs** [comment]
I must be blind. 
![image](https://user-images.githubusercontent.com/67970402/88467135-b9c56780-cea1-11ea-8fe9-0cfc65cb7c2e.png)

**Comment by urapadmin** [comment]
no, your are not. It's a bug. You can see and test the easter egg button in your version if you are admin or turn "test mode" on: configuration / admin / test_mode = yup. 
That's a good example why staying logged in as admin is a bad idea because such things would go unnoticed. You did not and so we know about this bug.

**Comment by luizaogs** [comment]
Oh good. Well not about the bug, about catching it. Good news is that in admin it works wonders (and the easter egg icon is very cute).

**Comment by urapadmin** [comment]
### 9.4.4
accessible for all users now
