### ISSUE TITLE
Fake empty image container in survey dayplans

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#772]
Okay, bad title, but it's a bug that's a bit weird to replicate:

Step 1: Go to survey unit, and then add a feature.

![image](https://user-images.githubusercontent.com/61027113/88337504-71b91000-ccfc-11ea-9345-a8b3eb8ca84f.png)

Step 2: Add image to that feature. Any image should do.

![image](https://user-images.githubusercontent.com/61027113/88337566-8bf2ee00-ccfc-11ea-9239-ff81cd92409d.png)

Step 3: go back to your survey unit

Step 4: there should be an empty image container in the bottom left

![image](https://user-images.githubusercontent.com/61027113/88337603-990fdd00-ccfc-11ea-8eb9-6e2cee897b36.png)

Step 5: Try to put an image there

Result is an error: 

![image](https://user-images.githubusercontent.com/61027113/88337298-20108580-ccfc-11ea-95ce-9e89997d79bd.png)

I think this is because it didn't actually create a new image container, or at least not completely. Note that there is no new blank record in the dayplans in step 4; it's just a container in the bottom left. I tried similar things in other places, but it seems to only present in surveys under these specific circumstances. It also doesn't have this fake container when you first enter the survey unit. 

Make sense? This is kind of a long process to recreate the bug, but one that I ran across a couple times in survey this afternoon.

**Comment by urapadmin** [comment]
yes, makes perfect sense.

**Comment by urapadmin** [comment]
### 9.4.3
fixed. The issue was a general issue when opening a form with dayplans (excavation forms, feature and survey). If the user was in one of those forms before, selecting a dayplan then the next form with dayplans would have shown this strange empty container.

**Comment by SamKimball-BrownU** [comment]
Resolved in Excavation/feature recording and survey/feature recording. I can't think of anywhere else this might happen, so I'd say resolved! Tried it in both simple and non-simple recording.
