### ISSUE TITLE
director's view definition and requirements

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#774]
we want to put the director's view on the plan for arch1900 in September.

Needs input from Anna as to what she wants for teaching students and input from Laurel for requirements in the field. So far there are ideas floating around but nothing coherent. 

As soon as I have the requirements I will create some kind of mock to finish the definition and then try to implement this module until September. 

But that's tight, folks!

**Comment by aes1884** [comment]
At the moment, my two big asks would be the ability to track who does what on the recording system (for assessment purposes), and some way to see at a glance what fields aren't filled in so I can get missing info sorted out. If I think of more I'll add them.
