### ISSUE TITLE
resize boxes showing team member drop down for survey transects

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#777]
File this one under "insatiable directors" but also under "probably really easy just annoying to fix formatting thing".

The drop down boxes that show team members for survey transects are ever so slightly too large, so that one can see the very top of the next person's initials. 

Not sure why that bothers me more than that the boxes for the things found above are too small for the words to fit, but there you have it. Insatiable and irrational.

![image](https://user-images.githubusercontent.com/49291909/88436607-997aa780-cdd2-11ea-82a7-916e6cb48319.png)

**Comment by urapadmin** [comment]
### 9.5.3
I tried something against both issues

**Comment by luizaogs** [comment]
Both look good now!
