### ISSUE TITLE
description of small find not visible in tag analysis 

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#780]
Again, more of a question than an issue -- in tag analysis, if the object is a small find and the description for that has yet to be filled out it does not show up in the collected material tab (here I am referring to LA-006-4): 

![image](https://user-images.githubusercontent.com/67970402/88443653-1fa0e900-cde7-11ea-8b72-a358f12bcb0c.png)

For the other two small finds at the top, the descriptions are there simply because I messed up the workflow and filled out the small finds tab rather than the general collected material description, when really I should have filled out only the latter because the former would have been updated later by the registrar. So I suppose this has to do with workflow: is tag analysis generally only used later, and would the small find description always already be there when it is being used? I don't think it's a huge deal either way but it did throw me off at first because it looked like information was missing, so I thought I would point it out!

**Comment by urapadmin** [comment]
What are you expecting here if the information is missing indeed?

**Comment by luizaogs** [comment]
Well the small find description is missing, not the collected material description, for the same object. Which is why I was confused in the first place as the excavator who had filled out the collected material description but then saw this blank space.

**Comment by urapadmin** [comment]
Ok. In this case I could show the collected material description whenever there is no small find description. I guess that does not only solve a problem that exists only from a  test perspective it might also be useful in analysis. For, yes, the workflow is rather that at the point of tag analysis the registrar has usually already done her work.

**Comment by urapadmin** [comment]
no, in fact I won't change anything here. The description of the collected material would be visible if it were not already a small find. And that makes sense: If a registrar checks something as a small find it also needs to be registered and as long as it isn't not having a description here shows indeed that something is missing.
