### ISSUE TITLE
some options in the admin menu are orange?

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#782]
This had not been the case before -- at least not for the use_simple_excavating option, which is the one I would have noticed since I was using it often until you added the cool test feature that lets me use simple excavation without going through admin. It's also showing up for a few other things (such as allow_surveyor_request). Not sure if purposeful or not so checking!

![image](https://user-images.githubusercontent.com/67970402/88553266-15533a80-cff3-11ea-895b-ae4e9e5d761b.png)

**Comment by urapadmin** [comment]
see #764

**Comment by urapadmin** [comment]
this is correct and can be closed
