### ISSUE TITLE
"waiting" on photo import dialog box is confusing

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#783]
![image](https://user-images.githubusercontent.com/49291909/88580718-092ea380-d01a-11ea-9911-e259b5952073.png)

Every time I upload photos I get confused by the "waiting" in the dialog box after I either drag and drop or use the browser to add photos. To me it reads like I need to wait for the system to do something before I hit the check button. It is not a very big deal and I would get used to it in the field if I were uploading daily and I don't even know if you could change that, but since I have tripped on it many times I thought I would mention it.

**Comment by urapadmin** [comment]
### 0.8.12
changed

**Comment by luizaogs** [comment]
Testing something else and saw this, so closing it because it has indeed been changed (helpfully so).
