### ISSUE TITLE
Text Color - Feature list in Excavation/Feature Recording. Should be White.

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#784]
Here's a screenshot from Excavation/Feature Recording:

![image](https://user-images.githubusercontent.com/61027113/88593162-c3c3a380-d024-11ea-971f-1e00a47c3635.png)

Note that the text color is black. In every other instance where we use a colored background, the text color switches to white, like so:

![image](https://user-images.githubusercontent.com/61027113/88593215-d938cd80-d024-11ea-88d1-829adf7eba3d.png)

Certainly inconsistent with the rest of the software, and I think white text would make it easier to see.

**Comment by urapadmin** [comment]
hmpf. never ending ...
### fixed in 9.4.7

**Comment by urapadmin** [comment]
wait... are you in 9.4.6? Because my 9.4.6 has at least white labels in the table header in excavation/feature recording

**Comment by urapadmin** [comment]
also those two turquoise colors are not the same either and I thought that is fixed.

**Comment by urapadmin** [comment]
please double check, this was already fixed from my perspective.
But I fixed the tab header in 9.4.7: The label of the tab itself is white now.

**Comment by SamKimball-BrownU** [comment]
This is all correct. I just went in and double checked; I see what you describe. The only issue was the label of the tab itself, which you discovered. 

This was created during 9.4.5? I think. I just copy and pasted the pictures from the previous ticket. My bad.

**Comment by SamKimball-BrownU** [comment]
so no issue with the colors either

**Comment by urapadmin** [comment]
good. Than we have only the tiny little thing with the tab label in the next round.

**Comment by SamKimball-BrownU** [comment]
Resolved.
