### ISSUE TITLE
"Modified by" label on unit edit accessed through gear icon: Updated only after "refreshing" page

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#785]
Minor issue, but, when something is edited in this form, the modified by label is only updated if you "refresh" that page by going to another unit and then back.

Steps to reproduce: 

1: go through gear icon to edit units
2: note the current modified_by label (particularly the time)
3: modify something in that form
4: check the modified label again. It should be the exact same as in step 2. Oof.
5: use the arrows in top right to go to a different unit, and then back to the same one
6: check the modified label again. It should be updated to the correct thing now

Again, minor issue. I think it is fairly similar to this issue from #389 

https://github.com/urapadmin/kiosk/issues/389#issuecomment-657162390

**Comment by urapadmin** [comment]
This is okay. The record gets saved only when either going somewhere else or when leaving the form entirely.
