### ISSUE TITLE
Tiny Text in survey descriptions

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#786]
Text in the survey description field is tiny. It should certainly be larger in order for it to match with the rest of the software. Happens on both ipad and windows. 

![image](https://user-images.githubusercontent.com/61027113/88605994-1ad77180-d041-11ea-942a-61f79590d7dd.png)

**Comment by urapadmin** [comment]
### 9.4.6
fixed

**Comment by SamKimball-BrownU** [comment]
Resolved.
