### ISSUE TITLE
locus: pin board button in the project title

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#790]
the pin board button is not well positioned here. It cuts the title.

**Comment by urapadmin** [comment]
### v9.4.5
I moved it to the left next to the menu button on this form. 
Perhaps we should think about moving it there in general, but that is for another milestone.

**Comment by luizaogs** [comment]
Works! I hadn't noticed its placement before at all but now that you mention it it might indeed be best to shift it there for all of them -- looks much neater. Should I start a new ticket or will you?

**Comment by luizaogs** [comment]
Actually I'll just start it in case this gets lost in the millions of notifications you're certainly getting these days.
