### ISSUE TITLE
survey units: list of tags should be scrollable

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#793]
if there are more tags than fit the list the list should be scrollable (in fact it should always have a scrollbar)

**Comment by urapadmin** [comment]
### 9.4.6
and the same should be fixed everywhere where we can select a tag from that kind of list. (which is ugly but that's for another day)

**Comment by SamKimball-BrownU** [comment]
This all works. Easy to test. Nice. 

But! new ticket: #794
