### ISSUE TITLE
Tag list in Tag Analysis is different than everywhere else

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#794]
When selecting from list of tags in tag analysis, you select the tags with green check marks

![image](https://user-images.githubusercontent.com/61027113/88714626-b0770d80-d0e2-11ea-96b3-c69bcf2c9c61.png)

Everywhere else, you select them with grey arrows. Like so (this is taken from survey, but it happens in locus and feature too)

![image](https://user-images.githubusercontent.com/61027113/88714720-cf759f80-d0e2-11ea-9525-53448a2fbff2.png)

So there is an inconsistency here. Perhaps we need a new tag for this type of issue of UI inconsistency.

**Comment by urapadmin** [comment]
Ja, this whole dialog is just ugly and needs a redesign. Later milestone.

**Comment by urapadmin** [comment]
### 9.5.3
not quite a redesign but at least the dialog in tag analysis looks closer to the other ones now.

**Comment by luizaogs** [comment]
@urapadmin -- I'm closing this because it looks as you intended it to for this ticket, but just a reminder in case you want to open a new ticket for a redesign (as you mention in a comment above).
