### ISSUE TITLE
moving pinboard button to menu area on all (?) forms

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#795]
Related to #790 -- pinboard buttons currently cut the titles on several of the forms, and moving them left to the menu area looks neater.

**Comment by urapadmin** [comment]
It would go where we had the issue with the redundant button of late. I think now that we all like the pin board it makes sense.
@lbestock: Laurel?

**Comment by lbestock** [comment]
YES. The pinboard is really good and it makes perfect sense to put it up in the menu area.

**Comment by urapadmin** [comment]
### 9.5.3
the redundant qr-code button is now gone and instead the pin button is right of the menu button.
This should be the case everywhere in the system.
- [ ] make sure the qr-code in the menu still opens the correct qr-code on all form
- [ ] make sure the pin button is in the right place

**Comment by luizaogs** [comment]
Oh wait, I lied -- should the overall features form in a survey unit have the qr button in the hamburger menu? Or just the individual feature forms? If the former should as well, it currently does not.

![image](https://user-images.githubusercontent.com/67970402/93002325-3240c000-f504-11ea-8017-0f36d6a48c65.png)

**Comment by urapadmin** [comment]
### @test 10.0.1
It should have it now!

**Comment by luizaogs** [comment]
The interpretation tab in individual feature forms still doesn't have the qr button, but the rest is now there.

**Comment by urapadmin** [comment]
### 10.0.2
we're getting there...

**Comment by luizaogs** [comment]
We're there!
