### ISSUE TITLE
floating "context" labels in survey + feature collected material headers

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#796]
While checking if things were labeled correctly when going through tag analysis we noticed that collected materials for survey units and features have a weird floating "context" label in the header (this is not only the case when going through tag analysis, it's on all collected material forms for those types of units): 

![image](https://user-images.githubusercontent.com/67970402/88708356-8a04a280-d0e1-11ea-8c5e-ff66951b971a.png)

This is not the case for collected material in actual contexts, of course, since in those forms the context number goes in that space: 

![image](https://user-images.githubusercontent.com/67970402/88708469-b02a4280-d0e1-11ea-9963-68adcfc6d70d.png)

_Originally posted by @luizaogs in https://github.com/urapadmin/kiosk/issues/674#issuecomment-665215404_

**Comment by urapadmin** [comment]
### 9.4.7
fixed
