### ISSUE TITLE
show imported images

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#80]
After importing via bulk import the imported group should be filtered automatically

**Comment by urapadmin** [comment]
the same should be true after using upload import

**Comment by urapadmin** [comment]
### kiosk 0.8.27
After closing the import dialog the tags used for the import are inserted into the "tags" field and the file repository reloads.
The result should be exactly what had been imported. 

Unless, in fact, instead of the automatic import_* tag a user has set the tag field to something specific. In this case it is that sequence of tags the file repository uses to fetch the images. That can result in more than just the imported images.

**Comment by lbestock** [comment]
File Import automatic tag: works.
File Import custom previously unassigned tag: works.
File Import custom previously assigned tag: does precisely what you said it should. Next, via upload

**Comment by lbestock** [comment]
File upload automatic tag: works
File upload custom tag: works

This is really good.
