### ISSUE TITLE
new categories of collected materials needed for arch1900

### ISSUE THREAD

**Issue by aes1884** [urapadmin/kiosk#803]
In addition to the types of collected materials already present as options, we need the following:
- brick
- mortar
- plaster
- rubber
- asphalt
- concrete
- stone 
Also, if there is a way to do subcategories, it would be great if nails could be a subcategory of metal and slate could be a subcategory of stone. But if not, it's fine as is.
This will greatly reduce our use of the 'other' category and make eventual analysis much easier.

**Comment by urapadmin** [comment]
Anna, is that obsolete, now? You have your materials?

**Comment by aes1884** [comment]
Yes, I have the value list as I want it now
