### ISSUE TITLE
configuration update for valuelist_locus_relations_opposites needed

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#805]
I think "rests against" is off the list anyhow, so I will delete it from the list of locus relations (and patch the configuration key so that all projects get it) as soon as the following tickets are tested:
#801 and #800

**Comment by urapadmin** [comment]
and don't forget the kiosk side of this since kiosk repairs broken relations.

**Comment by luizaogs** [comment]
The other two tickets have been closed.

**Comment by urapadmin** [comment]
### 9.5.3
patched. After the next update rests against should not be offered anymore in the drop-down.

**Comment by urapadmin** [comment]
perhaps the reason for #712 ?

**Comment by luizaogs** [comment]
It indeed is not there anymore.
