### ISSUE TITLE
Unable to prepare alice in kiosk

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#807]
I suppose you can see for yourself. Perhaps just server weirdness, but figured it would be good to make a ticket anyway. Prof. Beefstock was also unable to prepare it. 

https://test.arch-kiosk.brown.edu/workstationmanagercontroller/workstations

![image](https://user-images.githubusercontent.com/61027113/89073396-05638f80-d340-11ea-8541-37fa3a878e79.png)

**Comment by SamKimball-BrownU** [comment]
aha! after I dismissed this, and refreshed the page, it is inexplicably prepared for download. that previous "an unexpected transmission error occurred" popup happened several times. Very strange indeed.

**Comment by urapadmin** [comment]
I saw you battling Beset, restarted the server and prepared Alice for you. I also cancelled several of your attempts because they were all doomed to be in vain. The software cannot handle multiple users at this point particularly when it comes to preparing workstations. And it won't for a while because that is a test problem and does not occur in the field (where we use a local server and a single operator).

**Comment by SamKimball-BrownU** [comment]
Marking this as hiccup for now, feel free to change.

**Comment by SamKimball-BrownU** [comment]
Ah! I see. Divine intervention.

> I saw you battling Beset, restarted the server and prepared Alice for you. I also cancelled several of your attempts because they were all doomed to be in vain. The software cannot handle multiple users at this point particularly when it comes to preparing workstations. And it won't for a while because that is a test problem and does not occur in the field (where we use a local server and a single operator).

**Comment by urapadmin** [comment]
just ideas: #809

**Comment by urapadmin** [comment]
### kiosk 0.8.12
go on recording if this particular problem, that forking won't even start happens again

**Comment by urapadmin** [comment]
we have the field manager now that replaces the workstation manager. So this can be closed.
