### ISSUE TITLE
hidden loci should not be used as identifiers by kiosk

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#808]
11 is a context. It is the invisible context the feature 11 is using. Also something I cannot address in kiosk at this point. Kiosk does not know about hidden loci and all that crap we have because we started with a hierarchical database structure. We will never get rid entirely of these reoccurring problems as long as the basis of our system is the Uronarti data structure. This is one of those late flowers growing out of that rotten turf.

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/787#issuecomment-667338294_

**Comment by urapadmin** [comment]
new dsd instruction suppresses hidden loci: https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:dataset_field_instruction_reference#skip_index_on_parameters|skip_index_on(parameters,...)

**Comment by urapadmin** [comment]
### solved in kiosk 0.8.12

**Comment by lbestock** [comment]
How do I test this?

**Comment by urapadmin** [comment]
In the file repository. 
- [ ] The hidden locus should not appear. e.g. in the edit file dialog in the list of loci. 
- [ ] You should also not be able to add a hidden locus to an image.
- [ ] When searching for loci the hidden locus should not be accepted as a valid context identifier.
