### ISSUE TITLE
incomplete file name in file repository PDF

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#811]
The file name in the file repository of a recently imported file is incomplete. It's a pdf called rusty motor, and yet in the file repository it just gets called motor. The other files in the same import have taken their names more totally from the file name. Weird. I did search the import again (code named "birdbath" as a tag to make my life easier) and so refreshed, and it was still the case:

![image](https://user-images.githubusercontent.com/49291909/89084523-f2ac8300-d35e-11ea-811b-df1e11103f0a.png)

The imported files:

![image](https://user-images.githubusercontent.com/49291909/89084731-00fa9f00-d35f-11ea-8e54-828209e76970.png)

It is a strange inconsistency because now I note, when looking at all the files, that some files came in without names at all through the file import in previous imports: 

![image](https://user-images.githubusercontent.com/49291909/89085991-5e8eeb80-d35f-11ea-83bb-61518168c16c.png)

Only that was an import or two ago and I cannot recall if I changed the import settings.

**Comment by lbestock** [comment]
Ah the "screen" from "screen shot xxxx" is missing in the filename, too. All the filenames from that import are partial.

**Comment by lbestock** [comment]
The no name files must have been imported with no settings at all, and those with truncated names were imported with the "context from operating file system" box checked. But it isn't getting the whole name for some reason.

**Comment by lbestock** [comment]
This has been in USTP at 0.8.10 but the same thing happens in PVD 0.8.11:
![image](https://user-images.githubusercontent.com/49291909/89087018-c6920180-d360-11ea-9bbe-fb0aed79bb1b.png)

(Also check that out - 8 files in a single import. That was what I was really trying to figure out, was if the limit was in fact 5!)

**Comment by lbestock** [comment]
It is 10 :)

**Comment by urapadmin** [comment]
because of the space. In that case it expects the first part to be an identifier and the second part is the description. 
What were your exact setting for the import?

**Comment by urapadmin** [comment]
### 0.8.12
Changed it slightly. This is how it should be now:
- [ ] if you have the options recognize identifier AND recognize description on and feed it a file with identifier and description separated by a blank (the description can have more blanks, just the FIRST blank is the separator) it should take the identifier and the description
- [ ] if you have the options recognize identifier AND recognize description on and feed it a file with just a description with several blanks, then it tries to use the first part as an identifier. It it isn't a valid identifier it assumes that the whole filename as the description and takes only that. 
- [ ] if you have only the options recognize description on and feed it a file with whatever description with several blanks and perhaps even a first part that would be a valid identifier,it will always take the whole filename as the description.
- [ ] if you have only the options recognize identifier on and feed it a file with a valid identifier first and then whatever description with several blanks and perhaps even a first part, it will only use the identifier.

**Comment by urapadmin** [comment]
Those screenshots are extremely huge and pngs (which have bad compression) You would be impressed how long it takes to download them here in Germany. Please use screenshots to actually illustrate something and not just a huge load. And if you can find some screen capture setting that saves them as jpg (4 times smaller) and maybe not capture your whole screen, things are smoother and then there is global warming, you know ... Perhaps a topic for "how we test", too.

**Comment by lbestock** [comment]
Thank you - so dumb. It would never have occurred to me that screen shots were large files, and I didn't notice. And then I used a bunch of them in testing uploading, too, so again huge.

**Comment by lbestock** [comment]
An immediate and quite funny failure for unforeseen reasons that have nothing to do with the software: I tried it (knowing what would happen) with a context where the context itself had a space in it. Something a developer would not anticipate and a user did without thinking: we have a unit "LA test". Can't upload to that one, since we also have LA.

**Comment by lbestock** [comment]
Fun. It all works. But I will not close it because we should discuss the issue of a context that has a space in it.

**Comment by urapadmin** [comment]
make a new ticket for this. But I can already tell you that that's not a problem at all. If a project really wants to do that (I would always advice against it for the simple reason that a space is a hole and you know what ontological trouble that can cause). 
We would simply configure different, project-specific patterns used to identify the parts of the filename. If you need a space but never have a, say $ sign in your identifiers, then we use that one as a separator between identifier and description. 

What is not possibly possible is that sometimes the identifier is and sometimes isn't a separator. Kiosk is in the end deterministic.
