### ISSUE TITLE
unable to add a context to a pdf in file repository

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#814]
Not sure if the file type has anything to do with this, or at least, I've been able to add contexts to other images without any trouble here in 0.8.10 on USTP. But I clicked on the pdf "motor" which has figured elsewhere and thought I would add a context. With my mouse hovering over the little create context + button I already noticed an oddity: the upload arrow over the image lit up. And indeed, clicking brings up the upload dialog box rather than letting me attach a context:
![image](https://user-images.githubusercontent.com/49291909/89108038-62744980-d403-11ea-9818-63f5520a1e1c.png)

I checked this with another pdf on USTP and indeed it seems to be a file type issue.

**Comment by urapadmin** [comment]
that's not because of the file type it was because the dummy icon is so small and so things happened. 
### 0.8.12 fixed
This is fixed in regular 0.8.12 and I have applied this single thing as a patch to thew running USTP 0.8.10
But I suggest you test in PVD

**Comment by urapadmin** [comment]
also: why does this pdf not have a preview on Beset? -> new ticket.

**Comment by lbestock** [comment]
Tested PVD local 0.10.0 and works just fine.
