### ISSUE TITLE
PDFs don't have previews on Beset

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#815]
we have a motor.pdf that does not have a preview. On my local development server it does. So there must be something missing or in the way on Beset.

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/814#issuecomment-667577115_

**Comment by urapadmin** [comment]
ImageMagick was not able to write temporary files due to access restrictions. It needed a different temp path as an environment variable in the web.config:
<add key="MAGICK_TEMPORARY_PATH" value="e:\test\kiosk\temp" />

That's a confiuration change I have to apply to all projects.

**Comment by urapadmin** [comment]
- [ ] urap
- [ ] ustp
- [ ] khpp
- [ ] arch1900
- [ ] ustp_test
- [ ] urap_test
- [ ] test

**Comment by urapadmin** [comment]
### 0.9.15 with changed configuration
- [ ] pdfs should show correct thumbnails in all projects now

**Comment by luizaogs** [comment]
So I tested this in PVD but then noticed that you wanted it tested for all projects, which I can't do, so I guess no need to test it in PVD when the rest is tested because it worked there!

**Comment by urapadmin** [comment]
no, this can be closed. Should PDFs go missing again in a different system, we make a new ticket.
