### ISSUE TITLE
default image import settings to "last used"

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#816]
Particularly when using Beset and so limited to 10 images at a time for import, it would be useful if the import settings could be remembered instead of always switching back to qr-code.

**Comment by urapadmin** [comment]
hm. begs the question where to store such information. If I store it in the kiosk-config, the server will reboot because of it.

**Comment by urapadmin** [comment]
also begs the question whether we would store such things even user-specifc? There is not mechanism for that at all.

**Comment by urapadmin** [comment]
ok. The first solution is to save all the settings for the user and temporarily. Temporarily here means: until redis is restarted. That would happen e.g. when the server (the machine Beset) restarts. But it also allows us to reset to default and we are not tampering with any local files that would lead to a restart. 

But it also means: Such user settings cannot be transferred to a different server. 

### kiosk 0.8.16
- [ ] first implementation only covers upload. If that works, I will add the batch import

**Comment by lbestock** [comment]
Can you release 0.8.17 somewhere so I can test it?

**Comment by urapadmin** [comment]
0.8.17 is released for pvd now.

Am 17.09.2020 um 01:40 schrieb lbestock - notifications@github.com:

**Comment by lbestock** [comment]
Works.
