### ISSUE TITLE
implement Nikon .cr2 raw format

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#818]
there are example photos on the Canon website and I have some locally. Perhaps all I need is put the correct fileimportextension in charge. CR2 does not trigger anything currently and renaming them to raw did not work.

**Comment by urapadmin** [comment]
### kiosk 0.8.16
- [ ] Canon files ending on cr2 can be imported now.

**Comment by lbestock** [comment]
How many raw file types ARE there? The CR2 worked and the NEF but the CRW I tried did not. Do we care or close?

**Comment by urapadmin** [comment]
I don't know what a CRW file is. This was about cr2. So you can close it, if it worked.

**Comment by urapadmin** [comment]
To answer your question: Every manufacturer has their own raw file format. Means, there is at least Olympus ahead for us. But that's for another ticket.

**Comment by lbestock** [comment]
It was another Canon raw format - they have many, unhelpfully.

**Comment by urapadmin** [comment]
Please make a new request for that new format and close this one here, if it is okay.
