### ISSUE TITLE
Left button for photos of contexts does not work

### ISSUE THREAD

**Issue by Sboracci** [urapadmin/kiosk#819]
When trying to cycle through my photos of a context (Context MB-002), I could cycle right through all of the photos, and it would circle back around, but the left button would not work.
![IMG_0348](https://user-images.githubusercontent.com/68704735/89130260-71c1c880-d4d1-11ea-9485-be69b3621552.PNG)

**Comment by urapadmin** [comment]
there was something confusing about it, indeed. Take into account that the order of the images is backwards: The first is always the most recently added, the last one the oldest.

**Comment by urapadmin** [comment]
### 9.5.3
should be fixed. Same issue might be with other portals (a list of records) as well. I have only attended to this one here.

**Comment by myjaylee1123** [comment]
issue is fixed. left button does work now.
