### ISSUE TITLE
exporting signature sketch exports project logo instead

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#820]
I was trying to export a sketch I had made of locus relations using the signature function but saving it to the camera roll just gave me the PVD2020 project logo (the one with the easter eggs, no less). Not sure if this is a Filemaker issue instead of a bug? 

In other news, the issue I had whined about in #738 seems to be resolved, which is interesting considering how you mentioned that it was unresolvable. Yay?

**Comment by urapadmin** [comment]
Is this still the case with 10.5.1?
see #821

**Comment by luizaogs** [comment]
No longer an issue, either.
