### ISSUE TITLE
PVD logo showing up when clicking view on a locus relation signature sketch

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#821]
Related to #820, methinks. 

When clicking on view right after inserting a signature locus relations sketch, I get the easter egg project logo (I know you've changed it but I'm using an old version on my iPad so don't be alarmed, the new version is on my laptop). After clicking on done and asking to view it again, the sketch comes up correctly.

**Comment by luizaogs** [comment]
Hmm is this not the same issue as #727?

**Comment by urapadmin** [comment]
is this still the case with 10.5.1?

**Comment by luizaogs** [comment]
Doesn't happen anymore -- I tried all of the combinations you mention above.
