### ISSUE TITLE
wonky display in file repository for image with long description/many features

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#824]
In file repository, there seems to be a bit of an issue with a wonky display/design of an image that has a particularly long description (well really, it's a bunch of different descriptions from different features) and that is assigned to several features. The image is 65c3b64d-ab9b-4930-9b6a-148896a933a5. 

![image](https://user-images.githubusercontent.com/67970402/89356932-7fc04680-d695-11ea-9b39-4a7f63dca906.png)
![image](https://user-images.githubusercontent.com/67970402/89357158-112fb880-d696-11ea-809d-1a25ece48c13.png)

Admittedly this is one that shows up in a LOT of places and I don't know how common that actually is in a real field scenario, but since this happened when trying to illustrate "feature relationships" it might have a real field correlate.

**Comment by urapadmin** [comment]
methinks I should not only attend to the layout issue in the edit file dialog but also cut looong descriptions in the file repository at some point.

**Comment by urapadmin** [comment]
### 0.8.13
two things here:
- [ ] in the image list all descriptions longer than 90 characters (you don't need to count :o) will be cut off and an ellipse is added.
- [ ] in the file edit dialog the list of contexts should run over several lines if necessary.

**Comment by urapadmin** [comment]
still a bit wonky in the image list with the identifiers line up without a break. I'll attend to that in the next iteration.

**Comment by urapadmin** [comment]
###0.8.14
now the identifiers should break into several lines if necessary, too.

**Comment by luizaogs** [comment]
Is it desirable/possible to also introduce semicolons between the different descriptions? In both the image list and file edit dialog. It's currently a bit disorienting because it looks like it's all the same thing.

Sorry if this should be a separate ticket. I don't think I'm very good at judging when things should be broken into separate issues...but this seemed like part of the same thing. Feel free to just tell me when I should do it differently (obviously).

**Comment by urapadmin** [comment]
I have added semikolons. It did not help much. So I have also left justified the description block. It might be a bit better now? In the end stringing descriptions is chaotic and in the list it is rather a preview. You find the whole description when you click on the image.

**Comment by luizaogs** [comment]
I think it's easier to follow now, yes.
