### ISSUE TITLE
modified_by of the recording records created in kiosk need the recording user id of the logged on kiosk user instead of "sys"

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#827]
Currently I have only made sure that this works for the image record itself. 
Laurel might have stumbled over exactly the fact that the image itself got the right user but all the recording records like dayplans, locus_photo etc. still get "sys".

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/548#issuecomment-669439662_

**Comment by urapadmin** [comment]
### 0.8.13
the logged on user should be registered as "modified_by" to the recording record in these situations:
- [ ] importing a new file via upload
- [ ] adding a context to an existing file in the file edit dialog
- [ ] detaching a file from a context in the file edit dialog (leaves the recording record intact but without a file now)

In all of these cases the modified_by attribute in the recording system should show the recording user (which is usually the same as the kiosk user). So in dayplan, locus photo and collected material photo the little green button should show the correct modified_by user.

**Comment by lbestock** [comment]
Here you go, Luiza, a more kiosky one since you're done with the others :) Ask if you have questions, of course. I have been doing these things in other tests and am pretty sure they work, but a systematic test is still necessary! Go for it.

**Comment by urapadmin** [comment]
I feel I should add here that the modified, modified_by etc. attributes one sees in the file repository's file dialog belong to the image itself. They only change if the image itself or one of the tags change. 

Here we are talking about the attributes of the data records that refer to the image, so the dayplan record, the locus_photo record etc.

**Comment by luizaogs** [comment]
Of course I'm going to ask a question (a dumb one, I believe). So for this I'm using both kiosk and FM (the little green button being the recorded by on FM that one can click on to look at the date?), and will have to synchronize to get the file repository changes back onto FM. Yes?

**Comment by urapadmin** [comment]
precisely. And I am happy you do make sure that you understand instead of assuming you would. Refreshing.

**Comment by luizaogs** [comment]
That's because my default is to assume I know nothing :) Case in point: everything seems to be working fine BUT I cannot find a green button in dayplans? Am I blind?

**Comment by lbestock** [comment]
You are not! Recently referenced in #378, too.

**Comment by luizaogs** [comment]
Ah. Well good, I'm glad I don't need to go get new glasses again. Lutz, let me know if you want me to wait until this is fixed to make sure it works with dayplans or if you want me to try uploading a locus or collected material picture instead.

**Comment by luizaogs** [comment]
This works fine, now that I can see the little green button in dayplans.
