### ISSUE TITLE
Change "date of definition" in excavation contexts tab to "date opened"

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#830]
Date of definition, to me, implies the date that it was entered into the software. In reality, it just carries the "date opened" field. It would certainly make sense to name these two things the same way, and date opened seems to be the more descriptive of the two.

However, this might be a bug/unintended.

Context this came up in: I was trying to create some contexts that are.... legacy? in some ways. They were certainly excavated before, I'm just defining them differently now (the container vs what is contained as two separate contexts). So, I entered in the date opened as the original date that the context was excavated.

**Comment by urapadmin** [comment]
@lbestock: You opinion?

**Comment by lbestock** [comment]
I agree they should be named the same thing, and that "date opened" seems to make more sense for both locations. Particularly given that the only time that will differ, the "definition" (making of the record) and "opened" (beginning of the context as an archaeological entity) is indeed in legacy input and in that case the date of the excavation itself is what belongs in that list. The created and modified by for the record is now easily accessible in the info button.

**Comment by urapadmin** [comment]
### 9.5.3
changed in excavation and simple excavation.
