### ISSUE TITLE
the "logs" menu should only appear while inside of the administration plugin

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#831]
currently it seems to be always there.

**Comment by urapadmin** [comment]
### kiosk 0.8.15
just a configuration issue. But hence it needs to be tested in all projects

**Comment by lbestock** [comment]
How do I test this?

**Comment by urapadmin** [comment]
well, if the "logs" menu item appears anywhere else BUT in the administration part of kiosk it is a bug.

**Comment by luizaogs** [comment]
This means what I'm seeing in the screenshot here, yes? The bottom section of the menu, including logs, only shows up in the admin part so if this looks right it can be closed.

![image](https://user-images.githubusercontent.com/67970402/110707034-7b35b080-81d7-11eb-8e3d-5705c9c7b130.png)

**Comment by urapadmin** [comment]
it is more about where it should not appear. The menu should only be visible when you are in administration and never when you are anywhere else, like file repository, workstations etc..

**Comment by urapadmin** [comment]
if that is so, it can be closed, indeed.

**Comment by urapadmin** [comment]
BUT: It has to be tested in ALL projects. Including khpp, ustp, urap, so you might want to leave it open.

**Comment by luizaogs** [comment]
Yes, so that is working fine for PVD but I can't test the others of course.
