### ISSUE TITLE
importing contextless images -- a tad confusing

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#832]
We spoke about this a bit during the meeting and it seems like a couple of us had a bit of trouble figuring out how to import images with no contexts that were to be later assigned to contexts through the file repository. At least for me, this was because I expected to have to click on one of the four importing options (the yellowish rectangles) and it took me a while to figure out that in fact all of them should remain unchecked, and that the relevant checkbox was the "import only files with contexts" one above. It might be more user-friendly to move that option below with the other ones, so that one knows where to find it (and then maybe you could even include a suggestion that these imports should perhaps be tagged to make it easier to find them in the little description for that option, where you explain what it does?).

Laurel mentioned that this is a relic of an older version of the import interface and that it is something that might now be changed, so here is a ticket.

**Comment by urapadmin** [comment]
relic? I don't know of no relic in that user interface. It is not trying to be intuitive but rather versatile. The process isn't really intuitive. This is a part of the software users have to learn, they must not just figure it out.  
The said option is different from the other options. All the other options are controlling all kinds of ways of identifying contexts and dates from a file. And their order is important. If they are all checked and all of these methods produce results, the last one (the one below) wins. The option we are talking about here is really a more general option that controls what to do if no context can be found at all. So...
I am reluctant and do not find it illogical where the option is located. I opt for the user's manual as a solution here.

**Comment by luizaogs** [comment]
Ok, then. I assign Sam and the users manual and close it.

**Comment by SamKimball-BrownU** [comment]
I'm reopening this because I think that there is a fairly easy solution to this problem, to make the option more visible. It is kind of hidden, with black text against a dark background. Maybe simply changing the text color to white would make it more obvious to users. 

Plus, it will look better anyway. Thoughts?

**Comment by urapadmin** [comment]
This is due to the color scheme I created for pvd. The whole styling lacks consistency and we have a big ticket for it here: 
#690. I will link this issue there so that I don't forget about the specific problem.

**Comment by urapadmin** [comment]
The color question will be tackled in a new ticket: #1015 
I close this here.
