### ISSUE TITLE
fetching 'em in the file repository

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#834]
Option is currently "fetch' em." Should probably be "fetch 'em”?

Yes, I am aware of how annoying I am and am sorry for it.

**Comment by urapadmin** [comment]
embarrassing. 
### Fixed in 0.8.15

**Comment by luizaogs** [comment]
(Since I am the only person who would ever catch this -- I see all typos everywhere, it's a curse -- not embarrassing. Just think of me as your annoying and highly picky copy editor.)
