### ISSUE TITLE
internal server error for kiosk?

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#836]
Hm so trying to download my workstation currently and getting this fun screen: 

![image](https://user-images.githubusercontent.com/67970402/91708483-c64f7680-eb57-11ea-9570-7871d15e2b6f.png)

Tested on both my Mac and my phone, not yet on an iPad.

(I don't actually know what to tag this. Is it Beset?)

**Comment by urapadmin** [comment]
Brown has restarted Beset. They do that to install super important 
security updates. After that I always have to restart parts of our own 
software.

You should be able to close this, now.

**Comment by luizaogs** [comment]
Yup.
