### ISSUE TITLE
picture description issue -- cursor automatically going to second blank image

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#837]
I accidentally added two blank image holders for collected material photographs. After I add the first image, the cursor automatically goes to the description field for the second image holder (the one on top), when it should have presumably gone to the first image description field instead (the bottom one). Tried it twice in two different collected materials, happened both times. 

This was on iPad.

**Comment by urapadmin** [comment]
not unrelated to #819

**Comment by urapadmin** [comment]
this time it had nothing to do with field order. It was something that should, in fact, happen to all images lists. 
Well, I just fixed it here.

**Comment by urapadmin** [comment]
### test recording 10.5.1
should be better now.

**Comment by luizaogs** [comment]
It is.
