### ISSUE TITLE
workstations need to fall back to a defined workstation state when an operation fails

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#840]
If a workstation is in state "EXPORT_TO_FILEMAKER" and a user repeats the fork operation, which then fails, the state must not be any longer EXPORT_TO_FILEMAKER but IDLE, simply because it is safer to repeat the fork until it works.
The same is true for "IN_THE_FIELD" if EXPORT_TO_FILEMAKER fails.

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/546#issuecomment-687343556_

**Comment by urapadmin** [comment]
also test :
- original state "IN THE FIELD" (so the user has downloaded the file)
- repeat EXPORT_TO_FILEMAKER, which fails
- the state now should be READY_FOR_EXPORT.
- repeat EXPORT_TO_FILEMAKER, this time it works
- the result must be "READY FOR IMPORT" and not "IN_THE_FIELD", so the kiosk workstation state needs to be reset after every successful export!

**Comment by urapadmin** [comment]
see also #622

**Comment by urapadmin** [comment]
### @test 0.13.7
I found a rather elegant solution (means it did not need disruptive changes to the code) so it turned out not to be such an enormous task, unless I overlooked all the side effects. So this is what we should see now:

If a workstation operation is interrupted either by the user or by an error the resulting state of the workstation should be the state that naturally precedes the operation (which is not necessarily the same state the workstation was in when the operation was started):
So these are possible starting states and the resulting states IF the operation is interrupted or fails:

- [ ] workstation in state "synchronized" (IDLE) + operation fork -> IDLE
- [ ] workstation in state "forked - needs export" (READY_FOR_EXPORT) + fork -> IDLE
- [ ] workstation in state "forked - needs export" (READY_FOR_EXPORT) + prepare for download -> forked - needs export
- [ ] workstation in state "in the field" (IN_THE_FIELD + downloaded) + prepare for download -> forked - needs export
- [ ] workstation in state "uploaded - needs import" (IN_THE_FIELD + uploaded) + import -> "uploaded - needs import"
- [ ] workstation in state "waiting for synchronization" (BACK_FROM_FIELD) + import -> "uploaded - needs import"

**Comment by luizaogs** [comment]
Two questions as I try to test this: 

1. what does IDLE look like? 
2. when I stop an operation I get the "operation stopped by user" (or whatever it's called) thing showing up for the workstation, and the resulting state only appears after that goes away. Is there a way to check what that resulting state is beforehand? I tried testing this yesterday and forgot what I was testing because it takes a while to change, oops.

**Comment by urapadmin** [comment]
> Two questions as I try to test this:
> 
>     1. what does IDLE look like?

that is the initial state "synchronized - needs preparation". 

>     2. when I stop an operation I get the "operation stopped by user" (or whatever it's called) thing showing up for the workstation, and the resulting state only appears after that goes away. Is there a way to check what that resulting state is beforehand? I tried testing this yesterday and forgot what I was testing because it takes a while to change, oops.

You see what state a workstation is in when you look at the first option you get in the workstation's dialog.
IDLE - "prepare for field"
FORKED - "prepare for download"
IN THE FIELD (but not downloaded) - download workstation
IN THE FIELD (but downloaded) - upload workstation
BACK_FROM_FIELD (after the download) - import workstation
after that the workstation dialog shows no first option and waits for synchronization

**Comment by luizaogs** [comment]
Ok, it's all working.
