### ISSUE TITLE
bulk file import: list of file-extensions to search for does not seem to like blanks after the seperator

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#845]
when Laurel imported she created this:

> file_extensions is ['jpg', ' tif']

There is a blank before "tif" and indeed, the file import did not touch .tif files. I suspect the blank was the reason.

**Comment by urapadmin** [comment]
### kiosk 0.8.17
blanks are ignored now. So something like "jpg, tif" should find and import jpg and tif files

**Comment by lbestock** [comment]
Tested PVD local 0.10.0 works with our without the space
