### ISSUE TITLE
clicking the right button in photos in a context automatically puts cursor on description

### ISSUE THREAD

**Issue by myjaylee1123** [urapadmin/kiosk#849]
when i scroll through photos of a context the right button automatically puts cursor on description and pulls the keyboard up which is annoying. however, when i use the left button to scroll, the cursor is not automatically placed, and instead the full photo is seen instead. 
LEFT:
![IMG_0369](https://user-images.githubusercontent.com/47072505/92619722-e4bc1d00-f28f-11ea-87bf-ae875450f65e.PNG)
RIGHT:
![IMG_0368](https://user-images.githubusercontent.com/47072505/92619723-e554b380-f28f-11ea-8897-16213bdfb1e0.PNG)

**Comment by lbestock** [comment]
I am getting this when I scroll left, too. But mostly just noticing that it doesn't belong in my triage pane and so moving it.

**Comment by urapadmin** [comment]
### 10.3.6
This should be better now. And please test it in collected material photos as well.
