### ISSUE TITLE
keep users from entering nonsense to the workstation request: Requesting nothing.

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#850]
while filemaker accepts a workstation request that isn't asking for anything (the request field is empty), the kiosk import fails later on because a null value is not allowed there. Make sure that filemaker does not accept such requests in the first place.

**Comment by urapadmin** [comment]
I think this must be about surveyor requests, no?

**Comment by urapadmin** [comment]
### @test 10.8.1
Requests for dayplans are not longer accepted without a short text. Because of idiotic filemaker one can still manage to create such a thing by first adding one, then deleting the text without leaving the field, instead pressing the add button again. After a cascade of messages one is left with one empty request. When leaving the dialog there should be an error and it should not be possible to leave the request dialog as long as there is a request with an empty text.

**Comment by luizaogs** [comment]
Ok, so you do know that one gets a million messages if trying to add a new request after deleting the text of another, right? The error itself works, so if the cascade of messages is fine then this can be closed (sending it back so you see the question).

**Comment by urapadmin** [comment]
yes, the cascade is ugly but this is a rather rare case and I can live with it in this case.
