### ISSUE TITLE
transect order weirdness

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#851]
I was testing #777 and realized that the transects in unit 48 are not in the correct order (which they were when that ticket was opened, according to the screenshot there). Not sure what is up or even how the order might have been changed, but it looks correct for all other PVD survey units with transects so I thought I would bring it up in case something happened when you were resizing the boxes or something.

![image](https://user-images.githubusercontent.com/67970402/93001711-2272ad00-f4ff-11ea-8045-56bdd6b655aa.png)

**Comment by urapadmin** [comment]
also: The layout needs some alignment.

**Comment by urapadmin** [comment]
### recording 9.6.1
- [ ] Not sure what made the order change but since there was no order explicitly imposed on the view, it can happen. Now I am ordering those rows explicitly by creation time - which should coincide with the lot#.
- [ ] Total row is realigned.
