### ISSUE TITLE
typo in feature deletion warning

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#853]
Was testing #768 and noticed a teeny tiny typo in the feature deletion warning ("realy" should be "really").

![image](https://user-images.githubusercontent.com/67970402/93715115-481e3880-fb35-11ea-8c25-3bbeff8f2b19.png)

Don't kill me.

**Comment by urapadmin** [comment]
you're in Brazil, I am in Germany. You are safe :o)
Well. Kinda.

**Comment by luizaogs** [comment]
Kinda would be accurate :)

**Comment by urapadmin** [comment]
I humbly dedicate today's last ticket (in fact it is already 2 minutes past midnight, so tomorrow's first ticket) to you at the end of your special day.

**Comment by urapadmin** [comment]
proof :o)
![image](https://user-images.githubusercontent.com/38838314/115336004-50daf980-a16c-11eb-8ad3-773ba65cd9fe.png)

**Comment by urapadmin** [comment]
### @test 0.10.5
Version 0.10.5 is also dedicated to you and this ticket only.

**Comment by luizaogs** [comment]
I get my own version!!? I am honored :) 

(I even remembered to synchronize the patch, aren't you proud? Both synchronization and the new field manager are looking very fancy!)

**Comment by urapadmin** [comment]
and you got a revivial of the eggy logo in your version! I is a 
collector's item :o)

Am 20.04.2021 um 07:08 schrieb luizaogs - ***@***.***:

**Comment by luizaogs** [comment]
Ha I saw it but didn't know it was just for this one! I like it even more now.
