### ISSUE TITLE
context-independent description not in description in file-identifier-cache?

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#869]
Shouldn't it be there? 
And if so, it should get added when the description changes in the file edit dialog.

**Comment by urapadmin** [comment]
the file identifier cache can only store descriptions per identifier. The file repository must search for the image's direct description separately.

**Comment by urapadmin** [comment]
that was already obsolete in kiosk. My tests on 0.10.0 were successful. Candids as well as context-dependent images are found by their context-independent description

**Comment by urapadmin** [comment]
### @test 0.10.0
If you type in a context-independent description for an image, you should be able to find the image under that description in the file repository afterwards.

**Comment by luizaogs** [comment]
Works.
