### ISSUE TITLE
surveyor request should not allow choice of unit

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#88]
currently allows choice of unit, but should only be generated from within the relevant unit so that shouldn't be adjustable

**Comment by urapadmin** [comment]
is that relevant for USTP?

**Comment by lbestock** [comment]
Candace, what is your current workflow around map-making in the field and its relationship to excavation. Do you have a surveyor with you always? The sketch plans that go on your contexts - are those just sketches or measured, and if measured on the basis of surveying or just tapes on the ground? Do you survey deposits or just architecture?

**Comment by cmrice-arch** [comment]
We always have a surveyor on site with total station. The sketch plans are not-to-scale, just for quick reference. For the last few years, we have photogrammetric models with spatial data (or the photos for them) of every context. So we could do a scale drawing of every context if we wanted, but we also like some degree of sanity, so we store them in case we realize their importance after the fact. We draw our main architectural plan from orthorectified photos extracted from the models.

**Comment by lbestock** [comment]
Great. In other words, no need to get daily survey data from the GIS onto the iPads for drawing by supervisors, so surveyor request will be a nonissue.
