### ISSUE TITLE
"collected material" analysis widget

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#880]
- shows all the collected material that has been modified on the selected day (by that person and/or in the selected unit)
 - context# of the collected material
 - context# of the unit (unless a unit has been chosen)
 - recorder (unless a person has been chosen)
 - the creation date (time)
 - material (type)
 - photo count
 - has description?
 - is small find?
 
should have a selection of sort orders: 
- context# of unit, context# (default), creation date (time), 
- context# of unit, context#, is small find.

**Comment by luizaogs** [comment]
Currently not showing the number of the unit nor the recorder (no, I have not selected a unit or a recorder): 

![Screen Shot 2021-06-22 at 9 43 40 AM](https://user-images.githubusercontent.com/67970402/122926599-6b814880-d33e-11eb-8c92-daef43c5dfb3.png)

**Comment by urapadmin** [comment]
### @test kiosk 0.12
- [ ] the unit identifier should appear in front of the cm identifier unless a unit is selected
- [ ] the team member who last modified anything has its own column unless a team member is selected

**Comment by luizaogs** [comment]
Ah wait, I just realized while testing something else that you are currently using both "member" and "recorder" in the director's view (the former for features and probably other stuff and the latter for collected material). Do you care? Do you want a separate ticket?

**Comment by urapadmin** [comment]
yes, I do care but I will make a ticket myself. All these terms need to be unifified and configurable in kiosk one day.

**Comment by urapadmin** [comment]
> 
> yes, I do care but I will make a ticket myself. All these terms need to be unifified and configurable in kiosk one day.
> […](#)
> On 30. Jun 2021, at 15:12, luizaogs - ***@***.*** ***@***.***> wrote: ﻿ Ah wait, I just realized while testing something else that you are currently using both "member" and "recorder" in the director's view (the former for features and probably other stuff and the latter for collected material). Do you care? Do you want a separate ticket? — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.
see #1163
