### ISSUE TITLE
team member selector

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#882]
just a new selection widget that allows to select a person that has been active on some record on a certain day.
We decided to not make it subordinate to the unit or the other way around. 

- data widgets decide themselves whether they limit  their data to any or both of the selections

**Comment by luizaogs** [comment]
(I'm not sure if I can test director's view things or if you're leaving them open for the field so I'm leaving most of them alone, but this one seemed pretty straightforward...)
