### ISSUE TITLE
literals on director's view must not be static. Kiosk needs plurals for them, too.

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#892]
This is about the archaeological terms like locus etc.
Only the record types are translated into the project-specific types. Apart from that all other literals are static URAP. e.g. loci, collectedt material, feature etc. IT all needs to be customizable. 

But so far we have not really decided where and how to customize kiosk... So I rather wait for a more general mechanism. It should be in connection with the filemaker configuration, too, shouldn't it?
see #889

**Comment by urapadmin** [comment]
relies on #889

**Comment by urapadmin** [comment]
#645 is connected

**Comment by urapadmin** [comment]
#908

**Comment by urapadmin** [comment]
since #889 is not-in-v1 we need a kiosk-specific solution here that just changes the terms in the director's view.

**Comment by urapadmin** [comment]
since this is currently needed only in api calls, why not find a way to blend in certain filemaker config keys into the api call?

**Comment by urapadmin** [comment]
### @test kiosk 0.12.3
- [ ] when no unit is selected the unit info widget now uses the filemaker constant "label_for_unit_on_start_page" which we also use on the recording start page instead of "unit" 
- [ ] if a unit is selected the unit info widget now uses the filemaker constant "label_supervisor" instead of "supervisor". Apart form that it avoids the term "unit" (because not every unit has the same term and there it gets overly complicated to fix this in the director's view)
- [ ]

**Comment by luizaogs** [comment]
Works.
