### ISSUE TITLE
first start after installation: token of admin can't be authenticated

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#899]
the admin user has no password and in this case no api token is being created.

**Comment by urapadmin** [comment]
fixed in #0.8.22

**Comment by lbestock** [comment]
Version suggests we're talking about kiosk not FM. But I need more to know how to test this.

**Comment by urapadmin** [comment]
the labels suggest that, too. You can't test this, it occurs only after a fresh kiosk installation. I move it to my test pane.
