### ISSUE TITLE
dayplan show only the request of one day

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#90]
request_dayplan | To avoid confusion, would be good if each day we only saw that day’s requests.
- must be surveyor request or some such.

**Comment by urapadmin** [comment]
Any idea what that once meant? This is an issue from the old list when we kept bugs and requests in the wiki.

**Comment by lbestock** [comment]
I'm not sure what it meant. Let's close it - if it matters it will come up again, but currently no one uses surveyor request.
