### ISSUE TITLE
Director's View: add sort by identifier to images widget

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#904]
Current sort order is by time. That is important when reading narratives. When trying to get an overview of loci or CM I wanted to be able to sort by context.

**Comment by urapadmin** [comment]
### @test kiosk 0.8.24

**Comment by luizaogs** [comment]
Works but default is still date rather than context. Does that matter?

**Comment by urapadmin** [comment]
not for me 🍋

**Comment by lbestock** [comment]
Why the lemon? I am confused by the lemon! Default to date is just fine.

**Comment by urapadmin** [comment]
I liked it

**Comment by lbestock** [comment]
🥦 There are really a LOT of emoji.

**Comment by urapadmin** [comment]
yup. And it is the nonsensical ones only that make sense to use IMHO.

**Comment by luizaogs** [comment]
🍦
