### ISSUE TITLE
Director's View: show site

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#905]
Once a unit is selected it would help to have a static bit that shows site, whether or not the site was modified that day (which could only be on creation of the unit anyway). Major help in orientation for the director faced with work done lots of places.

**Comment by urapadmin** [comment]
see #906 
That seems to call for a static widget that just shows the current information for a selected unit. That includes site information.

**Comment by urapadmin** [comment]
Not sure what exactly it means that a site has been changed here. The unit would not pop up on that date if there had not been anything in the unit's context that changed. And so something in the site's context would have changed as well. 
BUT the site's own modification date would only reveal if any site attributes have changed, like description or the site map. 
I don't really see the value in this information for the director's view and leave it out for the time being. It would make it a bit harder to fetch data for this widget. I don't want to complicate things for no reason, So please review if that piece of data is really what you want.

**Comment by urapadmin** [comment]
### @test: kiosk 0.8.24
The unit info widget shows the site of the unit.

**Comment by lbestock** [comment]
I am not sure I understand - I definitely want to see the site of the unit, which is all I expected with this request, not to see any of the information attached to the site itself. Your first comment led me to believe that that could not be done, and your second that it _had_ been done. If the confusion is around "changed" it is moot I suspect - I made the request before any widgets showed anything static and so was still in the mindset of thinking site would only pop up if the site itself had been modified.

**Comment by urapadmin** [comment]
yes, the site of the unit is shown and independent of the modification date of either site or unit.

**Comment by lbestock** [comment]
Oh wait you don't close them, you leave them open but marked @test .24 as you did above....
