### ISSUE TITLE
Director's View: show unit description

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#906]
Once a unit is selected, it would help the director a lot to see the description of that unit. We discussed this as a separate and more static thing - this has nothing to do with whether the description was modified that day, only that when lots of units are being worked in at the same time keeping them straight is hard and this would help very quickly contextualize everything else being seen for the director.

We also discussed that this is necessary for Features. As Features are structurally Units I think that's taken care of by this ticket rather than needing its own.

**Comment by urapadmin** [comment]
see #905

**Comment by urapadmin** [comment]
### @test: v0.8.24
First unit info widget ready.
