### ISSUE TITLE
global priorities for loci

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#92]
locus observations -  A way of indicating in a sortable way priority globally for the locus, not just for collected material.

**Comment by urapadmin** [comment]
not sure what the purpose is and how and where it should be accessible

**Comment by lbestock** [comment]
Would only ever need to be seen in analysis - my idea here was that for instance sealed deposits in FA are ones I care about and the cleaning loci on top of the floor I do not. So "FA deposits" is too broad - some are important and some aren't. But forget it. Honestly "sealed" is the only thing I can think of that's useful and one will be able to get there through locus relations when we build analysis.
