### ISSUE TITLE
file-repository bulk operation: assign/unassign tags

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#928]

**Comment by urapadmin** [comment]
### @test 0.12.4
- [ ] tagging files en masse implemented. Just mark your files and use the toolbar button with the tags

**Comment by luizaogs** [comment]
Works. 

Should one be able to add a new tag and I just didn't figure out how to do it, or can one only pick from the menus currently? If that is the case, would you want to add the option to type in a completely new tag?

**Comment by urapadmin** [comment]
good point. Funny that did not occur to me. We have a good word for it: "betriebsblind".

**Comment by urapadmin** [comment]
- [ ] make it possible to add a completely new ticket.

**Comment by urapadmin** [comment]
### @test 0.13.
- [ ] there is a last collapsible panel that allows you to add new tags. 

- I have not included the new tags in the counting of changes because that counter is meant to show whether or not there is a selection in what can become a very long list of select boxes. I hope that becomes clear from the order in the dialog.
