### ISSUE TITLE
locus type negative 

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#93]
locus type - Make a negative locus type (low priority - can be dealt with by “other” now)

**Comment by urapadmin** [comment]
LK: currently a subtype under other. Isn't that enough?

**Comment by lbestock** [comment]
I think eventually it should be there because it’s just as common to encounter as architecture or deposit (and people forget to make negative loci all the time which would wreak havoc if we were making Harris matrices).

**Comment by urapadmin** [comment]
this can be closed, meanwhile, right?

**Comment by lbestock** [comment]
I believe we solved the structural issue. But in testing USTP I still don't see "cut" as a locus type, and that is supposed to be there. I can't remember - should I be able to configure possible locus types? I can't figure out how, if so.

**Comment by urapadmin** [comment]
yes, as a admin you go to the admin pane, button locus types and then add the locus type you think is missing. If it is supposed to have detailed fields you select a fields set, if not, you simply don't.

**Comment by lbestock** [comment]
Works.
However, now when I give "locus type" a type of locus that I have defined as ot I still get the "specific type" dropdown. Which would be fine I think if I were able to actually click on it and drop stuff down (I am not having the drop down menu problem more generally, just this one). I checked configuration - that value list has values, only I cannot get them here.
![image](https://user-images.githubusercontent.com/49291909/75635236-672d9b00-5be2-11ea-88ae-8197ba559f4e.png)

**Comment by urapadmin** [comment]
should be fixed. It has happened in particular with new loci. Was an obstinate bug, please keep an eye on it.

**Comment by lbestock** [comment]
First v8.9.9 test looks really good but I'll leave it here to test again since it bothered you.

**Comment by lbestock** [comment]
Tested again in USTP 8.9.11 and no sign of problems so we'll close it.
