### ISSUE TITLE
force delete loci with all related records

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#932]
The implementation of #742 allows a comparatively easy follow up for loci. So let's give admins the chance to erase a locus even if it has related records.

**Comment by urapadmin** [comment]
### recording 9.6
The delete button for loci is a bit hidden so that nobody hits it accidentally. You find it in the menu of the locus edit form.
- [ ] If a locus is not connected to further records (collected material, pottery, locus relation) a simple question occurs and the record gets deleted.
- [ ] if a locus is connected to other record types a detailed report of these connections appears and after that a second question to make sure the deletion is requested.
- [ ] after deleting a locus the locus edit form closes

**Comment by lbestock** [comment]
Signed into PVD 10.0 as admin (first time I encounter the second step of needing a password - very nice). Created a new locus NA1-001 with no attached data. On entering it and going to the menu I saw the delete button. Hitting it gave me the error message "your access privileges do not allow you to perform this action", and indeed it did not get deleted.

Created a second locus NA1-002, added a photograph, and then went to delete it. I received the context deletion popup (which however does not fit on the iPad mini so I can't read everything on it, including not being able to see the X and checkmark buttons in the lower left unless I move it around - screenshot if you want to see but I elect not to clutter the ticket unless needed). Pressing the checkmark gets me the extra security question, which I answered in the affirmative, and then I get again that I have an error: access privileges do not allow...

Same thing if I try to delete a previously existing locus record.

**Comment by urapadmin** [comment]
- [ ] centered the popup. Did that help? 
- [ ] All kinds of issues with deleting were due to a lack of privileges of the standard filemaker user we now use to log in. Should all be gone, now.

**Comment by lbestock** [comment]
The deleting itself seems to work fine now. The popup is still not fully visible in either orientation of holding the iPad (and in fact not centered itself if I turn to landscape).

![image](https://user-images.githubusercontent.com/49291909/108299068-c70eb000-716b-11eb-8046-8a1cdb9d4185.png)

**Comment by lbestock** [comment]
Though if I initiate the delete from landscape mode it looks totally proper and centered and I can see the buttons to delete or abort.

**Comment by urapadmin** [comment]
I will attend to this again - but, what will never work is that changing the orientation WHILE the popup is visible will not make the popup readjust. It can't. Filemaker does not tell me when the orientation changed. But we can live with that. 
But I will make sure that it looks proper on portrait when it is initiated in portrait...

**Comment by urapadmin** [comment]
### 10.0.2
I have done two things: First I asked filemaker to readjust the window so that it fits. That might fix it.
Second:  If you are in test mode, you'll get a nasty little window that shows the measures of the window and its orientation. Please make a snapshot of it when you encounter the issue in portrait mode. 

Again: You have to initiate the window in portrait mode. If you switch between portrait and landscape WHILE the popup is visible, it will not be readjusted. I can only try to get it fit on the screen it encounters when it opens.

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/108611209-4be70d00-73aa-11eb-8906-149665bde8b2.png)

Works beautifully, portrait and landscape.
