### ISSUE TITLE
locus photo list navigation confusion

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#933]
Testing #710. On the ipad when I use the navigation buttons in the photo list below the locus list, it calls up the keyboard whenever I advance. That is a minor irritation. More troublesome is that it does not seem to be consistent as to when and how I can call the popups to navigate through at all, nor how it behaves once I have. Sometimes I can activate the navigation tools without popping up an image first? But other times not? And once I have popped stuff up, sometimes the navigation buttons work as I expect them to and go to the next image, popped up. But sometimes they close the popup window entirely. (It is not just if I try to go back from the first image, or forward from the last image.) I think I need to know how this tool is supposed to work to test it truly, but currently it does not seem to be working properly.

**Comment by urapadmin** [comment]
popup? what? The navigation buttons should just jump between the images in the list. No popup intended.

**Comment by urapadmin** [comment]
### 10.0.1
This is a filemaker mess down there. No popup should occur (except when you click the popup button of the image).
But I tried something that might help with a popping up keyboard, which also should not really happen.
Please try again and perhaps give me  a screenshot of popups or what have you.

**Comment by lbestock** [comment]
I only went to popups because it wasn't working in what seemed anything like a reasonable manner when I didn't. I think I'd better show you because what doesn't happen when I hit buttons was as perplexing as what sometimes did, so screenshots would be negative and unillustrative.

**Comment by lbestock** [comment]
No further keyboard or popups or weirdness - it functions now as I would expect it to. Possibly this was because I tested in in FMGo 17 originally and have now upgraded to 18.
