### ISSUE TITLE
weird (but apparently harmless) kiosk message 

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#934]
So I suspect I am way behind on the kiosk developments but did not see a ticket directly related to this and thought it weird enough to warrant a ticket -- 

I just successfully downloaded my workstation to my laptop but got this odd message:

![image](https://user-images.githubusercontent.com/67970402/108087089-da2f5c00-7055-11eb-8197-376439dfc561.png)

Clearly it worked but I imagine that this shouldn't be there?

**Comment by urapadmin** [comment]
ja, one of those messages that are weird because I figured they'd never actually appear. Well, there it is. Please keep an eye on it and report here if it happens repeatedly or even somewhere else. 

With kiosk issues of the weird sort it can also help to report Browser and operating system here.

**Comment by luizaogs** [comment]
Woops, this was Chrome and macOS Big Sur 11.1. But yes, I will keep an eye out.

**Comment by luizaogs** [comment]
Just got it again on the synchronization screen. And again it seems to have been harmless because synchronization worked. Same browser and operating system.

![image](https://user-images.githubusercontent.com/67970402/108700118-e8adc580-74e4-11eb-9010-f37f8caac110.png)

**Comment by urapadmin** [comment]
except that you weren't able to see the synchronization results in the usual list, right?

**Comment by urapadmin** [comment]
hm. This is hard to find out for me since it happens only now and then. This is what could help me:
Your Browser has something called developer tools. You find them in the browser's menu under more tools:
![image](https://user-images.githubusercontent.com/38838314/108748107-3558c700-750c-11eb-856c-ecfd5ed6ac35.png)
If you activate them you'll get a new pane with tabs. You want the "console" tab. It looks something like that.
![image](https://user-images.githubusercontent.com/38838314/108748242-5c16fd80-750c-11eb-909b-63c8fa38b5da.png)

Next time you get that message, please activate those developer tools and make a snapshot of as many of the last console lines as you can get. Perhaps that gives me a clue.

**Comment by luizaogs** [comment]
I'm not sure what the usual list of synchronization results is since this was the first time I did it, but I did get a list of warnings and what I took to be results -- which I know you guys get (that's where duplicate images and whatnot are flagged, no?) so I didn't screenshot it.

I'll get you a developer tools screenshot next time.

**Comment by urapadmin** [comment]
from what you report, you did get the list of synchronization results. That makes it weirder. Well, I wait for the console log.

**Comment by urapadmin** [comment]
getting laurel in here, since it might happen to her, as well.

**Comment by urapadmin** [comment]
### @test:
has this been bothering you again in 0.12 / 0.13?

**Comment by luizaogs** [comment]
No, I don't think I've seen it recently. Haven't seen #980 in a while either, but wasn't sure how long I should wait to close it so I haven't.

**Comment by luizaogs** [comment]
Just got this again in 0.16.3, and again it seems to have been harmless: 

<img width="643" alt="Screen Shot 2022-03-07 at 4 42 20 PM" src="https://user-images.githubusercontent.com/67970402/157130631-29eeeb8d-d013-43f3-8d47-c08d466183d7.png">

But I of course forgot about the developer tools since this was ages ago. Hmpf. If I get it again I'll report back...

This was in Chrome and Mac OS Monterey 12.2.1.

**Comment by urapadmin** [comment]
One gets it when one gets logged out in the background. I would not worry about it too much. Should it appear more often and strangely connected to a certain operation, please reopen this here.
