### ISSUE TITLE
adding narrative photo blocks FM

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#936]
Back to FileMaker, back to fun. First download of 10.0.1 from the PVD local server to LDB's iPad mini. I created a new unit, no problem. I went to narrative/dayplan and added a photo using the ordinary camera tool. The screen became white and I could not do anything at all, nothing. When I turned the iPad horizontally I could see a sliver of what I expected, but nothing on the screen allowed me to touch it or go anywhere. 

![image](https://user-images.githubusercontent.com/49291909/108296025-c1fb3200-7166-11eb-9787-d421debb345c.png)

My only recourse was to quit FM and log back in again. Whereupon my image was where I expected it. Tried it twice, same thing.

**Comment by lbestock** [comment]
This also happened in site note photos. It does not happen in locus photos, locus relations photos, or CM photos. I have not yet tested other image containers. It happens only with the camera as the insert method - signature and choosing a photo already on the iPad do not trigger the problem.

**Comment by urapadmin** [comment]
what iOS and filemaker go version are you on?

**Comment by lbestock** [comment]
iOS 14.4
Hm Filemaker Go 17.0.5. Shall I update that before you look at this?

**Comment by lbestock** [comment]
Still happens in Go 18.

**Comment by lbestock** [comment]
VERY strange. I had a hiccup in the way this worked (a photo I added, and saw had been added by logging in again after force quitting) did not synchronize. So to reproduce my steps I prepped my station and downloaded it and created a new unit and some dayplans. And I created a dayplan with no problem with the camera; I thought for a second you might have fixed the problem, but the ticket was untouched and the version the same. Then I went to see if I could do the same in site notes. No, a site note camera photo crashed FM again. I then went BACK to my new unit to create another dayplan. And it crashed things as I have come to expect.

**Comment by urapadmin** [comment]
### 10.0.2
No idea. I can't see that issue on windows, in part because the whole camera thing does not exist. 
There could be trouble with the new temporary second window. I have colored it green now. Please see, if the trouble appears in green now.
And if so and you can click the green, it should disappear.

**Comment by lbestock** [comment]
Also occurs in pottery photo.

**Comment by lbestock** [comment]
Alas, I do not see any green. Interestingly I was able to recreate the weird sequence of events described above, where my first dayplan worked properly, I then went to Site Note photos, crashed things as of old, force quit, logged in, saw my site note photo, went back to dayplans, tried to add a dayplan, crashed.

**Comment by urapadmin** [comment]
@luizaogs: Luiza, getting you on here just in case you encounter something similar. You seem to be on a mac instead of on an ipad, but even so...

**Comment by urapadmin** [comment]
I can only reproduce this so far with filemaker go 17. The new Claris filemaker 19 does not seem to have the issue.

**Comment by urapadmin** [comment]
I can't reproduce that with fm go 18, either. Hmpf.

**Comment by lbestock** [comment]
I am in FM go 18, definitely. But I just DIDN'T have the problem when I was logged in as admin in the behind the scenes way you taught me (hold on file, sign in) but ldb upfront. But then I tried to repeat that to make sure, and the second time I was logged in that way I had the usual failure. So it is again maddeningly inconsistent.

**Comment by urapadmin** [comment]
@test ### 10.3.1
tried something. There is a config key now under admin: close_temp_window. "yup" is the default. If you set it to "nope" it will behave like before and you should get the errornous behaviour again.

**Comment by lbestock** [comment]
Alas, things are not perfect. My first attempt to make a new dayplan photo worked like a charm. My next attempt, making a site note photo, crashed as usual. Well, not quite as usual - the keyboard did not pop up. But the crash was familiar.

**Comment by urapadmin** [comment]
filemaker go handles the switching between window so unreliably that I cannot for my life find a pattern. I have to give up on the idea. So we are back to massive flickering ...

**Comment by lbestock** [comment]
I haven't seen it for ages now, including a bunch of recent USTP attempts, so I think we can close it.
