### ISSUE TITLE
filemaker login with preset user?

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#937]
I don't know if this is a bug but whenever I open FM right after download the login screen has "ldb" on it. Of course it's easy to just type in "logs" but I'm not sure why it happens in the first place, and should it not start out blank? Once I have logged in as me once "logs" is on the start page when I re-open. 

I guess related to #378.

**Comment by lbestock** [comment]
Well to some people that seemed so totally great, having "ldb" all ready to go, so much easier to login than ever before :)

**Comment by luizaogs** [comment]
I thought you would have appreciated it, yes. Almost stayed on as ldb myself since I have enough practice being you :)

**Comment by urapadmin** [comment]
on first open after a download it should be empty, indeed.

**Comment by urapadmin** [comment]
### v10.0.2 
should be empty now on first start.

**Comment by urapadmin** [comment]
10.3: I saw Laurel having "admin" now as the preset user. Also not correct. I have to look into this, again.

**Comment by urapadmin** [comment]
I did and I guess the admin was a side effect of a test release. I move it back to testing, nonetheless.

**Comment by luizaogs** [comment]
Looks good!
