### ISSUE TITLE
once filemaker can handle dummy files broken files should be dummies as well

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#941]
Currently fork produces a bunch of warning when a file cannot be found. That does not make much sense at that point. As soon as filemaker can handle dummies and we have file picking, maybe we can handle broken files like files that do not get transferred to the recording system

**Comment by urapadmin** [comment]
@test This has been done somewhere in February and can be tested.

**Comment by luizaogs** [comment]
Works!

**Comment by luizaogs** [comment]
ooo, closing this means that kiosk 0.10 can be closed I think? But I don't know how you handle those so won't do it myself.
