### ISSUE TITLE
force-quit FM did not require login again on reopening

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#943]
I have been force quitting FM regularly because of the photo problem #936. Most recently I added a pottery photo, was locked out of anything else, and so force quit as usual. Unlike every other time I have done that, I was not asked to login again nor was I taken to the start page - I went right back to where I had been and see that it did in fact accept my photo. But I should not have been there after forcing quit! It must not really have quit, somehow. I wasn't taken either to the FM home page to ask to choose my file, nor was I taken to the start page of our system. The sequence was repeatable, too.
On my iPad, FM Go 18, 10.0.1.

**Comment by urapadmin** [comment]
that is almost impossible unless force quitting filemaker and reopening it happened so fast that the quitting never really happened. Which would beg the question why the locked state was released. 

I don't know. Can you reproduce that without the locked out state to begin with?

**Comment by lbestock** [comment]
Ah good question! Wow, yes. If I swipe to force quit in dayplans even if I do it at lightspeed I have to log in again. If I swipe to force quit when the system is in pottery processing then no login is needed and I go straight there again after restart regardless of whether I am quick or slow.

**Comment by urapadmin** [comment]
that is super strange. But I suspect you are logged in properly when you find yourself immediately in pottery analysis. 
Hm. I have a hunch that this might again be connected to my new temporary window .... I take it from here.

**Comment by urapadmin** [comment]
@luizaogs: Luiza, getting you on here just in case you encounter something similar. You seem to be on a mac instead of on an ipad, but even so...

**Comment by urapadmin** [comment]
I have had that too, on occasion. But it was always connected to the weird grey panel that blocked filemaker. 
I will take it seriously again if we encounter it without a crash.
