### ISSUE TITLE
site map image added from iPad photos is rotated

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#944]
Orientation is rotated 90 degrees counter-clockwise for portrait orientation photos. There is no problem for landscape orientation photos. I foresee a bit of apple-hatred.

**Comment by urapadmin** [comment]
if that is something you encounter IN filemaker, there is nothing I can do about it.

**Comment by urapadmin** [comment]
please give more information where it happens and what exactly you did and what exactly is wrong.

**Comment by lbestock** [comment]
(But you can't do anything about it because it's in FM!)
I went to add a site map. Rather than use the camera, I went to "photos" that were on the iPad. Adding one that had been taken in portrait orientation with the iPad camera results in it being rotated in the site map:

![image](https://user-images.githubusercontent.com/49291909/108750811-7dc5b400-750f-11eb-9137-daab46eedab2.png)

**Comment by urapadmin** [comment]
that is really not a bug. That's how ipads take photos.
