### ISSUE TITLE
order for unit configuration?

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#945]
Was testing #742 and became a bit puzzled when I realized that the unit configuration jumps between sites with no warning, especially when I checked and made sure that not all of the units in Playground had cycled through in the unit configuration screen before it moved to Providence. This is probably more relevant for me to understand how this works than an actual issue, but is there an order there? If not, should there be one?

**Comment by urapadmin** [comment]
I am a bit puzzled, too. I should have thought, too, that you can only step through the units of the selected site here. 
I'll look into it.

**Comment by urapadmin** [comment]
ja, even limiting it to the currently selected site does only make limited sense. It can still be confusing (what if no site is selected?)
I myself often thought it strange that you navigate in there to some other unit and when you go back to start still the unit is selected that was selected on opening the unit configuration.

### @test 10.4.2
So I took a rather drastic measure and 
- [ ] show the configuration button on the start page only if a unit is selected
- [ ] in the configuration the back and next buttons are gone

I hope that has no side effects.

**Comment by luizaogs** [comment]
Don't know if you're planning to release this (and subsequent arch1900 versions) on Beset but if you do I'm happy to test it.

**Comment by urapadmin** [comment]
it just now arrived on Beset

**Comment by luizaogs** [comment]
Works. If there are side effects I suspect we (or rather, you) will find them!
