### ISSUE TITLE
changes in file handling or file picking MUST lead to a reimport of the file in export_to_filemaker

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#955]
and what about a change in representations? 

in fact everything that leads to a different file (or a dummy, but the filemaker import_from ... takes care of that) must lead to a new import. Currently if a file is there it is not imported again in the filemaker script. How and where do I notice that a file is represented now by a different file?

**Comment by urapadmin** [comment]
the simplest solution would be to drop the recording group's template whenever file picking rules or file handling rules change. 
But there can be other reasons for the representation to change (like a change in the representation definition). 

Currently there is no way to reset the filemaker template. Of course, I could empty the images table. But since we have #323 anyhow, I might cover that there. 

I still would rather want to notice that a file representation has changed. Just don't know where and how. Perhaps the hash can help?

**Comment by urapadmin** [comment]
cache files are not hashed. If I do that in fork, that would slow fork down. 
What about the simple file size? If a file's representation changes, the file size almost always changes, too. And if not, then replacing the representation isn't that important, anyhow. 
Could be part of the fm_image_transfer table and then transferred to the fm-internal image table, where it would also be used for future comparison.

**Comment by urapadmin** [comment]
I did that. Wow. There are so many variables now with files ... Testing is a nightmare.

**Comment by lbestock** [comment]
It's not just the title that is difficult...

After testing #1029 I changed the file picking rule for the recording group I had already set. Forking did not work. I set a very simple rule with context = FA-001 low resolution so I wouldn't have a big file size still. Images attached. (Also I learned my lesson about naming file picking groups, Jesus.)
![image](https://user-images.githubusercontent.com/49291909/115636602-48093580-a2dc-11eb-9616-a79d3e67b013.png)
![image](https://user-images.githubusercontent.com/49291909/115636644-5fe0b980-a2dc-11eb-9b2b-9883e0abc226.png)

**Comment by lbestock** [comment]
It also failed when I changed that rule to be contextuals tiny, as the rule for the default group is.

**Comment by lbestock** [comment]
I now created a new workstation in yet another new (better named) group. And a new rule for it before I had prepared a workstation in that group. And forking failed there, too.

**Comment by lbestock** [comment]
It must be something in the rule itself. I changed = to IN (I thought either would work? And no joy. And then I changed tiny to low. And THEN it worked.

**Comment by lbestock** [comment]
I will leave this open for you to check as there is much in here I do not understand. But I THINK the thing itself is working properly, and the problems I ran into are because file picking lost the ability to deal with = as an operator and tiny as a resolution (I tried those independently and each of them causes a fail).

**Comment by urapadmin** [comment]
1. "=" was a mistake in the documentation. I got rid of it with the "context" rule because it is really misleading. So "in" is what you want. I am glad to see that the error message was pretty clear on that front.
2. In rolling out I have overridden parts of the configuration that are responsible for "tiny". I added that just for testing purposes. I have now added it again.

@test ### 0.11.2
Here is what you should test:
- pick out a single file you want to test with. Add a file tag to it in the file repository that you will later use to address the file.
- Only after that fork. with file picking rules set to contextuals / low only. Make sure the single file arrived in the recording and has the low resolution.
- now add a file picking rule "tag" that addresses the file with the "tiny" resolution. DON'T change anything else about that file. Don't even look at it in the file repository. This is just to make sure that it does not get a new modification date.
- reset the workstation and prepare again. 
- Now the file in the recording system should be of resolution "tiny"

**Comment by lbestock** [comment]
Harder to test than anticipated, in part thanks to the server going kaputt for unknown reasons. But tested it is, and it works exactly as hoped, no modification of the date. The slight improvement of my life was helpful.
