### ISSUE TITLE
teach filemaker to actually do something with the new dummy image entries

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#956]
That will make file containers once again more awkward. 
This is what the image containers additionally have to do:

- [x] if an image is marked as dummy it should show a dummy representation in its primary container
- [x] a click on that dummy representation shows an explanatory message 
- [x] the image should show what kind of tile the original file is (by giving the file extension)
- [x] no popup shall be accessible if an image is a dummy
- [x] a dummy image cannot be modified
- [x] there must not be a delete button for the image

added the new features to the description of how to test an image container: 
https://www.meritaten.net/urapdev/doku.php?id=how_to_test_an_image_container

**Comment by urapadmin** [comment]
keep #957 at least in mind. Perhaps there is a way...

**Comment by urapadmin** [comment]
can't see a good way for #957

**Comment by urapadmin** [comment]
The first batch of image containers now deals with dummy images:
- [ ] dayplans (only in excavating/full excavation mode)
- [ ] site maps (entering with gear or clipboard icon)
- [ ] locus photos (only in locus form itself)
- [ ] collected material photos

**Comment by urapadmin** [comment]
after the first batch of file containers is tested as ok, 
these are the next file containers:

- [ ] locus photos in full excavating below the locus list
- [ ] dayplans in simple excavating
- [ ] photos in feature recording
- [ ] photos in pedestrian survey
- [ ] locus photos in simple excavating below the locus list
- [ ] locus relations
- [ ] images in tag analysis
- [ ] images in pottery
- [ ] images in pottery analysis
- [ ] images in inventory

**Comment by urapadmin** [comment]
### @test recording v.10.3
- [x] locus photos in full excavating below the locus list
- [x] dayplans in simple excavating
- [x] photos in feature recording
- [x] photos in pedestrian survey
- [x] locus photos in simple excavating below the locus list
- [x] locus relations
- [x] images in tag analysis
- [x] images in pottery
- [x] images in inventory
- [ ] did I forget anything anywhere else?

**Comment by lbestock** [comment]
Something happened? Now the image containers are blank rather than having dummies, and they are live - I can put new images in them. How did that happen? I have logged in and out and in and out a bunch of times, including using the admin sign in, but have not synchronized or re-downloaded since I tested precisely this yesterday.

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/110015725-33ec8300-7cf2-11eb-9e30-f8d2d24ae55f.png)

But a new download and a bunch of logging in and out differently has not repeated the issue and I'm back to proper dummies.

**Comment by urapadmin** [comment]
I have never witnessed this nor can I imagine how that could possibly happen. Next time STOP and call me (or send me the filemaker file via email or what have you).
When you are testing file picking in a bit more detail, it might come up again.
@luizaogs: I just add you here so that you are aware of the issue. Once you are involved in file picking testing you might encounter something similar.

**Comment by lbestock** [comment]
This is one of those ones that will never get closed because we will never see it happen again and will forget to look for it.

**Comment by lbestock** [comment]
Closed awaiting resurfacing.
