### ISSUE TITLE
log in to filemaker should use result in user id as it is stored in the excavators list

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#965]
currently when I type in an uppercase "Mawr" it is accepted but the user will be "Mawr".
It is okay to accept uppercase user ids but the logged in user must be set to the user-id as it is stored in the database

**Comment by urapadmin** [comment]
I also should try and see if I can keep iOS from suggesting an uppercase first character.

**Comment by urapadmin** [comment]
### 10.3.2

**Comment by lbestock** [comment]
Check release history before testing.

**Comment by lbestock** [comment]
You seem not to have kept it from suggesting an uppercase first letter but rather to have made it not matter since it will all end up uppercase (or all lowercase if I try Admin, and then it doesn't try to capitalize the password). It works. The whole login is a lot easier now.
