### ISSUE TITLE
FM tools usually hidden are visible

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#966]
![image](https://user-images.githubusercontent.com/49291909/110012330-6d22f400-7cee-11eb-8c12-075cc17d9d2f.png)
I should not be able to see the stuff in the header and footer, should I? They are active, too - I can get to the launch center or show omitted records or whatnot. I am both signed in and logged in as LDB.

**Comment by urapadmin** [comment]
see #962

**Comment by urapadmin** [comment]
### 10.3.5
should be solved. Only the admin should see the filemaker tools.

**Comment by lbestock** [comment]
Done. I still see them if I am logged in as LDB but signed in as admin, but that is such a weird case that I don't think it's relevant.
