### ISSUE TITLE
site map not present after switching file picking

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#967]
I am not in fact sure this has anything to do with file picking, and I did not notice after our first file picking download that the site map was missing or a dummy. But after our second more complicated file picking adventure to get me some images back, the site map is not visible in FM on the start page. We defined filepicking as low resolution for all contextuals with rule 1, and then dummy for all context = SA. A quick glance shows that these two rules seem to have been properly implemented, it's just the site map that is now gone. The images are still there and still called site maps when I go into the site through either the gear or the notecard, it's just that they're not displayed on start.

**Comment by urapadmin** [comment]
so, to clarify: The site map image is visible in the site form, just not on the start page?

**Comment by lbestock** [comment]
Correct.

**Comment by urapadmin** [comment]
### recording 10.3.6
fixed
