### ISSUE TITLE
battle flickering at least in some places

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#970]
there is a way to battle it in locus relations and when starting the app in the first place.

**Comment by urapadmin** [comment]
### v10.3.5
battled it during startup. So far the app had seizures between logging in and the appearance of the start page.

**Comment by urapadmin** [comment]
#791

**Comment by urapadmin** [comment]
- [ ] I still would want to battle it in locus relations. I'll have one more try.

**Comment by urapadmin** [comment]
#### @test recording 11.4
- [ ] first attempt: There will be still flickering (it can't be avoided) but in comparison it should be reduced. 
- [ ] flickering issues are particularly horrible with images involved. So adding an image, changing a relation with an image in place etc. was flickery and should now be less so.
- [ ] the question is: does it all still work. So ticket #799 has to be retested. You may reopen it.
- [ ] and most important: The issues in #936 should not reappear or this was all moot

**Comment by luizaogs** [comment]
So obviously I feel horribly guilty about the whole iPad thing and have asked to borrow a friend's to look at this stuff, and I will get it later today. Not a long term solution but I'll get one myself soon if that one does not appear. So ... stay tuned for some flickering testing.

**Comment by urapadmin** [comment]
So obviously it is pretty ridiculous to feel guilty about that, no? You should be stomping your foot, rather. On Fedex. 🚚 Delivery in the US is really a fragile thing. Now I wonder: Did you ever get a postcard from Germany? 📯

**Comment by lbestock** [comment]
Argh you feeling guilty is the exact opposite of what the whole point was! Just hate FedEx. Or the Brown Mail Room. We don't even know which one.

**Comment by lbestock** [comment]
Repetitions including after logging out and logging back in again have repeated the problem.

**Comment by lbestock** [comment]
Not sure if it helps identify the problem but this time I hit "delete" in the popup instead of "view" and it told me "error: this button requires that a field be active. Tap on a field to make it active." To which I had no choice but to say "ok" and then it took me back again to the big white blank stasis.

**Comment by lbestock** [comment]
URAP works fine. Lots of flickering, as we know, then the photo is there and I am back at the locus relations tab, though the same dialog box is open:
![image](https://user-images.githubusercontent.com/49291909/137599913-1e5c9966-4fd0-4a76-9e3a-251fccddad96.png)
Seems weird but might that have something to do with it? You've battled the issue of jumping to next tables previously and here the ideal would be to have no popup at all.

**Comment by urapadmin** [comment]
I mean the missing postcard.

**Comment by urapadmin** [comment]
as for filemaker, I want one of those banging-one's-had-to-a-wall emoticon gifs that went out of fashion. That piece of software is really a curse.

**Comment by lbestock** [comment]
Soon(ish) you will encounter the therapeutic purr of a balding crazy cat and I hope it restores you a bit.

**Comment by lbestock** [comment]
Testing in URAP still, so an old version first:
Dayplan: keyboard pops up when done.
Locus photo: keyboard pops up when done.
CM: keyboard pops up.
Pottery photo: nothing pops up, that's the only one that's just right.

Now on to PVD:
Dayplan: keyboard
Locus: keyboard
CM: keyboard
locus relations we know is a problem and this time it didn't pop me up anything, just went straight to a blank screen.
Well and pottery photo is now broken, too, in PVD. Straight to the blank screen just like locus relations.

**Comment by luizaogs** [comment]
> Soon(ish) you will encounter the therapeutic purr of a balding crazy cat and I hope it restores you a bit.

😸 (Github should have a cat reaction emoji. missed opportunity)

**Comment by urapadmin** [comment]
Can you please make sure that you are actually in filemaker go 19.3.1? I cannot reconstruct this with my ipad and wonder if you might select a fm go 18 or something when you use "send to" in iOS. Best to really delete all the other fm go versions. 
I will publish a version of the database that'll actually show the filemaker version.

**Comment by lbestock** [comment]
That is a handy feature for testing. You won't like the first answer: I opened the file without changing any of my previous patterns and it opened in 19.3.1.23, iOS 14.8. And my first dayplan resulted in the big blank.

**Comment by urapadmin** [comment]
I close this in favour of #1250
