### ISSUE TITLE
kiosk connection error in director's view

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#971]
I was in PVD local server 0.10.0 in the Director's View. I looked at a few days stuff properly and then went to another day and it gave me this:
![image](https://user-images.githubusercontent.com/49291909/110354702-7241b500-8006-11eb-956a-af448744d071.png)

I don't otherwise seem to have any problem with the server or anything - the file repository is fine.

**Comment by urapadmin** [comment]
you get that repeatedly?

**Comment by lbestock** [comment]
Yes and weirdly on the 19th of July 2020 in particular it seems? With two different kiosk logins with users with different privileges.

**Comment by urapadmin** [comment]
duplicate with #1073

**Comment by lbestock** [comment]
It is at least not a problem on the 19th of July 2020 in PVD any longer.
