### ISSUE TITLE
text color post-synchronization is illegible

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#973]
Kiosk 0.10.1 PVD local. Synchronized and the "synchronization was successful" text is so pale it cannot be seen. A quick ticket, I hope!

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/110548007-44d83280-80fe-11eb-8959-5e33f2071c2a.png)

**Comment by urapadmin** [comment]
see #690

**Comment by urapadmin** [comment]
### @test 0.11
In the field manager (I won't change the old workstation manager) this is due to the project's color scheme only. see #690

**Comment by lbestock** [comment]
Now it's so legible it almost hurts my eyes!
