### ISSUE TITLE
"modified on" for image changes when image added to a new context in file repository

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#975]
In testing #441 and seeing that indeed, a pre-existing image that is put into an additional context in the recording system retains its original "created on" date, as we expected, a small other issue was noted. The "modified on" field was the same as the original "created on" date after synchronization, which Lutz thinks is proper - the image wasn't modified, it was simply attached to a new context. But when I then added yet another new context using the file repository, not the recording system, the "modified on" was updated to today. (When I clicked "ok".)

![image](https://user-images.githubusercontent.com/49291909/110549103-946b2e00-80ff-11eb-99e8-23bfb1c045e6.png)

**Comment by urapadmin** [comment]
That seems indeed wrong

**Comment by urapadmin** [comment]
### @test 0.12.2
only

- [ ]  if the image itself is replaced 
- [ ] or the data connected directly to the image is changed (description, date of creation, tags)

should the modification date change

**Comment by luizaogs** [comment]
Hmm, I just added a context to 9dda039e-05ce-4a5e-96ce-7fac0cf3c37f and the modified date still changed, as did the modified by:

![Screen Shot 2021-07-05 at 6 03 12 PM](https://user-images.githubusercontent.com/67970402/124517943-a4e49a00-ddbb-11eb-9aa3-abd88c77979b.png)

![Screen Shot 2021-07-05 at 6 06 08 PM](https://user-images.githubusercontent.com/67970402/124517969-b3cb4c80-ddbb-11eb-90ab-c43362798981.png)

**Comment by urapadmin** [comment]
### @test kiosk 0.13
- [ ] the bug here was not related to adding a context but to the empty date and time of creation. You could have just opened and closed an image and the same would have happened. Should be fixed.

**Comment by luizaogs** [comment]
Ah. Well, everything seems to be working now.
