### ISSUE TITLE
use date container made not image creation date in dayplans

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#977]
As discovered in the long haul that was for nothing that was #976, the date on the images in dayplans is the image creation date. Is it possible to use the date of creation of the container instead? The image creation date will always be available in the file repository, but in the context of the recording system and that list of images (which are ordered by creation date of container, not image creation date) the important thing is when it was used, not when it was made.

**Comment by lbestock** [comment]
I think you took care of this in 10.3.6 in  responding to #378, in which case this can be closed.

**Comment by urapadmin** [comment]
that is really for you to decide :o) Did you test it?

**Comment by lbestock** [comment]
Replacing an old photo results in the date being updated - is that what you expected?

In dayplans the old-style date is semi visible behind the new style date. 

Clicking on the pen for record information results in an unexpected blank. (Both these points visible below.)
![image](https://user-images.githubusercontent.com/49291909/111211199-80fb0f80-85a4-11eb-9e76-f887cdd4b11d.png)

The date on date is not a problem in features or survey or simple excavating, just normal excavating.

The empty record information is not a problem in features but IS in survey and in simple excavating.

**Comment by urapadmin** [comment]
### @test 10.6.1
- [ ] date on date in simple excavating should be gone now
- [ ] clicking on the record information label in dayplans should be okay now everywhere: feature recording, survey, excavation and simple excavation
PS. A yes for "Replacing an old photo results in the date being updated - is that what you expected?"
