### ISSUE TITLE
file picking and date

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#982]
It should not be too complicated to make a file picking rule that uses either the creation date, the modification date or the date when the photo was shot. 

How do we phrase a span given that we have only operator and value?

**Comment by urapadmin** [comment]
### @test kiosk 0.11
date rule explained here: [https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#rules_types](https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#rules_types).
test all four operators:
- [ ] <
- [ ] >
- [ ] within
- [ ] not within

within and not within expect the two dates to be separated by comma.
dates have to be iso8601 dates: YYYY-MM-DD. e.g. 1973-02-28

**Comment by luizaogs** [comment]
Weird result with the "<" operator, with the following rule: 
![image](https://user-images.githubusercontent.com/67970402/120711393-b4f41b80-c495-11eb-9705-4090f0350c43.png)

Admittedly I have not gone through every single context but it seems to have worked fine, except for PBA. None of those images became dummies, even though a bunch are from before 28 August 2020. At first I thought it might be an issue with an overlap with another rule, but this is a different recording group than the PBA rule (which should have turned everything to dummies anyway). 

I will wait to add other rules and test the other operators, in case you want to take a look at this one.

**Comment by urapadmin** [comment]
see also #1099

**Comment by urapadmin** [comment]
### @test kiosk 0.13.6

background: 
The date rule was using the "modified" field of the image. And most of the images were indeed modified later than 2020-08-28. I suspect due to tags and other bugs. But I cannot really answer why the modification dates are deviating so often from the "date and time of creation". We have three dates with images: creation (automatically set when the image record was created), modified (that's when the image record was last modified, e.g. by adding a description, a tag etc.), date and time of creation (when the photo was shot). The latter date is what we add manually e.g. in the edit file dialog of the file repository. 

solution:
From now on I use both the date and time of creation and the modified date for the date rule. date and time of creation has precendence unless it is empty. Only in that case the "modified" date will be used for an image.
- [ ] That should settle the issue at hand.

**Comment by urapadmin** [comment]
I have documented this extension in [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:file_picking#rules_types](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:file_picking#rules_types)

**Comment by luizaogs** [comment]
Hmm. This looks better than it did before, but I still have images that I think should be dummies and aren't. In PBA, for instance, two are from 1 VIII 2020 and seem to also have been last modified then so they should be dummies? Unless I'm misunderstanding something. This is also the case with some in LA, and these are the only units I've checked so far.

![Screen Shot 2021-09-27 at 3 46 38 PM](https://user-images.githubusercontent.com/67970402/134982733-4e408da5-d81f-4302-b895-17f26c6db43a.png)

![Screen Shot 2021-09-27 at 3 49 02 PM](https://user-images.githubusercontent.com/67970402/134982993-c6cc187d-ce70-42dd-b6a3-26ae2940cbc2.png)

Oh wait, unless I need to re-add the file picking rule after you changed its configuration?

**Comment by urapadmin** [comment]
no, that is not necessary. I‘ll look into the particular example.

**Comment by urapadmin** [comment]
welcome in date-field hell (we have so many more than Dante): What you are looking at here are the dates of the dayplan record which consists of a dayplan description and all the dates (modifed, created) that refer to the dayplan record itself. 

File picking addresses the image records themselves. And the second example (the first one is a bit harder to identify) has 10.VIII 2020 as dates for both creation and modification of the dayplan record BUT:
![image](https://user-images.githubusercontent.com/38838314/135058638-3b1603dc-2536-4edd-afa7-5bde51fedaff.png)

the modification date of the image is in 2021. And that is why the date rule did not sort out this image. 

I know, who would ever understand these differences from a user perspective? I am only describing this here to address the issue. The date rule seems to work (you are welcome to look at the file repository yourself for a few examples since that is the only place where you can even see the dates of the image itself). The whole date shebang has given me headaches ever since.

The only consolation is that I don't expect these dates to deviate all that much in practice. But what I really need to do is write a piece about dates so that it becomes clear at least WHAT is going on, technically.

**Comment by luizaogs** [comment]
Phew ok, after my own headache I think this is working properly!
