### ISSUE TITLE
image labels look odd in tag analysis pinboard

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#983]
While testing #765 I realized that the little labels for the images in the pinboard look odd in tag analysis (I think it might be an issue with the sizes of the text boxes) while they look fine in pinboards in other forms. The ones in tag analysis are also missing the image description.

In tag analysis: 
![image](https://user-images.githubusercontent.com/67970402/110716490-0ae25b80-81e6-11eb-9d18-bfd5eb1c3499.png)

In excavation form:
![image](https://user-images.githubusercontent.com/67970402/110716514-159cf080-81e6-11eb-93ba-d115137c8969.png)

**Comment by urapadmin** [comment]
### @test 10.8
more or less everything was wrong in this pinboard. It should work now like the others.

**Comment by luizaogs** [comment]
It does indeed.
