### ISSUE TITLE
how many raw formats do we want to enable?

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#984]
Canon it appears has a ton of raw formats. #818 took care of .cr2 but there are still CRWs that won't come in and god knows how many others. Do we want to chase this endlessly or write something in a manual that tells how to get new file formats added to the mix? Or is that impossible?

**Comment by urapadmin** [comment]
it appears the cr2 format is the more recent format Canon uses. But it is indeed a different file format than crw. 
Before I go and implement a new format I would want to hear if anybody at ustp or on another project is actually using it.
