### ISSUE TITLE
scrolling does not work in locus relations on Mac

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#986]
When there are more locus relationships than fit on the screen, neither scrolling nor using the arrow keys to advance allows one to get beyond the bottom visible relation. This is in 10.3.6 URAP the REAL THING as I'm cleaning up the locus relations from #611.

Both scrolling and the arrow keys work properly with locus photos, one tab over.

**Comment by lbestock** [comment]
Same problem on the iPad.

**Comment by urapadmin** [comment]
### @test recording 10.4
there is a scrollbar now

**Comment by lbestock** [comment]
Works both Mac and iPad. Now I can finish the URAP locus relations, too!
