### ISSUE TITLE
create "tiny" image size for testing file picking

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#987]
In order to test file picking (#15) we need to be able to distinguish if the correctly sized images have been transferred. The suggested solution was to create a file size "tiny", or to temporarily set the resolution of "low" so low that images are visibly pixilated even at small size.

**Comment by urapadmin** [comment]
I configured a resolution "tiny" for the default recording group. So in file picking you just use the term "tiny" as resolution and Bob's your uncle.

**Comment by lbestock** [comment]
Bob IS my uncle. Amusingly this works much better on the iPad than the Mac, which shrinks them to fit. You made tiny really tiny, and hence the file is small, too, and I can now systematically test #15.
