### ISSUE TITLE
date fields should have latin representation

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#99]
all date fields need a latin representation in order to avoid  confusion. See if you can hook in at validation to translate latin to  American date. That would allow to input latin dates, even if they will  not appear in the field.
-- | --

**Comment by urapadmin** [comment]
at least in the filemaker app we should show the latin version as a translation

**Comment by urapadmin** [comment]
this is a somewhat more extensive task since we have a few date fields.

**Comment by urapadmin** [comment]
There is a bunch of date fields that cannot be edited. Those will either show a latin or the localized date format according to the new configuration key "labels/use_latin_date":

- [ ] excavating/excavating simple/feature recording/survey: unit creation date on first page
- [ ] excavating: locus creation date in locus list
- [ ] excavating/feature recording/survey: unit creation date: collected material date in cm list

**Comment by urapadmin** [comment]
These dates are input fields and they are supposed to have a latin representation below the field if the config key "visibility/show_additional_latin_date" is set.

- [ ]

**Comment by urapadmin** [comment]
### @test the modified_by label, now in latin:
- [x] locus upper right corner: shows the modification date of the locus data (but beware: changing something in one of the detail fields of the locus type does not change this date!)
- [x] locus - every lot should have one
- [x] locus - every locus photo should have one
- [x] excavation - here we have lots as well 
- [x] relations - every relation should have one
- [x] unit - first tab of excavation form (in simple exc. as well)
- [x] survey unit - first tab, lower right corner, same on the second tab.
- [x] feature unit - first tab, lower right corner, same on the second tab.
- [x] collected material -first tab upper right corner
- [x] collected material -third tab upper right corner (shows small find modification)
- [x] site notes: a label per note.
- [x] site purpose and site map (we have two of those: enter by note or gear from the start page)

**Comment by urapadmin** [comment]
### @test 9.6.2
These are dates that are not editable:

- [x] excavating/excavating simple/feature recording/survey: unit creation date on first page
- [x] excavating: locus creation date in locus list
- [x] excavating/feature recording/survey: collected material date in cm list
- [x] all little modified_by labels (OMG)
- [x] surveyor requests - date / time

**Comment by urapadmin** [comment]
### @test 9.6.2
And here are the edit fields that should show a latin representation below them unless the config key "show_additional_latin_date" is set to "nope":

- [x] excavating/simple exc.: daily narrative creation date
- [x] locus date opened and date closed
- [x] lot date time (in éxcavating form and in locus edit form)
- [x] collected material date collected
- [x] survey unit start date and time
- [x] bugs and features: created and modified
- [x] site notes

**Comment by lbestock** [comment]
Giving this one to you, Luiza. It should get you back in the swing of things. Happy 15 II 2021. Only you can't do the configuration part, so once you've hit it all I will change the configuration so you can test the difference. (We can also test changing the configuration of "use_latin_date" in general, which at first I mistook for this key. Currently on your version both are set to "yup".)

**Comment by urapadmin** [comment]
Luiza can do the config part. She can log in as admin. Much easier than having to synchronize in between tests.

**Comment by luizaogs** [comment]
This looks to me like an issue with centering the text, but in locus relations one can only see day and month, not year:

![image](https://user-images.githubusercontent.com/67970402/108410116-c32f6c00-7205-11eb-95b4-21f30124a715.png)

**Comment by luizaogs** [comment]
Not editable dates in collected material list are not correct in excavation, but are correct in survey and features.

**Comment by luizaogs** [comment]
Survey unit start date and time shows up in Latin regardless of whether the "show_additional_latin_date" is set to "nope."

**Comment by luizaogs** [comment]
Two last things: the last check box in the first list is a mystery to me, which is why it is currently unchecked, not because it's not working. [this one -- excavation: locus tab down below the locus list and only visible if recorded by is actually set for the locus (see next check box)! (on the first tab. Here you find a recorded by label and input field. It controls the label mentioned above.)]

I cannot for the life of me find two different dates for lots? Only this one below? Help. (also why that check box in the third list is unchecked, not because it's not working)
![image](https://user-images.githubusercontent.com/67970402/108415011-a8f88c80-720b-11eb-8ed1-05078f15ae60.png)

**Comment by urapadmin** [comment]
> 
> 
> Two last things: the last check box in the first list is a mystery to me, which is why it is currently unchecked, not because it's not working. [this one -- excavation: locus tab down below the locus list and only visible if recorded by is actually set for the locus (see next check box)! (on the first tab. Here you find a recorded by label and input field. It controls the label mentioned above.)]
> 
> I cannot for the life of me find two different dates for lots? Only this one below? Help. (also why that check box in the third list is unchecked, not because it's not working)
> 
> ![image](https://user-images.githubusercontent.com/67970402/108415011-a8f88c80-720b-11eb-8ed1-05078f15ae60.png)

This is about the __locus__ list in the excavation form (not visible in simple excavation mode!).
It is only visible if you click on a locus that has a recorder selected:
![image](https://user-images.githubusercontent.com/38838314/108541432-705ebe80-72b0-11eb-8a98-2f400ee979ee.png)
With a recorder selected the label appears:
![image](https://user-images.githubusercontent.com/38838314/108541560-94ba9b00-72b0-11eb-8a1d-8103b75153a4.png)
And as you can see - it is wrong :) No date whatsoever.

**Comment by luizaogs** [comment]
Oh I saw that! But didn't think I was looking at the right thing because the date wasn't there :) Oops.

But my question about lots remains, I think? In the third list of check boxes you mention this: "lot date time (in excavating form and in locus edit form)." I only see dates for lots in the screenshot I showed you above, so I'm not sure what else to test there.

**Comment by urapadmin** [comment]
ah, sorry, I missed that those were two questions. You should have a lot list in excavating (not in simple excavating) and a lot list in the locus form. They look the same but thanks to #!§$* filemaker I have to maintain such lists separately, so whenever I change something I have to change it in both places.

**Comment by luizaogs** [comment]
Ah I see. Then I believe we are good on that front.

**Comment by urapadmin** [comment]
### recording 10.0.2

> 
> 
> This looks to me like an issue with centering the text, but in locus relations one can only see day and month, not year:
> 

should be fixed
