### ISSUE TITLE
file picking record_type does not work

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#994]
First formal file picking tests.
PVD on the local server.

I wrote three rules:
1 contextuals tiny
2 record_type=site map low
3 record_type=collected_material_photo dummy

All photos are tiny, including site maps and CM photos. This was the second iteration of trying to get these rules to result in most images tiny, site maps low, CM photos absent. The first time I did not have the _ in record_type, and we were uncertain about what to call site maps and CM photos. Site map we saw is the name used in the file repository of this project. collected_material_photo we got from the file repository recording context aliases list in the wiki that is linked to from the file picking page. Changing these things still did not result in the expected application of rules 2 and 3.

Previous not formal uses of file picking have always done what I expected, but I have only ever messed with contexts, not record types.

**Comment by urapadmin** [comment]
### @test
the translation of the record type names did not work properly. Now it does.
No new version, I just patched it on PVD so that you can move on.

**Comment by urapadmin** [comment]
here are the translation settings for pvd:
  recording_context_aliases:
    collected_material_photo: collected material & small finds
    dayplan: trench/area
    locus: context
    locus_photo: context
    locus_relations: context relations
    pottery_images: pottery
    site: site map
    site_note_photo: site note
    tags: context tags
    unit: trench/area

**Comment by lbestock** [comment]
Bingo!
