### ISSUE TITLE
image without context results in weird double error message at synchronization

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#997]
I am not sure this is actually a problem - the doubled error message is a thing, but in fact the images did synchronize. 

Three times now I have followed the same steps and had the same results.
PVD on the local server 0.10.1.

Downloaded. Made a new dayplan in Playground unit Test. (Just one! I promise.) Twice I added an image using the photos function rather than the camera. The third time I made the dayplan in unit LA test and added a photo using the camera. All three times I checked that I could find the image in the gallery when searching its context, and I could. I then went back to the dayplan and deleted it. 

I checked again that the image was still present in the gallery, which it was, at the very bottom of the unsorted gallery, with  no context any more.

I logged out, uploaded and imported and synchronized. Each time I got error messages regarding TWO images, though I had put only one in. However, my original failure to find them in the file repository was my problem - they are there. Images added 25 III 21 and 26 III 21, and the synchronization logs for the same dates, the last two should be just either side of 1pm on the 26th.

**Comment by urapadmin** [comment]
"I got error messages regarding TWO images" is not telling what those error messages were. I need them or can't help.
Please make screenshots.

**Comment by lbestock** [comment]
Could not reproduce in 10.8.2.
