### ISSUE TITLE
arch1900 starts with "playground" as the preselected site

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#999]
That means, there are remains in the template to me. But what about preselecting the only site if there is only one site. And what about making that the other site if there is only an other site and playground?

**Comment by urapadmin** [comment]
I cannot understand why arch1900 would have any remains in the template because PrepareTemplate clears up these remains.
I might have done that accidentally manually.

**Comment by urapadmin** [comment]
### @test recording 10.4
- [ ] For projects that have only one site (other than playground) that site will be automatically selected when opening the start page
- [ ] For projects with more than one site (other than playground) the site selection will remain empty on start

**Comment by luizaogs** [comment]
Hmm, is this only applicable to arch1900? I thought not because you mention "projects" in the comment above but I'm in PVD 10.4.1 and there was no preselected site on the start page so not sure.

**Comment by urapadmin** [comment]
no, this should work in pvd, too. But the pvd playground is named "Playground" and the arch1900 one is named "playground". My code needs to be a bit more tolerant there.

**Comment by urapadmin** [comment]
### kiosk 10.5.1
- [ ] This should now work in pvd as well no matter if "playground" has capital letters or not.

**Comment by luizaogs** [comment]
Oops I just realized that I can't test the second part of this unless I create a new site in PVD and upload that database ... not sure if I should do that? Would it be easier to test it somewhere else?

**Comment by urapadmin** [comment]
no, thank you. I think we're good here.
